%TEST_GTA_PANELPROP

%% Test 1: Inspection Methods
if rand() >= (1 - .01) * BRAPH2TEST.RANDOM
	categories = num2cell(Category.getCategories());
	gt = GTA_PanelProp();
	 
	% get('ELCLASS')
	if isa(GTA_PanelProp, 'ConcreteElement')
		assert(strcmp(GTA_PanelProp().get('ELCLASS'), 'GTA_PanelProp'), ...
			[BRAPH2.STR ':GTA_PanelProp:' BRAPH2.FAIL_TEST], ...
			'GTA_PanelProp().get(''ELCLASS'') should return ''GTA_PanelProp''.')
	end
	 
	% getBuild()
	assert(GTA_PanelProp.getBuild() == 1 && GTA_PanelProp.getBuild() > 0, ...
		[BRAPH2.STR ':GTA_PanelProp:' BRAPH2.FAIL_TEST], ...
		'GTA_PanelProp.getBuild() should return the GTA_PanelProp build number.')
	assert(gt.getBuild() == 1 && gt.getBuild() > 0 , ...
		[BRAPH2.STR ':GTA_PanelProp:' BRAPH2.FAIL_TEST], ...
		'gt.getBuild() should return the GTA_PanelProp build number.')
	assert(Element.getBuild(gt) == 1 && Element.getBuild(gt) > 0, ...
		[BRAPH2.STR ':GTA_PanelProp:' BRAPH2.FAIL_TEST], ...
		'Element.getBuild(gt) should return the GTA_PanelProp build number.')
	assert(Element.getBuild('GTA_PanelProp') == 1 && Element.getBuild('GTA_PanelProp') > 0, ...
		[BRAPH2.STR ':GTA_PanelProp:' BRAPH2.FAIL_TEST], ...
		'Element.getBuild(''GTA_PanelProp'') should return the GTA_PanelProp build number.')
	 
	% getClass()
	assert(strcmp(GTA_PanelProp.getClass(), 'GTA_PanelProp'), ...
		[BRAPH2.STR ':GTA_PanelProp:' BRAPH2.FAIL_TEST], ...
		'GTA_PanelProp.getClass() should return ''GTA_PanelProp''.')
	assert(strcmp(gt.getClass(), 'GTA_PanelProp'), ...
		[BRAPH2.STR ':GTA_PanelProp:' BRAPH2.FAIL_TEST], ...
		'gt.getClass() should return ''GTA_PanelProp''.')
	assert(strcmp(Element.getClass(gt), 'GTA_PanelProp'), ...
		[BRAPH2.STR ':GTA_PanelProp:' BRAPH2.FAIL_TEST], ...
		'Element.getClass(gt) should return ''GTA_PanelProp''.')
	assert(strcmp(Element.getClass('GTA_PanelProp'), 'GTA_PanelProp'), ...
		[BRAPH2.STR ':GTA_PanelProp:' BRAPH2.FAIL_TEST], ...
		'Element.getClass(''GTA_PanelProp'') should return ''GTA_PanelProp''.')
	 
	% getSubclasses()
	assert(isequal(GTA_PanelProp.getSubclasses(), subclasses('GTA_PanelProp', [], [], true)), ...
		[BRAPH2.STR ':GTA_PanelProp:' BRAPH2.FAIL_TEST], ...
		'GTA_PanelProp.getSubclasses() should return the same result as subclasses(''GTA_PanelProp'', [], [], true).')
	assert(isequal(gt.getSubclasses(), subclasses('GTA_PanelProp', [], [], true)), ...
		[BRAPH2.STR ':GTA_PanelProp:' BRAPH2.FAIL_TEST], ...
		'el.getSubclasses() should return the same result as subclasses(''GTA_PanelProp'', [], [], true).')
	assert(isequal(Element.getSubclasses(gt), subclasses('GTA_PanelProp', [], [], true)), ...
		[BRAPH2.STR ':GTA_PanelProp:' BRAPH2.FAIL_TEST], ...
		'Element.getSubclasses(gt) should return the same result as subclasses(''GTA_PanelProp'', [], [], true).')
	assert(isequal(Element.getSubclasses('GTA_PanelProp'), subclasses('GTA_PanelProp', [], [], true)), ...
		[BRAPH2.STR ':GTA_PanelProp:' BRAPH2.FAIL_TEST], ...
		'Element.getSubclasses(''GTA_PanelProp'') should return the same result as subclasses(''GTA_PanelProp'', [], [], true).')
	 
	% getProps()
	assert(isempty(GTA_PanelProp.getProps()) || isequal(GTA_PanelProp.getProps(), 1:1:length(GTA_PanelProp.getProps())), ...
		[BRAPH2.STR ':GTA_PanelProp:' BRAPH2.FAIL_TEST], ...
		'GTA_PanelProp.getProps() should return a row vector [1:1:N].')
	assert(isempty(GTA_PanelProp.getProps()) || isequal(gt.getProps(), 1:1:length(GTA_PanelProp.getProps())), ...
		[BRAPH2.STR ':GTA_PanelProp:' BRAPH2.FAIL_TEST], ...
		'gt.getProps() should return a row vector [1:1:N].')
	assert(isempty(GTA_PanelProp.getProps()) || isequal(Element.getProps(gt), 1:1:length(GTA_PanelProp.getProps())), ...
		[BRAPH2.STR ':GTA_PanelProp:' BRAPH2.FAIL_TEST], ...
		'Element.getProps(gt) should return a row vector [1:1:N].')
	assert(isempty(GTA_PanelProp.getProps()) || isequal(Element.getProps('GTA_PanelProp'), 1:1:length(GTA_PanelProp.getProps())), ...
		[BRAPH2.STR ':GTA_PanelProp:' BRAPH2.FAIL_TEST], ...
		'Element.getProps(''GTA_PanelProp'') should return a row vector [1:1:N].')
	 
	% getProps(category)
	tmp = cellfun(@(category) GTA_PanelProp.getProps(category), categories, 'UniformOutput', false);
	assert(isempty(GTA_PanelProp.getProps()) || isequal(sort(horzcat(tmp{:})), 1:1:length(GTA_PanelProp.getProps())), ...
		[BRAPH2.STR ':GTA_PanelProp:' BRAPH2.FAIL_TEST], ...
		'GTA_PanelProp.getProps(category) does not work.')
	tmp = cellfun(@(category) gt.getProps(category), categories, 'UniformOutput', false);
	assert(isempty(GTA_PanelProp.getProps()) || isequal(sort(horzcat(tmp{:})), 1:1:length(GTA_PanelProp.getProps())), ...
		[BRAPH2.STR ':GTA_PanelProp:' BRAPH2.FAIL_TEST], ...
		'gt.getProps(category) does not work.')
	tmp = cellfun(@(category) Element.getProps(gt, category), categories, 'UniformOutput', false);
	assert(isempty(GTA_PanelProp.getProps()) || isequal(sort(horzcat(tmp{:})), 1:1:length(GTA_PanelProp.getProps())), ...
		[BRAPH2.STR ':GTA_PanelProp:' BRAPH2.FAIL_TEST], ...
		'Element.getProps(gt, category) does not work.')
	tmp = cellfun(@(category) Element.getProps('GTA_PanelProp', category), categories, 'UniformOutput', false);
	assert(isempty(GTA_PanelProp.getProps()) || isequal(sort(horzcat(tmp{:})), 1:1:length(GTA_PanelProp.getProps())), ...
		[BRAPH2.STR ':GTA_PanelProp:' BRAPH2.FAIL_TEST], ...
		'Element.getProps(''GTA_PanelProp'', category) does not work.')
	 
	% getPropNumber()
	assert(GTA_PanelProp.getPropNumber() == length(GTA_PanelProp.getProps()), ...
		[BRAPH2.STR ':GTA_PanelProp:' BRAPH2.FAIL_TEST], ...
		'GTA_PanelProp.getPropNumber() should return the number of properties.')
	assert(gt.getPropNumber() == length(GTA_PanelProp.getProps()), ...
		[BRAPH2.STR ':GTA_PanelProp:' BRAPH2.FAIL_TEST], ...
		'gt.getPropNumber() should return the number of properties.')
	assert(Element.getPropNumber(gt) == length(GTA_PanelProp.getProps()), ...
		[BRAPH2.STR ':GTA_PanelProp:' BRAPH2.FAIL_TEST], ...
		'Element.getPropNumber(gt) should return the number of properties.')
	assert(Element.getPropNumber('GTA_PanelProp') == length(GTA_PanelProp.getProps()), ...
		[BRAPH2.STR ':GTA_PanelProp:' BRAPH2.FAIL_TEST], ...
		'Element.getPropNumber(''GTA_PanelProp'') should return the number of properties.')
	 
	% getPropNumber(category)
	assert(sum(cellfun(@(category) GTA_PanelProp.getPropNumber(category), categories)) == GTA_PanelProp.getPropNumber(), ...
		[BRAPH2.STR ':GTA_PanelProp:' BRAPH2.FAIL_TEST], ...
		'GTA_PanelProp.getPropNumber(category) does not work.')
	assert(sum(cellfun(@(category) gt.getPropNumber(category), categories)) == GTA_PanelProp.getPropNumber(), ...
		[BRAPH2.STR ':GTA_PanelProp:' BRAPH2.FAIL_TEST], ...
		'gt.getPropNumber(category) does not work.')
	assert(sum(cellfun(@(category) Element.getPropNumber(gt, category), categories)) == GTA_PanelProp.getPropNumber(), ...
		[BRAPH2.STR ':GTA_PanelProp:' BRAPH2.FAIL_TEST], ...
		'Element.getPropNumber(gt, category) does not work.')
	assert(sum(cellfun(@(category) Element.getPropNumber('GTA_PanelProp', category), categories)) == GTA_PanelProp.getPropNumber(), ...
		[BRAPH2.STR ':GTA_PanelProp:' BRAPH2.FAIL_TEST], ...
		'Element.getPropNumber(''GTA_PanelProp'', category) does not work.')
	 
	% existsProp(prop)
	assert(~GTA_PanelProp.existsProp(NaN), ...
		[BRAPH2.STR ':GTA_PanelProp:' BRAPH2.FAIL_TEST], ...
		'GTA_PanelProp.existsProp(prop) does not work.')
	assert(~gt.existsProp(NaN), ...
		[BRAPH2.STR ':GTA_PanelProp:' BRAPH2.FAIL_TEST], ...
		'gt.existsProp(prop) does not work.')
	assert(~Element.existsProp(gt, NaN), ...
		[BRAPH2.STR ':GTA_PanelProp:' BRAPH2.FAIL_TEST], ...
		'Element.existsProp(gt, prop) does not work.')
	assert(~Element.existsProp('GTA_PanelProp', NaN), ...
		[BRAPH2.STR ':GTA_PanelProp:' BRAPH2.FAIL_TEST], ...
		'Element.existsProp(''GTA_PanelProp'', prop) does not work.')
	 
	assert_with_error('GTA_PanelProp.existsProp(NaN)', [BRAPH2.STR ':GTA_PanelProp:' BRAPH2.WRONG_INPUT])
	assert_with_error('varargin{1}.existsProp(NaN)', [BRAPH2.STR ':GTA_PanelProp:' BRAPH2.WRONG_INPUT], gt)
	assert_with_error('Element.existsProp(varargin{1}, NaN)', [BRAPH2.STR ':GTA_PanelProp:' BRAPH2.WRONG_INPUT], gt)
	assert_with_error('Element.existsProp(''GTA_PanelProp'', NaN)', [BRAPH2.STR ':GTA_PanelProp:' BRAPH2.WRONG_INPUT])
	 
	for prop = 1:1:GTA_PanelProp.getPropNumber()
		assert(GTA_PanelProp.existsProp(prop), ...
			[BRAPH2.STR ':GTA_PanelProp:' BRAPH2.FAIL_TEST], ...
			'GTA_PanelProp.existsProp(prop) does not work.')
		assert(gt.existsProp(prop), ...
			[BRAPH2.STR ':GTA_PanelProp:' BRAPH2.FAIL_TEST], ...
			'gt.existsProp(prop) does not work.')
		assert(Element.existsProp(gt, prop), ...
			[BRAPH2.STR ':GTA_PanelProp:' BRAPH2.FAIL_TEST], ...
			'Element.existsProp(gt, prop) does not work.')
		assert(Element.existsProp('GTA_PanelProp', prop), ...
			[BRAPH2.STR ':GTA_PanelProp:' BRAPH2.FAIL_TEST], ...
			'Element.existsProp(''GTA_PanelProp'', prop) does not work.')
	end
	 
	% existsTag(tag)
	assert(~GTA_PanelProp.existsTag(''), ...
		[BRAPH2.STR ':GTA_PanelProp:' BRAPH2.FAIL_TEST], ...
		'GTA_PanelProp.existsTag(tag) does not work.')
	assert(~gt.existsTag(''), ...
		[BRAPH2.STR ':GTA_PanelProp:' BRAPH2.FAIL_TEST], ...
		'gt.existsTag(tag) does not work.')
	assert(~Element.existsTag(gt, ''), ...
		[BRAPH2.STR ':GTA_PanelProp:' BRAPH2.FAIL_TEST], ...
		'Element.existsTag(gt, tag) does not work.')
	assert(~Element.existsTag('GTA_PanelProp', ''), ...
		[BRAPH2.STR ':GTA_PanelProp:' BRAPH2.FAIL_TEST], ...
		'Element.existsTag(''GTA_PanelProp'', tag) does not work.')
	 
	assert_with_error('GTA_PanelProp.existsTag('''')', [BRAPH2.STR ':GTA_PanelProp:' BRAPH2.WRONG_INPUT])
	assert_with_error('varargin{1}.existsTag('''')', [BRAPH2.STR ':GTA_PanelProp:' BRAPH2.WRONG_INPUT], gt)
	assert_with_error('Element.existsTag(varargin{1}, '''')', [BRAPH2.STR ':GTA_PanelProp:' BRAPH2.WRONG_INPUT], gt)
	assert_with_error('Element.existsTag(''GTA_PanelProp'', '''')', [BRAPH2.STR ':GTA_PanelProp:' BRAPH2.WRONG_INPUT])
	 
	for prop = 1:1:GTA_PanelProp.getPropNumber()
		tag = gt.getPropTag(prop);
		assert(GTA_PanelProp.existsTag(tag), ...
			[BRAPH2.STR ':GTA_PanelProp:' BRAPH2.FAIL_TEST], ...
			'GTA_PanelProp.existsTag(tag) does not work.')
		assert(gt.existsTag(tag), ...
			[BRAPH2.STR ':GTA_PanelProp:' BRAPH2.FAIL_TEST], ...
			'gt.existsTag(tag) does not work.')
		assert(Element.existsTag(gt, tag), ...
			[BRAPH2.STR ':GTA_PanelProp:' BRAPH2.FAIL_TEST], ...
			'Element.existsTag(gt, tga) does not work.')
		assert(Element.existsTag('GTA_PanelProp', tag), ...
			[BRAPH2.STR ':GTA_PanelProp:' BRAPH2.FAIL_TEST], ...
			'Element.existsTag(''GTA_PanelProp'', tag) does not work.')
	end
	 
	% getPropProp(pointer)
	for prop = 1:1:GTA_PanelProp.getPropNumber()
		assert(GTA_PanelProp.getPropProp(prop) == prop, ...
			[BRAPH2.STR ':GTA_PanelProp:' BRAPH2.FAIL_TEST], ...
			'GTA_PanelProp.getPropProp(prop) does not work.')
		assert(gt.getPropProp(prop) == prop, ...
			[BRAPH2.STR ':GTA_PanelProp:' BRAPH2.FAIL_TEST], ...
			'gt.getPropProp(prop) does not work.')
		assert(Element.getPropProp(gt, prop) == prop, ...
			[BRAPH2.STR ':GTA_PanelProp:' BRAPH2.FAIL_TEST], ...
			'Element.getPropProp(gt, prop) does not work.')
		assert(Element.getPropProp('GTA_PanelProp', prop) == prop, ...
			[BRAPH2.STR ':GTA_PanelProp:' BRAPH2.FAIL_TEST], ...
			'Element.getPropProp(''GTA_PanelProp'', prop) does not work.')
	 
		tag = gt.getPropTag(prop);
		assert(GTA_PanelProp.getPropProp(tag) == prop, ...
			[BRAPH2.STR ':GTA_PanelProp:' BRAPH2.FAIL_TEST], ...
			'GTA_PanelProp.getPropProp(tag) does not work.')
		assert(gt.getPropProp(tag) == prop, ...
			[BRAPH2.STR ':GTA_PanelProp:' BRAPH2.FAIL_TEST], ...
			'gt.getPropProp(tag) does not work.')
		assert(Element.getPropProp(gt, tag) == prop, ...
			[BRAPH2.STR ':GTA_PanelProp:' BRAPH2.FAIL_TEST], ...
			'Element.getPropProp(gt, tag) does not work.')
		assert(Element.getPropProp('GTA_PanelProp', prop) == prop, ...
			[BRAPH2.STR ':GTA_PanelProp:' BRAPH2.FAIL_TEST], ...
			'Element.getPropProp(''GTA_PanelProp'', tag) does not work.')
	end
	 
	% getPropTag(pointer)
	for prop = 1:1:GTA_PanelProp.getPropNumber()
		tag = gt.getPropTag(prop);
	 
		assert(strcmp(GTA_PanelProp.getPropTag(prop), tag), ...
			[BRAPH2.STR ':GTA_PanelProp:' BRAPH2.FAIL_TEST], ...
			'GTA_PanelProp.getPropTag(prop) does not work.')
		assert(strcmp(gt.getPropTag(prop), tag), ...
			[BRAPH2.STR ':GTA_PanelProp:' BRAPH2.FAIL_TEST], ...
			'gt.getPropTag(prop) does not work.')
		assert(strcmp(Element.getPropTag(gt, prop), tag), ...
			[BRAPH2.STR ':GTA_PanelProp:' BRAPH2.FAIL_TEST], ...
			'Element.getPropTag(gt, prop) does not work.')
		assert(strcmp(Element.getPropTag('GTA_PanelProp', prop), tag), ...
			[BRAPH2.STR ':GTA_PanelProp:' BRAPH2.FAIL_TEST], ...
			'Element.getPropTag(''GTA_PanelProp'', prop) does not work.')
	 
		assert(strcmp(GTA_PanelProp.getPropTag(tag), tag), ...
			[BRAPH2.STR ':GTA_PanelProp:' BRAPH2.FAIL_TEST], ...
			'GTA_PanelProp.getPropTag(tag) does not work.')
		assert(strcmp(gt.getPropTag(tag), tag), ...
			[BRAPH2.STR ':GTA_PanelProp:' BRAPH2.FAIL_TEST], ...
			'gt.getPropTag(tag) does not work.')
		assert(strcmp(Element.getPropTag(gt, tag), tag), ...
			[BRAPH2.STR ':GTA_PanelProp:' BRAPH2.FAIL_TEST], ...
			'Element.getPropTag(gt, tag) does not work.')
		assert(strcmp(Element.getPropTag('GTA_PanelProp', prop), tag), ...
			[BRAPH2.STR ':GTA_PanelProp:' BRAPH2.FAIL_TEST], ...
			'Element.getPropTag(''GTA_PanelProp'', tag) does not work.')
	end
	 
	% getPropCategory(pointer)
	for prop = 1:1:GTA_PanelProp.getPropNumber()
		tag = gt.getPropTag(prop);
	 
		assert(Category.existsCategory(GTA_PanelProp.getPropCategory(prop)), ...
			[BRAPH2.STR ':GTA_PanelProp:' BRAPH2.FAIL_TEST], ...
			'GTA_PanelProp.getPropCategory(prop) does not work.')
		assert(Category.existsCategory(gt.getPropCategory(prop)), ...
			[BRAPH2.STR ':GTA_PanelProp:' BRAPH2.FAIL_TEST], ...
			'gt.getPropCategory(prop) does not work.')
		assert(Category.existsCategory(Element.getPropCategory(gt, prop)), ...
			[BRAPH2.STR ':GTA_PanelProp:' BRAPH2.FAIL_TEST], ...
			'Element.getPropCategory(gt, prop) does not work.')
		assert(Category.existsCategory(Element.getPropCategory(gt, prop)), ...
			[BRAPH2.STR ':GTA_PanelProp:' BRAPH2.FAIL_TEST], ...
			'Element.getPropCategory(''GTA_PanelProp'', prop) does not work.')
	 
		assert(Category.existsCategory(GTA_PanelProp.getPropCategory(tag)), ...
			[BRAPH2.STR ':GTA_PanelProp:' BRAPH2.FAIL_TEST], ...
			'GTA_PanelProp.getPropCategory(tag) does not work.')
		assert(Category.existsCategory(gt.getPropCategory(tag)), ...
			[BRAPH2.STR ':GTA_PanelProp:' BRAPH2.FAIL_TEST], ...
			'gt.getPropCategory(tag) does not work.')
		assert(Category.existsCategory(Element.getPropCategory(gt, tag)), ...
			[BRAPH2.STR ':GTA_PanelProp:' BRAPH2.FAIL_TEST], ...
			'Element.getPropCategory(gt, tag) does not work.')
		assert(Category.existsCategory(Element.getPropCategory(gt, tag)), ...
			[BRAPH2.STR ':GTA_PanelProp:' BRAPH2.FAIL_TEST], ...
			'Element.getPropCategory(''GTA_PanelProp'', tag) does not work.')
	end
	 
	% getPropFormat(pointer)
	for prop = 1:1:GTA_PanelProp.getPropNumber()
		tag = gt.getPropTag(prop);
	 
		assert(Format.existsFormat(GTA_PanelProp.getPropFormat(prop)), ...
			[BRAPH2.STR ':GTA_PanelProp:' BRAPH2.FAIL_TEST], ...
			'GTA_PanelProp.getPropFormat(prop) does not work.')
		assert(Format.existsFormat(gt.getPropFormat(prop)), ...
			[BRAPH2.STR ':GTA_PanelProp:' BRAPH2.FAIL_TEST], ...
			'gt.getPropFormat(prop) does not work.')
		assert(Format.existsFormat(Element.getPropFormat(gt, prop)), ...
			[BRAPH2.STR ':GTA_PanelProp:' BRAPH2.FAIL_TEST], ...
			'Element.getPropFormat(gt, prop) does not work.')
		assert(Format.existsFormat(Element.getPropFormat(gt, prop)), ...
			[BRAPH2.STR ':GTA_PanelProp:' BRAPH2.FAIL_TEST], ...
			'Element.getPropFormat(''GTA_PanelProp'', prop) does not work.')
	 
		assert(Format.existsFormat(GTA_PanelProp.getPropFormat(tag)), ...
			[BRAPH2.STR ':GTA_PanelProp:' BRAPH2.FAIL_TEST], ...
			'GTA_PanelProp.getPropFormat(tag) does not work.')
		assert(Format.existsFormat(gt.getPropFormat(tag)), ...
			[BRAPH2.STR ':GTA_PanelProp:' BRAPH2.FAIL_TEST], ...
			'gt.getPropFormat(tag) does not work.')
		assert(Format.existsFormat(Element.getPropFormat(gt, tag)), ...
			[BRAPH2.STR ':GTA_PanelProp:' BRAPH2.FAIL_TEST], ...
			'Element.getPropFormat(gt, tag) does not work.')
		assert(Format.existsFormat(Element.getPropFormat(gt, tag)), ...
			[BRAPH2.STR ':GTA_PanelProp:' BRAPH2.FAIL_TEST], ...
			'Element.getPropFormat(''GTA_PanelProp'', tag) does not work.')
	end
	 
	% getPropDescription(pointer)
	for prop = 1:1:GTA_PanelProp.getPropNumber()
		tag = gt.getPropTag(prop);
	 
		assert(ischar(GTA_PanelProp.getPropDescription(prop)), ...
			[BRAPH2.STR ':GTA_PanelProp:' BRAPH2.FAIL_TEST], ...
			'GTA_PanelProp.getPropDescription(prop) does not work.')
		assert(ischar(gt.getPropDescription(prop)), ...
			[BRAPH2.STR ':GTA_PanelProp:' BRAPH2.FAIL_TEST], ...
			'gt.getPropDescription(prop) does not work.')
		assert(ischar(Element.getPropDescription(gt, prop)), ...
			[BRAPH2.STR ':GTA_PanelProp:' BRAPH2.FAIL_TEST], ...
			'Element.getPropDescription(gt, prop) does not work.')
		assert(ischar(Element.getPropDescription(gt, prop)), ...
			[BRAPH2.STR ':GTA_PanelProp:' BRAPH2.FAIL_TEST], ...
			'Element.getPropDescription(''GTA_PanelProp'', prop) does not work.')
	 
		assert(ischar(GTA_PanelProp.getPropDescription(tag)), ...
			[BRAPH2.STR ':GTA_PanelProp:' BRAPH2.FAIL_TEST], ...
			'GTA_PanelProp.getPropDescription(tag) does not work.')
		assert(ischar(gt.getPropDescription(tag)), ...
			[BRAPH2.STR ':GTA_PanelProp:' BRAPH2.FAIL_TEST], ...
			'gt.getPropDescription(tag) does not work.')
		assert(ischar(Element.getPropDescription(gt, tag)), ...
			[BRAPH2.STR ':GTA_PanelProp:' BRAPH2.FAIL_TEST], ...
			'Element.getPropDescription(gt, tag) does not work.')
		assert(ischar(Element.getPropDescription(gt, tag)), ...
			[BRAPH2.STR ':GTA_PanelProp:' BRAPH2.FAIL_TEST], ...
			'Element.getPropDescription(''GTA_PanelProp'', tag) does not work.')
	end
	 
	% getPropSettings(pointer)
	for prop = 1:1:GTA_PanelProp.getPropNumber()
		tag = gt.getPropTag(prop);
	 
		settings = GTA_PanelProp.getPropSettings(prop);
		settings = gt.getPropSettings(prop);
		settings = Element.getPropSettings(gt, prop);
		settings = Element.getPropSettings('GTA_PanelProp', prop);
	 
		settings = GTA_PanelProp.getPropSettings(tag);
		settings = gt.getPropSettings(tag);
		settings = Element.getPropSettings(gt, tag);
		settings = Element.getPropSettings('GTA_PanelProp', tag);
	end
	 
	% getPropDefault(pointer)
	for prop = 1:1:GTA_PanelProp.getPropNumber()
		tag = gt.getPropTag(prop);
	 
		default = GTA_PanelProp.getPropDefault(prop);
		default = gt.getPropDefault(prop);
		default = Element.getPropDefault(gt, prop);
		default = Element.getPropDefault('GTA_PanelProp', prop);
	 
		default = GTA_PanelProp.getPropDefault(tag);
		default = gt.getPropDefault(tag);
		default = Element.getPropDefault(gt, tag);
		default = Element.getPropDefault('GTA_PanelProp', tag);
	end
	 
	% getPropDefaultConditioned(pointer)
	for prop = 1:1:GTA_PanelProp.getPropNumber()
		tag = gt.getPropTag(prop);
	 
		conditioned_default = GTA_PanelProp.getPropDefaultConditioned(prop);
		conditioned_default = gt.getPropDefaultConditioned(prop);
		conditioned_default = Element.getPropDefaultConditioned(gt, prop);
		conditioned_default = Element.getPropDefaultConditioned('GTA_PanelProp', prop);
	 
		conditioned_default = GTA_PanelProp.getPropDefaultConditioned(tag);
		conditioned_default = gt.getPropDefaultConditioned(tag);
		conditioned_default = Element.getPropDefaultConditioned(gt, tag);
		conditioned_default = Element.getPropDefaultConditioned('GTA_PanelProp', tag);
	end
	 
	% checkProp(pointer, value)
	for prop = 1:1:GTA_PanelProp.getPropNumber()
		tag = gt.getPropTag(prop);
	 
		assert(~GTA_PanelProp.checkProp(prop, {'probably wrong value', 1}), ...
			[BRAPH2.STR ':GTA_PanelProp:' BRAPH2.FAIL_TEST], ...
			'GTA_PanelProp.checkProp(prop, value) does not work.')
		assert(~gt.checkProp(prop, {'probably wrong value', 1}), ...
			[BRAPH2.STR ':GTA_PanelProp:' BRAPH2.FAIL_TEST], ...
			'gt.checkProp(prop, value) does not work.')
		assert(~Element.checkProp(gt, prop, {'probably wrong value', 1}), ...
			[BRAPH2.STR ':GTA_PanelProp:' BRAPH2.FAIL_TEST], ...
			'Element.checkProp(gt, prop, value) does not work.')
		assert(~Element.checkProp('GTA_PanelProp', prop, {'probably wrong value', 1}), ...
			[BRAPH2.STR ':GTA_PanelProp:' BRAPH2.FAIL_TEST], ...
			'Element.checkProp(''GTA_PanelProp'', prop, value) does not work.')
	 
		assert_with_error('GTA_PanelProp.checkProp(varargin{1}, {''probably wrong value'', 1})', [BRAPH2.STR ':GTA_PanelProp:' BRAPH2.WRONG_INPUT], prop)
		assert_with_error('varargin{2}.checkProp(varargin{1}, {''probably wrong value'', 1})', [BRAPH2.STR ':GTA_PanelProp:' BRAPH2.WRONG_INPUT], prop, gt)
		assert_with_error('Element.checkProp(varargin{2}, varargin{1}, {''probably wrong value'', 1})', [BRAPH2.STR ':GTA_PanelProp:' BRAPH2.WRONG_INPUT], prop, gt)
		assert_with_error('Element.checkProp(''GTA_PanelProp'', varargin{1}, {''probably wrong value'', 1})', [BRAPH2.STR ':GTA_PanelProp:' BRAPH2.WRONG_INPUT], prop)
	 
		assert(~GTA_PanelProp.checkProp(tag, {'probably wrong value', 1}), ...
			[BRAPH2.STR ':GTA_PanelProp:' BRAPH2.FAIL_TEST], ...
			'GTA_PanelProp.checkProp(tag, value) does not work.')
		assert(~gt.checkProp(tag, {'probably wrong value', 1}), ...
			[BRAPH2.STR ':GTA_PanelProp:' BRAPH2.FAIL_TEST], ...
			'gt.checkProp(tag, value) does not work.')
		assert(~Element.checkProp(gt, tag, {'probably wrong value', 1}), ...
			[BRAPH2.STR ':GTA_PanelProp:' BRAPH2.FAIL_TEST], ...
			'Element.checkProp(gt, tag, value) does not work.')
		assert(~Element.checkProp('GTA_PanelProp', tag, {'probably wrong value', 1}), ...
			[BRAPH2.STR ':GTA_PanelProp:' BRAPH2.FAIL_TEST], ...
			'Element.checkProp(''GTA_PanelProp'', tag, value) does not work.')
	 
		assert_with_error('GTA_PanelProp.checkProp(varargin{1}, {''probably wrong value'', 1})', [BRAPH2.STR ':GTA_PanelProp:' BRAPH2.WRONG_INPUT], tag)
		assert_with_error('varargin{2}.checkProp(varargin{1}, {''probably wrong value'', 1})', [BRAPH2.STR ':GTA_PanelProp:' BRAPH2.WRONG_INPUT], tag, gt)
		assert_with_error('Element.checkProp(varargin{2}, varargin{1}, {''probably wrong value'', 1})', [BRAPH2.STR ':GTA_PanelProp:' BRAPH2.WRONG_INPUT], tag, gt)
		assert_with_error('Element.checkProp(''GTA_PanelProp'', varargin{1}, {''probably wrong value'', 1})', [BRAPH2.STR ':GTA_PanelProp:' BRAPH2.WRONG_INPUT], tag)
	 
		assert(GTA_PanelProp.checkProp(prop, Element.getPropDefaultConditioned(GTA_PanelProp, prop)), ...
			[BRAPH2.STR ':GTA_PanelProp:' BRAPH2.FAIL_TEST], ...
			'GTA_PanelProp.checkProp(prop, <conditioned default value>) does not work.')
		assert(gt.checkProp(prop, Element.getPropDefaultConditioned(GTA_PanelProp, prop)), ...
			[BRAPH2.STR ':GTA_PanelProp:' BRAPH2.FAIL_TEST], ...
			'gt.checkProp(prop, <conditioned default value>) does not work.')
		assert(Element.checkProp(gt, prop, Element.getPropDefaultConditioned(GTA_PanelProp, prop)), ...
			[BRAPH2.STR ':GTA_PanelProp:' BRAPH2.FAIL_TEST], ...
			'Element.checkProp(gt, prop, <conditioned default value>) does not work.')
		assert(Element.checkProp('GTA_PanelProp', prop, Element.getPropDefaultConditioned(GTA_PanelProp, prop)), ...
			[BRAPH2.STR ':GTA_PanelProp:' BRAPH2.FAIL_TEST], ...
			'Element.checkProp(''GTA_PanelProp'', prop, <conditioned default value>) does not work.')
	 
		assert(GTA_PanelProp.checkProp(tag, Element.getPropDefaultConditioned(GTA_PanelProp, prop)), ...
			[BRAPH2.STR ':GTA_PanelProp:' BRAPH2.FAIL_TEST], ...
			'GTA_PanelProp.checkProp(tag, <conditioned default value>) does not work.')
		assert(gt.checkProp(tag, Element.getPropDefaultConditioned(GTA_PanelProp, prop)), ...
			[BRAPH2.STR ':GTA_PanelProp:' BRAPH2.FAIL_TEST], ...
			'gt.checkProp(tag, <conditioned default value>) does not work.')
		assert(Element.checkProp(gt, tag, Element.getPropDefaultConditioned(GTA_PanelProp, prop)), ...
			[BRAPH2.STR ':GTA_PanelProp:' BRAPH2.FAIL_TEST], ...
			'Element.checkProp(gt, tag, <conditioned default value>) does not work.')
		assert(Element.checkProp('GTA_PanelProp', tag, Element.getPropDefaultConditioned(GTA_PanelProp, prop)), ...
			[BRAPH2.STR ':GTA_PanelProp:' BRAPH2.FAIL_TEST], ...
			'Element.checkProp(''GTA_PanelProp'', tag, <conditioned default value>) does not work.')
	 
	end
	 
end

%% Test 2: Instantiation - defaults
if rand() >= (1 - .01) * BRAPH2TEST.RANDOM
	gt = GTA_PanelProp( ...
		GTA_PanelProp.ELCLASS, GTA_PanelProp.getNoValue(), ...
		GTA_PanelProp.NAME, GTA_PanelProp.getNoValue(), ...
		GTA_PanelProp.DESCRIPTION, GTA_PanelProp.getNoValue(), ...
		GTA_PanelProp.TEMPLATE, GTA_PanelProp.getPropDefault(GTA_PanelProp.TEMPLATE), ...
		GTA_PanelProp.ID, GTA_PanelProp.getPropDefault(GTA_PanelProp.ID), ...
		GTA_PanelProp.LABEL, GTA_PanelProp.getPropDefault(GTA_PanelProp.LABEL), ...
		GTA_PanelProp.NOTES, GTA_PanelProp.getPropDefault(GTA_PanelProp.NOTES), ...
		GTA_PanelProp.TOSTRING, GTA_PanelProp.getNoValue(), ...
		GTA_PanelProp.ST_C, GTA_PanelProp.getNoValue(), ...
		GTA_PanelProp.ST_M, GTA_PanelProp.getPropDefault(GTA_PanelProp.ST_M), ...
		GTA_PanelProp.ST_P, GTA_PanelProp.getPropDefault(GTA_PanelProp.ST_P), ...
		GTA_PanelProp.ST_D, GTA_PanelProp.getPropDefault(GTA_PanelProp.ST_D), ...
		GTA_PanelProp.ST_R, GTA_PanelProp.getNoValue(), ...
		GTA_PanelProp.ST_Q, GTA_PanelProp.getNoValue(), ...
		GTA_PanelProp.ST_E, GTA_PanelProp.getNoValue(), ...
		GTA_PanelProp.ST_F, GTA_PanelProp.getPropDefault(GTA_PanelProp.ST_F), ...
		GTA_PanelProp.ST_G, GTA_PanelProp.getPropDefault(GTA_PanelProp.ST_G) ...
		);
	 
	for prop = 1:1:GTA_PanelProp.getPropNumber()
	 
		% excluded props
		if any(prop == [])
			continue
		end
	 
		TAG = upper(GTA_PanelProp.getPropTag(prop));
		switch GTA_PanelProp.getPropCategory(prop)
			case {Category.CONSTANT, Category.RESULT, Category.QUERY}
				% getr
				assert( ...
					gt.getr(prop) == GTA_PanelProp.getNoValue(), ...
					[BRAPH2.STR ':GTA_PanelProp:' BRAPH2.FAIL_TEST], ...
					['Being a ' GTA_PanelProp.getCategoryName(GTA_PanelProp.getPropCategory(prop)) ', GTA_PanelProp.getr(' int2str(prop) ') must be inizialized to NoValue(). ' ...
					'Or there could be an error in GTA_PanelProp.getr(' int2str(prop) ').'] ...
					)
				assert( ...
					gt.getr(TAG) == GTA_PanelProp.getNoValue(), ...
					[BRAPH2.STR ':GTA_PanelProp:' BRAPH2.FAIL_TEST], ...
					['Being a ' GTA_PanelProp.getCategoryName(GTA_PanelProp.getPropCategory(prop)) ', GTA_PanelProp.getr(' TAG ') must be inizialized to NoValue(). ' ...
					'Or there could be an error in GTA_PanelProp.getr(' TAG ').'] ...
					)
				% get
				assert( ...
					~isa(gt.get(prop), 'NoValue'), ...
					[BRAPH2.STR ':GTA_PanelProp:' BRAPH2.FAIL_TEST], ...
					['GTA_PanelProp.get(' int2str(prop) ') must NOT be a NoValue, because it should have been calculated.'] ...
					)
				if isempty(gt.getPropSettings(prop))
					assert( ...
						gt.checkFormat(gt.getPropFormat(prop), gt.get(prop)), ...
						[BRAPH2.STR ':GTA_PanelProp:' BRAPH2.FAIL_TEST], ...
						['GTA_PanelProp.get(' int2str(prop) ') returns a value with the wrong format.'] ...
						)
				else
					assert( ...
						gt.checkFormat(gt.getPropFormat(prop), gt.get(prop), gt.getPropSettings(prop)), ...
						[BRAPH2.STR ':GTA_PanelProp:' BRAPH2.FAIL_TEST], ...
						['GTA_PanelProp.get(' int2str(prop) ') returns a value with the wrong format.'] ...
						)
				end
			case Category.EVANESCENT
				% getr
				assert( ...
					gt.getr(prop) == GTA_PanelProp.getNoValue(), ...
					[BRAPH2.STR ':GTA_PanelProp:' BRAPH2.FAIL_TEST], ...
					['Being a ' GTA_PanelProp.getCategoryName(GTA_PanelProp.getPropCategory(prop)) ', GTA_PanelProp.getr(' int2str(prop) ') must be inizialized to NoValue(). ' ...
					'Or there could be an error in GTA_PanelProp.getr(' int2str(prop) ').'] ...
					)
				assert( ...
					gt.getr(TAG) == GTA_PanelProp.getNoValue(), ...
					[BRAPH2.STR ':GTA_PanelProp:' BRAPH2.FAIL_TEST], ...
					['Being a ' GTA_PanelProp.getCategoryName(GTA_PanelProp.getPropCategory(prop)) ', GTA_PanelProp.getr(' TAG ') must be inizialized to NoValue(). ' ...
					'Or there could be an error in GTA_PanelProp.getr(' TAG ').'] ...
					)
				% get
				warning_backup = warning('off', [BRAPH2.STR ':GTA_PanelProp']);
				assert( ...
					~isa(gt.get(prop), 'NoValue'), ...
					[BRAPH2.STR ':GTA_PanelProp:' BRAPH2.FAIL_TEST], ...
					['GTA_PanelProp.get(' int2str(prop) ') must NOT be a NoValue, because it should have been calculated.'] ...
					)
				if isempty(gt.getPropSettings(prop))
					assert( ...
						gt.checkFormat(gt.getPropFormat(prop), gt.get(prop)), ...
						[BRAPH2.STR ':GTA_PanelProp:' BRAPH2.FAIL_TEST], ...
						['GTA_PanelProp.get(' int2str(prop) ') returns a value with the wrong format.'] ...
						)
				else
					assert( ...
						gt.checkFormat(gt.getPropFormat(prop), gt.get(prop), gt.getPropSettings(prop)), ...
						[BRAPH2.STR ':GTA_PanelProp:' BRAPH2.FAIL_TEST], ...
						['GTA_PanelProp.get(' int2str(prop) ') returns a value with the wrong format.'] ...
						)
				end
				warning(warning_backup)
			otherwise % case {Category.METADATA, Category.PARAMETER, Category.DATA, Category.FIGURE, Category.GUI}
				assert( ...
					isequal(gt.getr(prop), GTA_PanelProp.getPropDefaultConditioned(prop)), ...
					[BRAPH2.STR ':GTA_PanelProp:' BRAPH2.FAIL_TEST], ...
					['GTA_PanelProp.getr(' int2str(prop) ') must be inizialized to its default value ' ...
					'given by GTA_PanelProp.getPropDefaultConditioned(' int2str(prop) '). ' ...
					'Or there could be an error in GTA_PanelProp.getr(' int2str(prop) ').'] ...
					)
				assert( ...
					isequal(gt.getr(TAG), GTA_PanelProp.getPropDefaultConditioned(prop)), ...
					[BRAPH2.STR ':GTA_PanelProp:' BRAPH2.FAIL_TEST], ...
					['GTA_PanelProp.getr(' TAG ') must be inizialized to its default value ' ...
					'given by GTA_PanelProp.getPropDefaultConditioned(' int2str(prop) '). ' ...
					'Or there could be an error in GTA_PanelProp.getr(' TAG ').'] ...
					)
		end
	end
end

%% Test 3: Memorize
if rand() >= (1 - .01) * BRAPH2TEST.RANDOM
	gt = GTA_PanelProp( ...
		GTA_PanelProp.ELCLASS, GTA_PanelProp.getNoValue(), ...
		GTA_PanelProp.NAME, GTA_PanelProp.getNoValue(), ...
		GTA_PanelProp.DESCRIPTION, GTA_PanelProp.getNoValue(), ...
		GTA_PanelProp.TEMPLATE, GTA_PanelProp.getPropDefault(GTA_PanelProp.TEMPLATE), ...
		GTA_PanelProp.ID, GTA_PanelProp.getPropDefault(GTA_PanelProp.ID), ...
		GTA_PanelProp.LABEL, GTA_PanelProp.getPropDefault(GTA_PanelProp.LABEL), ...
		GTA_PanelProp.NOTES, GTA_PanelProp.getPropDefault(GTA_PanelProp.NOTES), ...
		GTA_PanelProp.TOSTRING, GTA_PanelProp.getNoValue(), ...
		GTA_PanelProp.ST_C, GTA_PanelProp.getNoValue(), ...
		GTA_PanelProp.ST_M, GTA_PanelProp.getPropDefault(GTA_PanelProp.ST_M), ...
		GTA_PanelProp.ST_P, GTA_PanelProp.getPropDefault(GTA_PanelProp.ST_P), ...
		GTA_PanelProp.ST_D, GTA_PanelProp.getPropDefault(GTA_PanelProp.ST_D), ...
		GTA_PanelProp.ST_R, GTA_PanelProp.getNoValue(), ...
		GTA_PanelProp.ST_Q, GTA_PanelProp.getNoValue(), ...
		GTA_PanelProp.ST_E, GTA_PanelProp.getNoValue(), ...
		GTA_PanelProp.ST_F, GTA_PanelProp.getPropDefault(GTA_PanelProp.ST_F), ...
		GTA_PanelProp.ST_G, GTA_PanelProp.getPropDefault(GTA_PanelProp.ST_G) ...
		);
	 
	for prop = 1:1:GTA_PanelProp.getPropNumber()
	 
		% excluded props
		if any(prop == [])
			continue
		end
	 
		TAG = upper(GTA_PanelProp.getPropTag(prop));
		switch GTA_PanelProp.getPropCategory(prop)
			case Category.RESULT
				assert( ...
					~isa(gt.get(prop), 'NoValue'), ...
					[BRAPH2.STR ':GTA_PanelProp:' BRAPH2.FAIL_TEST], ...
					['GTA_PanelProp.get(' int2str(prop) ') must NOT be a NoValue, because it should have been calculated.'] ...
					)
				assert( ...
					isa(gt.getr(prop), 'NoValue'), ...
					[BRAPH2.STR ':GTA_PanelProp:' BRAPH2.FAIL_TEST], ...
					['GTA_PanelProp.getr(' int2str(prop) ') must be a NoValue, because it should NOT have been memorized.'] ...
					)
				assert( ...
					~isa(gt.memorize(prop), 'NoValue'), ...
					[BRAPH2.STR ':GTA_PanelProp:' BRAPH2.FAIL_TEST], ...
					['GTA_PanelProp.memorize(' int2str(prop) ') must NOT be a NoValue, because it should have been calculated.'] ...
					)
				assert( ...
					~isa(gt.getr(prop), 'NoValue'), ...
					[BRAPH2.STR ':GTA_PanelProp:' BRAPH2.FAIL_TEST], ...
					['GTA_PanelProp.getr(' int2str(prop) ') must NOT be a NoValue, because it should have been memorized.'] ...
					)
				assert( ...
					gt.checkFormat(gt.getPropFormat(prop), gt.getr(prop),gt.getPropSettings(prop)), ...
					[BRAPH2.STR ':GTA_PanelProp:' BRAPH2.FAIL_TEST], ...
					['GTA_PanelProp.getr(' int2str(prop) ') returns a value with the wrong format.'] ...
					)
			case Category.QUERY
	% 			warning_backup = warning('off', [BRAPH2.STR ':GTA_PanelProp']);
				assert( ...
					~isa(gt.get(prop), 'NoValue'), ...
					[BRAPH2.STR ':GTA_PanelProp:' BRAPH2.FAIL_TEST], ...
					['GTA_PanelProp.get(' int2str(prop) ') must NOT be a NoValue, because it should have been calculated.'] ...
					)
				assert( ...
					isa(gt.getr(prop), 'NoValue'), ...
					[BRAPH2.STR ':GTA_PanelProp:' BRAPH2.FAIL_TEST], ...
					['GTA_PanelProp.getr(' int2str(prop) ') must be a NoValue, because it should NOT have been memorized.'] ...
					)
	% following tests excluded because properties QUERY should not be memorized
	% 			warning_backup = warning('off', [BRAPH2.STR ':GTA_PanelProp']);
	% 			assert( ...
	% 				~isa(gt.memorize(prop), 'NoValue'), ...
	% 				[BRAPH2.STR ':GTA_PanelProp:' BRAPH2.FAIL_TEST], ...
	% 				['GTA_PanelProp.memorize(' int2str(prop) ') must NOT be a NoValue, because it should have been calculated.'] ...
	% 				)
	% 			warning(warning_backup)
	% 			assert( ...
	% 				~isa(gt.getr(prop), 'NoValue'), ...
	% 				[BRAPH2.STR ':GTA_PanelProp:' BRAPH2.FAIL_TEST], ...
	% 				['GTA_PanelProp.getr(' int2str(prop) ') must NOT be a NoValue, because it should have been memorized.'] ...
	% 				)
	% 			assert( ...
	% 				gt.checkFormat(gt.getPropFormat(prop), gt.getr(prop),gt.getPropSettings(prop)), ...
	% 				[BRAPH2.STR ':GTA_PanelProp:' BRAPH2.FAIL_TEST], ...
	% 				['GTA_PanelProp.getr(' int2str(prop) ') returns a value with the wrong format.'] ...
	% 				)
	% 			warning(warning_backup)
			case Category.EVANESCENT
				warning_backup = warning('off', [BRAPH2.STR ':GTA_PanelProp']);
				assert( ...
					~isa(gt.get(prop), 'NoValue'), ...
					[BRAPH2.STR ':GTA_PanelProp:' BRAPH2.FAIL_TEST], ...
					['GTA_PanelProp.get(' int2str(prop) ') must NOT be a NoValue, because it should have been calculated.'] ...
					)
				warning(warning_backup)
				assert( ...
					isa(gt.getr(prop), 'NoValue'), ...
					[BRAPH2.STR ':GTA_PanelProp:' BRAPH2.FAIL_TEST], ...
					['GTA_PanelProp.getr(' int2str(prop) ') must be a NoValue, because it should NOT have been memorized.'] ...
					)
				assert( ...
					~isa(gt.memorize(prop), 'NoValue'), ...
					[BRAPH2.STR ':GTA_PanelProp:' BRAPH2.FAIL_TEST], ...
					['GTA_PanelProp.memorize(' int2str(prop) ') must NOT be a NoValue, because it should have been calculated.'] ...
					)
				assert( ...
					~isa(gt.getr(prop), 'NoValue'), ...
					[BRAPH2.STR ':GTA_PanelProp:' BRAPH2.FAIL_TEST], ...
					['GTA_PanelProp.getr(' int2str(prop) ') must NOT be a NoValue, because it should have been memorized.'] ...
					)
				assert( ...
					gt.checkFormat(gt.getPropFormat(prop), gt.getr(prop),gt.getPropSettings(prop)), ...
					[BRAPH2.STR ':GTA_PanelProp:' BRAPH2.FAIL_TEST], ...
					['GTA_PanelProp.getr(' int2str(prop) ') returns a value with the wrong format.'] ...
					)
				if gt.getPropFormat(prop) == Format.HANDLE
					warning_backup = warning('off', 'BRAPH2:GTA_PanelProp');
					delete(ancestor(gt.get(prop), 'figure'))
					warning(warning_backup)
				end
		end
	end
	 
	if ~isempty(GTA_PanelProp.getProps(Category.RESULT))
		for prop = 1:1:GTA_PanelProp.getPropNumber()
	 
			% excluded props
			if any(prop == [])
				continue
			end
	 
			switch GTA_PanelProp.getPropCategory(prop)
				case {Category.PARAMETER, Category.DATA}
					assert( ...
						gt.isLocked(prop), ...
						[BRAPH2.STR ':GTA_PanelProp:' BRAPH2.FAIL_TEST], ...
						['GTA_PanelProp.isLocked(' int2str(prop) ') must be locked because a result has been calculated.'] ...
						)
				otherwise
					assert( ...
						~gt.isLocked(prop), ...
						[BRAPH2.STR ':GTA_PanelProp:' BRAPH2.FAIL_TEST], ...
						['GTA_PanelProp.isLocked(' int2str(prop) ') must NOT be locked even though a result has been calculated.'] ...
						)
			end
		end
	end
end

%% Test 4: Lock 1
if rand() >= (1 - .01) * BRAPH2TEST.RANDOM
	gt = GTA_PanelProp();
	 
	for prop = 1:1:GTA_PanelProp.getPropNumber()
		TAG = upper(GTA_PanelProp.getPropTag(prop));
		assert( ...
			~gt.isLocked(prop), ...
			[BRAPH2.STR ':GTA_PanelProp:' BRAPH2.FAIL_TEST], ...
			['GTA_PanelProp.isLocked(' int2str(prop) ') must NOT be locked when it is instantiated.'] ...
			)
		assert( ...
			~gt.isLocked(TAG), ...
			[BRAPH2.STR ':GTA_PanelProp:' BRAPH2.FAIL_TEST], ...
			['GTA_PanelProp.isLocked(' TAG ') must NOT be locked when it is instantiated.'] ...
			)
	end
	 
	gt.lock()
	 
	for prop = 1:1:GTA_PanelProp.getPropNumber()
		switch GTA_PanelProp.getPropCategory(prop)
			case {Category.PARAMETER, Category.DATA}
				assert( ...
					gt.isLocked(prop), ...
					[BRAPH2.STR ':GTA_PanelProp:' BRAPH2.FAIL_TEST], ...
					['GTA_PanelProp.isLocked(' int2str(prop) ') must be locked because the element is now locked.'] ...
					)
			case {Category.CONSTANT, Category.METADATA, Category.RESULT, Category.QUERY, Category.EVANESCENT, Category.FIGURE, Category.GUI}
				assert( ...
					~gt.isLocked(prop), ...
					[BRAPH2.STR ':GTA_PanelProp:' BRAPH2.FAIL_TEST], ...
					['GTA_PanelProp.isLocked(' int2str(prop) ') must NOT be locked even though the element is now locked.'] ...
					)
		end
	end
end

%% Test 5: Lock 2
if rand() >= (1 - .01) * BRAPH2TEST.RANDOM
	gt = GTA_PanelProp();
	 
	warning_backup = warning('off', 'BRAPH2:GTA_PanelProp');
	for prop = 1:1:GTA_PanelProp.getPropNumber()
		gt.lock(prop)
		switch GTA_PanelProp.getPropCategory(prop)
			case {Category.PARAMETER, Category.DATA, Category.FIGURE, Category.GUI}
				assert( ...
					gt.isLocked(prop), ...
					[BRAPH2.STR ':GTA_PanelProp:' BRAPH2.FAIL_TEST], ...
					['GTA_PanelProp.isLocked(' int2str(prop) ') must be locked.'] ...
					)
			case {Category.CONSTANT, Category.METADATA, Category.RESULT, Category.QUERY, Category.EVANESCENT}
				assert( ...
					~gt.isLocked(prop), ...
					[BRAPH2.STR ':GTA_PanelProp:' BRAPH2.FAIL_TEST], ...
					['GTA_PanelProp.isLocked(' int2str(prop) ') must NOT be locked even though locking has been attempted.'] ...
					)
		end
	end
	warning(warning_backup)
end

%% Test 6: Check
if rand() >= (1 - .01) * BRAPH2TEST.RANDOM
	gt = GTA_PanelProp();
	 
	for prop = 1:1:GTA_PanelProp.getPropNumber()
		TAG = upper(GTA_PanelProp.getPropTag(prop));
		assert( ...
			gt.isChecked(prop), ...
			[BRAPH2.STR ':GTA_PanelProp:' BRAPH2.FAIL_TEST], ...
			['GTA_PanelProp.isChecked(' int2str(prop) ') must be checked when it is instantiated.'] ...
			)
		assert( ...
			gt.isChecked(TAG), ...
			[BRAPH2.STR ':GTA_PanelProp:' BRAPH2.FAIL_TEST], ...
			['GTA_PanelProp.isChecked(' TAG ') must be checked when it is instantiated.'] ...
			)
	end
	 
	gt.unchecked()
	 
	for prop = 1:1:GTA_PanelProp.getPropNumber()
		assert( ...
			~gt.isChecked(prop), ...
			[BRAPH2.STR ':GTA_PanelProp:' BRAPH2.FAIL_TEST], ...
			['GTA_PanelProp.isChecked(' int2str(prop) ') must NOT be checked because it has been set to unchecked.'] ...
			)
	end
	 
	gt.checked()
	 
	for prop = 1:1:GTA_PanelProp.getPropNumber()
		assert( ...
			gt.isChecked(prop), ...
			[BRAPH2.STR ':GTA_PanelProp:' BRAPH2.FAIL_TEST], ...
			['GTA_PanelProp.isChecked(' int2str(prop) ') must be checked because it has been set to checked.'] ...
			)
	end
end

%% Test 7: Callbacks
if rand() >= (1 - .01) * BRAPH2TEST.RANDOM
	% basic GTA_PanelProp
	gt_0 = GTA_PanelProp( ...
		GTA_PanelProp.ELCLASS, GTA_PanelProp.getNoValue(), ...
		GTA_PanelProp.NAME, GTA_PanelProp.getNoValue(), ...
		GTA_PanelProp.DESCRIPTION, GTA_PanelProp.getNoValue(), ...
		GTA_PanelProp.TEMPLATE, GTA_PanelProp.getPropDefault(GTA_PanelProp.TEMPLATE), ...
		GTA_PanelProp.ID, GTA_PanelProp.getPropDefault(GTA_PanelProp.ID), ...
		GTA_PanelProp.LABEL, GTA_PanelProp.getPropDefault(GTA_PanelProp.LABEL), ...
		GTA_PanelProp.NOTES, GTA_PanelProp.getPropDefault(GTA_PanelProp.NOTES), ...
		GTA_PanelProp.TOSTRING, GTA_PanelProp.getNoValue(), ...
		GTA_PanelProp.ST_C, GTA_PanelProp.getNoValue(), ...
		GTA_PanelProp.ST_M, GTA_PanelProp.getPropDefault(GTA_PanelProp.ST_M), ...
		GTA_PanelProp.ST_P, GTA_PanelProp.getPropDefault(GTA_PanelProp.ST_P), ...
		GTA_PanelProp.ST_D, GTA_PanelProp.getPropDefault(GTA_PanelProp.ST_D), ...
		GTA_PanelProp.ST_R, GTA_PanelProp.getNoValue(), ...
		GTA_PanelProp.ST_Q, GTA_PanelProp.getNoValue(), ...
		GTA_PanelProp.ST_E, GTA_PanelProp.getNoValue(), ...
		GTA_PanelProp.ST_F, GTA_PanelProp.getPropDefault(GTA_PanelProp.ST_F), ...
		GTA_PanelProp.ST_G, GTA_PanelProp.getPropDefault(GTA_PanelProp.ST_G) ...
		);
	 
	% GTA_PanelProp with 1st callbacks
	gt_1 = GTA_PanelProp( ...
		GTA_PanelProp.ELCLASS, GTA_PanelProp.getNoValue(), ...
		GTA_PanelProp.NAME, GTA_PanelProp.getNoValue(), ...
		GTA_PanelProp.DESCRIPTION, GTA_PanelProp.getNoValue(), ...
		GTA_PanelProp.TEMPLATE, gt_0.getCallback(4), ..., ...
		GTA_PanelProp.ID, gt_0.getCallback(5), ..., ...
		GTA_PanelProp.LABEL, GTA_PanelProp.getPropDefault(GTA_PanelProp.LABEL), ...
		GTA_PanelProp.NOTES, GTA_PanelProp.getPropDefault(GTA_PanelProp.NOTES), ...
		GTA_PanelProp.TOSTRING, GTA_PanelProp.getNoValue(), ...
		GTA_PanelProp.ST_C, GTA_PanelProp.getNoValue(), ...
		GTA_PanelProp.ST_M, GTA_PanelProp.getPropDefault(GTA_PanelProp.ST_M), ...
		GTA_PanelProp.ST_P, gt_0.getCallback(11), ..., ...
		GTA_PanelProp.ST_D, gt_0.getCallback(12), ..., ...
		GTA_PanelProp.ST_R, GTA_PanelProp.getNoValue(), ...
		GTA_PanelProp.ST_Q, GTA_PanelProp.getNoValue(), ...
		GTA_PanelProp.ST_E, GTA_PanelProp.getNoValue(), ...
		GTA_PanelProp.ST_F, gt_0.getCallback(16), ..., ...
		GTA_PanelProp.ST_G, gt_0.getCallback(17) ... ...
		);
	 
	prop_number = GTA_PanelProp.getPropNumber();
	for prop = 1:1:prop_number
		TAG = upper(GTA_PanelProp.getPropTag(prop));
		switch GTA_PanelProp.getPropCategory(prop)
			case {Category.PARAMETER, Category.DATA, Category.FIGURE, Category.GUI}
				assert( ...
					isa(gt_1.getr(prop), 'Callback'), ...
					[BRAPH2.STR ':GTA_PanelProp:' BRAPH2.FAIL_TEST], ...
					['GTA_PanelProp.getr(' int2str(prop) ') must be a callback.'] ...
					)
				assert( ...
					isequal(gt_1.get(prop), gt_0.get(prop)) && ~isa(gt_1.get(prop), 'Callback'), ...
					[BRAPH2.STR ':GTA_PanelProp:' BRAPH2.FAIL_TEST], ...
					['GTA_PanelProp.get(' int2str(prop) ') must be the actual property and NOT a callback.'] ...
					)
			otherwise
				assert( ...
					~isa(gt_1.getr(prop), 'Callback'), ...
					[BRAPH2.STR ':GTA_PanelProp:' BRAPH2.FAIL_TEST], ...
					['GTA_PanelProp.getr(' int2str(prop) ') must NOT be a callback.'] ...
					)
		end
	end
	 
	% GTA_PanelProp with 2nd callbacks
	gt_2 = GTA_PanelProp( ...
		GTA_PanelProp.ELCLASS, GTA_PanelProp.getNoValue(), ...
		GTA_PanelProp.NAME, GTA_PanelProp.getNoValue(), ...
		GTA_PanelProp.DESCRIPTION, GTA_PanelProp.getNoValue(), ...
		GTA_PanelProp.TEMPLATE, gt_1.getCallback(4), ..., ...
		GTA_PanelProp.ID, gt_1.getCallback(5), ..., ...
		GTA_PanelProp.LABEL, GTA_PanelProp.getPropDefault(GTA_PanelProp.LABEL), ...
		GTA_PanelProp.NOTES, GTA_PanelProp.getPropDefault(GTA_PanelProp.NOTES), ...
		GTA_PanelProp.TOSTRING, GTA_PanelProp.getNoValue(), ...
		GTA_PanelProp.ST_C, GTA_PanelProp.getNoValue(), ...
		GTA_PanelProp.ST_M, GTA_PanelProp.getPropDefault(GTA_PanelProp.ST_M), ...
		GTA_PanelProp.ST_P, gt_1.getCallback(11), ..., ...
		GTA_PanelProp.ST_D, gt_1.getCallback(12), ..., ...
		GTA_PanelProp.ST_R, GTA_PanelProp.getNoValue(), ...
		GTA_PanelProp.ST_Q, GTA_PanelProp.getNoValue(), ...
		GTA_PanelProp.ST_E, GTA_PanelProp.getNoValue(), ...
		GTA_PanelProp.ST_F, gt_1.getCallback(16), ..., ...
		GTA_PanelProp.ST_G, gt_1.getCallback(17) ... ...
		);
	 
	prop_number = GTA_PanelProp.getPropNumber();
	for prop = 1:1:prop_number
		TAG = upper(GTA_PanelProp.getPropTag(prop));
		switch GTA_PanelProp.getPropCategory(prop)
			case {Category.PARAMETER, Category.DATA, Category.FIGURE, Category.GUI}
				assert( ...
					isa(gt_2.getr(prop), 'Callback'), ...
					[BRAPH2.STR ':GTA_PanelProp:' BRAPH2.FAIL_TEST], ...
					['GTA_PanelProp.getr(' int2str(prop) ') must be a callback.'] ...
					)
				assert( ...
					isequal(gt_2.get(prop), gt_0.get(prop)) && ~isa(gt_1.get(prop), 'Callback'), ...
					[BRAPH2.STR ':GTA_PanelProp:' BRAPH2.FAIL_TEST], ...
					['GTA_PanelProp.get(' int2str(prop) ') must be the actual property and NOT a callback.'] ...
					)
			otherwise
				assert( ...
					~isa(gt_2.getr(prop), 'Callback'), ...
					[BRAPH2.STR ':GTA_PanelProp:' BRAPH2.FAIL_TEST], ...
					['GTA_PanelProp.getr(' int2str(prop) ') must NOT be a callback.'] ...
					)
		end
	end
	 
	% GTA_PanelProp with 3rd callbacks
	gt_3 = GTA_PanelProp( ...
		GTA_PanelProp.ELCLASS, GTA_PanelProp.getNoValue(), ...
		GTA_PanelProp.NAME, GTA_PanelProp.getNoValue(), ...
		GTA_PanelProp.DESCRIPTION, GTA_PanelProp.getNoValue(), ...
		GTA_PanelProp.TEMPLATE, gt_2.getCallback(4), ..., ...
		GTA_PanelProp.ID, gt_2.getCallback(5), ..., ...
		GTA_PanelProp.LABEL, GTA_PanelProp.getPropDefault(GTA_PanelProp.LABEL), ...
		GTA_PanelProp.NOTES, GTA_PanelProp.getPropDefault(GTA_PanelProp.NOTES), ...
		GTA_PanelProp.TOSTRING, GTA_PanelProp.getNoValue(), ...
		GTA_PanelProp.ST_C, GTA_PanelProp.getNoValue(), ...
		GTA_PanelProp.ST_M, GTA_PanelProp.getPropDefault(GTA_PanelProp.ST_M), ...
		GTA_PanelProp.ST_P, gt_2.getCallback(11), ..., ...
		GTA_PanelProp.ST_D, gt_2.getCallback(12), ..., ...
		GTA_PanelProp.ST_R, GTA_PanelProp.getNoValue(), ...
		GTA_PanelProp.ST_Q, GTA_PanelProp.getNoValue(), ...
		GTA_PanelProp.ST_E, GTA_PanelProp.getNoValue(), ...
		GTA_PanelProp.ST_F, gt_2.getCallback(16), ..., ...
		GTA_PanelProp.ST_G, gt_2.getCallback(17) ... ...
		);
	 
	prop_number = GTA_PanelProp.getPropNumber();
	for prop = 1:1:prop_number
		TAG = upper(GTA_PanelProp.getPropTag(prop));
		switch GTA_PanelProp.getPropCategory(prop)
			case {Category.PARAMETER, Category.DATA, Category.FIGURE, Category.GUI}
				assert( ...
					isa(gt_3.getr(prop), 'Callback'), ...
					[BRAPH2.STR ':GTA_PanelProp:' BRAPH2.FAIL_TEST], ...
					['GTA_PanelProp.getr(' int2str(prop) ') must be a callback.'] ...
					)
				assert( ...
					isequal(gt_3.get(prop), gt_0.get(prop)) && ~isa(gt_1.get(prop), 'Callback'), ...
					[BRAPH2.STR ':GTA_PanelProp:' BRAPH2.FAIL_TEST], ...
					['GTA_PanelProp.get(' int2str(prop) ') must be the actual property and NOT a callback.'] ...
					)
			otherwise
				assert( ...
					~isa(gt_3.getr(prop), 'Callback'), ...
					[BRAPH2.STR ':GTA_PanelProp:' BRAPH2.FAIL_TEST], ...
					['GTA_PanelProp.getr(' int2str(prop) ') must NOT be a callback.'] ...
					)
		end
	end
	 
end

%% Test 8: Copy
if rand() >= (1 - .01) * BRAPH2TEST.RANDOM
	% copy empty element
	gt = GTA_PanelProp();
	 
	gt_copy = gt.copy();
	 
	assert(gt_copy ~= gt, ...
		[BRAPH2.STR ':GTA_PanelProp:' BRAPH2.FAIL_TEST], ...
		'GTA_PanelProp.copy() does not work. A copied element must point to a copied element.')
	assert(isequal(gt_copy, gt), ...
		[BRAPH2.STR ':GTA_PanelProp:' BRAPH2.FAIL_TEST], ...
		'GTA_PanelProp.copy() does not work. A copied element must have the same property values of the original element.')
	 
	for prop = 1:1:GTA_PanelProp.getPropNumber()
		value = gt.getr(prop);
		value_copy = gt_copy.getr(prop);
		switch GTA_PanelProp.getPropCategory(prop)
			case {Category.EVANESCENT}
				assert( ...
					isa(value_copy, 'NoValue'), ...
					[BRAPH2.STR ':GTA_PanelProp:' BRAPH2.FAIL_TEST], ...
					'GTA_PanelProp.copy() does not work. The copied value of an EVANESCENT property must be NoValue.' ...
					)
			otherwise
				if isa(value, 'NoValue')
					assert( ...
						value_copy == value, ...
						[BRAPH2.STR ':GTA_PanelProp:' BRAPH2.FAIL_TEST], ...
						'GTA_PanelProp.copy() does not work. There should be a unique instance of NoValue.' ...
						)
				elseif isa(value, 'Element')
					assert( ...
						value_copy ~= value, ...
						[BRAPH2.STR ':GTA_PanelProp:' BRAPH2.FAIL_TEST], ...
						'GTA_PanelProp.copy() does not work. The handle of a copied element should point to a copied element.' ...
						)
					assert( ...
						isequal(value_copy, value), ...
						[BRAPH2.STR ':GTA_PanelProp:' BRAPH2.FAIL_TEST], ...
						'GTA_PanelProp.copy() does not work. When empty, a copied element should be equal to the element.' ...
						)
				elseif iscell(value) && all(all(cellfun(@(x) isa(x, 'Element'), value)))
					for j = 1:1:length(value)
						assert( ...
							value_copy ~= value, ...
							[BRAPH2.STR ':GTA_PanelProp:' BRAPH2.FAIL_TEST], ...
							'GTA_PanelProp.copy() does not work. The handle of a copied element should point to a copied element.' ...
							)
						assert( ...
							isequal(value_copy, value), ...
							[BRAPH2.STR ':GTA_PanelProp:' BRAPH2.FAIL_TEST], ...
							'GTA_PanelProp.copy() does not work. When empty, a copied element should be equal to the element.' ...
							)
					end
				else
					assert( ...
						isequal(value_copy, value), ...
						[BRAPH2.STR ':GTA_PanelProp:' BRAPH2.FAIL_TEST], ...
						'GTA_PanelProp.copy() does not work. The value copy should be equal to the original.' ...
						)
				end
				assert( ...
					gt_copy.isLocked(prop) == gt.isLocked(prop), ...
					[BRAPH2.STR ':GTA_PanelProp:' BRAPH2.FAIL_TEST], ...
					'GTA_PanelProp.copy() does not work. The locked status of the copied and original elements must be the same.' ...
					)
				assert( ...
					gt_copy.isChecked(prop) == gt.isChecked(prop), ...
					[BRAPH2.STR ':GTA_PanelProp:' BRAPH2.FAIL_TEST], ...
					'GTA_PanelProp.copy() does not work. The checked status of the copied and original elements must be the same.' ...
					)
				assert( ...
					gt_copy.getPropSeed(prop) == gt.getPropSeed(prop), ...
					[BRAPH2.STR ':GTA_PanelProp:' BRAPH2.FAIL_TEST], ...
					'GTA_PanelProp.copy() does not work. The randomization seeds of the copied and original elements must be the same.' ...
					)
		end
	end
	 
	% copy element with default initialization and memorization
	gt = GTA_PanelProp( ...
		GTA_PanelProp.ELCLASS, GTA_PanelProp.getNoValue(), ...
		GTA_PanelProp.NAME, GTA_PanelProp.getNoValue(), ...
		GTA_PanelProp.DESCRIPTION, GTA_PanelProp.getNoValue(), ...
		GTA_PanelProp.TEMPLATE, GTA_PanelProp.getPropDefault(GTA_PanelProp.TEMPLATE), ...
		GTA_PanelProp.ID, GTA_PanelProp.getPropDefault(GTA_PanelProp.ID), ...
		GTA_PanelProp.LABEL, GTA_PanelProp.getPropDefault(GTA_PanelProp.LABEL), ...
		GTA_PanelProp.NOTES, GTA_PanelProp.getPropDefault(GTA_PanelProp.NOTES), ...
		GTA_PanelProp.TOSTRING, GTA_PanelProp.getNoValue(), ...
		GTA_PanelProp.ST_C, GTA_PanelProp.getNoValue(), ...
		GTA_PanelProp.ST_M, GTA_PanelProp.getPropDefault(GTA_PanelProp.ST_M), ...
		GTA_PanelProp.ST_P, GTA_PanelProp.getPropDefault(GTA_PanelProp.ST_P), ...
		GTA_PanelProp.ST_D, GTA_PanelProp.getPropDefault(GTA_PanelProp.ST_D), ...
		GTA_PanelProp.ST_R, GTA_PanelProp.getNoValue(), ...
		GTA_PanelProp.ST_Q, GTA_PanelProp.getNoValue(), ...
		GTA_PanelProp.ST_E, GTA_PanelProp.getNoValue(), ...
		GTA_PanelProp.ST_F, GTA_PanelProp.getPropDefault(GTA_PanelProp.ST_F), ...
		GTA_PanelProp.ST_G, GTA_PanelProp.getPropDefault(GTA_PanelProp.ST_G) ...
		);
	 
	for prop = 1:1:GTA_PanelProp.getPropNumber()
		if GTA_PanelProp.getPropCategory(prop) == Category.QUERY
			% properties QUERY should not be memorized
			% warning_backup = warning('off', [BRAPH2.STR ':GTA_PanelProp']);
			% gt.memorize(prop);
			% warning(warning_backup)
		elseif GTA_PanelProp.getPropCategory(prop) == Category.EVANESCENT && gt.getPropFormat(prop) == Format.HANDLE
			gt.memorize(prop);
			warning_backup = warning('off', 'BRAPH2:GTA_PanelProp');
			delete(ancestor(gt.get(prop), 'figure'))
			warning(warning_backup)
		else
			gt.memorize(prop);
		end
	end
	 
	% copy element with default initialization
	gt_copy = gt.copy();
	 
	for prop = 1:1:GTA_PanelProp.getPropNumber()
		value = gt.getr(prop);
		value_copy = gt_copy.getr(prop);
		switch GTA_PanelProp.getPropCategory(prop)
			case {Category.EVANESCENT Category.QUERY}
				assert( ...
					isa(value_copy, 'NoValue'), ...
					[BRAPH2.STR ':GTA_PanelProp:' BRAPH2.FAIL_TEST], ...
					'GTA_PanelProp.copy() does not work. The copied value of an EVANESCENT property must be NoValue.' ...
					)
			otherwise
				if isa(value, 'NoValue')
					assert( ...
						value_copy == value, ...
						[BRAPH2.STR ':GTA_PanelProp:' BRAPH2.FAIL_TEST], ...
						'GTA_PanelProp.copy() does not work. There should be a unique instance of NoValue.' ...
						)
				elseif isa(value, 'Element')
					assert( ...
						value_copy ~= value, ...
						[BRAPH2.STR ':GTA_PanelProp:' BRAPH2.FAIL_TEST], ...
						'GTA_PanelProp.copy() does not work. The handle of a copied element should point to a copied element.' ...
						)
					assert( ...
						isequal(value_copy, value), ...
						[BRAPH2.STR ':GTA_PanelProp:' BRAPH2.FAIL_TEST], ...
						'GTA_PanelProp.copy() does not work. When empty, a copied element should be equal to the element.' ...
						)
				elseif iscell(value) && all(all(cellfun(@(x) isa(x, 'Element'), value)))
					for j = 1:1:length(value)
						assert( ...
							value_copy ~= value, ...
							[BRAPH2.STR ':GTA_PanelProp:' BRAPH2.FAIL_TEST], ...
							'GTA_PanelProp.copy() does not work. The handle of a copied element should point to a copied element.' ...
							)
						assert( ...
							isequal(value_copy, value), ...
							[BRAPH2.STR ':GTA_PanelProp:' BRAPH2.FAIL_TEST], ...
							'GTA_PanelProp.copy() does not work. When empty, a copied element should be equal to the element.' ...
							)
					end
				else
					assert( ...
						isequal(value_copy, value), ...
						[BRAPH2.STR ':GTA_PanelProp:' BRAPH2.FAIL_TEST], ...
						'GTA_PanelProp.copy() does not work. The value copy should be equal to the original.' ...
						)
				end
	 
					assert( ...
						gt_copy.isLocked(prop) == gt.isLocked(prop), ...
						[BRAPH2.STR ':GTA_PanelProp:' BRAPH2.FAIL_TEST], ...
						'GTA_PanelProp.copy() does not work. The locked status of the copied and original elements must be the same.' ...
						)
	 
					assert( ...
						gt_copy.isChecked(prop) == gt.isChecked(prop), ...
						[BRAPH2.STR ':GTA_PanelProp:' BRAPH2.FAIL_TEST], ...
						'GTA_PanelProp.copy() does not work. The checked status of the copied and original elements must be the same.' ...
						)
	 
					assert( ...
						gt_copy.getPropSeed(prop) == gt.getPropSeed(prop), ...
						[BRAPH2.STR ':GTA_PanelProp:' BRAPH2.FAIL_TEST], ...
						'GTA_PanelProp.copy() does not work. The randomization seeds of the copied and original elements must be the same.' ...
						)
		end
	end
	 
	% copy element with callbacks
	gt_0 = GTA_PanelProp( ...
		GTA_PanelProp.ELCLASS, GTA_PanelProp.getNoValue(), ...
		GTA_PanelProp.NAME, GTA_PanelProp.getNoValue(), ...
		GTA_PanelProp.DESCRIPTION, GTA_PanelProp.getNoValue(), ...
		GTA_PanelProp.TEMPLATE, GTA_PanelProp.getPropDefault(GTA_PanelProp.TEMPLATE), ...
		GTA_PanelProp.ID, GTA_PanelProp.getPropDefault(GTA_PanelProp.ID), ...
		GTA_PanelProp.LABEL, GTA_PanelProp.getPropDefault(GTA_PanelProp.LABEL), ...
		GTA_PanelProp.NOTES, GTA_PanelProp.getPropDefault(GTA_PanelProp.NOTES), ...
		GTA_PanelProp.TOSTRING, GTA_PanelProp.getNoValue(), ...
		GTA_PanelProp.ST_C, GTA_PanelProp.getNoValue(), ...
		GTA_PanelProp.ST_M, GTA_PanelProp.getPropDefault(GTA_PanelProp.ST_M), ...
		GTA_PanelProp.ST_P, GTA_PanelProp.getPropDefault(GTA_PanelProp.ST_P), ...
		GTA_PanelProp.ST_D, GTA_PanelProp.getPropDefault(GTA_PanelProp.ST_D), ...
		GTA_PanelProp.ST_R, GTA_PanelProp.getNoValue(), ...
		GTA_PanelProp.ST_Q, GTA_PanelProp.getNoValue(), ...
		GTA_PanelProp.ST_E, GTA_PanelProp.getNoValue(), ...
		GTA_PanelProp.ST_F, GTA_PanelProp.getPropDefault(GTA_PanelProp.ST_F), ...
		GTA_PanelProp.ST_G, GTA_PanelProp.getPropDefault(GTA_PanelProp.ST_G) ...
		);
	 
	gt = GTA_PanelProp( ...
		GTA_PanelProp.ELCLASS, GTA_PanelProp.getNoValue(), ...
		GTA_PanelProp.NAME, GTA_PanelProp.getNoValue(), ...
		GTA_PanelProp.DESCRIPTION, GTA_PanelProp.getNoValue(), ...
		GTA_PanelProp.TEMPLATE, gt_0.getCallback(4), ..., ...
		GTA_PanelProp.ID, gt_0.getCallback(5), ..., ...
		GTA_PanelProp.LABEL, GTA_PanelProp.getPropDefault(GTA_PanelProp.LABEL), ...
		GTA_PanelProp.NOTES, GTA_PanelProp.getPropDefault(GTA_PanelProp.NOTES), ...
		GTA_PanelProp.TOSTRING, GTA_PanelProp.getNoValue(), ...
		GTA_PanelProp.ST_C, GTA_PanelProp.getNoValue(), ...
		GTA_PanelProp.ST_M, GTA_PanelProp.getPropDefault(GTA_PanelProp.ST_M), ...
		GTA_PanelProp.ST_P, gt_0.getCallback(11), ..., ...
		GTA_PanelProp.ST_D, gt_0.getCallback(12), ..., ...
		GTA_PanelProp.ST_R, GTA_PanelProp.getNoValue(), ...
		GTA_PanelProp.ST_Q, GTA_PanelProp.getNoValue(), ...
		GTA_PanelProp.ST_E, GTA_PanelProp.getNoValue(), ...
		GTA_PanelProp.ST_F, gt_0.getCallback(16), ..., ...
		GTA_PanelProp.ST_G, gt_0.getCallback(17) ... ...
		);
	 
	gt_copy = gt.copy();
	gt_0_copy = gt_copy.getr('ID').get('EL');
	 
	for prop = 1:1:GTA_PanelProp.getPropNumber()
		value = gt.getr(prop);
		value_copy = gt_copy.getr(prop);
		switch GTA_PanelProp.getPropCategory(prop)
			case {Category.EVANESCENT}
				assert( ...
					isa(value_copy, 'NoValue'), ...
					[BRAPH2.STR ':GTA_PanelProp:' BRAPH2.FAIL_TEST], ...
					'GTA_PanelProp.copy() does not work. The copied value of an EVANESCENT property must be NoValue.' ...
					)
			otherwise
				if isa(value, 'NoValue')
					assert( ...
						value_copy == value, ...
						[BRAPH2.STR ':GTA_PanelProp:' BRAPH2.FAIL_TEST], ...
						'GTA_PanelProp.copy() does not work. There should be a unique instance of NoValue.' ...
						)
				elseif isa(value, 'Element')
					assert( ...
						value_copy ~= value, ...
						[BRAPH2.STR ':GTA_PanelProp:' BRAPH2.FAIL_TEST], ...
						'GTA_PanelProp.copy() does not work. The handle of a copied element should point to a copied element.' ...
						)
					assert( ...
						isequal(value_copy, value), ...
						[BRAPH2.STR ':GTA_PanelProp:' BRAPH2.FAIL_TEST], ...
						'GTA_PanelProp.copy() does not work. When empty, a copied element should be equal to the element.' ...
						)
				elseif iscell(value) && all(all(cellfun(@(x) isa(x, 'Element'), value)))
					for j = 1:1:length(value)
						assert( ...
							value_copy ~= value, ...
							[BRAPH2.STR ':GTA_PanelProp:' BRAPH2.FAIL_TEST], ...
							'GTA_PanelProp.copy() does not work. The handle of a copied element should point to a copied element.' ...
							)
						assert( ...
							isequal(value_copy, value), ...
							[BRAPH2.STR ':GTA_PanelProp:' BRAPH2.FAIL_TEST], ...
							'GTA_PanelProp.copy() does not work. When empty, a copied element should be equal to the element.' ...
							)
					end
				else
					assert( ...
						isequal(value_copy, value), ...
						[BRAPH2.STR ':GTA_PanelProp:' BRAPH2.FAIL_TEST], ...
						'GTA_PanelProp.copy() does not work. The value copy should be equal to the original.' ...
						)
				end
				if isa(value, 'Callback')
					assert( ...
						value == gt_0.getCallback(prop), ...
						[BRAPH2.STR ':GTA_PanelProp:' BRAPH2.FAIL_TEST], ...
						'GTA_PanelProp.copy() does not work. The callback should be obtained from GTA_PanelProp.getCallback().' ...
						)
					assert( ...
						value_copy == gt_0_copy.getCallback(prop), ...
						[BRAPH2.STR ':GTA_PanelProp:' BRAPH2.FAIL_TEST], ...
						'GTA_PanelProp.copy() does not work. The callback should be obtained from GTA_PanelProp.getCallback().' ...
						)
				end
	 
					assert( ...
						gt_copy.isLocked(prop) == gt.isLocked(prop), ...
						[BRAPH2.STR ':GTA_PanelProp:' BRAPH2.FAIL_TEST], ...
						'GTA_PanelProp.copy() does not work. The locked status of the copied and original elements must be the same.' ...
						)
	 
					assert( ...
						gt_copy.isChecked(prop) == gt.isChecked(prop), ...
						[BRAPH2.STR ':GTA_PanelProp:' BRAPH2.FAIL_TEST], ...
						'GTA_PanelProp.copy() does not work. The checked status of the copied and original elements must be the same.' ...
						)
	 
					assert( ...
						gt_copy.getPropSeed(prop) == gt.getPropSeed(prop), ...
						[BRAPH2.STR ':GTA_PanelProp:' BRAPH2.FAIL_TEST], ...
						'GTA_PanelProp.copy() does not work. The randomization seeds of the copied and original elements must be the same.' ...
						)
		end
	end
	 
end

%% Test 9: Template
if rand() >= (1 - .01) * BRAPH2TEST.RANDOM
	gt_template = GTA_PanelProp();
	gt = GTA_PanelProp('TEMPLATE', gt_template);
	 
	for prop = 1:1:GTA_PanelProp.getPropNumber()
	 
		% excluded props
		if any(prop == [])
			continue
		end
	 
		TAG = upper(GTA_PanelProp.getPropTag(prop));
		switch GTA_PanelProp.getPropCategory(prop)
			case {Category.PARAMETER}
				if prop == GTA_PanelProp.TEMPLATE
					assert( ...
						isa(gt.getr(prop), 'GTA_PanelProp'), ...
						[BRAPH2.STR ':GTA_PanelProp:' BRAPH2.FAIL_TEST], ...
						'GTA_PanelProp TEMPLATE does not work. GTA_PanelProp.getr(''TEMPLATE'') should be a GTA_PanelProp element.' ...
						)
					assert( ...
						isa(gt_template.getr(prop), 'NoValue'), ...
						[BRAPH2.STR ':GTA_PanelProp:' BRAPH2.FAIL_TEST], ...
						'GTA_PanelProp TEMPLATE does not work. GTA_PanelProp_template.getr(''TEMPLATE'') should be a NoValue.' ...
						)
				else
					assert( ...
						isa(gt.getr(prop), 'Callback'), ...
						[BRAPH2.STR ':GTA_PanelProp:' BRAPH2.FAIL_TEST], ...
						['GTA_PanelProp TEMPLATE does not work. GTA_PanelProp.getr(' TAG ') should be a Callback.'] ...
						)
					assert( ...
						gt.getr(prop).get('EL') == gt_template && gt.getr(prop).get('PROP') == prop && strcmp(gt.getr(prop).get('TAG'), TAG), ...
						[BRAPH2.STR ':GTA_PanelProp:' BRAPH2.FAIL_TEST], ...
						['GTA_PanelProp TEMPLATE does not work. GTA_PanelProp.getr(' TAG ') should be a Callback to gt_template.' TAG '.'] ...
						)
					assert( ...
						isa(gt_template.getr(prop), 'NoValue'), ...
						[BRAPH2.STR ':GTA_PanelProp:' BRAPH2.FAIL_TEST], ...
						['GTA_PanelProp TEMPLATE does not work. GTA_PanelProp_template.getr(' TAG ') should be a NoValue.'] ...
						)
				end
			otherwise
				assert( ...
					isa(gt.getr(prop), 'NoValue'), ...
					[BRAPH2.STR ':GTA_PanelProp:' BRAPH2.FAIL_TEST], ...
					['GTA_PanelProp TEMPLATE does not work. GTA_PanelProp.getr(' TAG ') should be a NoValue.'] ...
					)
				assert( ...
					isa(gt_template.getr(prop), 'NoValue'), ...
					[BRAPH2.STR ':GTA_PanelProp:' BRAPH2.FAIL_TEST], ...
					['GTA_PanelProp TEMPLATE does not work. GTA_PanelProp_template.getr(' TAG ') should be a NoValue.'] ...
					)
		end
	end
end

%% Test 10: Save Load
if rand() >= (1 - .01) * BRAPH2TEST.RANDOM
	gt = GTA_PanelProp( ...
		GTA_PanelProp.ELCLASS, GTA_PanelProp.getNoValue(), ...
		GTA_PanelProp.NAME, GTA_PanelProp.getNoValue(), ...
		GTA_PanelProp.DESCRIPTION, GTA_PanelProp.getNoValue(), ...
		GTA_PanelProp.TEMPLATE, GTA_PanelProp.getPropDefault(GTA_PanelProp.TEMPLATE), ...
		GTA_PanelProp.ID, GTA_PanelProp.getPropDefault(GTA_PanelProp.ID), ...
		GTA_PanelProp.LABEL, GTA_PanelProp.getPropDefault(GTA_PanelProp.LABEL), ...
		GTA_PanelProp.NOTES, GTA_PanelProp.getPropDefault(GTA_PanelProp.NOTES), ...
		GTA_PanelProp.TOSTRING, GTA_PanelProp.getNoValue(), ...
		GTA_PanelProp.ST_C, GTA_PanelProp.getNoValue(), ...
		GTA_PanelProp.ST_M, GTA_PanelProp.getPropDefault(GTA_PanelProp.ST_M), ...
		GTA_PanelProp.ST_P, GTA_PanelProp.getPropDefault(GTA_PanelProp.ST_P), ...
		GTA_PanelProp.ST_D, GTA_PanelProp.getPropDefault(GTA_PanelProp.ST_D), ...
		GTA_PanelProp.ST_R, GTA_PanelProp.getNoValue(), ...
		GTA_PanelProp.ST_Q, GTA_PanelProp.getNoValue(), ...
		GTA_PanelProp.ST_E, GTA_PanelProp.getNoValue(), ...
		GTA_PanelProp.ST_F, GTA_PanelProp.getPropDefault(GTA_PanelProp.ST_F), ...
		GTA_PanelProp.ST_G, GTA_PanelProp.getPropDefault(GTA_PanelProp.ST_G) ...
		);
	 
	filename = [fileparts(which('test_braph2')) filesep 'gta_panelprop_to_be_erased.b2'];
	 
	Element.save(gt, filename)
	 
	gt_loaded = Element.load(filename);
	 
	assert( ...
		isequal(gt.copy(), gt_loaded), ...
		[BRAPH2.STR ':GTA_PanelProp:' BRAPH2.FAIL_TEST], ...
		'GTA_PanelProp.save(gt) and/or GTA_PanelProp.load() do not work.' ...
		)
	 
	delete(filename)
end

%% Test 11: JSON
if rand() >= (1 - .01) * BRAPH2TEST.RANDOM
	gt = GTA_PanelProp( ...
		GTA_PanelProp.ELCLASS, GTA_PanelProp.getNoValue(), ...
		GTA_PanelProp.NAME, GTA_PanelProp.getNoValue(), ...
		GTA_PanelProp.DESCRIPTION, GTA_PanelProp.getNoValue(), ...
		GTA_PanelProp.TEMPLATE, GTA_PanelProp.getPropDefault(GTA_PanelProp.TEMPLATE), ...
		GTA_PanelProp.ID, GTA_PanelProp.getPropDefault(GTA_PanelProp.ID), ...
		GTA_PanelProp.LABEL, GTA_PanelProp.getPropDefault(GTA_PanelProp.LABEL), ...
		GTA_PanelProp.NOTES, GTA_PanelProp.getPropDefault(GTA_PanelProp.NOTES), ...
		GTA_PanelProp.TOSTRING, GTA_PanelProp.getNoValue(), ...
		GTA_PanelProp.ST_C, GTA_PanelProp.getNoValue(), ...
		GTA_PanelProp.ST_M, GTA_PanelProp.getPropDefault(GTA_PanelProp.ST_M), ...
		GTA_PanelProp.ST_P, GTA_PanelProp.getPropDefault(GTA_PanelProp.ST_P), ...
		GTA_PanelProp.ST_D, GTA_PanelProp.getPropDefault(GTA_PanelProp.ST_D), ...
		GTA_PanelProp.ST_R, GTA_PanelProp.getNoValue(), ...
		GTA_PanelProp.ST_Q, GTA_PanelProp.getNoValue(), ...
		GTA_PanelProp.ST_E, GTA_PanelProp.getNoValue(), ...
		GTA_PanelProp.ST_F, GTA_PanelProp.getPropDefault(GTA_PanelProp.ST_F), ...
		GTA_PanelProp.ST_G, GTA_PanelProp.getPropDefault(GTA_PanelProp.ST_G) ...
		);
	 
	[json, struct, el_list] = encodeJSON(gt);
	[gt_dec, struct_dec, el_list_dec] = Element.decodeJSON(json);
	 
	assert(gt_dec ~= gt, ...
		[BRAPH2.STR ':GTA_PanelProp:' BRAPH2.FAIL_TEST], ...
		'GTA_PanelProp.encodeJSON() or GTA_PanelProp.decodeJSON() does not work. A JSON encoded/decoded element must point to an element other than the original one.' ...
		)
	if all(cellfun(@(prop) GTA_PanelProp.getPropFormat(prop), num2cell(GTA_PanelProp.getProps())) == Format.HANDLE) && all(cellfun(@(prop) GTA_PanelProp.getPropFormat(prop), num2cell(GTA_PanelProp.getProps())) == Format.NET)
		assert(isequal(gt_dec, gt), ...
			[BRAPH2.STR ':GTA_PanelProp:' BRAPH2.FAIL_TEST], ...
			'GTA_PanelProp.encodeJSON() or GTA_PanelProp.decodeJSON() does not work. A JSON encoded/decoded element must have the same property values of the original element.' ...
			)
	end
end

%% Test 12: Buttons & Listener Graphics
if rand() >= (1 - .01) * BRAPH2TEST.RANDOM
	gt = GTA_PanelProp();
	gui = GUI('POSITION', [0 0 1 1], 'CLOSEREQ', false);
	
	pr_C = PanelProp('PARENT', gui, 'EL', gt, 'PROP', gt.ST_C, 'BKGCOLOR', BRAPH2.COL_C);
	pr_C.get('DRAW', 'Units', 'normalized', 'Position', [.05 .70 .40 .25])
	assert(check_graphics(pr_C.getr('H'), 'uipanel'))
	assert(check_graphics(pr_C.getr('PARENT').getr('H'), 'figure'))
	assert(check_graphics(pr_C.getr('LABEL_TITLE'), 'uilabel'))
	assert(~check_graphics(pr_C.getr('BUTTON_CB'), 'uibutton'))
	assert(~check_graphics(pr_C.getr('BUTTON_CALC'), 'uibutton'))
	assert(~check_graphics(pr_C.getr('BUTTON_DEL'), 'uibutton'))    
	assert(all(cellfun(@(x) isa(x, 'event.listener'), pr_C.getr('LISTENER_SET'))))
	assert(isa(pr_C.getr('LISTENER_MEMORIZED'), 'NoValue'))    
	assert(all(cellfun(@(x) isa(x, 'event.listener'), pr_C.getr('LISTENER_LOCKED'))))
	
	pr_M = PanelProp('PARENT', gui, 'EL', gt, 'PROP', gt.ST_M, 'BKGCOLOR', BRAPH2.COL_M);
	pr_M.get('DRAW', 'Units', 'normalized', 'Position', [.55 .70 .40 .25])
	assert(check_graphics(pr_M.getr('H'), 'uipanel'))
	assert(check_graphics(pr_M.getr('PARENT').getr('H'), 'figure'))
	assert(check_graphics(pr_M.getr('LABEL_TITLE'), 'uilabel'))
	assert(~check_graphics(pr_M.getr('BUTTON_CB'), 'uibutton'))
	assert(~check_graphics(pr_M.getr('BUTTON_CALC'), 'uibutton'))
	assert(~check_graphics(pr_M.getr('BUTTON_DEL'), 'uibutton'))
	assert(all(cellfun(@(x) isa(x, 'event.listener'), pr_M.getr('LISTENER_SET'))))
	assert(isa(pr_M.getr('LISTENER_MEMORIZED'), 'NoValue'))    
	assert(all(cellfun(@(x) isa(x, 'event.listener'), pr_M.getr('LISTENER_LOCKED'))))
	
	pr_P = PanelProp('PARENT', gui, 'EL', gt, 'PROP', gt.ST_P, 'BKGCOLOR', BRAPH2.COL_P);
	pr_P.get('DRAW', 'Units', 'normalized', 'Position', [.05 .40 .20 .25])
	assert(check_graphics(pr_P.getr('H'), 'uipanel'))
	assert(check_graphics(pr_P.getr('PARENT').getr('H'), 'figure'))
	assert(check_graphics(pr_P.getr('LABEL_TITLE'), 'uilabel'))
	assert(check_graphics(pr_P.getr('BUTTON_CB'), 'uibutton'))
	assert(~check_graphics(pr_P.getr('BUTTON_CALC'), 'uibutton'))
	assert(~check_graphics(pr_P.getr('BUTTON_DEL'), 'uibutton'))    
	assert(all(cellfun(@(x) isa(x, 'event.listener'), pr_P.getr('LISTENER_SET'))))
	assert(isa(pr_P.getr('LISTENER_MEMORIZED'), 'NoValue'))    
	assert(all(cellfun(@(x) isa(x, 'event.listener'), pr_P.getr('LISTENER_LOCKED'))))
	
	pr_D = PanelProp('PARENT', gui, 'EL', gt, 'PROP', gt.ST_D, 'BKGCOLOR', BRAPH2.COL_D);
	pr_D.get('DRAW', 'Units', 'normalized', 'Position', [.25 .40 .20 .25])
	assert(check_graphics(pr_D.getr('H'), 'uipanel'))
	assert(check_graphics(pr_D.getr('PARENT').getr('H'), 'figure'))
	assert(check_graphics(pr_D.getr('LABEL_TITLE'), 'uilabel'))
	assert(check_graphics(pr_D.getr('BUTTON_CB'), 'uibutton'))
	assert(~check_graphics(pr_D.getr('BUTTON_CALC'), 'uibutton'))
	assert(~check_graphics(pr_D.getr('BUTTON_DEL'), 'uibutton'))
	assert(all(cellfun(@(x) isa(x, 'event.listener'), pr_D.getr('LISTENER_SET'))))
	assert(isa(pr_D.getr('LISTENER_MEMORIZED'), 'NoValue'))
	assert(all(cellfun(@(x) isa(x, 'event.listener'), pr_D.getr('LISTENER_LOCKED'))))
	
	pr_R = PanelProp('PARENT', gui, 'EL', gt, 'PROP', gt.ST_R, 'BKGCOLOR', BRAPH2.COL_R);
	pr_R.get('DRAW', 'Units', 'normalized', 'Position', [.05 .10 .25 .25])
	assert(check_graphics(pr_R.getr('H'), 'uipanel'))
	assert(check_graphics(pr_R.getr('PARENT').getr('H'), 'figure'))    
	assert(check_graphics(pr_R.getr('LABEL_TITLE'), 'uilabel'))
	assert(~check_graphics(pr_R.getr('BUTTON_CB'), 'uibutton'))
	assert(check_graphics(pr_R.getr('BUTTON_CALC'), 'uibutton'))
	assert(check_graphics(pr_R.getr('BUTTON_DEL'), 'uibutton'))    
	assert(all(cellfun(@(x) isa(x, 'event.listener'), pr_R.getr('LISTENER_SET'))))
	assert(all(cellfun(@(x) isa(x, 'event.listener'), pr_R.getr('LISTENER_MEMORIZED'))))
	assert(all(cellfun(@(x) isa(x, 'event.listener'), pr_R.getr('LISTENER_LOCKED'))))
	
	pr_Q = PanelProp('PARENT', gui, 'EL', gt, 'PROP', gt.ST_Q, 'BKGCOLOR', BRAPH2.COL_Q);
	pr_Q.get('DRAW', 'Units', 'normalized', 'Position', [.35 .10 .25 .25])
	assert(check_graphics(pr_Q.getr('H'), 'uipanel'))
	assert(check_graphics(pr_Q.getr('PARENT').getr('H'), 'figure'))
	assert(check_graphics(pr_Q.getr('LABEL_TITLE'), 'uilabel'))
	assert(~check_graphics(pr_Q.getr('BUTTON_CB'), 'uibutton'))
	assert(check_graphics(pr_Q.getr('BUTTON_CALC'), 'uibutton'))
	assert(check_graphics(pr_Q.getr('BUTTON_DEL'), 'uibutton'))    
	assert(all(cellfun(@(x) isa(x, 'event.listener'), pr_Q.getr('LISTENER_SET'))))
	assert(all(cellfun(@(x) isa(x, 'event.listener'), pr_Q.getr('LISTENER_MEMORIZED'))))
	assert(all(cellfun(@(x) isa(x, 'event.listener'), pr_Q.getr('LISTENER_LOCKED'))))
	
	pr_E = PanelProp('PARENT', gui, 'EL', gt, 'PROP', gt.ST_E, 'BKGCOLOR', BRAPH2.COL_E);
	pr_E.get('DRAW', 'Units', 'normalized', 'Position', [.65 .10 .25 .25])
	assert(check_graphics(pr_E.getr('H'), 'uipanel'))
	assert(check_graphics(pr_E.getr('PARENT').getr('H'), 'figure'))
	assert(check_graphics(pr_E.getr('LABEL_TITLE'), 'uilabel'))
	assert(~check_graphics(pr_E.getr('BUTTON_CB'), 'uibutton'))
	assert(check_graphics(pr_E.getr('BUTTON_CALC'), 'uibutton'))
	assert(check_graphics(pr_E.getr('BUTTON_DEL'), 'uibutton'))
	assert(all(cellfun(@(x) isa(x, 'event.listener'), pr_E.getr('LISTENER_SET'))))
	assert(all(cellfun(@(x) isa(x, 'event.listener'), pr_E.getr('LISTENER_MEMORIZED'))))
	assert(all(cellfun(@(x) isa(x, 'event.listener'), pr_E.getr('LISTENER_LOCKED'))))
	
	pr_F = PanelProp('PARENT', gui, 'EL', gt, 'PROP', gt.ST_F, 'BKGCOLOR', BRAPH2.COL_F);
	pr_F.get('DRAW', 'Units', 'normalized', 'Position', [.50 .40 .20 .25])
	assert(check_graphics(pr_F.getr('H'), 'uipanel'))
	assert(check_graphics(pr_F.getr('PARENT').getr('H'), 'figure'))
	assert(check_graphics(pr_F.getr('LABEL_TITLE'), 'uilabel'))
	assert(check_graphics(pr_F.getr('BUTTON_CB'), 'uibutton'))
	assert(~check_graphics(pr_F.getr('BUTTON_CALC'), 'uibutton'))
	assert(~check_graphics(pr_F.getr('BUTTON_DEL'), 'uibutton'))    
	assert(all(cellfun(@(x) isa(x, 'event.listener'), pr_F.getr('LISTENER_SET'))))
	assert(isa(pr_F.getr('LISTENER_MEMORIZED'), 'NoValue'))
	assert(all(cellfun(@(x) isa(x, 'event.listener'), pr_F.getr('LISTENER_LOCKED'))))
	
	pr_G = PanelProp('PARENT', gui, 'EL', gt, 'PROP', gt.ST_G, 'BKGCOLOR', BRAPH2.COL_G);
	pr_G.get('DRAW', 'Units', 'normalized', 'Position', [.75 .40 .20 .25])
	assert(check_graphics(pr_G.getr('H'), 'uipanel'))
	assert(check_graphics(pr_G.getr('PARENT').getr('H'), 'figure'))
	assert(check_graphics(pr_G.getr('LABEL_TITLE'), 'uilabel'))
	assert(check_graphics(pr_G.getr('BUTTON_CB'), 'uibutton'))
	assert(~check_graphics(pr_G.getr('BUTTON_CALC'), 'uibutton'))
	assert(~check_graphics(pr_G.getr('BUTTON_DEL'), 'uibutton'))    
	assert(all(cellfun(@(x) isa(x, 'event.listener'), pr_G.getr('LISTENER_SET'))))
	assert(isa(pr_G.getr('LISTENER_MEMORIZED'), 'NoValue'))    
	assert(all(cellfun(@(x) isa(x, 'event.listener'), pr_G.getr('LISTENER_LOCKED'))))
	
	pr_C.get('SHOW') % shows all
	
	pr_P.get('HIDE') % hides all
	
	pr_R.get('SHOW') % shows all
	
	pr_F.get('CLOSE') % closes all
	
	assert(~check_graphics(pr_C.getr('H'), 'uipanel'))
	assert(~check_graphics(pr_C.getr('PARENT').getr('H'), 'figure'))
	assert(~check_graphics(pr_C.getr('LABEL_TITLE'), 'uilabel'))
	assert(~check_graphics(pr_C.getr('BUTTON_CB'), 'uibutton'))
	assert(~check_graphics(pr_C.getr('BUTTON_CALC'), 'uibutton'))
	assert(~check_graphics(pr_C.getr('BUTTON_DEL'), 'uibutton'))    
	assert(isa(pr_C.getr('LISTENER_SET'), 'NoValue'))
	assert(isa(pr_C.getr('LISTENER_MEMORIZED'), 'NoValue'))    
	assert(isa(pr_C.getr('LISTENER_LOCKED'), 'NoValue'))
	
	assert(~check_graphics(pr_M.getr('H'), 'uipanel'))
	assert(~check_graphics(pr_M.getr('PARENT').getr('H'), 'figure'))
	assert(~check_graphics(pr_M.getr('LABEL_TITLE'), 'uilabel'))
	assert(~check_graphics(pr_M.getr('BUTTON_CB'), 'uibutton'))
	assert(~check_graphics(pr_M.getr('BUTTON_CALC'), 'uibutton'))
	assert(~check_graphics(pr_M.getr('BUTTON_DEL'), 'uibutton'))
	assert(isa(pr_M.getr('LISTENER_SET'), 'NoValue'))    
	assert(isa(pr_M.getr('LISTENER_MEMORIZED'), 'NoValue'))    
	assert(isa(pr_M.getr('LISTENER_LOCKED'), 'NoValue'))
	
	assert(~check_graphics(pr_P.getr('H'), 'uipanel'))
	assert(~check_graphics(pr_P.getr('PARENT').getr('H'), 'figure'))
	assert(~check_graphics(pr_P.getr('LABEL_TITLE'), 'uilabel'))
	assert(~check_graphics(pr_P.getr('BUTTON_CB'), 'uibutton'))
	assert(~check_graphics(pr_P.getr('BUTTON_CALC'), 'uibutton'))
	assert(~check_graphics(pr_P.getr('BUTTON_DEL'), 'uibutton'))    
	assert(isa(pr_P.getr('LISTENER_SET'), 'NoValue'))    
	assert(isa(pr_P.getr('LISTENER_MEMORIZED'), 'NoValue'))    
	assert(isa(pr_P.getr('LISTENER_LOCKED'), 'NoValue'))
	
	assert(~check_graphics(pr_D.getr('H'), 'uipanel'))
	assert(~check_graphics(pr_D.getr('PARENT').getr('H'), 'figure'))
	assert(~check_graphics(pr_D.getr('LABEL_TITLE'), 'uilabel'))
	assert(~check_graphics(pr_D.getr('BUTTON_CB'), 'uibutton'))
	assert(~check_graphics(pr_D.getr('BUTTON_CALC'), 'uibutton'))
	assert(~check_graphics(pr_D.getr('BUTTON_DEL'), 'uibutton'))
	assert(isa(pr_D.getr('LISTENER_SET'), 'NoValue'))    
	assert(isa(pr_D.getr('LISTENER_MEMORIZED'), 'NoValue'))
	assert(isa(pr_D.getr('LISTENER_LOCKED'), 'NoValue'))
	
	assert(~check_graphics(pr_R.getr('H'), 'uipanel'))
	assert(~check_graphics(pr_R.getr('PARENT').getr('H'), 'figure'))    
	assert(~check_graphics(pr_R.getr('LABEL_TITLE'), 'uilabel'))
	assert(~check_graphics(pr_R.getr('BUTTON_CB'), 'uibutton'))
	assert(~check_graphics(pr_R.getr('BUTTON_CALC'), 'uibutton'))
	assert(~check_graphics(pr_R.getr('BUTTON_DEL'), 'uibutton'))    
	assert(isa(pr_R.getr('LISTENER_SET'), 'NoValue'))    
	assert(isa(pr_R.getr('LISTENER_MEMORIZED'), 'NoValue'))    
	assert(isa(pr_R.getr('LISTENER_LOCKED'), 'NoValue'))
	
	assert(~check_graphics(pr_Q.getr('H'), 'uipanel'))
	assert(~check_graphics(pr_Q.getr('PARENT').getr('H'), 'figure'))
	assert(~check_graphics(pr_Q.getr('LABEL_TITLE'), 'uilabel'))
	assert(~check_graphics(pr_Q.getr('BUTTON_CB'), 'uibutton'))
	assert(~check_graphics(pr_Q.getr('BUTTON_CALC'), 'uibutton'))
	assert(~check_graphics(pr_Q.getr('BUTTON_DEL'), 'uibutton'))    
	assert(isa(pr_Q.getr('LISTENER_SET'), 'NoValue'))    
	assert(isa(pr_Q.getr('LISTENER_MEMORIZED'), 'NoValue'))    
	assert(isa(pr_Q.getr('LISTENER_LOCKED'), 'NoValue'))
	
	assert(~check_graphics(pr_E.getr('H'), 'uipanel'))
	assert(~check_graphics(pr_E.getr('PARENT').getr('H'), 'figure'))
	assert(~check_graphics(pr_E.getr('LABEL_TITLE'), 'uilabel'))
	assert(~check_graphics(pr_E.getr('BUTTON_CB'), 'uibutton'))
	assert(~check_graphics(pr_E.getr('BUTTON_CALC'), 'uibutton'))
	assert(~check_graphics(pr_E.getr('BUTTON_DEL'), 'uibutton'))
	assert(isa(pr_E.getr('LISTENER_SET'), 'NoValue'))    
	assert(isa(pr_E.getr('LISTENER_MEMORIZED'), 'NoValue'))    
	assert(isa(pr_E.getr('LISTENER_LOCKED'), 'NoValue'))
	
	assert(~check_graphics(pr_F.getr('H'), 'uipanel'))
	assert(~check_graphics(pr_F.getr('PARENT').getr('H'), 'figure'))
	assert(~check_graphics(pr_F.getr('LABEL_TITLE'), 'uilabel'))
	assert(~check_graphics(pr_F.getr('BUTTON_CB'), 'uibutton'))
	assert(~check_graphics(pr_F.getr('BUTTON_CALC'), 'uibutton'))
	assert(~check_graphics(pr_F.getr('BUTTON_DEL'), 'uibutton'))    
	assert(isa(pr_F.getr('LISTENER_SET'), 'NoValue'))    
	assert(isa(pr_F.getr('LISTENER_MEMORIZED'), 'NoValue'))    
	assert(isa(pr_F.getr('LISTENER_LOCKED'), 'NoValue'))
	
	assert(~check_graphics(pr_G.getr('H'), 'uipanel'))
	assert(~check_graphics(pr_G.getr('PARENT').getr('H'), 'figure'))
	assert(~check_graphics(pr_G.getr('LABEL_TITLE'), 'uilabel'))
	assert(~check_graphics(pr_G.getr('BUTTON_CB'), 'uibutton'))
	assert(~check_graphics(pr_G.getr('BUTTON_CALC'), 'uibutton'))
	assert(~check_graphics(pr_G.getr('BUTTON_DEL'), 'uibutton'))    
	assert(isa(pr_G.getr('LISTENER_SET'), 'NoValue'))    
	assert(isa(pr_G.getr('LISTENER_MEMORIZED'), 'NoValue'))    
	assert(isa(pr_G.getr('LISTENER_LOCKED'), 'NoValue'))
end

%% Test 13: Button & Listener Dynamics
if rand() >= (1 - .01) * BRAPH2TEST.RANDOM
	gt = GTA_PanelProp();
	gui = GUI('POSITION', [0 0 1 1], 'CLOSEREQ', false);
	
	pr_C = PanelProp('PARENT', gui, 'EL', gt, 'PROP', gt.ST_C, 'BKGCOLOR', BRAPH2.COL_C);
	pr_C.get('DRAW', 'Units', 'normalized', 'Position', [.05 .70 .40 .25])
	
	pr_M = PanelProp('PARENT', gui, 'EL', gt, 'PROP', gt.ST_M, 'BKGCOLOR', BRAPH2.COL_M);
	pr_M.get('DRAW', 'Units', 'normalized', 'Position', [.55 .70 .40 .25])
	
	pr_P = PanelProp('PARENT', gui, 'EL', gt, 'PROP', gt.ST_P, 'BKGCOLOR', BRAPH2.COL_P);
	pr_P.get('DRAW', 'Units', 'normalized', 'Position', [.05 .40 .20 .25])
	
	pr_D = PanelProp('PARENT', gui, 'EL', gt, 'PROP', gt.ST_D, 'BKGCOLOR', BRAPH2.COL_D);
	pr_D.get('DRAW', 'Units', 'normalized', 'Position', [.25 .40 .20 .25])
	
	pr_R = PanelProp('PARENT', gui, 'EL', gt, 'PROP', gt.ST_R, 'BKGCOLOR', BRAPH2.COL_R);
	pr_R.get('DRAW', 'Units', 'normalized', 'Position', [.05 .10 .25 .25])
	
	pr_Q = PanelProp('PARENT', gui, 'EL', gt, 'PROP', gt.ST_Q, 'BKGCOLOR', BRAPH2.COL_Q);
	pr_Q.get('DRAW', 'Units', 'normalized', 'Position', [.35 .10 .25 .25])
	
	pr_E = PanelProp('PARENT', gui, 'EL', gt, 'PROP', gt.ST_E, 'BKGCOLOR', BRAPH2.COL_E);
	pr_E.get('DRAW', 'Units', 'normalized', 'Position', [.65 .10 .25 .25])
	
	pr_F = PanelProp('PARENT', gui, 'EL', gt, 'PROP', gt.ST_F, 'BKGCOLOR', BRAPH2.COL_F);
	pr_F.get('DRAW', 'Units', 'normalized', 'Position', [.50 .40 .20 .25])
	
	pr_G = PanelProp('PARENT', gui, 'EL', gt, 'PROP', gt.ST_G, 'BKGCOLOR', BRAPH2.COL_G);
	pr_G.get('DRAW', 'Units', 'normalized', 'Position', [.75 .40 .20 .25])
	
	pr_C.get('SHOW') % shows all
	
	% set
	label_title_C = pr_C.get('LABEL_TITLE');
	assert(~isequal(get(label_title_C, 'Position'), [0 0 0 0]))
	set(label_title_C, 'Position', [0 0 0 0])
	assert(isequal(get(label_title_C, 'Position'), [0 0 0 0]))
	
	label_title_M = pr_M.get('LABEL_TITLE');
	assert(~isequal(get(label_title_M, 'Position'), [0 0 0 0]))
	set(label_title_M, 'Position', [0 0 0 0])
	assert(isequal(get(label_title_M, 'Position'), [0 0 0 0]))
	
	label_title_P = pr_P.get('LABEL_TITLE');
	assert(~isequal(get(label_title_P, 'Position'), [0 0 0 0]))
	set(label_title_P, 'Position', [0 0 0 0])
	assert(isequal(get(label_title_P, 'Position'), [0 0 0 0]))
	
	label_title_D = pr_D.get('LABEL_TITLE');
	assert(~isequal(get(label_title_D, 'Position'), [0 0 0 0]))
	set(label_title_D, 'Position', [0 0 0 0])
	assert(isequal(get(label_title_D, 'Position'), [0 0 0 0]))
	
	label_title_R = pr_R.get('LABEL_TITLE');
	assert(~isequal(get(label_title_R, 'Position'), [0 0 0 0]))
	set(label_title_R, 'Position', [0 0 0 0])
	assert(isequal(get(label_title_R, 'Position'), [0 0 0 0]))
	
	label_title_Q = pr_Q.get('LABEL_TITLE');
	assert(~isequal(get(label_title_Q, 'Position'), [0 0 0 0]))
	set(label_title_Q, 'Position', [0 0 0 0])
	assert(isequal(get(label_title_Q, 'Position'), [0 0 0 0]))
	
	label_title_E = pr_E.get('LABEL_TITLE');
	assert(~isequal(get(label_title_E, 'Position'), [0 0 0 0]))
	set(label_title_E, 'Position', [0 0 0 0])
	assert(isequal(get(label_title_E, 'Position'), [0 0 0 0]))
	
	label_title_F = pr_F.get('LABEL_TITLE');
	assert(~isequal(get(label_title_F, 'Position'), [0 0 0 0]))
	set(label_title_F, 'Position', [0 0 0 0])
	assert(isequal(get(label_title_F, 'Position'), [0 0 0 0]))
	
	label_title_G = pr_G.get('LABEL_TITLE');
	assert(~isequal(get(label_title_G, 'Position'), [0 0 0 0]))
	set(label_title_G, 'Position', [0 0 0 0])
	assert(isequal(get(label_title_G, 'Position'), [0 0 0 0]))
	
	gt.set('ST_C', Element.getNoValue())
	assert(~isequal(get(label_title_C, 'Position'), [0 0 0 0]))
	assert(isequal(get(label_title_M, 'Position'), [0 0 0 0]))
	assert(isequal(get(label_title_P, 'Position'), [0 0 0 0]))
	assert(isequal(get(label_title_D, 'Position'), [0 0 0 0]))
	assert(isequal(get(label_title_R, 'Position'), [0 0 0 0]))
	assert(isequal(get(label_title_Q, 'Position'), [0 0 0 0]))
	assert(isequal(get(label_title_E, 'Position'), [0 0 0 0]))
	assert(isequal(get(label_title_F, 'Position'), [0 0 0 0]))
	assert(isequal(get(label_title_G, 'Position'), [0 0 0 0]))
	
	gt.set('ST_M', '12345')
	assert(~isequal(get(label_title_C, 'Position'), [0 0 0 0]))
	assert(~isequal(get(label_title_M, 'Position'), [0 0 0 0]))
	assert(isequal(get(label_title_P, 'Position'), [0 0 0 0]))
	assert(isequal(get(label_title_D, 'Position'), [0 0 0 0]))
	assert(isequal(get(label_title_R, 'Position'), [0 0 0 0]))
	assert(isequal(get(label_title_Q, 'Position'), [0 0 0 0]))
	assert(isequal(get(label_title_E, 'Position'), [0 0 0 0]))
	assert(isequal(get(label_title_F, 'Position'), [0 0 0 0]))
	assert(isequal(get(label_title_G, 'Position'), [0 0 0 0]))
	
	gt.set('ST_P', '1234')
	assert(~isequal(get(label_title_C, 'Position'), [0 0 0 0]))
	assert(~isequal(get(label_title_M, 'Position'), [0 0 0 0]))
	assert(~isequal(get(label_title_P, 'Position'), [0 0 0 0]))
	assert(isequal(get(label_title_D, 'Position'), [0 0 0 0]))
	assert(isequal(get(label_title_R, 'Position'), [0 0 0 0]))
	assert(isequal(get(label_title_Q, 'Position'), [0 0 0 0]))
	assert(isequal(get(label_title_E, 'Position'), [0 0 0 0]))
	assert(isequal(get(label_title_F, 'Position'), [0 0 0 0]))
	assert(isequal(get(label_title_G, 'Position'), [0 0 0 0]))
	
	gt.set('ST_D', '123456')
	assert(~isequal(get(label_title_C, 'Position'), [0 0 0 0]))
	assert(~isequal(get(label_title_M, 'Position'), [0 0 0 0]))
	assert(~isequal(get(label_title_P, 'Position'), [0 0 0 0]))
	assert(~isequal(get(label_title_D, 'Position'), [0 0 0 0]))
	assert(isequal(get(label_title_R, 'Position'), [0 0 0 0]))
	assert(isequal(get(label_title_Q, 'Position'), [0 0 0 0]))
	assert(isequal(get(label_title_E, 'Position'), [0 0 0 0]))
	assert(isequal(get(label_title_F, 'Position'), [0 0 0 0]))
	assert(isequal(get(label_title_G, 'Position'), [0 0 0 0]))
	
	gt.set('ST_R', Element.getNoValue())
	assert(~isequal(get(label_title_R, 'Position'), [0 0 0 0]))
	assert(~isequal(get(label_title_M, 'Position'), [0 0 0 0]))
	assert(~isequal(get(label_title_P, 'Position'), [0 0 0 0]))
	assert(~isequal(get(label_title_D, 'Position'), [0 0 0 0]))
	assert(~isequal(get(label_title_R, 'Position'), [0 0 0 0]))
	assert(isequal(get(label_title_Q, 'Position'), [0 0 0 0]))
	assert(isequal(get(label_title_E, 'Position'), [0 0 0 0]))
	assert(isequal(get(label_title_F, 'Position'), [0 0 0 0]))
	assert(isequal(get(label_title_G, 'Position'), [0 0 0 0]))
	
	gt.set('ST_Q', Element.getNoValue())
	assert(~isequal(get(label_title_C, 'Position'), [0 0 0 0]))
	assert(~isequal(get(label_title_M, 'Position'), [0 0 0 0]))
	assert(~isequal(get(label_title_P, 'Position'), [0 0 0 0]))
	assert(~isequal(get(label_title_D, 'Position'), [0 0 0 0]))
	assert(~isequal(get(label_title_R, 'Position'), [0 0 0 0]))
	assert(~isequal(get(label_title_Q, 'Position'), [0 0 0 0]))
	assert(isequal(get(label_title_E, 'Position'), [0 0 0 0]))
	assert(isequal(get(label_title_F, 'Position'), [0 0 0 0]))
	assert(isequal(get(label_title_G, 'Position'), [0 0 0 0]))
	
	gt.set('ST_E', Element.getNoValue())
	assert(~isequal(get(label_title_C, 'Position'), [0 0 0 0]))
	assert(~isequal(get(label_title_M, 'Position'), [0 0 0 0]))
	assert(~isequal(get(label_title_P, 'Position'), [0 0 0 0]))
	assert(~isequal(get(label_title_D, 'Position'), [0 0 0 0]))
	assert(~isequal(get(label_title_R, 'Position'), [0 0 0 0]))
	assert(~isequal(get(label_title_Q, 'Position'), [0 0 0 0]))
	assert(~isequal(get(label_title_E, 'Position'), [0 0 0 0]))
	assert(isequal(get(label_title_F, 'Position'), [0 0 0 0]))
	assert(isequal(get(label_title_G, 'Position'), [0 0 0 0]))
	
	gt.set('ST_F', '1234')
	assert(~isequal(get(label_title_C, 'Position'), [0 0 0 0]))
	assert(~isequal(get(label_title_M, 'Position'), [0 0 0 0]))
	assert(~isequal(get(label_title_P, 'Position'), [0 0 0 0]))
	assert(~isequal(get(label_title_D, 'Position'), [0 0 0 0]))
	assert(~isequal(get(label_title_R, 'Position'), [0 0 0 0]))
	assert(~isequal(get(label_title_Q, 'Position'), [0 0 0 0]))
	assert(~isequal(get(label_title_E, 'Position'), [0 0 0 0]))
	assert(~isequal(get(label_title_F, 'Position'), [0 0 0 0]))
	assert(isequal(get(label_title_G, 'Position'), [0 0 0 0]))
	
	gt.set('ST_G', '1234')
	assert(~isequal(get(label_title_C, 'Position'), [0 0 0 0]))
	assert(~isequal(get(label_title_M, 'Position'), [0 0 0 0]))
	assert(~isequal(get(label_title_P, 'Position'), [0 0 0 0]))
	assert(~isequal(get(label_title_D, 'Position'), [0 0 0 0]))
	assert(~isequal(get(label_title_R, 'Position'), [0 0 0 0]))
	assert(~isequal(get(label_title_Q, 'Position'), [0 0 0 0]))
	assert(~isequal(get(label_title_E, 'Position'), [0 0 0 0]))
	assert(~isequal(get(label_title_F, 'Position'), [0 0 0 0]))
	assert(~isequal(get(label_title_G, 'Position'), [0 0 0 0]))
	
	% memorize & locked
	label_title_C = pr_C.get('LABEL_TITLE');
	assert(~isequal(get(label_title_C, 'Position'), [0 0 0 0]))
	set(label_title_C, 'Position', [0 0 0 0])
	assert(isequal(get(label_title_C, 'Position'), [0 0 0 0]))
	
	label_title_M = pr_M.get('LABEL_TITLE');
	assert(~isequal(get(label_title_M, 'Position'), [0 0 0 0]))
	set(label_title_M, 'Position', [0 0 0 0])
	assert(isequal(get(label_title_M, 'Position'), [0 0 0 0]))
	
	label_title_P = pr_P.get('LABEL_TITLE');
	assert(~isequal(get(label_title_P, 'Position'), [0 0 0 0]))
	set(label_title_P, 'Position', [0 0 0 0])
	assert(isequal(get(label_title_P, 'Position'), [0 0 0 0]))
	
	label_title_D = pr_D.get('LABEL_TITLE');
	assert(~isequal(get(label_title_D, 'Position'), [0 0 0 0]))
	set(label_title_D, 'Position', [0 0 0 0])
	assert(isequal(get(label_title_D, 'Position'), [0 0 0 0]))
	
	label_title_R = pr_R.get('LABEL_TITLE');
	assert(~isequal(get(label_title_R, 'Position'), [0 0 0 0]))
	set(label_title_R, 'Position', [0 0 0 0])
	assert(isequal(get(label_title_R, 'Position'), [0 0 0 0]))
	
	label_title_Q = pr_Q.get('LABEL_TITLE');
	assert(~isequal(get(label_title_Q, 'Position'), [0 0 0 0]))
	set(label_title_Q, 'Position', [0 0 0 0])
	assert(isequal(get(label_title_Q, 'Position'), [0 0 0 0]))
	
	label_title_E = pr_E.get('LABEL_TITLE');
	assert(~isequal(get(label_title_E, 'Position'), [0 0 0 0]))
	set(label_title_E, 'Position', [0 0 0 0])
	assert(isequal(get(label_title_E, 'Position'), [0 0 0 0]))
	
	label_title_F = pr_F.get('LABEL_TITLE');
	assert(~isequal(get(label_title_F, 'Position'), [0 0 0 0]))
	set(label_title_F, 'Position', [0 0 0 0])
	assert(isequal(get(label_title_F, 'Position'), [0 0 0 0]))
	
	label_title_G = pr_G.get('LABEL_TITLE');
	assert(~isequal(get(label_title_G, 'Position'), [0 0 0 0]))
	set(label_title_G, 'Position', [0 0 0 0])
	assert(isequal(get(label_title_G, 'Position'), [0 0 0 0]))
	
	button_calc_R = pr_R.get('BUTTON_CALC');
	assert(~isequal(get(button_calc_R, 'Position'), [0 0 0 0]))
	set(button_calc_R, 'Position', [0 0 0 0])
	assert(isequal(get(button_calc_R, 'Position'), [0 0 0 0]))
	button_del_R = pr_R.get('BUTTON_DEL');
	assert(~isequal(get(button_del_R, 'Position'), [0 0 0 0]))
	set(button_del_R, 'Position', [0 0 0 0])
	assert(isequal(get(button_del_R, 'Position'), [0 0 0 0])) 
	
	button_calc_Q = pr_Q.get('BUTTON_CALC');
	assert(~isequal(get(button_calc_Q, 'Position'), [0 0 0 0]))
	set(button_calc_Q, 'Position', [0 0 0 0])
	assert(isequal(get(button_calc_Q, 'Position'), [0 0 0 0]))
	button_del_Q = pr_Q.get('BUTTON_DEL');
	assert(~isequal(get(button_del_Q, 'Position'), [0 0 0 0]))
	set(button_del_Q, 'Position', [0 0 0 0])
	assert(isequal(get(button_del_Q, 'Position'), [0 0 0 0]))
	
	button_calc_E = pr_E.get('BUTTON_CALC');
	assert(~isequal(get(button_calc_E, 'Position'), [0 0 0 0]))
	set(button_calc_E, 'Position', [0 0 0 0])
	assert(isequal(get(button_calc_E, 'Position'), [0 0 0 0]))
	button_del_E = pr_E.get('BUTTON_DEL');
	assert(~isequal(get(button_del_E, 'Position'), [0 0 0 0]))
	set(button_del_E, 'Position', [0 0 0 0])
	assert(isequal(get(button_del_E, 'Position'), [0 0 0 0]))
	
	gt.memorize('ST_R') % also locks P and D
	assert(~isequal(get(button_calc_R, 'Position'), [0 0 0 0]))
	assert(~isequal(get(button_del_R, 'Position'), [0 0 0 0]))
	assert(isequal(get(button_calc_Q, 'Position'), [0 0 0 0]))
	assert(isequal(get(button_del_Q, 'Position'), [0 0 0 0]))
	assert(isequal(get(button_calc_E, 'Position'), [0 0 0 0]))
	assert(isequal(get(button_del_E, 'Position'), [0 0 0 0]))
	
	assert(isequal(get(label_title_C, 'Position'), [0 0 0 0]))
	assert(isequal(get(label_title_M, 'Position'), [0 0 0 0]))
	assert(~isequal(get(label_title_P, 'Position'), [0 0 0 0]))
	assert(~isequal(get(label_title_D, 'Position'), [0 0 0 0]))
	assert(~isequal(get(label_title_R, 'Position'), [0 0 0 0]))
	assert(isequal(get(label_title_Q, 'Position'), [0 0 0 0]))
	assert(isequal(get(label_title_E, 'Position'), [0 0 0 0]))
	assert(isequal(get(label_title_F, 'Position'), [0 0 0 0]))
	assert(isequal(get(label_title_G, 'Position'), [0 0 0 0]))
	
	warning('off', [BRAPH2.STR ':' class(gt)])
	gt.memorize('ST_Q')
	warning('on', [BRAPH2.STR ':' class(gt)])
	assert(~isequal(get(button_calc_R, 'Position'), [0 0 0 0]))
	assert(~isequal(get(button_del_R, 'Position'), [0 0 0 0]))
	assert(~isequal(get(button_calc_Q, 'Position'), [0 0 0 0]))
	assert(~isequal(get(button_del_Q, 'Position'), [0 0 0 0]))
	assert(isequal(get(button_calc_E, 'Position'), [0 0 0 0]))
	assert(isequal(get(button_del_E, 'Position'), [0 0 0 0]))
	
	assert(isequal(get(label_title_C, 'Position'), [0 0 0 0]))
	assert(isequal(get(label_title_M, 'Position'), [0 0 0 0]))
	assert(~isequal(get(label_title_P, 'Position'), [0 0 0 0]))
	assert(~isequal(get(label_title_D, 'Position'), [0 0 0 0]))
	assert(~isequal(get(label_title_R, 'Position'), [0 0 0 0]))
	assert(~isequal(get(label_title_Q, 'Position'), [0 0 0 0]))
	assert(isequal(get(label_title_E, 'Position'), [0 0 0 0]))
	assert(isequal(get(label_title_F, 'Position'), [0 0 0 0]))
	assert(isequal(get(label_title_G, 'Position'), [0 0 0 0]))
	
	gt.memorize('ST_E')
	assert(~isequal(get(button_calc_R, 'Position'), [0 0 0 0]))
	assert(~isequal(get(button_del_R, 'Position'), [0 0 0 0]))
	assert(~isequal(get(button_calc_Q, 'Position'), [0 0 0 0]))
	assert(~isequal(get(button_del_Q, 'Position'), [0 0 0 0]))
	assert(~isequal(get(button_calc_E, 'Position'), [0 0 0 0]))
	assert(~isequal(get(button_del_E, 'Position'), [0 0 0 0]))
	
	assert(isequal(get(label_title_C, 'Position'), [0 0 0 0]))
	assert(isequal(get(label_title_M, 'Position'), [0 0 0 0]))
	assert(~isequal(get(label_title_P, 'Position'), [0 0 0 0]))
	assert(~isequal(get(label_title_D, 'Position'), [0 0 0 0]))
	assert(~isequal(get(label_title_R, 'Position'), [0 0 0 0]))
	assert(~isequal(get(label_title_Q, 'Position'), [0 0 0 0]))
	assert(~isequal(get(label_title_E, 'Position'), [0 0 0 0]))
	assert(isequal(get(label_title_F, 'Position'), [0 0 0 0]))
	assert(isequal(get(label_title_G, 'Position'), [0 0 0 0]))
	
	gt.lock('ST_F')
	assert(isequal(get(label_title_C, 'Position'), [0 0 0 0]))
	assert(isequal(get(label_title_M, 'Position'), [0 0 0 0]))
	assert(~isequal(get(label_title_P, 'Position'), [0 0 0 0]))
	assert(~isequal(get(label_title_D, 'Position'), [0 0 0 0]))
	assert(~isequal(get(label_title_R, 'Position'), [0 0 0 0]))
	assert(~isequal(get(label_title_Q, 'Position'), [0 0 0 0]))
	assert(~isequal(get(label_title_E, 'Position'), [0 0 0 0]))
	assert(~isequal(get(label_title_F, 'Position'), [0 0 0 0]))
	assert(isequal(get(label_title_G, 'Position'), [0 0 0 0]))
	
	gt.lock('ST_G')
	assert(isequal(get(label_title_C, 'Position'), [0 0 0 0]))
	assert(isequal(get(label_title_M, 'Position'), [0 0 0 0]))
	assert(~isequal(get(label_title_P, 'Position'), [0 0 0 0]))
	assert(~isequal(get(label_title_D, 'Position'), [0 0 0 0]))
	assert(~isequal(get(label_title_R, 'Position'), [0 0 0 0]))
	assert(~isequal(get(label_title_Q, 'Position'), [0 0 0 0]))
	assert(~isequal(get(label_title_E, 'Position'), [0 0 0 0]))
	assert(~isequal(get(label_title_F, 'Position'), [0 0 0 0]))
	assert(~isequal(get(label_title_G, 'Position'), [0 0 0 0]))
	
	pr_F.get('CLOSE') % closes all
end

%% Test 14: No Figures Left
if rand() >= (1 - 1) * BRAPH2TEST.RANDOM
	assert(isempty(findall(0, 'type', 'figure')), ...
		[BRAPH2.STR ':GTA_PanelProp:' BRAPH2.FAIL_TEST], ...
		[' When testing GTA_PanelProp no figures should be left over, either visible or not. ' ...
		int2str(length(findall(0, 'type', 'figure'))) ' figure(s) were left over.'] ...
		)
end

%% Test 15: Delete Figures
if rand() >= (1 - 1) * BRAPH2TEST.RANDOM
	delete(findall(0, 'type', 'figure'))
end

