distribution_name = 'DiSTAP';
distribution_moniker = 'distap';
pipeline_folders = {
    'RamanSpectra'
    'VariationalAutoencoder'
    'VariationalAutoencoderRamanSpectra'
    };
braph2_version = 'heads/develop';

% Add here all included and excluded folders and elements
% '-folder'                 the folder and its elements will be excluded
%
% '+folder'                 the folder is included, but not its elements
%   '+_ElementName.gen.m'   the element is included,
%                           if the folder is included
%
% '+folder*'                the folder and its elements are included
%   '-_ElementName.gen.m'   the element is excluded,
%                           if the folder and its elements are included
% (by default, the folders are included as '+folder*')
rollcall = { ...
    '+util*', ...
    '+ds*', '-ds_examples', ...
    '-atlas', ...
    '-gt',  ...
    '+cohort*', ...
    '-analysis', ...
    '+nn*', ...
    '+gui*', ...
    '-brainsurfs', ...
    '-atlases', ...
    '-graphs', ...
    '-measures', ...
    '-neuralnetworks', ...
    '+pipelines', ...
    '+RamanSpectra*', '+VariationalAutoencoder*', '+VariationalAutoencoderRamanSpectra*', ...
    '+test*', ...
    '-sandbox' ...
    };
files_to_delete = { ...
    ['src' filesep 'gui' filesep 'test_PanelPropCell.m'], ...
    ['src' filesep 'gui' filesep 'test_PanelPropClassList.m'], ...
    ['src' filesep 'gui' filesep 'test_PanelPropIDictTable.m'], ...
    ['src' filesep 'gui' filesep 'test_PanelPropRVectorSmart.m'], ...
    ['src' filesep 'gui' filesep 'test_PanelPropRVectorView.m'], ...
    ['src' filesep 'gui' filesep 'test_PanelPropStringList.m'], ...
    ['src' filesep 'gui' filesep 'test_SettingsAmbientPP.m'], ...
    ['src' filesep 'gui' filesep 'test_SettingsAreaPP.m'], ...
    ['src' filesep 'gui' filesep 'test_SettingsAxisPP.m'], ...
    ['src' filesep 'gui' filesep 'test_SettingsLinePP.m'], ...
    ['src' filesep 'gui' filesep 'test_SettingsPP.m'], ...
    ['src' filesep 'gui' filesep 'test_SettingsSurfacePP.m'], ...
    ['src' filesep 'gui' filesep 'test_SettingsTextPP.m'], ...
    ['pipelines' filesep 'RamanSpectra' filesep 'test_ImporterRamanExperiment_ASC.m'], ...
    ['pipelines' filesep 'RamanSpectra' filesep 'test_ImporterRamanExperiment_B2.m'], ...
    ['pipelines' filesep 'RamanSpectra' filesep 'test_ImporterRamanExperiment_TXT.m'] ...
    };
