%TEST_NNVARIATIONALAUTOENCODEREVALUATOR

%% Test 1: Inspection Methods
if rand() >= (1 - .01) * BRAPH2TEST.RANDOM
	categories = num2cell(Category.getCategories());
	nne = NNVariationalAutoencoderEvaluator();
	 
	% get('ELCLASS')
	if isa(NNVariationalAutoencoderEvaluator, 'ConcreteElement')
		assert(strcmp(NNVariationalAutoencoderEvaluator().get('ELCLASS'), 'NNVariationalAutoencoderEvaluator'), ...
			[BRAPH2.STR ':NNVariationalAutoencoderEvaluator:' BRAPH2.FAIL_TEST], ...
			'NNVariationalAutoencoderEvaluator().get(''ELCLASS'') should return ''NNVariationalAutoencoderEvaluator''.')
	end
	 
	% getBuild()
	assert(NNVariationalAutoencoderEvaluator.getBuild() == 1 && NNVariationalAutoencoderEvaluator.getBuild() > 0, ...
		[BRAPH2.STR ':NNVariationalAutoencoderEvaluator:' BRAPH2.FAIL_TEST], ...
		'NNVariationalAutoencoderEvaluator.getBuild() should return the NNVariationalAutoencoderEvaluator build number.')
	assert(nne.getBuild() == 1 && nne.getBuild() > 0 , ...
		[BRAPH2.STR ':NNVariationalAutoencoderEvaluator:' BRAPH2.FAIL_TEST], ...
		'nne.getBuild() should return the NNVariationalAutoencoderEvaluator build number.')
	assert(Element.getBuild(nne) == 1 && Element.getBuild(nne) > 0, ...
		[BRAPH2.STR ':NNVariationalAutoencoderEvaluator:' BRAPH2.FAIL_TEST], ...
		'Element.getBuild(nne) should return the NNVariationalAutoencoderEvaluator build number.')
	assert(Element.getBuild('NNVariationalAutoencoderEvaluator') == 1 && Element.getBuild('NNVariationalAutoencoderEvaluator') > 0, ...
		[BRAPH2.STR ':NNVariationalAutoencoderEvaluator:' BRAPH2.FAIL_TEST], ...
		'Element.getBuild(''NNVariationalAutoencoderEvaluator'') should return the NNVariationalAutoencoderEvaluator build number.')
	 
	% getClass()
	assert(strcmp(NNVariationalAutoencoderEvaluator.getClass(), 'NNVariationalAutoencoderEvaluator'), ...
		[BRAPH2.STR ':NNVariationalAutoencoderEvaluator:' BRAPH2.FAIL_TEST], ...
		'NNVariationalAutoencoderEvaluator.getClass() should return ''NNVariationalAutoencoderEvaluator''.')
	assert(strcmp(nne.getClass(), 'NNVariationalAutoencoderEvaluator'), ...
		[BRAPH2.STR ':NNVariationalAutoencoderEvaluator:' BRAPH2.FAIL_TEST], ...
		'nne.getClass() should return ''NNVariationalAutoencoderEvaluator''.')
	assert(strcmp(Element.getClass(nne), 'NNVariationalAutoencoderEvaluator'), ...
		[BRAPH2.STR ':NNVariationalAutoencoderEvaluator:' BRAPH2.FAIL_TEST], ...
		'Element.getClass(nne) should return ''NNVariationalAutoencoderEvaluator''.')
	assert(strcmp(Element.getClass('NNVariationalAutoencoderEvaluator'), 'NNVariationalAutoencoderEvaluator'), ...
		[BRAPH2.STR ':NNVariationalAutoencoderEvaluator:' BRAPH2.FAIL_TEST], ...
		'Element.getClass(''NNVariationalAutoencoderEvaluator'') should return ''NNVariationalAutoencoderEvaluator''.')
	 
	% getSubclasses()
	assert(isequal(NNVariationalAutoencoderEvaluator.getSubclasses(), subclasses('NNVariationalAutoencoderEvaluator', [], [], true)), ...
		[BRAPH2.STR ':NNVariationalAutoencoderEvaluator:' BRAPH2.FAIL_TEST], ...
		'NNVariationalAutoencoderEvaluator.getSubclasses() should return the same result as subclasses(''NNVariationalAutoencoderEvaluator'', [], [], true).')
	assert(isequal(nne.getSubclasses(), subclasses('NNVariationalAutoencoderEvaluator', [], [], true)), ...
		[BRAPH2.STR ':NNVariationalAutoencoderEvaluator:' BRAPH2.FAIL_TEST], ...
		'el.getSubclasses() should return the same result as subclasses(''NNVariationalAutoencoderEvaluator'', [], [], true).')
	assert(isequal(Element.getSubclasses(nne), subclasses('NNVariationalAutoencoderEvaluator', [], [], true)), ...
		[BRAPH2.STR ':NNVariationalAutoencoderEvaluator:' BRAPH2.FAIL_TEST], ...
		'Element.getSubclasses(nne) should return the same result as subclasses(''NNVariationalAutoencoderEvaluator'', [], [], true).')
	assert(isequal(Element.getSubclasses('NNVariationalAutoencoderEvaluator'), subclasses('NNVariationalAutoencoderEvaluator', [], [], true)), ...
		[BRAPH2.STR ':NNVariationalAutoencoderEvaluator:' BRAPH2.FAIL_TEST], ...
		'Element.getSubclasses(''NNVariationalAutoencoderEvaluator'') should return the same result as subclasses(''NNVariationalAutoencoderEvaluator'', [], [], true).')
	 
	% getProps()
	assert(isempty(NNVariationalAutoencoderEvaluator.getProps()) || isequal(NNVariationalAutoencoderEvaluator.getProps(), 1:1:length(NNVariationalAutoencoderEvaluator.getProps())), ...
		[BRAPH2.STR ':NNVariationalAutoencoderEvaluator:' BRAPH2.FAIL_TEST], ...
		'NNVariationalAutoencoderEvaluator.getProps() should return a row vector [1:1:N].')
	assert(isempty(NNVariationalAutoencoderEvaluator.getProps()) || isequal(nne.getProps(), 1:1:length(NNVariationalAutoencoderEvaluator.getProps())), ...
		[BRAPH2.STR ':NNVariationalAutoencoderEvaluator:' BRAPH2.FAIL_TEST], ...
		'nne.getProps() should return a row vector [1:1:N].')
	assert(isempty(NNVariationalAutoencoderEvaluator.getProps()) || isequal(Element.getProps(nne), 1:1:length(NNVariationalAutoencoderEvaluator.getProps())), ...
		[BRAPH2.STR ':NNVariationalAutoencoderEvaluator:' BRAPH2.FAIL_TEST], ...
		'Element.getProps(nne) should return a row vector [1:1:N].')
	assert(isempty(NNVariationalAutoencoderEvaluator.getProps()) || isequal(Element.getProps('NNVariationalAutoencoderEvaluator'), 1:1:length(NNVariationalAutoencoderEvaluator.getProps())), ...
		[BRAPH2.STR ':NNVariationalAutoencoderEvaluator:' BRAPH2.FAIL_TEST], ...
		'Element.getProps(''NNVariationalAutoencoderEvaluator'') should return a row vector [1:1:N].')
	 
	% getProps(category)
	tmp = cellfun(@(category) NNVariationalAutoencoderEvaluator.getProps(category), categories, 'UniformOutput', false);
	assert(isempty(NNVariationalAutoencoderEvaluator.getProps()) || isequal(sort(horzcat(tmp{:})), 1:1:length(NNVariationalAutoencoderEvaluator.getProps())), ...
		[BRAPH2.STR ':NNVariationalAutoencoderEvaluator:' BRAPH2.FAIL_TEST], ...
		'NNVariationalAutoencoderEvaluator.getProps(category) does not work.')
	tmp = cellfun(@(category) nne.getProps(category), categories, 'UniformOutput', false);
	assert(isempty(NNVariationalAutoencoderEvaluator.getProps()) || isequal(sort(horzcat(tmp{:})), 1:1:length(NNVariationalAutoencoderEvaluator.getProps())), ...
		[BRAPH2.STR ':NNVariationalAutoencoderEvaluator:' BRAPH2.FAIL_TEST], ...
		'nne.getProps(category) does not work.')
	tmp = cellfun(@(category) Element.getProps(nne, category), categories, 'UniformOutput', false);
	assert(isempty(NNVariationalAutoencoderEvaluator.getProps()) || isequal(sort(horzcat(tmp{:})), 1:1:length(NNVariationalAutoencoderEvaluator.getProps())), ...
		[BRAPH2.STR ':NNVariationalAutoencoderEvaluator:' BRAPH2.FAIL_TEST], ...
		'Element.getProps(nne, category) does not work.')
	tmp = cellfun(@(category) Element.getProps('NNVariationalAutoencoderEvaluator', category), categories, 'UniformOutput', false);
	assert(isempty(NNVariationalAutoencoderEvaluator.getProps()) || isequal(sort(horzcat(tmp{:})), 1:1:length(NNVariationalAutoencoderEvaluator.getProps())), ...
		[BRAPH2.STR ':NNVariationalAutoencoderEvaluator:' BRAPH2.FAIL_TEST], ...
		'Element.getProps(''NNVariationalAutoencoderEvaluator'', category) does not work.')
	 
	% getPropNumber()
	assert(NNVariationalAutoencoderEvaluator.getPropNumber() == length(NNVariationalAutoencoderEvaluator.getProps()), ...
		[BRAPH2.STR ':NNVariationalAutoencoderEvaluator:' BRAPH2.FAIL_TEST], ...
		'NNVariationalAutoencoderEvaluator.getPropNumber() should return the number of properties.')
	assert(nne.getPropNumber() == length(NNVariationalAutoencoderEvaluator.getProps()), ...
		[BRAPH2.STR ':NNVariationalAutoencoderEvaluator:' BRAPH2.FAIL_TEST], ...
		'nne.getPropNumber() should return the number of properties.')
	assert(Element.getPropNumber(nne) == length(NNVariationalAutoencoderEvaluator.getProps()), ...
		[BRAPH2.STR ':NNVariationalAutoencoderEvaluator:' BRAPH2.FAIL_TEST], ...
		'Element.getPropNumber(nne) should return the number of properties.')
	assert(Element.getPropNumber('NNVariationalAutoencoderEvaluator') == length(NNVariationalAutoencoderEvaluator.getProps()), ...
		[BRAPH2.STR ':NNVariationalAutoencoderEvaluator:' BRAPH2.FAIL_TEST], ...
		'Element.getPropNumber(''NNVariationalAutoencoderEvaluator'') should return the number of properties.')
	 
	% getPropNumber(category)
	assert(sum(cellfun(@(category) NNVariationalAutoencoderEvaluator.getPropNumber(category), categories)) == NNVariationalAutoencoderEvaluator.getPropNumber(), ...
		[BRAPH2.STR ':NNVariationalAutoencoderEvaluator:' BRAPH2.FAIL_TEST], ...
		'NNVariationalAutoencoderEvaluator.getPropNumber(category) does not work.')
	assert(sum(cellfun(@(category) nne.getPropNumber(category), categories)) == NNVariationalAutoencoderEvaluator.getPropNumber(), ...
		[BRAPH2.STR ':NNVariationalAutoencoderEvaluator:' BRAPH2.FAIL_TEST], ...
		'nne.getPropNumber(category) does not work.')
	assert(sum(cellfun(@(category) Element.getPropNumber(nne, category), categories)) == NNVariationalAutoencoderEvaluator.getPropNumber(), ...
		[BRAPH2.STR ':NNVariationalAutoencoderEvaluator:' BRAPH2.FAIL_TEST], ...
		'Element.getPropNumber(nne, category) does not work.')
	assert(sum(cellfun(@(category) Element.getPropNumber('NNVariationalAutoencoderEvaluator', category), categories)) == NNVariationalAutoencoderEvaluator.getPropNumber(), ...
		[BRAPH2.STR ':NNVariationalAutoencoderEvaluator:' BRAPH2.FAIL_TEST], ...
		'Element.getPropNumber(''NNVariationalAutoencoderEvaluator'', category) does not work.')
	 
	% existsProp(prop)
	assert(~NNVariationalAutoencoderEvaluator.existsProp(NaN), ...
		[BRAPH2.STR ':NNVariationalAutoencoderEvaluator:' BRAPH2.FAIL_TEST], ...
		'NNVariationalAutoencoderEvaluator.existsProp(prop) does not work.')
	assert(~nne.existsProp(NaN), ...
		[BRAPH2.STR ':NNVariationalAutoencoderEvaluator:' BRAPH2.FAIL_TEST], ...
		'nne.existsProp(prop) does not work.')
	assert(~Element.existsProp(nne, NaN), ...
		[BRAPH2.STR ':NNVariationalAutoencoderEvaluator:' BRAPH2.FAIL_TEST], ...
		'Element.existsProp(nne, prop) does not work.')
	assert(~Element.existsProp('NNVariationalAutoencoderEvaluator', NaN), ...
		[BRAPH2.STR ':NNVariationalAutoencoderEvaluator:' BRAPH2.FAIL_TEST], ...
		'Element.existsProp(''NNVariationalAutoencoderEvaluator'', prop) does not work.')
	 
	assert_with_error('NNVariationalAutoencoderEvaluator.existsProp(NaN)', [BRAPH2.STR ':NNVariationalAutoencoderEvaluator:' BRAPH2.WRONG_INPUT])
	assert_with_error('varargin{1}.existsProp(NaN)', [BRAPH2.STR ':NNVariationalAutoencoderEvaluator:' BRAPH2.WRONG_INPUT], nne)
	assert_with_error('Element.existsProp(varargin{1}, NaN)', [BRAPH2.STR ':NNVariationalAutoencoderEvaluator:' BRAPH2.WRONG_INPUT], nne)
	assert_with_error('Element.existsProp(''NNVariationalAutoencoderEvaluator'', NaN)', [BRAPH2.STR ':NNVariationalAutoencoderEvaluator:' BRAPH2.WRONG_INPUT])
	 
	for prop = 1:1:NNVariationalAutoencoderEvaluator.getPropNumber()
		assert(NNVariationalAutoencoderEvaluator.existsProp(prop), ...
			[BRAPH2.STR ':NNVariationalAutoencoderEvaluator:' BRAPH2.FAIL_TEST], ...
			'NNVariationalAutoencoderEvaluator.existsProp(prop) does not work.')
		assert(nne.existsProp(prop), ...
			[BRAPH2.STR ':NNVariationalAutoencoderEvaluator:' BRAPH2.FAIL_TEST], ...
			'nne.existsProp(prop) does not work.')
		assert(Element.existsProp(nne, prop), ...
			[BRAPH2.STR ':NNVariationalAutoencoderEvaluator:' BRAPH2.FAIL_TEST], ...
			'Element.existsProp(nne, prop) does not work.')
		assert(Element.existsProp('NNVariationalAutoencoderEvaluator', prop), ...
			[BRAPH2.STR ':NNVariationalAutoencoderEvaluator:' BRAPH2.FAIL_TEST], ...
			'Element.existsProp(''NNVariationalAutoencoderEvaluator'', prop) does not work.')
	end
	 
	% existsTag(tag)
	assert(~NNVariationalAutoencoderEvaluator.existsTag(''), ...
		[BRAPH2.STR ':NNVariationalAutoencoderEvaluator:' BRAPH2.FAIL_TEST], ...
		'NNVariationalAutoencoderEvaluator.existsTag(tag) does not work.')
	assert(~nne.existsTag(''), ...
		[BRAPH2.STR ':NNVariationalAutoencoderEvaluator:' BRAPH2.FAIL_TEST], ...
		'nne.existsTag(tag) does not work.')
	assert(~Element.existsTag(nne, ''), ...
		[BRAPH2.STR ':NNVariationalAutoencoderEvaluator:' BRAPH2.FAIL_TEST], ...
		'Element.existsTag(nne, tag) does not work.')
	assert(~Element.existsTag('NNVariationalAutoencoderEvaluator', ''), ...
		[BRAPH2.STR ':NNVariationalAutoencoderEvaluator:' BRAPH2.FAIL_TEST], ...
		'Element.existsTag(''NNVariationalAutoencoderEvaluator'', tag) does not work.')
	 
	assert_with_error('NNVariationalAutoencoderEvaluator.existsTag('''')', [BRAPH2.STR ':NNVariationalAutoencoderEvaluator:' BRAPH2.WRONG_INPUT])
	assert_with_error('varargin{1}.existsTag('''')', [BRAPH2.STR ':NNVariationalAutoencoderEvaluator:' BRAPH2.WRONG_INPUT], nne)
	assert_with_error('Element.existsTag(varargin{1}, '''')', [BRAPH2.STR ':NNVariationalAutoencoderEvaluator:' BRAPH2.WRONG_INPUT], nne)
	assert_with_error('Element.existsTag(''NNVariationalAutoencoderEvaluator'', '''')', [BRAPH2.STR ':NNVariationalAutoencoderEvaluator:' BRAPH2.WRONG_INPUT])
	 
	for prop = 1:1:NNVariationalAutoencoderEvaluator.getPropNumber()
		tag = nne.getPropTag(prop);
		assert(NNVariationalAutoencoderEvaluator.existsTag(tag), ...
			[BRAPH2.STR ':NNVariationalAutoencoderEvaluator:' BRAPH2.FAIL_TEST], ...
			'NNVariationalAutoencoderEvaluator.existsTag(tag) does not work.')
		assert(nne.existsTag(tag), ...
			[BRAPH2.STR ':NNVariationalAutoencoderEvaluator:' BRAPH2.FAIL_TEST], ...
			'nne.existsTag(tag) does not work.')
		assert(Element.existsTag(nne, tag), ...
			[BRAPH2.STR ':NNVariationalAutoencoderEvaluator:' BRAPH2.FAIL_TEST], ...
			'Element.existsTag(nne, tga) does not work.')
		assert(Element.existsTag('NNVariationalAutoencoderEvaluator', tag), ...
			[BRAPH2.STR ':NNVariationalAutoencoderEvaluator:' BRAPH2.FAIL_TEST], ...
			'Element.existsTag(''NNVariationalAutoencoderEvaluator'', tag) does not work.')
	end
	 
	% getPropProp(pointer)
	for prop = 1:1:NNVariationalAutoencoderEvaluator.getPropNumber()
		assert(NNVariationalAutoencoderEvaluator.getPropProp(prop) == prop, ...
			[BRAPH2.STR ':NNVariationalAutoencoderEvaluator:' BRAPH2.FAIL_TEST], ...
			'NNVariationalAutoencoderEvaluator.getPropProp(prop) does not work.')
		assert(nne.getPropProp(prop) == prop, ...
			[BRAPH2.STR ':NNVariationalAutoencoderEvaluator:' BRAPH2.FAIL_TEST], ...
			'nne.getPropProp(prop) does not work.')
		assert(Element.getPropProp(nne, prop) == prop, ...
			[BRAPH2.STR ':NNVariationalAutoencoderEvaluator:' BRAPH2.FAIL_TEST], ...
			'Element.getPropProp(nne, prop) does not work.')
		assert(Element.getPropProp('NNVariationalAutoencoderEvaluator', prop) == prop, ...
			[BRAPH2.STR ':NNVariationalAutoencoderEvaluator:' BRAPH2.FAIL_TEST], ...
			'Element.getPropProp(''NNVariationalAutoencoderEvaluator'', prop) does not work.')
	 
		tag = nne.getPropTag(prop);
		assert(NNVariationalAutoencoderEvaluator.getPropProp(tag) == prop, ...
			[BRAPH2.STR ':NNVariationalAutoencoderEvaluator:' BRAPH2.FAIL_TEST], ...
			'NNVariationalAutoencoderEvaluator.getPropProp(tag) does not work.')
		assert(nne.getPropProp(tag) == prop, ...
			[BRAPH2.STR ':NNVariationalAutoencoderEvaluator:' BRAPH2.FAIL_TEST], ...
			'nne.getPropProp(tag) does not work.')
		assert(Element.getPropProp(nne, tag) == prop, ...
			[BRAPH2.STR ':NNVariationalAutoencoderEvaluator:' BRAPH2.FAIL_TEST], ...
			'Element.getPropProp(nne, tag) does not work.')
		assert(Element.getPropProp('NNVariationalAutoencoderEvaluator', prop) == prop, ...
			[BRAPH2.STR ':NNVariationalAutoencoderEvaluator:' BRAPH2.FAIL_TEST], ...
			'Element.getPropProp(''NNVariationalAutoencoderEvaluator'', tag) does not work.')
	end
	 
	% getPropTag(pointer)
	for prop = 1:1:NNVariationalAutoencoderEvaluator.getPropNumber()
		tag = nne.getPropTag(prop);
	 
		assert(strcmp(NNVariationalAutoencoderEvaluator.getPropTag(prop), tag), ...
			[BRAPH2.STR ':NNVariationalAutoencoderEvaluator:' BRAPH2.FAIL_TEST], ...
			'NNVariationalAutoencoderEvaluator.getPropTag(prop) does not work.')
		assert(strcmp(nne.getPropTag(prop), tag), ...
			[BRAPH2.STR ':NNVariationalAutoencoderEvaluator:' BRAPH2.FAIL_TEST], ...
			'nne.getPropTag(prop) does not work.')
		assert(strcmp(Element.getPropTag(nne, prop), tag), ...
			[BRAPH2.STR ':NNVariationalAutoencoderEvaluator:' BRAPH2.FAIL_TEST], ...
			'Element.getPropTag(nne, prop) does not work.')
		assert(strcmp(Element.getPropTag('NNVariationalAutoencoderEvaluator', prop), tag), ...
			[BRAPH2.STR ':NNVariationalAutoencoderEvaluator:' BRAPH2.FAIL_TEST], ...
			'Element.getPropTag(''NNVariationalAutoencoderEvaluator'', prop) does not work.')
	 
		assert(strcmp(NNVariationalAutoencoderEvaluator.getPropTag(tag), tag), ...
			[BRAPH2.STR ':NNVariationalAutoencoderEvaluator:' BRAPH2.FAIL_TEST], ...
			'NNVariationalAutoencoderEvaluator.getPropTag(tag) does not work.')
		assert(strcmp(nne.getPropTag(tag), tag), ...
			[BRAPH2.STR ':NNVariationalAutoencoderEvaluator:' BRAPH2.FAIL_TEST], ...
			'nne.getPropTag(tag) does not work.')
		assert(strcmp(Element.getPropTag(nne, tag), tag), ...
			[BRAPH2.STR ':NNVariationalAutoencoderEvaluator:' BRAPH2.FAIL_TEST], ...
			'Element.getPropTag(nne, tag) does not work.')
		assert(strcmp(Element.getPropTag('NNVariationalAutoencoderEvaluator', prop), tag), ...
			[BRAPH2.STR ':NNVariationalAutoencoderEvaluator:' BRAPH2.FAIL_TEST], ...
			'Element.getPropTag(''NNVariationalAutoencoderEvaluator'', tag) does not work.')
	end
	 
	% getPropCategory(pointer)
	for prop = 1:1:NNVariationalAutoencoderEvaluator.getPropNumber()
		tag = nne.getPropTag(prop);
	 
		assert(Category.existsCategory(NNVariationalAutoencoderEvaluator.getPropCategory(prop)), ...
			[BRAPH2.STR ':NNVariationalAutoencoderEvaluator:' BRAPH2.FAIL_TEST], ...
			'NNVariationalAutoencoderEvaluator.getPropCategory(prop) does not work.')
		assert(Category.existsCategory(nne.getPropCategory(prop)), ...
			[BRAPH2.STR ':NNVariationalAutoencoderEvaluator:' BRAPH2.FAIL_TEST], ...
			'nne.getPropCategory(prop) does not work.')
		assert(Category.existsCategory(Element.getPropCategory(nne, prop)), ...
			[BRAPH2.STR ':NNVariationalAutoencoderEvaluator:' BRAPH2.FAIL_TEST], ...
			'Element.getPropCategory(nne, prop) does not work.')
		assert(Category.existsCategory(Element.getPropCategory(nne, prop)), ...
			[BRAPH2.STR ':NNVariationalAutoencoderEvaluator:' BRAPH2.FAIL_TEST], ...
			'Element.getPropCategory(''NNVariationalAutoencoderEvaluator'', prop) does not work.')
	 
		assert(Category.existsCategory(NNVariationalAutoencoderEvaluator.getPropCategory(tag)), ...
			[BRAPH2.STR ':NNVariationalAutoencoderEvaluator:' BRAPH2.FAIL_TEST], ...
			'NNVariationalAutoencoderEvaluator.getPropCategory(tag) does not work.')
		assert(Category.existsCategory(nne.getPropCategory(tag)), ...
			[BRAPH2.STR ':NNVariationalAutoencoderEvaluator:' BRAPH2.FAIL_TEST], ...
			'nne.getPropCategory(tag) does not work.')
		assert(Category.existsCategory(Element.getPropCategory(nne, tag)), ...
			[BRAPH2.STR ':NNVariationalAutoencoderEvaluator:' BRAPH2.FAIL_TEST], ...
			'Element.getPropCategory(nne, tag) does not work.')
		assert(Category.existsCategory(Element.getPropCategory(nne, tag)), ...
			[BRAPH2.STR ':NNVariationalAutoencoderEvaluator:' BRAPH2.FAIL_TEST], ...
			'Element.getPropCategory(''NNVariationalAutoencoderEvaluator'', tag) does not work.')
	end
	 
	% getPropFormat(pointer)
	for prop = 1:1:NNVariationalAutoencoderEvaluator.getPropNumber()
		tag = nne.getPropTag(prop);
	 
		assert(Format.existsFormat(NNVariationalAutoencoderEvaluator.getPropFormat(prop)), ...
			[BRAPH2.STR ':NNVariationalAutoencoderEvaluator:' BRAPH2.FAIL_TEST], ...
			'NNVariationalAutoencoderEvaluator.getPropFormat(prop) does not work.')
		assert(Format.existsFormat(nne.getPropFormat(prop)), ...
			[BRAPH2.STR ':NNVariationalAutoencoderEvaluator:' BRAPH2.FAIL_TEST], ...
			'nne.getPropFormat(prop) does not work.')
		assert(Format.existsFormat(Element.getPropFormat(nne, prop)), ...
			[BRAPH2.STR ':NNVariationalAutoencoderEvaluator:' BRAPH2.FAIL_TEST], ...
			'Element.getPropFormat(nne, prop) does not work.')
		assert(Format.existsFormat(Element.getPropFormat(nne, prop)), ...
			[BRAPH2.STR ':NNVariationalAutoencoderEvaluator:' BRAPH2.FAIL_TEST], ...
			'Element.getPropFormat(''NNVariationalAutoencoderEvaluator'', prop) does not work.')
	 
		assert(Format.existsFormat(NNVariationalAutoencoderEvaluator.getPropFormat(tag)), ...
			[BRAPH2.STR ':NNVariationalAutoencoderEvaluator:' BRAPH2.FAIL_TEST], ...
			'NNVariationalAutoencoderEvaluator.getPropFormat(tag) does not work.')
		assert(Format.existsFormat(nne.getPropFormat(tag)), ...
			[BRAPH2.STR ':NNVariationalAutoencoderEvaluator:' BRAPH2.FAIL_TEST], ...
			'nne.getPropFormat(tag) does not work.')
		assert(Format.existsFormat(Element.getPropFormat(nne, tag)), ...
			[BRAPH2.STR ':NNVariationalAutoencoderEvaluator:' BRAPH2.FAIL_TEST], ...
			'Element.getPropFormat(nne, tag) does not work.')
		assert(Format.existsFormat(Element.getPropFormat(nne, tag)), ...
			[BRAPH2.STR ':NNVariationalAutoencoderEvaluator:' BRAPH2.FAIL_TEST], ...
			'Element.getPropFormat(''NNVariationalAutoencoderEvaluator'', tag) does not work.')
	end
	 
	% getPropDescription(pointer)
	for prop = 1:1:NNVariationalAutoencoderEvaluator.getPropNumber()
		tag = nne.getPropTag(prop);
	 
		assert(ischar(NNVariationalAutoencoderEvaluator.getPropDescription(prop)), ...
			[BRAPH2.STR ':NNVariationalAutoencoderEvaluator:' BRAPH2.FAIL_TEST], ...
			'NNVariationalAutoencoderEvaluator.getPropDescription(prop) does not work.')
		assert(ischar(nne.getPropDescription(prop)), ...
			[BRAPH2.STR ':NNVariationalAutoencoderEvaluator:' BRAPH2.FAIL_TEST], ...
			'nne.getPropDescription(prop) does not work.')
		assert(ischar(Element.getPropDescription(nne, prop)), ...
			[BRAPH2.STR ':NNVariationalAutoencoderEvaluator:' BRAPH2.FAIL_TEST], ...
			'Element.getPropDescription(nne, prop) does not work.')
		assert(ischar(Element.getPropDescription(nne, prop)), ...
			[BRAPH2.STR ':NNVariationalAutoencoderEvaluator:' BRAPH2.FAIL_TEST], ...
			'Element.getPropDescription(''NNVariationalAutoencoderEvaluator'', prop) does not work.')
	 
		assert(ischar(NNVariationalAutoencoderEvaluator.getPropDescription(tag)), ...
			[BRAPH2.STR ':NNVariationalAutoencoderEvaluator:' BRAPH2.FAIL_TEST], ...
			'NNVariationalAutoencoderEvaluator.getPropDescription(tag) does not work.')
		assert(ischar(nne.getPropDescription(tag)), ...
			[BRAPH2.STR ':NNVariationalAutoencoderEvaluator:' BRAPH2.FAIL_TEST], ...
			'nne.getPropDescription(tag) does not work.')
		assert(ischar(Element.getPropDescription(nne, tag)), ...
			[BRAPH2.STR ':NNVariationalAutoencoderEvaluator:' BRAPH2.FAIL_TEST], ...
			'Element.getPropDescription(nne, tag) does not work.')
		assert(ischar(Element.getPropDescription(nne, tag)), ...
			[BRAPH2.STR ':NNVariationalAutoencoderEvaluator:' BRAPH2.FAIL_TEST], ...
			'Element.getPropDescription(''NNVariationalAutoencoderEvaluator'', tag) does not work.')
	end
	 
	% getPropSettings(pointer)
	for prop = 1:1:NNVariationalAutoencoderEvaluator.getPropNumber()
		tag = nne.getPropTag(prop);
	 
		settings = NNVariationalAutoencoderEvaluator.getPropSettings(prop);
		settings = nne.getPropSettings(prop);
		settings = Element.getPropSettings(nne, prop);
		settings = Element.getPropSettings('NNVariationalAutoencoderEvaluator', prop);
	 
		settings = NNVariationalAutoencoderEvaluator.getPropSettings(tag);
		settings = nne.getPropSettings(tag);
		settings = Element.getPropSettings(nne, tag);
		settings = Element.getPropSettings('NNVariationalAutoencoderEvaluator', tag);
	end
	 
	% getPropDefault(pointer)
	for prop = 1:1:NNVariationalAutoencoderEvaluator.getPropNumber()
		tag = nne.getPropTag(prop);
	 
		default = NNVariationalAutoencoderEvaluator.getPropDefault(prop);
		default = nne.getPropDefault(prop);
		default = Element.getPropDefault(nne, prop);
		default = Element.getPropDefault('NNVariationalAutoencoderEvaluator', prop);
	 
		default = NNVariationalAutoencoderEvaluator.getPropDefault(tag);
		default = nne.getPropDefault(tag);
		default = Element.getPropDefault(nne, tag);
		default = Element.getPropDefault('NNVariationalAutoencoderEvaluator', tag);
	end
	 
	% getPropDefaultConditioned(pointer)
	for prop = 1:1:NNVariationalAutoencoderEvaluator.getPropNumber()
		tag = nne.getPropTag(prop);
	 
		conditioned_default = NNVariationalAutoencoderEvaluator.getPropDefaultConditioned(prop);
		conditioned_default = nne.getPropDefaultConditioned(prop);
		conditioned_default = Element.getPropDefaultConditioned(nne, prop);
		conditioned_default = Element.getPropDefaultConditioned('NNVariationalAutoencoderEvaluator', prop);
	 
		conditioned_default = NNVariationalAutoencoderEvaluator.getPropDefaultConditioned(tag);
		conditioned_default = nne.getPropDefaultConditioned(tag);
		conditioned_default = Element.getPropDefaultConditioned(nne, tag);
		conditioned_default = Element.getPropDefaultConditioned('NNVariationalAutoencoderEvaluator', tag);
	end
	 
	% checkProp(pointer, value)
	for prop = 1:1:NNVariationalAutoencoderEvaluator.getPropNumber()
		tag = nne.getPropTag(prop);
	 
		assert(~NNVariationalAutoencoderEvaluator.checkProp(prop, {'probably wrong value', 1}), ...
			[BRAPH2.STR ':NNVariationalAutoencoderEvaluator:' BRAPH2.FAIL_TEST], ...
			'NNVariationalAutoencoderEvaluator.checkProp(prop, value) does not work.')
		assert(~nne.checkProp(prop, {'probably wrong value', 1}), ...
			[BRAPH2.STR ':NNVariationalAutoencoderEvaluator:' BRAPH2.FAIL_TEST], ...
			'nne.checkProp(prop, value) does not work.')
		assert(~Element.checkProp(nne, prop, {'probably wrong value', 1}), ...
			[BRAPH2.STR ':NNVariationalAutoencoderEvaluator:' BRAPH2.FAIL_TEST], ...
			'Element.checkProp(nne, prop, value) does not work.')
		assert(~Element.checkProp('NNVariationalAutoencoderEvaluator', prop, {'probably wrong value', 1}), ...
			[BRAPH2.STR ':NNVariationalAutoencoderEvaluator:' BRAPH2.FAIL_TEST], ...
			'Element.checkProp(''NNVariationalAutoencoderEvaluator'', prop, value) does not work.')
	 
		assert_with_error('NNVariationalAutoencoderEvaluator.checkProp(varargin{1}, {''probably wrong value'', 1})', [BRAPH2.STR ':NNVariationalAutoencoderEvaluator:' BRAPH2.WRONG_INPUT], prop)
		assert_with_error('varargin{2}.checkProp(varargin{1}, {''probably wrong value'', 1})', [BRAPH2.STR ':NNVariationalAutoencoderEvaluator:' BRAPH2.WRONG_INPUT], prop, nne)
		assert_with_error('Element.checkProp(varargin{2}, varargin{1}, {''probably wrong value'', 1})', [BRAPH2.STR ':NNVariationalAutoencoderEvaluator:' BRAPH2.WRONG_INPUT], prop, nne)
		assert_with_error('Element.checkProp(''NNVariationalAutoencoderEvaluator'', varargin{1}, {''probably wrong value'', 1})', [BRAPH2.STR ':NNVariationalAutoencoderEvaluator:' BRAPH2.WRONG_INPUT], prop)
	 
		assert(~NNVariationalAutoencoderEvaluator.checkProp(tag, {'probably wrong value', 1}), ...
			[BRAPH2.STR ':NNVariationalAutoencoderEvaluator:' BRAPH2.FAIL_TEST], ...
			'NNVariationalAutoencoderEvaluator.checkProp(tag, value) does not work.')
		assert(~nne.checkProp(tag, {'probably wrong value', 1}), ...
			[BRAPH2.STR ':NNVariationalAutoencoderEvaluator:' BRAPH2.FAIL_TEST], ...
			'nne.checkProp(tag, value) does not work.')
		assert(~Element.checkProp(nne, tag, {'probably wrong value', 1}), ...
			[BRAPH2.STR ':NNVariationalAutoencoderEvaluator:' BRAPH2.FAIL_TEST], ...
			'Element.checkProp(nne, tag, value) does not work.')
		assert(~Element.checkProp('NNVariationalAutoencoderEvaluator', tag, {'probably wrong value', 1}), ...
			[BRAPH2.STR ':NNVariationalAutoencoderEvaluator:' BRAPH2.FAIL_TEST], ...
			'Element.checkProp(''NNVariationalAutoencoderEvaluator'', tag, value) does not work.')
	 
		assert_with_error('NNVariationalAutoencoderEvaluator.checkProp(varargin{1}, {''probably wrong value'', 1})', [BRAPH2.STR ':NNVariationalAutoencoderEvaluator:' BRAPH2.WRONG_INPUT], tag)
		assert_with_error('varargin{2}.checkProp(varargin{1}, {''probably wrong value'', 1})', [BRAPH2.STR ':NNVariationalAutoencoderEvaluator:' BRAPH2.WRONG_INPUT], tag, nne)
		assert_with_error('Element.checkProp(varargin{2}, varargin{1}, {''probably wrong value'', 1})', [BRAPH2.STR ':NNVariationalAutoencoderEvaluator:' BRAPH2.WRONG_INPUT], tag, nne)
		assert_with_error('Element.checkProp(''NNVariationalAutoencoderEvaluator'', varargin{1}, {''probably wrong value'', 1})', [BRAPH2.STR ':NNVariationalAutoencoderEvaluator:' BRAPH2.WRONG_INPUT], tag)
	 
		assert(NNVariationalAutoencoderEvaluator.checkProp(prop, Element.getPropDefaultConditioned(NNVariationalAutoencoderEvaluator, prop)), ...
			[BRAPH2.STR ':NNVariationalAutoencoderEvaluator:' BRAPH2.FAIL_TEST], ...
			'NNVariationalAutoencoderEvaluator.checkProp(prop, <conditioned default value>) does not work.')
		assert(nne.checkProp(prop, Element.getPropDefaultConditioned(NNVariationalAutoencoderEvaluator, prop)), ...
			[BRAPH2.STR ':NNVariationalAutoencoderEvaluator:' BRAPH2.FAIL_TEST], ...
			'nne.checkProp(prop, <conditioned default value>) does not work.')
		assert(Element.checkProp(nne, prop, Element.getPropDefaultConditioned(NNVariationalAutoencoderEvaluator, prop)), ...
			[BRAPH2.STR ':NNVariationalAutoencoderEvaluator:' BRAPH2.FAIL_TEST], ...
			'Element.checkProp(nne, prop, <conditioned default value>) does not work.')
		assert(Element.checkProp('NNVariationalAutoencoderEvaluator', prop, Element.getPropDefaultConditioned(NNVariationalAutoencoderEvaluator, prop)), ...
			[BRAPH2.STR ':NNVariationalAutoencoderEvaluator:' BRAPH2.FAIL_TEST], ...
			'Element.checkProp(''NNVariationalAutoencoderEvaluator'', prop, <conditioned default value>) does not work.')
	 
		assert(NNVariationalAutoencoderEvaluator.checkProp(tag, Element.getPropDefaultConditioned(NNVariationalAutoencoderEvaluator, prop)), ...
			[BRAPH2.STR ':NNVariationalAutoencoderEvaluator:' BRAPH2.FAIL_TEST], ...
			'NNVariationalAutoencoderEvaluator.checkProp(tag, <conditioned default value>) does not work.')
		assert(nne.checkProp(tag, Element.getPropDefaultConditioned(NNVariationalAutoencoderEvaluator, prop)), ...
			[BRAPH2.STR ':NNVariationalAutoencoderEvaluator:' BRAPH2.FAIL_TEST], ...
			'nne.checkProp(tag, <conditioned default value>) does not work.')
		assert(Element.checkProp(nne, tag, Element.getPropDefaultConditioned(NNVariationalAutoencoderEvaluator, prop)), ...
			[BRAPH2.STR ':NNVariationalAutoencoderEvaluator:' BRAPH2.FAIL_TEST], ...
			'Element.checkProp(nne, tag, <conditioned default value>) does not work.')
		assert(Element.checkProp('NNVariationalAutoencoderEvaluator', tag, Element.getPropDefaultConditioned(NNVariationalAutoencoderEvaluator, prop)), ...
			[BRAPH2.STR ':NNVariationalAutoencoderEvaluator:' BRAPH2.FAIL_TEST], ...
			'Element.checkProp(''NNVariationalAutoencoderEvaluator'', tag, <conditioned default value>) does not work.')
	 
	end
	 
end

%% Test 2: Instantiation - defaults
if rand() >= (1 - .01) * BRAPH2TEST.RANDOM
	nne = NNVariationalAutoencoderEvaluator( ...
		NNVariationalAutoencoderEvaluator.ELCLASS, NNVariationalAutoencoderEvaluator.getNoValue(), ...
		NNVariationalAutoencoderEvaluator.NAME, NNVariationalAutoencoderEvaluator.getNoValue(), ...
		NNVariationalAutoencoderEvaluator.DESCRIPTION, NNVariationalAutoencoderEvaluator.getNoValue(), ...
		NNVariationalAutoencoderEvaluator.TEMPLATE, NNVariationalAutoencoderEvaluator.getPropDefault(NNVariationalAutoencoderEvaluator.TEMPLATE), ...
		NNVariationalAutoencoderEvaluator.ID, NNVariationalAutoencoderEvaluator.getPropDefault(NNVariationalAutoencoderEvaluator.ID), ...
		NNVariationalAutoencoderEvaluator.LABEL, NNVariationalAutoencoderEvaluator.getPropDefault(NNVariationalAutoencoderEvaluator.LABEL), ...
		NNVariationalAutoencoderEvaluator.NOTES, NNVariationalAutoencoderEvaluator.getPropDefault(NNVariationalAutoencoderEvaluator.NOTES), ...
		NNVariationalAutoencoderEvaluator.TOSTRING, NNVariationalAutoencoderEvaluator.getNoValue(), ...
		NNVariationalAutoencoderEvaluator.NN, NNVariationalAutoencoderEvaluator.getPropDefault(NNVariationalAutoencoderEvaluator.NN), ...
		NNVariationalAutoencoderEvaluator.D, NNVariationalAutoencoderEvaluator.getPropDefault(NNVariationalAutoencoderEvaluator.D), ...
		NNVariationalAutoencoderEvaluator.PLOT_LATENT_REPRESENTATIONS, NNVariationalAutoencoderEvaluator.getNoValue(), ...
		NNVariationalAutoencoderEvaluator.PREDICT_ENCODER, NNVariationalAutoencoderEvaluator.getNoValue() ...
		);
	 
	for prop = 1:1:NNVariationalAutoencoderEvaluator.getPropNumber()
	 
		% excluded props
		if any(prop == [NNVariationalAutoencoderEvaluator.PLOT_LATENT_REPRESENTATIONS NNVariationalAutoencoderEvaluator.PREDICT_ENCODER])
			continue
		end
	 
		TAG = upper(NNVariationalAutoencoderEvaluator.getPropTag(prop));
		switch NNVariationalAutoencoderEvaluator.getPropCategory(prop)
			case {Category.CONSTANT, Category.RESULT, Category.QUERY}
				% getr
				assert( ...
					nne.getr(prop) == NNVariationalAutoencoderEvaluator.getNoValue(), ...
					[BRAPH2.STR ':NNVariationalAutoencoderEvaluator:' BRAPH2.FAIL_TEST], ...
					['Being a ' NNVariationalAutoencoderEvaluator.getCategoryName(NNVariationalAutoencoderEvaluator.getPropCategory(prop)) ', NNVariationalAutoencoderEvaluator.getr(' int2str(prop) ') must be inizialized to NoValue(). ' ...
					'Or there could be an error in NNVariationalAutoencoderEvaluator.getr(' int2str(prop) ').'] ...
					)
				assert( ...
					nne.getr(TAG) == NNVariationalAutoencoderEvaluator.getNoValue(), ...
					[BRAPH2.STR ':NNVariationalAutoencoderEvaluator:' BRAPH2.FAIL_TEST], ...
					['Being a ' NNVariationalAutoencoderEvaluator.getCategoryName(NNVariationalAutoencoderEvaluator.getPropCategory(prop)) ', NNVariationalAutoencoderEvaluator.getr(' TAG ') must be inizialized to NoValue(). ' ...
					'Or there could be an error in NNVariationalAutoencoderEvaluator.getr(' TAG ').'] ...
					)
				% get
				assert( ...
					~isa(nne.get(prop), 'NoValue'), ...
					[BRAPH2.STR ':NNVariationalAutoencoderEvaluator:' BRAPH2.FAIL_TEST], ...
					['NNVariationalAutoencoderEvaluator.get(' int2str(prop) ') must NOT be a NoValue, because it should have been calculated.'] ...
					)
				if isempty(nne.getPropSettings(prop))
					assert( ...
						nne.checkFormat(nne.getPropFormat(prop), nne.get(prop)), ...
						[BRAPH2.STR ':NNVariationalAutoencoderEvaluator:' BRAPH2.FAIL_TEST], ...
						['NNVariationalAutoencoderEvaluator.get(' int2str(prop) ') returns a value with the wrong format.'] ...
						)
				else
					assert( ...
						nne.checkFormat(nne.getPropFormat(prop), nne.get(prop), nne.getPropSettings(prop)), ...
						[BRAPH2.STR ':NNVariationalAutoencoderEvaluator:' BRAPH2.FAIL_TEST], ...
						['NNVariationalAutoencoderEvaluator.get(' int2str(prop) ') returns a value with the wrong format.'] ...
						)
				end
			case Category.EVANESCENT
				% getr
				assert( ...
					nne.getr(prop) == NNVariationalAutoencoderEvaluator.getNoValue(), ...
					[BRAPH2.STR ':NNVariationalAutoencoderEvaluator:' BRAPH2.FAIL_TEST], ...
					['Being a ' NNVariationalAutoencoderEvaluator.getCategoryName(NNVariationalAutoencoderEvaluator.getPropCategory(prop)) ', NNVariationalAutoencoderEvaluator.getr(' int2str(prop) ') must be inizialized to NoValue(). ' ...
					'Or there could be an error in NNVariationalAutoencoderEvaluator.getr(' int2str(prop) ').'] ...
					)
				assert( ...
					nne.getr(TAG) == NNVariationalAutoencoderEvaluator.getNoValue(), ...
					[BRAPH2.STR ':NNVariationalAutoencoderEvaluator:' BRAPH2.FAIL_TEST], ...
					['Being a ' NNVariationalAutoencoderEvaluator.getCategoryName(NNVariationalAutoencoderEvaluator.getPropCategory(prop)) ', NNVariationalAutoencoderEvaluator.getr(' TAG ') must be inizialized to NoValue(). ' ...
					'Or there could be an error in NNVariationalAutoencoderEvaluator.getr(' TAG ').'] ...
					)
				% get
				warning_backup = warning('off', [BRAPH2.STR ':NNVariationalAutoencoderEvaluator']);
				assert( ...
					~isa(nne.get(prop), 'NoValue'), ...
					[BRAPH2.STR ':NNVariationalAutoencoderEvaluator:' BRAPH2.FAIL_TEST], ...
					['NNVariationalAutoencoderEvaluator.get(' int2str(prop) ') must NOT be a NoValue, because it should have been calculated.'] ...
					)
				if isempty(nne.getPropSettings(prop))
					assert( ...
						nne.checkFormat(nne.getPropFormat(prop), nne.get(prop)), ...
						[BRAPH2.STR ':NNVariationalAutoencoderEvaluator:' BRAPH2.FAIL_TEST], ...
						['NNVariationalAutoencoderEvaluator.get(' int2str(prop) ') returns a value with the wrong format.'] ...
						)
				else
					assert( ...
						nne.checkFormat(nne.getPropFormat(prop), nne.get(prop), nne.getPropSettings(prop)), ...
						[BRAPH2.STR ':NNVariationalAutoencoderEvaluator:' BRAPH2.FAIL_TEST], ...
						['NNVariationalAutoencoderEvaluator.get(' int2str(prop) ') returns a value with the wrong format.'] ...
						)
				end
				warning(warning_backup)
			otherwise % case {Category.METADATA, Category.PARAMETER, Category.DATA, Category.FIGURE, Category.GUI}
				assert( ...
					isequal(nne.getr(prop), NNVariationalAutoencoderEvaluator.getPropDefaultConditioned(prop)), ...
					[BRAPH2.STR ':NNVariationalAutoencoderEvaluator:' BRAPH2.FAIL_TEST], ...
					['NNVariationalAutoencoderEvaluator.getr(' int2str(prop) ') must be inizialized to its default value ' ...
					'given by NNVariationalAutoencoderEvaluator.getPropDefaultConditioned(' int2str(prop) '). ' ...
					'Or there could be an error in NNVariationalAutoencoderEvaluator.getr(' int2str(prop) ').'] ...
					)
				assert( ...
					isequal(nne.getr(TAG), NNVariationalAutoencoderEvaluator.getPropDefaultConditioned(prop)), ...
					[BRAPH2.STR ':NNVariationalAutoencoderEvaluator:' BRAPH2.FAIL_TEST], ...
					['NNVariationalAutoencoderEvaluator.getr(' TAG ') must be inizialized to its default value ' ...
					'given by NNVariationalAutoencoderEvaluator.getPropDefaultConditioned(' int2str(prop) '). ' ...
					'Or there could be an error in NNVariationalAutoencoderEvaluator.getr(' TAG ').'] ...
					)
		end
	end
end

%% Test 3: Memorize
if rand() >= (1 - .01) * BRAPH2TEST.RANDOM
	nne = NNVariationalAutoencoderEvaluator( ...
		NNVariationalAutoencoderEvaluator.ELCLASS, NNVariationalAutoencoderEvaluator.getNoValue(), ...
		NNVariationalAutoencoderEvaluator.NAME, NNVariationalAutoencoderEvaluator.getNoValue(), ...
		NNVariationalAutoencoderEvaluator.DESCRIPTION, NNVariationalAutoencoderEvaluator.getNoValue(), ...
		NNVariationalAutoencoderEvaluator.TEMPLATE, NNVariationalAutoencoderEvaluator.getPropDefault(NNVariationalAutoencoderEvaluator.TEMPLATE), ...
		NNVariationalAutoencoderEvaluator.ID, NNVariationalAutoencoderEvaluator.getPropDefault(NNVariationalAutoencoderEvaluator.ID), ...
		NNVariationalAutoencoderEvaluator.LABEL, NNVariationalAutoencoderEvaluator.getPropDefault(NNVariationalAutoencoderEvaluator.LABEL), ...
		NNVariationalAutoencoderEvaluator.NOTES, NNVariationalAutoencoderEvaluator.getPropDefault(NNVariationalAutoencoderEvaluator.NOTES), ...
		NNVariationalAutoencoderEvaluator.TOSTRING, NNVariationalAutoencoderEvaluator.getNoValue(), ...
		NNVariationalAutoencoderEvaluator.NN, NNVariationalAutoencoderEvaluator.getPropDefault(NNVariationalAutoencoderEvaluator.NN), ...
		NNVariationalAutoencoderEvaluator.D, NNVariationalAutoencoderEvaluator.getPropDefault(NNVariationalAutoencoderEvaluator.D), ...
		NNVariationalAutoencoderEvaluator.PLOT_LATENT_REPRESENTATIONS, NNVariationalAutoencoderEvaluator.getNoValue(), ...
		NNVariationalAutoencoderEvaluator.PREDICT_ENCODER, NNVariationalAutoencoderEvaluator.getNoValue() ...
		);
	 
	for prop = 1:1:NNVariationalAutoencoderEvaluator.getPropNumber()
	 
		% excluded props
		if any(prop == [NNVariationalAutoencoderEvaluator.PLOT_LATENT_REPRESENTATIONS NNVariationalAutoencoderEvaluator.PREDICT_ENCODER])
			continue
		end
	 
		TAG = upper(NNVariationalAutoencoderEvaluator.getPropTag(prop));
		switch NNVariationalAutoencoderEvaluator.getPropCategory(prop)
			case Category.RESULT
				assert( ...
					~isa(nne.get(prop), 'NoValue'), ...
					[BRAPH2.STR ':NNVariationalAutoencoderEvaluator:' BRAPH2.FAIL_TEST], ...
					['NNVariationalAutoencoderEvaluator.get(' int2str(prop) ') must NOT be a NoValue, because it should have been calculated.'] ...
					)
				assert( ...
					isa(nne.getr(prop), 'NoValue'), ...
					[BRAPH2.STR ':NNVariationalAutoencoderEvaluator:' BRAPH2.FAIL_TEST], ...
					['NNVariationalAutoencoderEvaluator.getr(' int2str(prop) ') must be a NoValue, because it should NOT have been memorized.'] ...
					)
				assert( ...
					~isa(nne.memorize(prop), 'NoValue'), ...
					[BRAPH2.STR ':NNVariationalAutoencoderEvaluator:' BRAPH2.FAIL_TEST], ...
					['NNVariationalAutoencoderEvaluator.memorize(' int2str(prop) ') must NOT be a NoValue, because it should have been calculated.'] ...
					)
				assert( ...
					~isa(nne.getr(prop), 'NoValue'), ...
					[BRAPH2.STR ':NNVariationalAutoencoderEvaluator:' BRAPH2.FAIL_TEST], ...
					['NNVariationalAutoencoderEvaluator.getr(' int2str(prop) ') must NOT be a NoValue, because it should have been memorized.'] ...
					)
				assert( ...
					nne.checkFormat(nne.getPropFormat(prop), nne.getr(prop),nne.getPropSettings(prop)), ...
					[BRAPH2.STR ':NNVariationalAutoencoderEvaluator:' BRAPH2.FAIL_TEST], ...
					['NNVariationalAutoencoderEvaluator.getr(' int2str(prop) ') returns a value with the wrong format.'] ...
					)
			case Category.QUERY
	% 			warning_backup = warning('off', [BRAPH2.STR ':NNVariationalAutoencoderEvaluator']);
				assert( ...
					~isa(nne.get(prop), 'NoValue'), ...
					[BRAPH2.STR ':NNVariationalAutoencoderEvaluator:' BRAPH2.FAIL_TEST], ...
					['NNVariationalAutoencoderEvaluator.get(' int2str(prop) ') must NOT be a NoValue, because it should have been calculated.'] ...
					)
				assert( ...
					isa(nne.getr(prop), 'NoValue'), ...
					[BRAPH2.STR ':NNVariationalAutoencoderEvaluator:' BRAPH2.FAIL_TEST], ...
					['NNVariationalAutoencoderEvaluator.getr(' int2str(prop) ') must be a NoValue, because it should NOT have been memorized.'] ...
					)
	% following tests excluded because properties QUERY should not be memorized
	% 			warning_backup = warning('off', [BRAPH2.STR ':NNVariationalAutoencoderEvaluator']);
	% 			assert( ...
	% 				~isa(nne.memorize(prop), 'NoValue'), ...
	% 				[BRAPH2.STR ':NNVariationalAutoencoderEvaluator:' BRAPH2.FAIL_TEST], ...
	% 				['NNVariationalAutoencoderEvaluator.memorize(' int2str(prop) ') must NOT be a NoValue, because it should have been calculated.'] ...
	% 				)
	% 			warning(warning_backup)
	% 			assert( ...
	% 				~isa(nne.getr(prop), 'NoValue'), ...
	% 				[BRAPH2.STR ':NNVariationalAutoencoderEvaluator:' BRAPH2.FAIL_TEST], ...
	% 				['NNVariationalAutoencoderEvaluator.getr(' int2str(prop) ') must NOT be a NoValue, because it should have been memorized.'] ...
	% 				)
	% 			assert( ...
	% 				nne.checkFormat(nne.getPropFormat(prop), nne.getr(prop),nne.getPropSettings(prop)), ...
	% 				[BRAPH2.STR ':NNVariationalAutoencoderEvaluator:' BRAPH2.FAIL_TEST], ...
	% 				['NNVariationalAutoencoderEvaluator.getr(' int2str(prop) ') returns a value with the wrong format.'] ...
	% 				)
	% 			warning(warning_backup)
			case Category.EVANESCENT
				warning_backup = warning('off', [BRAPH2.STR ':NNVariationalAutoencoderEvaluator']);
				assert( ...
					~isa(nne.get(prop), 'NoValue'), ...
					[BRAPH2.STR ':NNVariationalAutoencoderEvaluator:' BRAPH2.FAIL_TEST], ...
					['NNVariationalAutoencoderEvaluator.get(' int2str(prop) ') must NOT be a NoValue, because it should have been calculated.'] ...
					)
				warning(warning_backup)
				assert( ...
					isa(nne.getr(prop), 'NoValue'), ...
					[BRAPH2.STR ':NNVariationalAutoencoderEvaluator:' BRAPH2.FAIL_TEST], ...
					['NNVariationalAutoencoderEvaluator.getr(' int2str(prop) ') must be a NoValue, because it should NOT have been memorized.'] ...
					)
				assert( ...
					~isa(nne.memorize(prop), 'NoValue'), ...
					[BRAPH2.STR ':NNVariationalAutoencoderEvaluator:' BRAPH2.FAIL_TEST], ...
					['NNVariationalAutoencoderEvaluator.memorize(' int2str(prop) ') must NOT be a NoValue, because it should have been calculated.'] ...
					)
				assert( ...
					~isa(nne.getr(prop), 'NoValue'), ...
					[BRAPH2.STR ':NNVariationalAutoencoderEvaluator:' BRAPH2.FAIL_TEST], ...
					['NNVariationalAutoencoderEvaluator.getr(' int2str(prop) ') must NOT be a NoValue, because it should have been memorized.'] ...
					)
				assert( ...
					nne.checkFormat(nne.getPropFormat(prop), nne.getr(prop),nne.getPropSettings(prop)), ...
					[BRAPH2.STR ':NNVariationalAutoencoderEvaluator:' BRAPH2.FAIL_TEST], ...
					['NNVariationalAutoencoderEvaluator.getr(' int2str(prop) ') returns a value with the wrong format.'] ...
					)
				if nne.getPropFormat(prop) == Format.HANDLE
					warning_backup = warning('off', 'BRAPH2:NNVariationalAutoencoderEvaluator');
					delete(ancestor(nne.get(prop), 'figure'))
					warning(warning_backup)
				end
		end
	end
	 
	if ~isempty(NNVariationalAutoencoderEvaluator.getProps(Category.RESULT))
		for prop = 1:1:NNVariationalAutoencoderEvaluator.getPropNumber()
	 
			% excluded props
			if any(prop == [NNVariationalAutoencoderEvaluator.PLOT_LATENT_REPRESENTATIONS NNVariationalAutoencoderEvaluator.PREDICT_ENCODER])
				continue
			end
	 
			switch NNVariationalAutoencoderEvaluator.getPropCategory(prop)
				case {Category.PARAMETER, Category.DATA}
					assert( ...
						nne.isLocked(prop), ...
						[BRAPH2.STR ':NNVariationalAutoencoderEvaluator:' BRAPH2.FAIL_TEST], ...
						['NNVariationalAutoencoderEvaluator.isLocked(' int2str(prop) ') must be locked because a result has been calculated.'] ...
						)
				otherwise
					assert( ...
						~nne.isLocked(prop), ...
						[BRAPH2.STR ':NNVariationalAutoencoderEvaluator:' BRAPH2.FAIL_TEST], ...
						['NNVariationalAutoencoderEvaluator.isLocked(' int2str(prop) ') must NOT be locked even though a result has been calculated.'] ...
						)
			end
		end
	end
end

%% Test 4: Lock 1
if rand() >= (1 - .01) * BRAPH2TEST.RANDOM
	nne = NNVariationalAutoencoderEvaluator();
	 
	for prop = 1:1:NNVariationalAutoencoderEvaluator.getPropNumber()
		TAG = upper(NNVariationalAutoencoderEvaluator.getPropTag(prop));
		assert( ...
			~nne.isLocked(prop), ...
			[BRAPH2.STR ':NNVariationalAutoencoderEvaluator:' BRAPH2.FAIL_TEST], ...
			['NNVariationalAutoencoderEvaluator.isLocked(' int2str(prop) ') must NOT be locked when it is instantiated.'] ...
			)
		assert( ...
			~nne.isLocked(TAG), ...
			[BRAPH2.STR ':NNVariationalAutoencoderEvaluator:' BRAPH2.FAIL_TEST], ...
			['NNVariationalAutoencoderEvaluator.isLocked(' TAG ') must NOT be locked when it is instantiated.'] ...
			)
	end
	 
	nne.lock()
	 
	for prop = 1:1:NNVariationalAutoencoderEvaluator.getPropNumber()
		switch NNVariationalAutoencoderEvaluator.getPropCategory(prop)
			case {Category.PARAMETER, Category.DATA}
				assert( ...
					nne.isLocked(prop), ...
					[BRAPH2.STR ':NNVariationalAutoencoderEvaluator:' BRAPH2.FAIL_TEST], ...
					['NNVariationalAutoencoderEvaluator.isLocked(' int2str(prop) ') must be locked because the element is now locked.'] ...
					)
			case {Category.CONSTANT, Category.METADATA, Category.RESULT, Category.QUERY, Category.EVANESCENT, Category.FIGURE, Category.GUI}
				assert( ...
					~nne.isLocked(prop), ...
					[BRAPH2.STR ':NNVariationalAutoencoderEvaluator:' BRAPH2.FAIL_TEST], ...
					['NNVariationalAutoencoderEvaluator.isLocked(' int2str(prop) ') must NOT be locked even though the element is now locked.'] ...
					)
		end
	end
end

%% Test 5: Lock 2
if rand() >= (1 - .01) * BRAPH2TEST.RANDOM
	nne = NNVariationalAutoencoderEvaluator();
	 
	warning_backup = warning('off', 'BRAPH2:NNVariationalAutoencoderEvaluator');
	for prop = 1:1:NNVariationalAutoencoderEvaluator.getPropNumber()
		nne.lock(prop)
		switch NNVariationalAutoencoderEvaluator.getPropCategory(prop)
			case {Category.PARAMETER, Category.DATA, Category.FIGURE, Category.GUI}
				assert( ...
					nne.isLocked(prop), ...
					[BRAPH2.STR ':NNVariationalAutoencoderEvaluator:' BRAPH2.FAIL_TEST], ...
					['NNVariationalAutoencoderEvaluator.isLocked(' int2str(prop) ') must be locked.'] ...
					)
			case {Category.CONSTANT, Category.METADATA, Category.RESULT, Category.QUERY, Category.EVANESCENT}
				assert( ...
					~nne.isLocked(prop), ...
					[BRAPH2.STR ':NNVariationalAutoencoderEvaluator:' BRAPH2.FAIL_TEST], ...
					['NNVariationalAutoencoderEvaluator.isLocked(' int2str(prop) ') must NOT be locked even though locking has been attempted.'] ...
					)
		end
	end
	warning(warning_backup)
end

%% Test 6: Check
if rand() >= (1 - .01) * BRAPH2TEST.RANDOM
	nne = NNVariationalAutoencoderEvaluator();
	 
	for prop = 1:1:NNVariationalAutoencoderEvaluator.getPropNumber()
		TAG = upper(NNVariationalAutoencoderEvaluator.getPropTag(prop));
		assert( ...
			nne.isChecked(prop), ...
			[BRAPH2.STR ':NNVariationalAutoencoderEvaluator:' BRAPH2.FAIL_TEST], ...
			['NNVariationalAutoencoderEvaluator.isChecked(' int2str(prop) ') must be checked when it is instantiated.'] ...
			)
		assert( ...
			nne.isChecked(TAG), ...
			[BRAPH2.STR ':NNVariationalAutoencoderEvaluator:' BRAPH2.FAIL_TEST], ...
			['NNVariationalAutoencoderEvaluator.isChecked(' TAG ') must be checked when it is instantiated.'] ...
			)
	end
	 
	nne.unchecked()
	 
	for prop = 1:1:NNVariationalAutoencoderEvaluator.getPropNumber()
		assert( ...
			~nne.isChecked(prop), ...
			[BRAPH2.STR ':NNVariationalAutoencoderEvaluator:' BRAPH2.FAIL_TEST], ...
			['NNVariationalAutoencoderEvaluator.isChecked(' int2str(prop) ') must NOT be checked because it has been set to unchecked.'] ...
			)
	end
	 
	nne.checked()
	 
	for prop = 1:1:NNVariationalAutoencoderEvaluator.getPropNumber()
		assert( ...
			nne.isChecked(prop), ...
			[BRAPH2.STR ':NNVariationalAutoencoderEvaluator:' BRAPH2.FAIL_TEST], ...
			['NNVariationalAutoencoderEvaluator.isChecked(' int2str(prop) ') must be checked because it has been set to checked.'] ...
			)
	end
end

%% Test 7: Callbacks
if rand() >= (1 - .01) * BRAPH2TEST.RANDOM
	% basic NNVariationalAutoencoderEvaluator
	nne_0 = NNVariationalAutoencoderEvaluator( ...
		NNVariationalAutoencoderEvaluator.ELCLASS, NNVariationalAutoencoderEvaluator.getNoValue(), ...
		NNVariationalAutoencoderEvaluator.NAME, NNVariationalAutoencoderEvaluator.getNoValue(), ...
		NNVariationalAutoencoderEvaluator.DESCRIPTION, NNVariationalAutoencoderEvaluator.getNoValue(), ...
		NNVariationalAutoencoderEvaluator.TEMPLATE, NNVariationalAutoencoderEvaluator.getPropDefault(NNVariationalAutoencoderEvaluator.TEMPLATE), ...
		NNVariationalAutoencoderEvaluator.ID, NNVariationalAutoencoderEvaluator.getPropDefault(NNVariationalAutoencoderEvaluator.ID), ...
		NNVariationalAutoencoderEvaluator.LABEL, NNVariationalAutoencoderEvaluator.getPropDefault(NNVariationalAutoencoderEvaluator.LABEL), ...
		NNVariationalAutoencoderEvaluator.NOTES, NNVariationalAutoencoderEvaluator.getPropDefault(NNVariationalAutoencoderEvaluator.NOTES), ...
		NNVariationalAutoencoderEvaluator.TOSTRING, NNVariationalAutoencoderEvaluator.getNoValue(), ...
		NNVariationalAutoencoderEvaluator.NN, NNVariationalAutoencoderEvaluator.getPropDefault(NNVariationalAutoencoderEvaluator.NN), ...
		NNVariationalAutoencoderEvaluator.D, NNVariationalAutoencoderEvaluator.getPropDefault(NNVariationalAutoencoderEvaluator.D), ...
		NNVariationalAutoencoderEvaluator.PLOT_LATENT_REPRESENTATIONS, NNVariationalAutoencoderEvaluator.getNoValue(), ...
		NNVariationalAutoencoderEvaluator.PREDICT_ENCODER, NNVariationalAutoencoderEvaluator.getNoValue() ...
		);
	 
	% NNVariationalAutoencoderEvaluator with 1st callbacks
	nne_1 = NNVariationalAutoencoderEvaluator( ...
		NNVariationalAutoencoderEvaluator.ELCLASS, NNVariationalAutoencoderEvaluator.getNoValue(), ...
		NNVariationalAutoencoderEvaluator.NAME, NNVariationalAutoencoderEvaluator.getNoValue(), ...
		NNVariationalAutoencoderEvaluator.DESCRIPTION, NNVariationalAutoencoderEvaluator.getNoValue(), ...
		NNVariationalAutoencoderEvaluator.TEMPLATE, nne_0.getCallback(4), ..., ...
		NNVariationalAutoencoderEvaluator.ID, nne_0.getCallback(5), ..., ...
		NNVariationalAutoencoderEvaluator.LABEL, NNVariationalAutoencoderEvaluator.getPropDefault(NNVariationalAutoencoderEvaluator.LABEL), ...
		NNVariationalAutoencoderEvaluator.NOTES, NNVariationalAutoencoderEvaluator.getPropDefault(NNVariationalAutoencoderEvaluator.NOTES), ...
		NNVariationalAutoencoderEvaluator.TOSTRING, NNVariationalAutoencoderEvaluator.getNoValue(), ...
		NNVariationalAutoencoderEvaluator.NN, nne_0.getCallback(9), ..., ...
		NNVariationalAutoencoderEvaluator.D, nne_0.getCallback(10), ..., ...
		NNVariationalAutoencoderEvaluator.PLOT_LATENT_REPRESENTATIONS, NNVariationalAutoencoderEvaluator.getNoValue(), ...
		NNVariationalAutoencoderEvaluator.PREDICT_ENCODER, NNVariationalAutoencoderEvaluator.getNoValue() ...
		);
	 
	prop_number = NNVariationalAutoencoderEvaluator.getPropNumber();
	for prop = 1:1:prop_number
		TAG = upper(NNVariationalAutoencoderEvaluator.getPropTag(prop));
		switch NNVariationalAutoencoderEvaluator.getPropCategory(prop)
			case {Category.PARAMETER, Category.DATA, Category.FIGURE, Category.GUI}
				assert( ...
					isa(nne_1.getr(prop), 'Callback'), ...
					[BRAPH2.STR ':NNVariationalAutoencoderEvaluator:' BRAPH2.FAIL_TEST], ...
					['NNVariationalAutoencoderEvaluator.getr(' int2str(prop) ') must be a callback.'] ...
					)
				assert( ...
					isequal(nne_1.get(prop), nne_0.get(prop)) && ~isa(nne_1.get(prop), 'Callback'), ...
					[BRAPH2.STR ':NNVariationalAutoencoderEvaluator:' BRAPH2.FAIL_TEST], ...
					['NNVariationalAutoencoderEvaluator.get(' int2str(prop) ') must be the actual property and NOT a callback.'] ...
					)
			otherwise
				assert( ...
					~isa(nne_1.getr(prop), 'Callback'), ...
					[BRAPH2.STR ':NNVariationalAutoencoderEvaluator:' BRAPH2.FAIL_TEST], ...
					['NNVariationalAutoencoderEvaluator.getr(' int2str(prop) ') must NOT be a callback.'] ...
					)
		end
	end
	 
	% NNVariationalAutoencoderEvaluator with 2nd callbacks
	nne_2 = NNVariationalAutoencoderEvaluator( ...
		NNVariationalAutoencoderEvaluator.ELCLASS, NNVariationalAutoencoderEvaluator.getNoValue(), ...
		NNVariationalAutoencoderEvaluator.NAME, NNVariationalAutoencoderEvaluator.getNoValue(), ...
		NNVariationalAutoencoderEvaluator.DESCRIPTION, NNVariationalAutoencoderEvaluator.getNoValue(), ...
		NNVariationalAutoencoderEvaluator.TEMPLATE, nne_1.getCallback(4), ..., ...
		NNVariationalAutoencoderEvaluator.ID, nne_1.getCallback(5), ..., ...
		NNVariationalAutoencoderEvaluator.LABEL, NNVariationalAutoencoderEvaluator.getPropDefault(NNVariationalAutoencoderEvaluator.LABEL), ...
		NNVariationalAutoencoderEvaluator.NOTES, NNVariationalAutoencoderEvaluator.getPropDefault(NNVariationalAutoencoderEvaluator.NOTES), ...
		NNVariationalAutoencoderEvaluator.TOSTRING, NNVariationalAutoencoderEvaluator.getNoValue(), ...
		NNVariationalAutoencoderEvaluator.NN, nne_1.getCallback(9), ..., ...
		NNVariationalAutoencoderEvaluator.D, nne_1.getCallback(10), ..., ...
		NNVariationalAutoencoderEvaluator.PLOT_LATENT_REPRESENTATIONS, NNVariationalAutoencoderEvaluator.getNoValue(), ...
		NNVariationalAutoencoderEvaluator.PREDICT_ENCODER, NNVariationalAutoencoderEvaluator.getNoValue() ...
		);
	 
	prop_number = NNVariationalAutoencoderEvaluator.getPropNumber();
	for prop = 1:1:prop_number
		TAG = upper(NNVariationalAutoencoderEvaluator.getPropTag(prop));
		switch NNVariationalAutoencoderEvaluator.getPropCategory(prop)
			case {Category.PARAMETER, Category.DATA, Category.FIGURE, Category.GUI}
				assert( ...
					isa(nne_2.getr(prop), 'Callback'), ...
					[BRAPH2.STR ':NNVariationalAutoencoderEvaluator:' BRAPH2.FAIL_TEST], ...
					['NNVariationalAutoencoderEvaluator.getr(' int2str(prop) ') must be a callback.'] ...
					)
				assert( ...
					isequal(nne_2.get(prop), nne_0.get(prop)) && ~isa(nne_1.get(prop), 'Callback'), ...
					[BRAPH2.STR ':NNVariationalAutoencoderEvaluator:' BRAPH2.FAIL_TEST], ...
					['NNVariationalAutoencoderEvaluator.get(' int2str(prop) ') must be the actual property and NOT a callback.'] ...
					)
			otherwise
				assert( ...
					~isa(nne_2.getr(prop), 'Callback'), ...
					[BRAPH2.STR ':NNVariationalAutoencoderEvaluator:' BRAPH2.FAIL_TEST], ...
					['NNVariationalAutoencoderEvaluator.getr(' int2str(prop) ') must NOT be a callback.'] ...
					)
		end
	end
	 
	% NNVariationalAutoencoderEvaluator with 3rd callbacks
	nne_3 = NNVariationalAutoencoderEvaluator( ...
		NNVariationalAutoencoderEvaluator.ELCLASS, NNVariationalAutoencoderEvaluator.getNoValue(), ...
		NNVariationalAutoencoderEvaluator.NAME, NNVariationalAutoencoderEvaluator.getNoValue(), ...
		NNVariationalAutoencoderEvaluator.DESCRIPTION, NNVariationalAutoencoderEvaluator.getNoValue(), ...
		NNVariationalAutoencoderEvaluator.TEMPLATE, nne_2.getCallback(4), ..., ...
		NNVariationalAutoencoderEvaluator.ID, nne_2.getCallback(5), ..., ...
		NNVariationalAutoencoderEvaluator.LABEL, NNVariationalAutoencoderEvaluator.getPropDefault(NNVariationalAutoencoderEvaluator.LABEL), ...
		NNVariationalAutoencoderEvaluator.NOTES, NNVariationalAutoencoderEvaluator.getPropDefault(NNVariationalAutoencoderEvaluator.NOTES), ...
		NNVariationalAutoencoderEvaluator.TOSTRING, NNVariationalAutoencoderEvaluator.getNoValue(), ...
		NNVariationalAutoencoderEvaluator.NN, nne_2.getCallback(9), ..., ...
		NNVariationalAutoencoderEvaluator.D, nne_2.getCallback(10), ..., ...
		NNVariationalAutoencoderEvaluator.PLOT_LATENT_REPRESENTATIONS, NNVariationalAutoencoderEvaluator.getNoValue(), ...
		NNVariationalAutoencoderEvaluator.PREDICT_ENCODER, NNVariationalAutoencoderEvaluator.getNoValue() ...
		);
	 
	prop_number = NNVariationalAutoencoderEvaluator.getPropNumber();
	for prop = 1:1:prop_number
		TAG = upper(NNVariationalAutoencoderEvaluator.getPropTag(prop));
		switch NNVariationalAutoencoderEvaluator.getPropCategory(prop)
			case {Category.PARAMETER, Category.DATA, Category.FIGURE, Category.GUI}
				assert( ...
					isa(nne_3.getr(prop), 'Callback'), ...
					[BRAPH2.STR ':NNVariationalAutoencoderEvaluator:' BRAPH2.FAIL_TEST], ...
					['NNVariationalAutoencoderEvaluator.getr(' int2str(prop) ') must be a callback.'] ...
					)
				assert( ...
					isequal(nne_3.get(prop), nne_0.get(prop)) && ~isa(nne_1.get(prop), 'Callback'), ...
					[BRAPH2.STR ':NNVariationalAutoencoderEvaluator:' BRAPH2.FAIL_TEST], ...
					['NNVariationalAutoencoderEvaluator.get(' int2str(prop) ') must be the actual property and NOT a callback.'] ...
					)
			otherwise
				assert( ...
					~isa(nne_3.getr(prop), 'Callback'), ...
					[BRAPH2.STR ':NNVariationalAutoencoderEvaluator:' BRAPH2.FAIL_TEST], ...
					['NNVariationalAutoencoderEvaluator.getr(' int2str(prop) ') must NOT be a callback.'] ...
					)
		end
	end
	 
end

%% Test 8: Copy
if rand() >= (1 - .01) * BRAPH2TEST.RANDOM
	% copy empty element
	nne = NNVariationalAutoencoderEvaluator();
	 
	nne_copy = nne.copy();
	 
	assert(nne_copy ~= nne, ...
		[BRAPH2.STR ':NNVariationalAutoencoderEvaluator:' BRAPH2.FAIL_TEST], ...
		'NNVariationalAutoencoderEvaluator.copy() does not work. A copied element must point to a copied element.')
	assert(isequal(nne_copy, nne), ...
		[BRAPH2.STR ':NNVariationalAutoencoderEvaluator:' BRAPH2.FAIL_TEST], ...
		'NNVariationalAutoencoderEvaluator.copy() does not work. A copied element must have the same property values of the original element.')
	 
	for prop = 1:1:NNVariationalAutoencoderEvaluator.getPropNumber()
		value = nne.getr(prop);
		value_copy = nne_copy.getr(prop);
		switch NNVariationalAutoencoderEvaluator.getPropCategory(prop)
			case {Category.EVANESCENT}
				assert( ...
					isa(value_copy, 'NoValue'), ...
					[BRAPH2.STR ':NNVariationalAutoencoderEvaluator:' BRAPH2.FAIL_TEST], ...
					'NNVariationalAutoencoderEvaluator.copy() does not work. The copied value of an EVANESCENT property must be NoValue.' ...
					)
			otherwise
				if isa(value, 'NoValue')
					assert( ...
						value_copy == value, ...
						[BRAPH2.STR ':NNVariationalAutoencoderEvaluator:' BRAPH2.FAIL_TEST], ...
						'NNVariationalAutoencoderEvaluator.copy() does not work. There should be a unique instance of NoValue.' ...
						)
				elseif isa(value, 'Element')
					assert( ...
						value_copy ~= value, ...
						[BRAPH2.STR ':NNVariationalAutoencoderEvaluator:' BRAPH2.FAIL_TEST], ...
						'NNVariationalAutoencoderEvaluator.copy() does not work. The handle of a copied element should point to a copied element.' ...
						)
					assert( ...
						isequal(value_copy, value), ...
						[BRAPH2.STR ':NNVariationalAutoencoderEvaluator:' BRAPH2.FAIL_TEST], ...
						'NNVariationalAutoencoderEvaluator.copy() does not work. When empty, a copied element should be equal to the element.' ...
						)
				elseif iscell(value) && all(all(cellfun(@(x) isa(x, 'Element'), value)))
					for j = 1:1:length(value)
						assert( ...
							value_copy ~= value, ...
							[BRAPH2.STR ':NNVariationalAutoencoderEvaluator:' BRAPH2.FAIL_TEST], ...
							'NNVariationalAutoencoderEvaluator.copy() does not work. The handle of a copied element should point to a copied element.' ...
							)
						assert( ...
							isequal(value_copy, value), ...
							[BRAPH2.STR ':NNVariationalAutoencoderEvaluator:' BRAPH2.FAIL_TEST], ...
							'NNVariationalAutoencoderEvaluator.copy() does not work. When empty, a copied element should be equal to the element.' ...
							)
					end
				else
					assert( ...
						isequal(value_copy, value), ...
						[BRAPH2.STR ':NNVariationalAutoencoderEvaluator:' BRAPH2.FAIL_TEST], ...
						'NNVariationalAutoencoderEvaluator.copy() does not work. The value copy should be equal to the original.' ...
						)
				end
				assert( ...
					nne_copy.isLocked(prop) == nne.isLocked(prop), ...
					[BRAPH2.STR ':NNVariationalAutoencoderEvaluator:' BRAPH2.FAIL_TEST], ...
					'NNVariationalAutoencoderEvaluator.copy() does not work. The locked status of the copied and original elements must be the same.' ...
					)
				assert( ...
					nne_copy.isChecked(prop) == nne.isChecked(prop), ...
					[BRAPH2.STR ':NNVariationalAutoencoderEvaluator:' BRAPH2.FAIL_TEST], ...
					'NNVariationalAutoencoderEvaluator.copy() does not work. The checked status of the copied and original elements must be the same.' ...
					)
				assert( ...
					nne_copy.getPropSeed(prop) == nne.getPropSeed(prop), ...
					[BRAPH2.STR ':NNVariationalAutoencoderEvaluator:' BRAPH2.FAIL_TEST], ...
					'NNVariationalAutoencoderEvaluator.copy() does not work. The randomization seeds of the copied and original elements must be the same.' ...
					)
		end
	end
	 
	% copy element with default initialization and memorization
	nne = NNVariationalAutoencoderEvaluator( ...
		NNVariationalAutoencoderEvaluator.ELCLASS, NNVariationalAutoencoderEvaluator.getNoValue(), ...
		NNVariationalAutoencoderEvaluator.NAME, NNVariationalAutoencoderEvaluator.getNoValue(), ...
		NNVariationalAutoencoderEvaluator.DESCRIPTION, NNVariationalAutoencoderEvaluator.getNoValue(), ...
		NNVariationalAutoencoderEvaluator.TEMPLATE, NNVariationalAutoencoderEvaluator.getPropDefault(NNVariationalAutoencoderEvaluator.TEMPLATE), ...
		NNVariationalAutoencoderEvaluator.ID, NNVariationalAutoencoderEvaluator.getPropDefault(NNVariationalAutoencoderEvaluator.ID), ...
		NNVariationalAutoencoderEvaluator.LABEL, NNVariationalAutoencoderEvaluator.getPropDefault(NNVariationalAutoencoderEvaluator.LABEL), ...
		NNVariationalAutoencoderEvaluator.NOTES, NNVariationalAutoencoderEvaluator.getPropDefault(NNVariationalAutoencoderEvaluator.NOTES), ...
		NNVariationalAutoencoderEvaluator.TOSTRING, NNVariationalAutoencoderEvaluator.getNoValue(), ...
		NNVariationalAutoencoderEvaluator.NN, NNVariationalAutoencoderEvaluator.getPropDefault(NNVariationalAutoencoderEvaluator.NN), ...
		NNVariationalAutoencoderEvaluator.D, NNVariationalAutoencoderEvaluator.getPropDefault(NNVariationalAutoencoderEvaluator.D), ...
		NNVariationalAutoencoderEvaluator.PLOT_LATENT_REPRESENTATIONS, NNVariationalAutoencoderEvaluator.getNoValue(), ...
		NNVariationalAutoencoderEvaluator.PREDICT_ENCODER, NNVariationalAutoencoderEvaluator.getNoValue() ...
		);
	 
	for prop = 1:1:NNVariationalAutoencoderEvaluator.getPropNumber()
		if NNVariationalAutoencoderEvaluator.getPropCategory(prop) == Category.QUERY
			% properties QUERY should not be memorized
			% warning_backup = warning('off', [BRAPH2.STR ':NNVariationalAutoencoderEvaluator']);
			% nne.memorize(prop);
			% warning(warning_backup)
		elseif NNVariationalAutoencoderEvaluator.getPropCategory(prop) == Category.EVANESCENT && nne.getPropFormat(prop) == Format.HANDLE
			nne.memorize(prop);
			warning_backup = warning('off', 'BRAPH2:NNVariationalAutoencoderEvaluator');
			delete(ancestor(nne.get(prop), 'figure'))
			warning(warning_backup)
		else
			nne.memorize(prop);
		end
	end
	 
	% copy element with default initialization
	nne_copy = nne.copy();
	 
	for prop = 1:1:NNVariationalAutoencoderEvaluator.getPropNumber()
		value = nne.getr(prop);
		value_copy = nne_copy.getr(prop);
		switch NNVariationalAutoencoderEvaluator.getPropCategory(prop)
			case {Category.EVANESCENT Category.QUERY}
				assert( ...
					isa(value_copy, 'NoValue'), ...
					[BRAPH2.STR ':NNVariationalAutoencoderEvaluator:' BRAPH2.FAIL_TEST], ...
					'NNVariationalAutoencoderEvaluator.copy() does not work. The copied value of an EVANESCENT property must be NoValue.' ...
					)
			otherwise
				if isa(value, 'NoValue')
					assert( ...
						value_copy == value, ...
						[BRAPH2.STR ':NNVariationalAutoencoderEvaluator:' BRAPH2.FAIL_TEST], ...
						'NNVariationalAutoencoderEvaluator.copy() does not work. There should be a unique instance of NoValue.' ...
						)
				elseif isa(value, 'Element')
					assert( ...
						value_copy ~= value, ...
						[BRAPH2.STR ':NNVariationalAutoencoderEvaluator:' BRAPH2.FAIL_TEST], ...
						'NNVariationalAutoencoderEvaluator.copy() does not work. The handle of a copied element should point to a copied element.' ...
						)
					assert( ...
						isequal(value_copy, value), ...
						[BRAPH2.STR ':NNVariationalAutoencoderEvaluator:' BRAPH2.FAIL_TEST], ...
						'NNVariationalAutoencoderEvaluator.copy() does not work. When empty, a copied element should be equal to the element.' ...
						)
				elseif iscell(value) && all(all(cellfun(@(x) isa(x, 'Element'), value)))
					for j = 1:1:length(value)
						assert( ...
							value_copy ~= value, ...
							[BRAPH2.STR ':NNVariationalAutoencoderEvaluator:' BRAPH2.FAIL_TEST], ...
							'NNVariationalAutoencoderEvaluator.copy() does not work. The handle of a copied element should point to a copied element.' ...
							)
						assert( ...
							isequal(value_copy, value), ...
							[BRAPH2.STR ':NNVariationalAutoencoderEvaluator:' BRAPH2.FAIL_TEST], ...
							'NNVariationalAutoencoderEvaluator.copy() does not work. When empty, a copied element should be equal to the element.' ...
							)
					end
				else
					assert( ...
						isequal(value_copy, value), ...
						[BRAPH2.STR ':NNVariationalAutoencoderEvaluator:' BRAPH2.FAIL_TEST], ...
						'NNVariationalAutoencoderEvaluator.copy() does not work. The value copy should be equal to the original.' ...
						)
				end
	 
					assert( ...
						nne_copy.isLocked(prop) == nne.isLocked(prop), ...
						[BRAPH2.STR ':NNVariationalAutoencoderEvaluator:' BRAPH2.FAIL_TEST], ...
						'NNVariationalAutoencoderEvaluator.copy() does not work. The locked status of the copied and original elements must be the same.' ...
						)
	 
					assert( ...
						nne_copy.isChecked(prop) == nne.isChecked(prop), ...
						[BRAPH2.STR ':NNVariationalAutoencoderEvaluator:' BRAPH2.FAIL_TEST], ...
						'NNVariationalAutoencoderEvaluator.copy() does not work. The checked status of the copied and original elements must be the same.' ...
						)
	 
					assert( ...
						nne_copy.getPropSeed(prop) == nne.getPropSeed(prop), ...
						[BRAPH2.STR ':NNVariationalAutoencoderEvaluator:' BRAPH2.FAIL_TEST], ...
						'NNVariationalAutoencoderEvaluator.copy() does not work. The randomization seeds of the copied and original elements must be the same.' ...
						)
		end
	end
	 
	% copy element with callbacks
	nne_0 = NNVariationalAutoencoderEvaluator( ...
		NNVariationalAutoencoderEvaluator.ELCLASS, NNVariationalAutoencoderEvaluator.getNoValue(), ...
		NNVariationalAutoencoderEvaluator.NAME, NNVariationalAutoencoderEvaluator.getNoValue(), ...
		NNVariationalAutoencoderEvaluator.DESCRIPTION, NNVariationalAutoencoderEvaluator.getNoValue(), ...
		NNVariationalAutoencoderEvaluator.TEMPLATE, NNVariationalAutoencoderEvaluator.getPropDefault(NNVariationalAutoencoderEvaluator.TEMPLATE), ...
		NNVariationalAutoencoderEvaluator.ID, NNVariationalAutoencoderEvaluator.getPropDefault(NNVariationalAutoencoderEvaluator.ID), ...
		NNVariationalAutoencoderEvaluator.LABEL, NNVariationalAutoencoderEvaluator.getPropDefault(NNVariationalAutoencoderEvaluator.LABEL), ...
		NNVariationalAutoencoderEvaluator.NOTES, NNVariationalAutoencoderEvaluator.getPropDefault(NNVariationalAutoencoderEvaluator.NOTES), ...
		NNVariationalAutoencoderEvaluator.TOSTRING, NNVariationalAutoencoderEvaluator.getNoValue(), ...
		NNVariationalAutoencoderEvaluator.NN, NNVariationalAutoencoderEvaluator.getPropDefault(NNVariationalAutoencoderEvaluator.NN), ...
		NNVariationalAutoencoderEvaluator.D, NNVariationalAutoencoderEvaluator.getPropDefault(NNVariationalAutoencoderEvaluator.D), ...
		NNVariationalAutoencoderEvaluator.PLOT_LATENT_REPRESENTATIONS, NNVariationalAutoencoderEvaluator.getNoValue(), ...
		NNVariationalAutoencoderEvaluator.PREDICT_ENCODER, NNVariationalAutoencoderEvaluator.getNoValue() ...
		);
	 
	nne = NNVariationalAutoencoderEvaluator( ...
		NNVariationalAutoencoderEvaluator.ELCLASS, NNVariationalAutoencoderEvaluator.getNoValue(), ...
		NNVariationalAutoencoderEvaluator.NAME, NNVariationalAutoencoderEvaluator.getNoValue(), ...
		NNVariationalAutoencoderEvaluator.DESCRIPTION, NNVariationalAutoencoderEvaluator.getNoValue(), ...
		NNVariationalAutoencoderEvaluator.TEMPLATE, nne_0.getCallback(4), ..., ...
		NNVariationalAutoencoderEvaluator.ID, nne_0.getCallback(5), ..., ...
		NNVariationalAutoencoderEvaluator.LABEL, NNVariationalAutoencoderEvaluator.getPropDefault(NNVariationalAutoencoderEvaluator.LABEL), ...
		NNVariationalAutoencoderEvaluator.NOTES, NNVariationalAutoencoderEvaluator.getPropDefault(NNVariationalAutoencoderEvaluator.NOTES), ...
		NNVariationalAutoencoderEvaluator.TOSTRING, NNVariationalAutoencoderEvaluator.getNoValue(), ...
		NNVariationalAutoencoderEvaluator.NN, nne_0.getCallback(9), ..., ...
		NNVariationalAutoencoderEvaluator.D, nne_0.getCallback(10), ..., ...
		NNVariationalAutoencoderEvaluator.PLOT_LATENT_REPRESENTATIONS, NNVariationalAutoencoderEvaluator.getNoValue(), ...
		NNVariationalAutoencoderEvaluator.PREDICT_ENCODER, NNVariationalAutoencoderEvaluator.getNoValue() ...
		);
	 
	nne_copy = nne.copy();
	nne_0_copy = nne_copy.getr('ID').get('EL');
	 
	for prop = 1:1:NNVariationalAutoencoderEvaluator.getPropNumber()
		value = nne.getr(prop);
		value_copy = nne_copy.getr(prop);
		switch NNVariationalAutoencoderEvaluator.getPropCategory(prop)
			case {Category.EVANESCENT}
				assert( ...
					isa(value_copy, 'NoValue'), ...
					[BRAPH2.STR ':NNVariationalAutoencoderEvaluator:' BRAPH2.FAIL_TEST], ...
					'NNVariationalAutoencoderEvaluator.copy() does not work. The copied value of an EVANESCENT property must be NoValue.' ...
					)
			otherwise
				if isa(value, 'NoValue')
					assert( ...
						value_copy == value, ...
						[BRAPH2.STR ':NNVariationalAutoencoderEvaluator:' BRAPH2.FAIL_TEST], ...
						'NNVariationalAutoencoderEvaluator.copy() does not work. There should be a unique instance of NoValue.' ...
						)
				elseif isa(value, 'Element')
					assert( ...
						value_copy ~= value, ...
						[BRAPH2.STR ':NNVariationalAutoencoderEvaluator:' BRAPH2.FAIL_TEST], ...
						'NNVariationalAutoencoderEvaluator.copy() does not work. The handle of a copied element should point to a copied element.' ...
						)
					assert( ...
						isequal(value_copy, value), ...
						[BRAPH2.STR ':NNVariationalAutoencoderEvaluator:' BRAPH2.FAIL_TEST], ...
						'NNVariationalAutoencoderEvaluator.copy() does not work. When empty, a copied element should be equal to the element.' ...
						)
				elseif iscell(value) && all(all(cellfun(@(x) isa(x, 'Element'), value)))
					for j = 1:1:length(value)
						assert( ...
							value_copy ~= value, ...
							[BRAPH2.STR ':NNVariationalAutoencoderEvaluator:' BRAPH2.FAIL_TEST], ...
							'NNVariationalAutoencoderEvaluator.copy() does not work. The handle of a copied element should point to a copied element.' ...
							)
						assert( ...
							isequal(value_copy, value), ...
							[BRAPH2.STR ':NNVariationalAutoencoderEvaluator:' BRAPH2.FAIL_TEST], ...
							'NNVariationalAutoencoderEvaluator.copy() does not work. When empty, a copied element should be equal to the element.' ...
							)
					end
				else
					assert( ...
						isequal(value_copy, value), ...
						[BRAPH2.STR ':NNVariationalAutoencoderEvaluator:' BRAPH2.FAIL_TEST], ...
						'NNVariationalAutoencoderEvaluator.copy() does not work. The value copy should be equal to the original.' ...
						)
				end
				if isa(value, 'Callback')
					assert( ...
						value == nne_0.getCallback(prop), ...
						[BRAPH2.STR ':NNVariationalAutoencoderEvaluator:' BRAPH2.FAIL_TEST], ...
						'NNVariationalAutoencoderEvaluator.copy() does not work. The callback should be obtained from NNVariationalAutoencoderEvaluator.getCallback().' ...
						)
					assert( ...
						value_copy == nne_0_copy.getCallback(prop), ...
						[BRAPH2.STR ':NNVariationalAutoencoderEvaluator:' BRAPH2.FAIL_TEST], ...
						'NNVariationalAutoencoderEvaluator.copy() does not work. The callback should be obtained from NNVariationalAutoencoderEvaluator.getCallback().' ...
						)
				end
	 
					assert( ...
						nne_copy.isLocked(prop) == nne.isLocked(prop), ...
						[BRAPH2.STR ':NNVariationalAutoencoderEvaluator:' BRAPH2.FAIL_TEST], ...
						'NNVariationalAutoencoderEvaluator.copy() does not work. The locked status of the copied and original elements must be the same.' ...
						)
	 
					assert( ...
						nne_copy.isChecked(prop) == nne.isChecked(prop), ...
						[BRAPH2.STR ':NNVariationalAutoencoderEvaluator:' BRAPH2.FAIL_TEST], ...
						'NNVariationalAutoencoderEvaluator.copy() does not work. The checked status of the copied and original elements must be the same.' ...
						)
	 
					assert( ...
						nne_copy.getPropSeed(prop) == nne.getPropSeed(prop), ...
						[BRAPH2.STR ':NNVariationalAutoencoderEvaluator:' BRAPH2.FAIL_TEST], ...
						'NNVariationalAutoencoderEvaluator.copy() does not work. The randomization seeds of the copied and original elements must be the same.' ...
						)
		end
	end
	 
end

%% Test 9: Template
if rand() >= (1 - .01) * BRAPH2TEST.RANDOM
	nne_template = NNVariationalAutoencoderEvaluator();
	nne = NNVariationalAutoencoderEvaluator('TEMPLATE', nne_template);
	 
	for prop = 1:1:NNVariationalAutoencoderEvaluator.getPropNumber()
	 
		% excluded props
		if any(prop == [NNVariationalAutoencoderEvaluator.PLOT_LATENT_REPRESENTATIONS NNVariationalAutoencoderEvaluator.PREDICT_ENCODER])
			continue
		end
	 
		TAG = upper(NNVariationalAutoencoderEvaluator.getPropTag(prop));
		switch NNVariationalAutoencoderEvaluator.getPropCategory(prop)
			case {Category.PARAMETER}
				if prop == NNVariationalAutoencoderEvaluator.TEMPLATE
					assert( ...
						isa(nne.getr(prop), 'NNVariationalAutoencoderEvaluator'), ...
						[BRAPH2.STR ':NNVariationalAutoencoderEvaluator:' BRAPH2.FAIL_TEST], ...
						'NNVariationalAutoencoderEvaluator TEMPLATE does not work. NNVariationalAutoencoderEvaluator.getr(''TEMPLATE'') should be a NNVariationalAutoencoderEvaluator element.' ...
						)
					assert( ...
						isa(nne_template.getr(prop), 'NoValue'), ...
						[BRAPH2.STR ':NNVariationalAutoencoderEvaluator:' BRAPH2.FAIL_TEST], ...
						'NNVariationalAutoencoderEvaluator TEMPLATE does not work. NNVariationalAutoencoderEvaluator_template.getr(''TEMPLATE'') should be a NoValue.' ...
						)
				else
					assert( ...
						isa(nne.getr(prop), 'Callback'), ...
						[BRAPH2.STR ':NNVariationalAutoencoderEvaluator:' BRAPH2.FAIL_TEST], ...
						['NNVariationalAutoencoderEvaluator TEMPLATE does not work. NNVariationalAutoencoderEvaluator.getr(' TAG ') should be a Callback.'] ...
						)
					assert( ...
						nne.getr(prop).get('EL') == nne_template && nne.getr(prop).get('PROP') == prop && strcmp(nne.getr(prop).get('TAG'), TAG), ...
						[BRAPH2.STR ':NNVariationalAutoencoderEvaluator:' BRAPH2.FAIL_TEST], ...
						['NNVariationalAutoencoderEvaluator TEMPLATE does not work. NNVariationalAutoencoderEvaluator.getr(' TAG ') should be a Callback to nne_template.' TAG '.'] ...
						)
					assert( ...
						isa(nne_template.getr(prop), 'NoValue'), ...
						[BRAPH2.STR ':NNVariationalAutoencoderEvaluator:' BRAPH2.FAIL_TEST], ...
						['NNVariationalAutoencoderEvaluator TEMPLATE does not work. NNVariationalAutoencoderEvaluator_template.getr(' TAG ') should be a NoValue.'] ...
						)
				end
			otherwise
				assert( ...
					isa(nne.getr(prop), 'NoValue'), ...
					[BRAPH2.STR ':NNVariationalAutoencoderEvaluator:' BRAPH2.FAIL_TEST], ...
					['NNVariationalAutoencoderEvaluator TEMPLATE does not work. NNVariationalAutoencoderEvaluator.getr(' TAG ') should be a NoValue.'] ...
					)
				assert( ...
					isa(nne_template.getr(prop), 'NoValue'), ...
					[BRAPH2.STR ':NNVariationalAutoencoderEvaluator:' BRAPH2.FAIL_TEST], ...
					['NNVariationalAutoencoderEvaluator TEMPLATE does not work. NNVariationalAutoencoderEvaluator_template.getr(' TAG ') should be a NoValue.'] ...
					)
		end
	end
end

%% Test 10: Save Load
if rand() >= (1 - .01) * BRAPH2TEST.RANDOM
	nne = NNVariationalAutoencoderEvaluator( ...
		NNVariationalAutoencoderEvaluator.ELCLASS, NNVariationalAutoencoderEvaluator.getNoValue(), ...
		NNVariationalAutoencoderEvaluator.NAME, NNVariationalAutoencoderEvaluator.getNoValue(), ...
		NNVariationalAutoencoderEvaluator.DESCRIPTION, NNVariationalAutoencoderEvaluator.getNoValue(), ...
		NNVariationalAutoencoderEvaluator.TEMPLATE, NNVariationalAutoencoderEvaluator.getPropDefault(NNVariationalAutoencoderEvaluator.TEMPLATE), ...
		NNVariationalAutoencoderEvaluator.ID, NNVariationalAutoencoderEvaluator.getPropDefault(NNVariationalAutoencoderEvaluator.ID), ...
		NNVariationalAutoencoderEvaluator.LABEL, NNVariationalAutoencoderEvaluator.getPropDefault(NNVariationalAutoencoderEvaluator.LABEL), ...
		NNVariationalAutoencoderEvaluator.NOTES, NNVariationalAutoencoderEvaluator.getPropDefault(NNVariationalAutoencoderEvaluator.NOTES), ...
		NNVariationalAutoencoderEvaluator.TOSTRING, NNVariationalAutoencoderEvaluator.getNoValue(), ...
		NNVariationalAutoencoderEvaluator.NN, NNVariationalAutoencoderEvaluator.getPropDefault(NNVariationalAutoencoderEvaluator.NN), ...
		NNVariationalAutoencoderEvaluator.D, NNVariationalAutoencoderEvaluator.getPropDefault(NNVariationalAutoencoderEvaluator.D), ...
		NNVariationalAutoencoderEvaluator.PLOT_LATENT_REPRESENTATIONS, NNVariationalAutoencoderEvaluator.getNoValue(), ...
		NNVariationalAutoencoderEvaluator.PREDICT_ENCODER, NNVariationalAutoencoderEvaluator.getNoValue() ...
		);
	 
	filename = [fileparts(which('test_braph2')) filesep 'nnvariationalautoencoderevaluator_to_be_erased.b2'];
	 
	Element.save(nne, filename)
	 
	nne_loaded = Element.load(filename);
	 
	assert( ...
		isequal(nne.copy(), nne_loaded), ...
		[BRAPH2.STR ':NNVariationalAutoencoderEvaluator:' BRAPH2.FAIL_TEST], ...
		'NNVariationalAutoencoderEvaluator.save(nne) and/or NNVariationalAutoencoderEvaluator.load() do not work.' ...
		)
	 
	delete(filename)
end

%% Test 11: JSON
if rand() >= (1 - .01) * BRAPH2TEST.RANDOM
	nne = NNVariationalAutoencoderEvaluator( ...
		NNVariationalAutoencoderEvaluator.ELCLASS, NNVariationalAutoencoderEvaluator.getNoValue(), ...
		NNVariationalAutoencoderEvaluator.NAME, NNVariationalAutoencoderEvaluator.getNoValue(), ...
		NNVariationalAutoencoderEvaluator.DESCRIPTION, NNVariationalAutoencoderEvaluator.getNoValue(), ...
		NNVariationalAutoencoderEvaluator.TEMPLATE, NNVariationalAutoencoderEvaluator.getPropDefault(NNVariationalAutoencoderEvaluator.TEMPLATE), ...
		NNVariationalAutoencoderEvaluator.ID, NNVariationalAutoencoderEvaluator.getPropDefault(NNVariationalAutoencoderEvaluator.ID), ...
		NNVariationalAutoencoderEvaluator.LABEL, NNVariationalAutoencoderEvaluator.getPropDefault(NNVariationalAutoencoderEvaluator.LABEL), ...
		NNVariationalAutoencoderEvaluator.NOTES, NNVariationalAutoencoderEvaluator.getPropDefault(NNVariationalAutoencoderEvaluator.NOTES), ...
		NNVariationalAutoencoderEvaluator.TOSTRING, NNVariationalAutoencoderEvaluator.getNoValue(), ...
		NNVariationalAutoencoderEvaluator.NN, NNVariationalAutoencoderEvaluator.getPropDefault(NNVariationalAutoencoderEvaluator.NN), ...
		NNVariationalAutoencoderEvaluator.D, NNVariationalAutoencoderEvaluator.getPropDefault(NNVariationalAutoencoderEvaluator.D), ...
		NNVariationalAutoencoderEvaluator.PLOT_LATENT_REPRESENTATIONS, NNVariationalAutoencoderEvaluator.getNoValue(), ...
		NNVariationalAutoencoderEvaluator.PREDICT_ENCODER, NNVariationalAutoencoderEvaluator.getNoValue() ...
		);
	 
	[json, struct, el_list] = encodeJSON(nne);
	[nne_dec, struct_dec, el_list_dec] = Element.decodeJSON(json);
	 
	assert(nne_dec ~= nne, ...
		[BRAPH2.STR ':NNVariationalAutoencoderEvaluator:' BRAPH2.FAIL_TEST], ...
		'NNVariationalAutoencoderEvaluator.encodeJSON() or NNVariationalAutoencoderEvaluator.decodeJSON() does not work. A JSON encoded/decoded element must point to an element other than the original one.' ...
		)
	if all(cellfun(@(prop) NNVariationalAutoencoderEvaluator.getPropFormat(prop), num2cell(NNVariationalAutoencoderEvaluator.getProps())) == Format.HANDLE) && all(cellfun(@(prop) NNVariationalAutoencoderEvaluator.getPropFormat(prop), num2cell(NNVariationalAutoencoderEvaluator.getProps())) == Format.NET)
		assert(isequal(nne_dec, nne), ...
			[BRAPH2.STR ':NNVariationalAutoencoderEvaluator:' BRAPH2.FAIL_TEST], ...
			'NNVariationalAutoencoderEvaluator.encodeJSON() or NNVariationalAutoencoderEvaluator.decodeJSON() does not work. A JSON encoded/decoded element must have the same property values of the original element.' ...
			)
	end
end

%% Test 12: No Figures Left
if rand() >= (1 - 1) * BRAPH2TEST.RANDOM
	assert(isempty(findall(0, 'type', 'figure')), ...
		[BRAPH2.STR ':NNVariationalAutoencoderEvaluator:' BRAPH2.FAIL_TEST], ...
		[' When testing NNVariationalAutoencoderEvaluator no figures should be left over, either visible or not. ' ...
		int2str(length(findall(0, 'type', 'figure'))) ' figure(s) were left over.'] ...
		)
end

%% Test 13: Delete Figures
if rand() >= (1 - 1) * BRAPH2TEST.RANDOM
	delete(findall(0, 'type', 'figure'))
end

