%TEST_NNVARIATIONALAUTOENCODER

%% Test 1: Inspection Methods
if rand() >= (1 - .01) * BRAPH2TEST.RANDOM
	categories = num2cell(Category.getCategories());
	nnvae = NNVariationalAutoencoder();
	 
	% get('ELCLASS')
	if isa(NNVariationalAutoencoder, 'ConcreteElement')
		assert(strcmp(NNVariationalAutoencoder().get('ELCLASS'), 'NNVariationalAutoencoder'), ...
			[BRAPH2.STR ':NNVariationalAutoencoder:' BRAPH2.FAIL_TEST], ...
			'NNVariationalAutoencoder().get(''ELCLASS'') should return ''NNVariationalAutoencoder''.')
	end
	 
	% getBuild()
	assert(NNVariationalAutoencoder.getBuild() == 1 && NNVariationalAutoencoder.getBuild() > 0, ...
		[BRAPH2.STR ':NNVariationalAutoencoder:' BRAPH2.FAIL_TEST], ...
		'NNVariationalAutoencoder.getBuild() should return the NNVariationalAutoencoder build number.')
	assert(nnvae.getBuild() == 1 && nnvae.getBuild() > 0 , ...
		[BRAPH2.STR ':NNVariationalAutoencoder:' BRAPH2.FAIL_TEST], ...
		'nnvae.getBuild() should return the NNVariationalAutoencoder build number.')
	assert(Element.getBuild(nnvae) == 1 && Element.getBuild(nnvae) > 0, ...
		[BRAPH2.STR ':NNVariationalAutoencoder:' BRAPH2.FAIL_TEST], ...
		'Element.getBuild(nnvae) should return the NNVariationalAutoencoder build number.')
	assert(Element.getBuild('NNVariationalAutoencoder') == 1 && Element.getBuild('NNVariationalAutoencoder') > 0, ...
		[BRAPH2.STR ':NNVariationalAutoencoder:' BRAPH2.FAIL_TEST], ...
		'Element.getBuild(''NNVariationalAutoencoder'') should return the NNVariationalAutoencoder build number.')
	 
	% getClass()
	assert(strcmp(NNVariationalAutoencoder.getClass(), 'NNVariationalAutoencoder'), ...
		[BRAPH2.STR ':NNVariationalAutoencoder:' BRAPH2.FAIL_TEST], ...
		'NNVariationalAutoencoder.getClass() should return ''NNVariationalAutoencoder''.')
	assert(strcmp(nnvae.getClass(), 'NNVariationalAutoencoder'), ...
		[BRAPH2.STR ':NNVariationalAutoencoder:' BRAPH2.FAIL_TEST], ...
		'nnvae.getClass() should return ''NNVariationalAutoencoder''.')
	assert(strcmp(Element.getClass(nnvae), 'NNVariationalAutoencoder'), ...
		[BRAPH2.STR ':NNVariationalAutoencoder:' BRAPH2.FAIL_TEST], ...
		'Element.getClass(nnvae) should return ''NNVariationalAutoencoder''.')
	assert(strcmp(Element.getClass('NNVariationalAutoencoder'), 'NNVariationalAutoencoder'), ...
		[BRAPH2.STR ':NNVariationalAutoencoder:' BRAPH2.FAIL_TEST], ...
		'Element.getClass(''NNVariationalAutoencoder'') should return ''NNVariationalAutoencoder''.')
	 
	% getSubclasses()
	assert(isequal(NNVariationalAutoencoder.getSubclasses(), subclasses('NNVariationalAutoencoder', [], [], true)), ...
		[BRAPH2.STR ':NNVariationalAutoencoder:' BRAPH2.FAIL_TEST], ...
		'NNVariationalAutoencoder.getSubclasses() should return the same result as subclasses(''NNVariationalAutoencoder'', [], [], true).')
	assert(isequal(nnvae.getSubclasses(), subclasses('NNVariationalAutoencoder', [], [], true)), ...
		[BRAPH2.STR ':NNVariationalAutoencoder:' BRAPH2.FAIL_TEST], ...
		'el.getSubclasses() should return the same result as subclasses(''NNVariationalAutoencoder'', [], [], true).')
	assert(isequal(Element.getSubclasses(nnvae), subclasses('NNVariationalAutoencoder', [], [], true)), ...
		[BRAPH2.STR ':NNVariationalAutoencoder:' BRAPH2.FAIL_TEST], ...
		'Element.getSubclasses(nnvae) should return the same result as subclasses(''NNVariationalAutoencoder'', [], [], true).')
	assert(isequal(Element.getSubclasses('NNVariationalAutoencoder'), subclasses('NNVariationalAutoencoder', [], [], true)), ...
		[BRAPH2.STR ':NNVariationalAutoencoder:' BRAPH2.FAIL_TEST], ...
		'Element.getSubclasses(''NNVariationalAutoencoder'') should return the same result as subclasses(''NNVariationalAutoencoder'', [], [], true).')
	 
	% getProps()
	assert(isempty(NNVariationalAutoencoder.getProps()) || isequal(NNVariationalAutoencoder.getProps(), 1:1:length(NNVariationalAutoencoder.getProps())), ...
		[BRAPH2.STR ':NNVariationalAutoencoder:' BRAPH2.FAIL_TEST], ...
		'NNVariationalAutoencoder.getProps() should return a row vector [1:1:N].')
	assert(isempty(NNVariationalAutoencoder.getProps()) || isequal(nnvae.getProps(), 1:1:length(NNVariationalAutoencoder.getProps())), ...
		[BRAPH2.STR ':NNVariationalAutoencoder:' BRAPH2.FAIL_TEST], ...
		'nnvae.getProps() should return a row vector [1:1:N].')
	assert(isempty(NNVariationalAutoencoder.getProps()) || isequal(Element.getProps(nnvae), 1:1:length(NNVariationalAutoencoder.getProps())), ...
		[BRAPH2.STR ':NNVariationalAutoencoder:' BRAPH2.FAIL_TEST], ...
		'Element.getProps(nnvae) should return a row vector [1:1:N].')
	assert(isempty(NNVariationalAutoencoder.getProps()) || isequal(Element.getProps('NNVariationalAutoencoder'), 1:1:length(NNVariationalAutoencoder.getProps())), ...
		[BRAPH2.STR ':NNVariationalAutoencoder:' BRAPH2.FAIL_TEST], ...
		'Element.getProps(''NNVariationalAutoencoder'') should return a row vector [1:1:N].')
	 
	% getProps(category)
	tmp = cellfun(@(category) NNVariationalAutoencoder.getProps(category), categories, 'UniformOutput', false);
	assert(isempty(NNVariationalAutoencoder.getProps()) || isequal(sort(horzcat(tmp{:})), 1:1:length(NNVariationalAutoencoder.getProps())), ...
		[BRAPH2.STR ':NNVariationalAutoencoder:' BRAPH2.FAIL_TEST], ...
		'NNVariationalAutoencoder.getProps(category) does not work.')
	tmp = cellfun(@(category) nnvae.getProps(category), categories, 'UniformOutput', false);
	assert(isempty(NNVariationalAutoencoder.getProps()) || isequal(sort(horzcat(tmp{:})), 1:1:length(NNVariationalAutoencoder.getProps())), ...
		[BRAPH2.STR ':NNVariationalAutoencoder:' BRAPH2.FAIL_TEST], ...
		'nnvae.getProps(category) does not work.')
	tmp = cellfun(@(category) Element.getProps(nnvae, category), categories, 'UniformOutput', false);
	assert(isempty(NNVariationalAutoencoder.getProps()) || isequal(sort(horzcat(tmp{:})), 1:1:length(NNVariationalAutoencoder.getProps())), ...
		[BRAPH2.STR ':NNVariationalAutoencoder:' BRAPH2.FAIL_TEST], ...
		'Element.getProps(nnvae, category) does not work.')
	tmp = cellfun(@(category) Element.getProps('NNVariationalAutoencoder', category), categories, 'UniformOutput', false);
	assert(isempty(NNVariationalAutoencoder.getProps()) || isequal(sort(horzcat(tmp{:})), 1:1:length(NNVariationalAutoencoder.getProps())), ...
		[BRAPH2.STR ':NNVariationalAutoencoder:' BRAPH2.FAIL_TEST], ...
		'Element.getProps(''NNVariationalAutoencoder'', category) does not work.')
	 
	% getPropNumber()
	assert(NNVariationalAutoencoder.getPropNumber() == length(NNVariationalAutoencoder.getProps()), ...
		[BRAPH2.STR ':NNVariationalAutoencoder:' BRAPH2.FAIL_TEST], ...
		'NNVariationalAutoencoder.getPropNumber() should return the number of properties.')
	assert(nnvae.getPropNumber() == length(NNVariationalAutoencoder.getProps()), ...
		[BRAPH2.STR ':NNVariationalAutoencoder:' BRAPH2.FAIL_TEST], ...
		'nnvae.getPropNumber() should return the number of properties.')
	assert(Element.getPropNumber(nnvae) == length(NNVariationalAutoencoder.getProps()), ...
		[BRAPH2.STR ':NNVariationalAutoencoder:' BRAPH2.FAIL_TEST], ...
		'Element.getPropNumber(nnvae) should return the number of properties.')
	assert(Element.getPropNumber('NNVariationalAutoencoder') == length(NNVariationalAutoencoder.getProps()), ...
		[BRAPH2.STR ':NNVariationalAutoencoder:' BRAPH2.FAIL_TEST], ...
		'Element.getPropNumber(''NNVariationalAutoencoder'') should return the number of properties.')
	 
	% getPropNumber(category)
	assert(sum(cellfun(@(category) NNVariationalAutoencoder.getPropNumber(category), categories)) == NNVariationalAutoencoder.getPropNumber(), ...
		[BRAPH2.STR ':NNVariationalAutoencoder:' BRAPH2.FAIL_TEST], ...
		'NNVariationalAutoencoder.getPropNumber(category) does not work.')
	assert(sum(cellfun(@(category) nnvae.getPropNumber(category), categories)) == NNVariationalAutoencoder.getPropNumber(), ...
		[BRAPH2.STR ':NNVariationalAutoencoder:' BRAPH2.FAIL_TEST], ...
		'nnvae.getPropNumber(category) does not work.')
	assert(sum(cellfun(@(category) Element.getPropNumber(nnvae, category), categories)) == NNVariationalAutoencoder.getPropNumber(), ...
		[BRAPH2.STR ':NNVariationalAutoencoder:' BRAPH2.FAIL_TEST], ...
		'Element.getPropNumber(nnvae, category) does not work.')
	assert(sum(cellfun(@(category) Element.getPropNumber('NNVariationalAutoencoder', category), categories)) == NNVariationalAutoencoder.getPropNumber(), ...
		[BRAPH2.STR ':NNVariationalAutoencoder:' BRAPH2.FAIL_TEST], ...
		'Element.getPropNumber(''NNVariationalAutoencoder'', category) does not work.')
	 
	% existsProp(prop)
	assert(~NNVariationalAutoencoder.existsProp(NaN), ...
		[BRAPH2.STR ':NNVariationalAutoencoder:' BRAPH2.FAIL_TEST], ...
		'NNVariationalAutoencoder.existsProp(prop) does not work.')
	assert(~nnvae.existsProp(NaN), ...
		[BRAPH2.STR ':NNVariationalAutoencoder:' BRAPH2.FAIL_TEST], ...
		'nnvae.existsProp(prop) does not work.')
	assert(~Element.existsProp(nnvae, NaN), ...
		[BRAPH2.STR ':NNVariationalAutoencoder:' BRAPH2.FAIL_TEST], ...
		'Element.existsProp(nnvae, prop) does not work.')
	assert(~Element.existsProp('NNVariationalAutoencoder', NaN), ...
		[BRAPH2.STR ':NNVariationalAutoencoder:' BRAPH2.FAIL_TEST], ...
		'Element.existsProp(''NNVariationalAutoencoder'', prop) does not work.')
	 
	assert_with_error('NNVariationalAutoencoder.existsProp(NaN)', [BRAPH2.STR ':NNVariationalAutoencoder:' BRAPH2.WRONG_INPUT])
	assert_with_error('varargin{1}.existsProp(NaN)', [BRAPH2.STR ':NNVariationalAutoencoder:' BRAPH2.WRONG_INPUT], nnvae)
	assert_with_error('Element.existsProp(varargin{1}, NaN)', [BRAPH2.STR ':NNVariationalAutoencoder:' BRAPH2.WRONG_INPUT], nnvae)
	assert_with_error('Element.existsProp(''NNVariationalAutoencoder'', NaN)', [BRAPH2.STR ':NNVariationalAutoencoder:' BRAPH2.WRONG_INPUT])
	 
	for prop = 1:1:NNVariationalAutoencoder.getPropNumber()
		assert(NNVariationalAutoencoder.existsProp(prop), ...
			[BRAPH2.STR ':NNVariationalAutoencoder:' BRAPH2.FAIL_TEST], ...
			'NNVariationalAutoencoder.existsProp(prop) does not work.')
		assert(nnvae.existsProp(prop), ...
			[BRAPH2.STR ':NNVariationalAutoencoder:' BRAPH2.FAIL_TEST], ...
			'nnvae.existsProp(prop) does not work.')
		assert(Element.existsProp(nnvae, prop), ...
			[BRAPH2.STR ':NNVariationalAutoencoder:' BRAPH2.FAIL_TEST], ...
			'Element.existsProp(nnvae, prop) does not work.')
		assert(Element.existsProp('NNVariationalAutoencoder', prop), ...
			[BRAPH2.STR ':NNVariationalAutoencoder:' BRAPH2.FAIL_TEST], ...
			'Element.existsProp(''NNVariationalAutoencoder'', prop) does not work.')
	end
	 
	% existsTag(tag)
	assert(~NNVariationalAutoencoder.existsTag(''), ...
		[BRAPH2.STR ':NNVariationalAutoencoder:' BRAPH2.FAIL_TEST], ...
		'NNVariationalAutoencoder.existsTag(tag) does not work.')
	assert(~nnvae.existsTag(''), ...
		[BRAPH2.STR ':NNVariationalAutoencoder:' BRAPH2.FAIL_TEST], ...
		'nnvae.existsTag(tag) does not work.')
	assert(~Element.existsTag(nnvae, ''), ...
		[BRAPH2.STR ':NNVariationalAutoencoder:' BRAPH2.FAIL_TEST], ...
		'Element.existsTag(nnvae, tag) does not work.')
	assert(~Element.existsTag('NNVariationalAutoencoder', ''), ...
		[BRAPH2.STR ':NNVariationalAutoencoder:' BRAPH2.FAIL_TEST], ...
		'Element.existsTag(''NNVariationalAutoencoder'', tag) does not work.')
	 
	assert_with_error('NNVariationalAutoencoder.existsTag('''')', [BRAPH2.STR ':NNVariationalAutoencoder:' BRAPH2.WRONG_INPUT])
	assert_with_error('varargin{1}.existsTag('''')', [BRAPH2.STR ':NNVariationalAutoencoder:' BRAPH2.WRONG_INPUT], nnvae)
	assert_with_error('Element.existsTag(varargin{1}, '''')', [BRAPH2.STR ':NNVariationalAutoencoder:' BRAPH2.WRONG_INPUT], nnvae)
	assert_with_error('Element.existsTag(''NNVariationalAutoencoder'', '''')', [BRAPH2.STR ':NNVariationalAutoencoder:' BRAPH2.WRONG_INPUT])
	 
	for prop = 1:1:NNVariationalAutoencoder.getPropNumber()
		tag = nnvae.getPropTag(prop);
		assert(NNVariationalAutoencoder.existsTag(tag), ...
			[BRAPH2.STR ':NNVariationalAutoencoder:' BRAPH2.FAIL_TEST], ...
			'NNVariationalAutoencoder.existsTag(tag) does not work.')
		assert(nnvae.existsTag(tag), ...
			[BRAPH2.STR ':NNVariationalAutoencoder:' BRAPH2.FAIL_TEST], ...
			'nnvae.existsTag(tag) does not work.')
		assert(Element.existsTag(nnvae, tag), ...
			[BRAPH2.STR ':NNVariationalAutoencoder:' BRAPH2.FAIL_TEST], ...
			'Element.existsTag(nnvae, tga) does not work.')
		assert(Element.existsTag('NNVariationalAutoencoder', tag), ...
			[BRAPH2.STR ':NNVariationalAutoencoder:' BRAPH2.FAIL_TEST], ...
			'Element.existsTag(''NNVariationalAutoencoder'', tag) does not work.')
	end
	 
	% getPropProp(pointer)
	for prop = 1:1:NNVariationalAutoencoder.getPropNumber()
		assert(NNVariationalAutoencoder.getPropProp(prop) == prop, ...
			[BRAPH2.STR ':NNVariationalAutoencoder:' BRAPH2.FAIL_TEST], ...
			'NNVariationalAutoencoder.getPropProp(prop) does not work.')
		assert(nnvae.getPropProp(prop) == prop, ...
			[BRAPH2.STR ':NNVariationalAutoencoder:' BRAPH2.FAIL_TEST], ...
			'nnvae.getPropProp(prop) does not work.')
		assert(Element.getPropProp(nnvae, prop) == prop, ...
			[BRAPH2.STR ':NNVariationalAutoencoder:' BRAPH2.FAIL_TEST], ...
			'Element.getPropProp(nnvae, prop) does not work.')
		assert(Element.getPropProp('NNVariationalAutoencoder', prop) == prop, ...
			[BRAPH2.STR ':NNVariationalAutoencoder:' BRAPH2.FAIL_TEST], ...
			'Element.getPropProp(''NNVariationalAutoencoder'', prop) does not work.')
	 
		tag = nnvae.getPropTag(prop);
		assert(NNVariationalAutoencoder.getPropProp(tag) == prop, ...
			[BRAPH2.STR ':NNVariationalAutoencoder:' BRAPH2.FAIL_TEST], ...
			'NNVariationalAutoencoder.getPropProp(tag) does not work.')
		assert(nnvae.getPropProp(tag) == prop, ...
			[BRAPH2.STR ':NNVariationalAutoencoder:' BRAPH2.FAIL_TEST], ...
			'nnvae.getPropProp(tag) does not work.')
		assert(Element.getPropProp(nnvae, tag) == prop, ...
			[BRAPH2.STR ':NNVariationalAutoencoder:' BRAPH2.FAIL_TEST], ...
			'Element.getPropProp(nnvae, tag) does not work.')
		assert(Element.getPropProp('NNVariationalAutoencoder', prop) == prop, ...
			[BRAPH2.STR ':NNVariationalAutoencoder:' BRAPH2.FAIL_TEST], ...
			'Element.getPropProp(''NNVariationalAutoencoder'', tag) does not work.')
	end
	 
	% getPropTag(pointer)
	for prop = 1:1:NNVariationalAutoencoder.getPropNumber()
		tag = nnvae.getPropTag(prop);
	 
		assert(strcmp(NNVariationalAutoencoder.getPropTag(prop), tag), ...
			[BRAPH2.STR ':NNVariationalAutoencoder:' BRAPH2.FAIL_TEST], ...
			'NNVariationalAutoencoder.getPropTag(prop) does not work.')
		assert(strcmp(nnvae.getPropTag(prop), tag), ...
			[BRAPH2.STR ':NNVariationalAutoencoder:' BRAPH2.FAIL_TEST], ...
			'nnvae.getPropTag(prop) does not work.')
		assert(strcmp(Element.getPropTag(nnvae, prop), tag), ...
			[BRAPH2.STR ':NNVariationalAutoencoder:' BRAPH2.FAIL_TEST], ...
			'Element.getPropTag(nnvae, prop) does not work.')
		assert(strcmp(Element.getPropTag('NNVariationalAutoencoder', prop), tag), ...
			[BRAPH2.STR ':NNVariationalAutoencoder:' BRAPH2.FAIL_TEST], ...
			'Element.getPropTag(''NNVariationalAutoencoder'', prop) does not work.')
	 
		assert(strcmp(NNVariationalAutoencoder.getPropTag(tag), tag), ...
			[BRAPH2.STR ':NNVariationalAutoencoder:' BRAPH2.FAIL_TEST], ...
			'NNVariationalAutoencoder.getPropTag(tag) does not work.')
		assert(strcmp(nnvae.getPropTag(tag), tag), ...
			[BRAPH2.STR ':NNVariationalAutoencoder:' BRAPH2.FAIL_TEST], ...
			'nnvae.getPropTag(tag) does not work.')
		assert(strcmp(Element.getPropTag(nnvae, tag), tag), ...
			[BRAPH2.STR ':NNVariationalAutoencoder:' BRAPH2.FAIL_TEST], ...
			'Element.getPropTag(nnvae, tag) does not work.')
		assert(strcmp(Element.getPropTag('NNVariationalAutoencoder', prop), tag), ...
			[BRAPH2.STR ':NNVariationalAutoencoder:' BRAPH2.FAIL_TEST], ...
			'Element.getPropTag(''NNVariationalAutoencoder'', tag) does not work.')
	end
	 
	% getPropCategory(pointer)
	for prop = 1:1:NNVariationalAutoencoder.getPropNumber()
		tag = nnvae.getPropTag(prop);
	 
		assert(Category.existsCategory(NNVariationalAutoencoder.getPropCategory(prop)), ...
			[BRAPH2.STR ':NNVariationalAutoencoder:' BRAPH2.FAIL_TEST], ...
			'NNVariationalAutoencoder.getPropCategory(prop) does not work.')
		assert(Category.existsCategory(nnvae.getPropCategory(prop)), ...
			[BRAPH2.STR ':NNVariationalAutoencoder:' BRAPH2.FAIL_TEST], ...
			'nnvae.getPropCategory(prop) does not work.')
		assert(Category.existsCategory(Element.getPropCategory(nnvae, prop)), ...
			[BRAPH2.STR ':NNVariationalAutoencoder:' BRAPH2.FAIL_TEST], ...
			'Element.getPropCategory(nnvae, prop) does not work.')
		assert(Category.existsCategory(Element.getPropCategory(nnvae, prop)), ...
			[BRAPH2.STR ':NNVariationalAutoencoder:' BRAPH2.FAIL_TEST], ...
			'Element.getPropCategory(''NNVariationalAutoencoder'', prop) does not work.')
	 
		assert(Category.existsCategory(NNVariationalAutoencoder.getPropCategory(tag)), ...
			[BRAPH2.STR ':NNVariationalAutoencoder:' BRAPH2.FAIL_TEST], ...
			'NNVariationalAutoencoder.getPropCategory(tag) does not work.')
		assert(Category.existsCategory(nnvae.getPropCategory(tag)), ...
			[BRAPH2.STR ':NNVariationalAutoencoder:' BRAPH2.FAIL_TEST], ...
			'nnvae.getPropCategory(tag) does not work.')
		assert(Category.existsCategory(Element.getPropCategory(nnvae, tag)), ...
			[BRAPH2.STR ':NNVariationalAutoencoder:' BRAPH2.FAIL_TEST], ...
			'Element.getPropCategory(nnvae, tag) does not work.')
		assert(Category.existsCategory(Element.getPropCategory(nnvae, tag)), ...
			[BRAPH2.STR ':NNVariationalAutoencoder:' BRAPH2.FAIL_TEST], ...
			'Element.getPropCategory(''NNVariationalAutoencoder'', tag) does not work.')
	end
	 
	% getPropFormat(pointer)
	for prop = 1:1:NNVariationalAutoencoder.getPropNumber()
		tag = nnvae.getPropTag(prop);
	 
		assert(Format.existsFormat(NNVariationalAutoencoder.getPropFormat(prop)), ...
			[BRAPH2.STR ':NNVariationalAutoencoder:' BRAPH2.FAIL_TEST], ...
			'NNVariationalAutoencoder.getPropFormat(prop) does not work.')
		assert(Format.existsFormat(nnvae.getPropFormat(prop)), ...
			[BRAPH2.STR ':NNVariationalAutoencoder:' BRAPH2.FAIL_TEST], ...
			'nnvae.getPropFormat(prop) does not work.')
		assert(Format.existsFormat(Element.getPropFormat(nnvae, prop)), ...
			[BRAPH2.STR ':NNVariationalAutoencoder:' BRAPH2.FAIL_TEST], ...
			'Element.getPropFormat(nnvae, prop) does not work.')
		assert(Format.existsFormat(Element.getPropFormat(nnvae, prop)), ...
			[BRAPH2.STR ':NNVariationalAutoencoder:' BRAPH2.FAIL_TEST], ...
			'Element.getPropFormat(''NNVariationalAutoencoder'', prop) does not work.')
	 
		assert(Format.existsFormat(NNVariationalAutoencoder.getPropFormat(tag)), ...
			[BRAPH2.STR ':NNVariationalAutoencoder:' BRAPH2.FAIL_TEST], ...
			'NNVariationalAutoencoder.getPropFormat(tag) does not work.')
		assert(Format.existsFormat(nnvae.getPropFormat(tag)), ...
			[BRAPH2.STR ':NNVariationalAutoencoder:' BRAPH2.FAIL_TEST], ...
			'nnvae.getPropFormat(tag) does not work.')
		assert(Format.existsFormat(Element.getPropFormat(nnvae, tag)), ...
			[BRAPH2.STR ':NNVariationalAutoencoder:' BRAPH2.FAIL_TEST], ...
			'Element.getPropFormat(nnvae, tag) does not work.')
		assert(Format.existsFormat(Element.getPropFormat(nnvae, tag)), ...
			[BRAPH2.STR ':NNVariationalAutoencoder:' BRAPH2.FAIL_TEST], ...
			'Element.getPropFormat(''NNVariationalAutoencoder'', tag) does not work.')
	end
	 
	% getPropDescription(pointer)
	for prop = 1:1:NNVariationalAutoencoder.getPropNumber()
		tag = nnvae.getPropTag(prop);
	 
		assert(ischar(NNVariationalAutoencoder.getPropDescription(prop)), ...
			[BRAPH2.STR ':NNVariationalAutoencoder:' BRAPH2.FAIL_TEST], ...
			'NNVariationalAutoencoder.getPropDescription(prop) does not work.')
		assert(ischar(nnvae.getPropDescription(prop)), ...
			[BRAPH2.STR ':NNVariationalAutoencoder:' BRAPH2.FAIL_TEST], ...
			'nnvae.getPropDescription(prop) does not work.')
		assert(ischar(Element.getPropDescription(nnvae, prop)), ...
			[BRAPH2.STR ':NNVariationalAutoencoder:' BRAPH2.FAIL_TEST], ...
			'Element.getPropDescription(nnvae, prop) does not work.')
		assert(ischar(Element.getPropDescription(nnvae, prop)), ...
			[BRAPH2.STR ':NNVariationalAutoencoder:' BRAPH2.FAIL_TEST], ...
			'Element.getPropDescription(''NNVariationalAutoencoder'', prop) does not work.')
	 
		assert(ischar(NNVariationalAutoencoder.getPropDescription(tag)), ...
			[BRAPH2.STR ':NNVariationalAutoencoder:' BRAPH2.FAIL_TEST], ...
			'NNVariationalAutoencoder.getPropDescription(tag) does not work.')
		assert(ischar(nnvae.getPropDescription(tag)), ...
			[BRAPH2.STR ':NNVariationalAutoencoder:' BRAPH2.FAIL_TEST], ...
			'nnvae.getPropDescription(tag) does not work.')
		assert(ischar(Element.getPropDescription(nnvae, tag)), ...
			[BRAPH2.STR ':NNVariationalAutoencoder:' BRAPH2.FAIL_TEST], ...
			'Element.getPropDescription(nnvae, tag) does not work.')
		assert(ischar(Element.getPropDescription(nnvae, tag)), ...
			[BRAPH2.STR ':NNVariationalAutoencoder:' BRAPH2.FAIL_TEST], ...
			'Element.getPropDescription(''NNVariationalAutoencoder'', tag) does not work.')
	end
	 
	% getPropSettings(pointer)
	for prop = 1:1:NNVariationalAutoencoder.getPropNumber()
		tag = nnvae.getPropTag(prop);
	 
		settings = NNVariationalAutoencoder.getPropSettings(prop);
		settings = nnvae.getPropSettings(prop);
		settings = Element.getPropSettings(nnvae, prop);
		settings = Element.getPropSettings('NNVariationalAutoencoder', prop);
	 
		settings = NNVariationalAutoencoder.getPropSettings(tag);
		settings = nnvae.getPropSettings(tag);
		settings = Element.getPropSettings(nnvae, tag);
		settings = Element.getPropSettings('NNVariationalAutoencoder', tag);
	end
	 
	% getPropDefault(pointer)
	for prop = 1:1:NNVariationalAutoencoder.getPropNumber()
		tag = nnvae.getPropTag(prop);
	 
		default = NNVariationalAutoencoder.getPropDefault(prop);
		default = nnvae.getPropDefault(prop);
		default = Element.getPropDefault(nnvae, prop);
		default = Element.getPropDefault('NNVariationalAutoencoder', prop);
	 
		default = NNVariationalAutoencoder.getPropDefault(tag);
		default = nnvae.getPropDefault(tag);
		default = Element.getPropDefault(nnvae, tag);
		default = Element.getPropDefault('NNVariationalAutoencoder', tag);
	end
	 
	% getPropDefaultConditioned(pointer)
	for prop = 1:1:NNVariationalAutoencoder.getPropNumber()
		tag = nnvae.getPropTag(prop);
	 
		conditioned_default = NNVariationalAutoencoder.getPropDefaultConditioned(prop);
		conditioned_default = nnvae.getPropDefaultConditioned(prop);
		conditioned_default = Element.getPropDefaultConditioned(nnvae, prop);
		conditioned_default = Element.getPropDefaultConditioned('NNVariationalAutoencoder', prop);
	 
		conditioned_default = NNVariationalAutoencoder.getPropDefaultConditioned(tag);
		conditioned_default = nnvae.getPropDefaultConditioned(tag);
		conditioned_default = Element.getPropDefaultConditioned(nnvae, tag);
		conditioned_default = Element.getPropDefaultConditioned('NNVariationalAutoencoder', tag);
	end
	 
	% checkProp(pointer, value)
	for prop = 1:1:NNVariationalAutoencoder.getPropNumber()
		tag = nnvae.getPropTag(prop);
	 
		assert(~NNVariationalAutoencoder.checkProp(prop, {'probably wrong value', 1}), ...
			[BRAPH2.STR ':NNVariationalAutoencoder:' BRAPH2.FAIL_TEST], ...
			'NNVariationalAutoencoder.checkProp(prop, value) does not work.')
		assert(~nnvae.checkProp(prop, {'probably wrong value', 1}), ...
			[BRAPH2.STR ':NNVariationalAutoencoder:' BRAPH2.FAIL_TEST], ...
			'nnvae.checkProp(prop, value) does not work.')
		assert(~Element.checkProp(nnvae, prop, {'probably wrong value', 1}), ...
			[BRAPH2.STR ':NNVariationalAutoencoder:' BRAPH2.FAIL_TEST], ...
			'Element.checkProp(nnvae, prop, value) does not work.')
		assert(~Element.checkProp('NNVariationalAutoencoder', prop, {'probably wrong value', 1}), ...
			[BRAPH2.STR ':NNVariationalAutoencoder:' BRAPH2.FAIL_TEST], ...
			'Element.checkProp(''NNVariationalAutoencoder'', prop, value) does not work.')
	 
		assert_with_error('NNVariationalAutoencoder.checkProp(varargin{1}, {''probably wrong value'', 1})', [BRAPH2.STR ':NNVariationalAutoencoder:' BRAPH2.WRONG_INPUT], prop)
		assert_with_error('varargin{2}.checkProp(varargin{1}, {''probably wrong value'', 1})', [BRAPH2.STR ':NNVariationalAutoencoder:' BRAPH2.WRONG_INPUT], prop, nnvae)
		assert_with_error('Element.checkProp(varargin{2}, varargin{1}, {''probably wrong value'', 1})', [BRAPH2.STR ':NNVariationalAutoencoder:' BRAPH2.WRONG_INPUT], prop, nnvae)
		assert_with_error('Element.checkProp(''NNVariationalAutoencoder'', varargin{1}, {''probably wrong value'', 1})', [BRAPH2.STR ':NNVariationalAutoencoder:' BRAPH2.WRONG_INPUT], prop)
	 
		assert(~NNVariationalAutoencoder.checkProp(tag, {'probably wrong value', 1}), ...
			[BRAPH2.STR ':NNVariationalAutoencoder:' BRAPH2.FAIL_TEST], ...
			'NNVariationalAutoencoder.checkProp(tag, value) does not work.')
		assert(~nnvae.checkProp(tag, {'probably wrong value', 1}), ...
			[BRAPH2.STR ':NNVariationalAutoencoder:' BRAPH2.FAIL_TEST], ...
			'nnvae.checkProp(tag, value) does not work.')
		assert(~Element.checkProp(nnvae, tag, {'probably wrong value', 1}), ...
			[BRAPH2.STR ':NNVariationalAutoencoder:' BRAPH2.FAIL_TEST], ...
			'Element.checkProp(nnvae, tag, value) does not work.')
		assert(~Element.checkProp('NNVariationalAutoencoder', tag, {'probably wrong value', 1}), ...
			[BRAPH2.STR ':NNVariationalAutoencoder:' BRAPH2.FAIL_TEST], ...
			'Element.checkProp(''NNVariationalAutoencoder'', tag, value) does not work.')
	 
		assert_with_error('NNVariationalAutoencoder.checkProp(varargin{1}, {''probably wrong value'', 1})', [BRAPH2.STR ':NNVariationalAutoencoder:' BRAPH2.WRONG_INPUT], tag)
		assert_with_error('varargin{2}.checkProp(varargin{1}, {''probably wrong value'', 1})', [BRAPH2.STR ':NNVariationalAutoencoder:' BRAPH2.WRONG_INPUT], tag, nnvae)
		assert_with_error('Element.checkProp(varargin{2}, varargin{1}, {''probably wrong value'', 1})', [BRAPH2.STR ':NNVariationalAutoencoder:' BRAPH2.WRONG_INPUT], tag, nnvae)
		assert_with_error('Element.checkProp(''NNVariationalAutoencoder'', varargin{1}, {''probably wrong value'', 1})', [BRAPH2.STR ':NNVariationalAutoencoder:' BRAPH2.WRONG_INPUT], tag)
	 
		assert(NNVariationalAutoencoder.checkProp(prop, Element.getPropDefaultConditioned(NNVariationalAutoencoder, prop)), ...
			[BRAPH2.STR ':NNVariationalAutoencoder:' BRAPH2.FAIL_TEST], ...
			'NNVariationalAutoencoder.checkProp(prop, <conditioned default value>) does not work.')
		assert(nnvae.checkProp(prop, Element.getPropDefaultConditioned(NNVariationalAutoencoder, prop)), ...
			[BRAPH2.STR ':NNVariationalAutoencoder:' BRAPH2.FAIL_TEST], ...
			'nnvae.checkProp(prop, <conditioned default value>) does not work.')
		assert(Element.checkProp(nnvae, prop, Element.getPropDefaultConditioned(NNVariationalAutoencoder, prop)), ...
			[BRAPH2.STR ':NNVariationalAutoencoder:' BRAPH2.FAIL_TEST], ...
			'Element.checkProp(nnvae, prop, <conditioned default value>) does not work.')
		assert(Element.checkProp('NNVariationalAutoencoder', prop, Element.getPropDefaultConditioned(NNVariationalAutoencoder, prop)), ...
			[BRAPH2.STR ':NNVariationalAutoencoder:' BRAPH2.FAIL_TEST], ...
			'Element.checkProp(''NNVariationalAutoencoder'', prop, <conditioned default value>) does not work.')
	 
		assert(NNVariationalAutoencoder.checkProp(tag, Element.getPropDefaultConditioned(NNVariationalAutoencoder, prop)), ...
			[BRAPH2.STR ':NNVariationalAutoencoder:' BRAPH2.FAIL_TEST], ...
			'NNVariationalAutoencoder.checkProp(tag, <conditioned default value>) does not work.')
		assert(nnvae.checkProp(tag, Element.getPropDefaultConditioned(NNVariationalAutoencoder, prop)), ...
			[BRAPH2.STR ':NNVariationalAutoencoder:' BRAPH2.FAIL_TEST], ...
			'nnvae.checkProp(tag, <conditioned default value>) does not work.')
		assert(Element.checkProp(nnvae, tag, Element.getPropDefaultConditioned(NNVariationalAutoencoder, prop)), ...
			[BRAPH2.STR ':NNVariationalAutoencoder:' BRAPH2.FAIL_TEST], ...
			'Element.checkProp(nnvae, tag, <conditioned default value>) does not work.')
		assert(Element.checkProp('NNVariationalAutoencoder', tag, Element.getPropDefaultConditioned(NNVariationalAutoencoder, prop)), ...
			[BRAPH2.STR ':NNVariationalAutoencoder:' BRAPH2.FAIL_TEST], ...
			'Element.checkProp(''NNVariationalAutoencoder'', tag, <conditioned default value>) does not work.')
	 
	end
	 
end

%% Test 2: Instantiation - defaults
if rand() >= (1 - .01) * BRAPH2TEST.RANDOM
	nnvae = NNVariationalAutoencoder( ...
		NNVariationalAutoencoder.ELCLASS, NNVariationalAutoencoder.getNoValue(), ...
		NNVariationalAutoencoder.NAME, NNVariationalAutoencoder.getNoValue(), ...
		NNVariationalAutoencoder.DESCRIPTION, NNVariationalAutoencoder.getNoValue(), ...
		NNVariationalAutoencoder.TEMPLATE, NNVariationalAutoencoder.getPropDefault(NNVariationalAutoencoder.TEMPLATE), ...
		NNVariationalAutoencoder.ID, NNVariationalAutoencoder.getPropDefault(NNVariationalAutoencoder.ID), ...
		NNVariationalAutoencoder.LABEL, NNVariationalAutoencoder.getPropDefault(NNVariationalAutoencoder.LABEL), ...
		NNVariationalAutoencoder.NOTES, NNVariationalAutoencoder.getPropDefault(NNVariationalAutoencoder.NOTES), ...
		NNVariationalAutoencoder.TOSTRING, NNVariationalAutoencoder.getNoValue(), ...
		NNVariationalAutoencoder.D, NNVariationalAutoencoder.getPropDefault(NNVariationalAutoencoder.D), ...
		NNVariationalAutoencoder.DP_CLASSES, NNVariationalAutoencoder.getPropDefault(NNVariationalAutoencoder.DP_CLASSES), ...
		NNVariationalAutoencoder.EPOCHS, NNVariationalAutoencoder.getPropDefault(NNVariationalAutoencoder.EPOCHS), ...
		NNVariationalAutoencoder.BATCH, NNVariationalAutoencoder.getPropDefault(NNVariationalAutoencoder.BATCH), ...
		NNVariationalAutoencoder.SHUFFLE, NNVariationalAutoencoder.getPropDefault(NNVariationalAutoencoder.SHUFFLE), ...
		NNVariationalAutoencoder.SOLVER, NNVariationalAutoencoder.getPropDefault(NNVariationalAutoencoder.SOLVER), ...
		NNVariationalAutoencoder.MODEL, NNVariationalAutoencoder.getNoValue(), ...
		NNVariationalAutoencoder.INPUTS, NNVariationalAutoencoder.getNoValue(), ...
		NNVariationalAutoencoder.TARGETS, NNVariationalAutoencoder.getNoValue(), ...
		NNVariationalAutoencoder.TRAIN, NNVariationalAutoencoder.getNoValue(), ...
		NNVariationalAutoencoder.VERBOSE, NNVariationalAutoencoder.getPropDefault(NNVariationalAutoencoder.VERBOSE), ...
		NNVariationalAutoencoder.PLOT_TRAINING, NNVariationalAutoencoder.getPropDefault(NNVariationalAutoencoder.PLOT_TRAINING), ...
		NNVariationalAutoencoder.PREDICT, NNVariationalAutoencoder.getNoValue(), ...
		NNVariationalAutoencoder.LEARN_RATE, NNVariationalAutoencoder.getPropDefault(NNVariationalAutoencoder.LEARN_RATE), ...
		NNVariationalAutoencoder.NUM_LATENT_REP, NNVariationalAutoencoder.getPropDefault(NNVariationalAutoencoder.NUM_LATENT_REP), ...
		NNVariationalAutoencoder.SIZE_INPUT, NNVariationalAutoencoder.getPropDefault(NNVariationalAutoencoder.SIZE_INPUT), ...
		NNVariationalAutoencoder.ITERATION_DIM, NNVariationalAutoencoder.getPropDefault(NNVariationalAutoencoder.ITERATION_DIM), ...
		NNVariationalAutoencoder.NUM_MBQ_OUTPUT, NNVariationalAutoencoder.getPropDefault(NNVariationalAutoencoder.NUM_MBQ_OUTPUT), ...
		NNVariationalAutoencoder.MINIBATCH_FORMAT_INPUT, NNVariationalAutoencoder.getNoValue(), ...
		NNVariationalAutoencoder.MINIBATCH_FORMAT_TARGET, NNVariationalAutoencoder.getNoValue(), ...
		NNVariationalAutoencoder.ENCODER, NNVariationalAutoencoder.getPropDefault(NNVariationalAutoencoder.ENCODER), ...
		NNVariationalAutoencoder.DECODER, NNVariationalAutoencoder.getPropDefault(NNVariationalAutoencoder.DECODER), ...
		NNVariationalAutoencoder.MBQ, NNVariationalAutoencoder.getNoValue(), ...
		NNVariationalAutoencoder.LOSS_FN, NNVariationalAutoencoder.getNoValue() ...
		);
	 
	for prop = 1:1:NNVariationalAutoencoder.getPropNumber()
	 
		% excluded props
		if any(prop == [])
			continue
		end
	 
		TAG = upper(NNVariationalAutoencoder.getPropTag(prop));
		switch NNVariationalAutoencoder.getPropCategory(prop)
			case {Category.CONSTANT, Category.RESULT, Category.QUERY}
				% getr
				assert( ...
					nnvae.getr(prop) == NNVariationalAutoencoder.getNoValue(), ...
					[BRAPH2.STR ':NNVariationalAutoencoder:' BRAPH2.FAIL_TEST], ...
					['Being a ' NNVariationalAutoencoder.getCategoryName(NNVariationalAutoencoder.getPropCategory(prop)) ', NNVariationalAutoencoder.getr(' int2str(prop) ') must be inizialized to NoValue(). ' ...
					'Or there could be an error in NNVariationalAutoencoder.getr(' int2str(prop) ').'] ...
					)
				assert( ...
					nnvae.getr(TAG) == NNVariationalAutoencoder.getNoValue(), ...
					[BRAPH2.STR ':NNVariationalAutoencoder:' BRAPH2.FAIL_TEST], ...
					['Being a ' NNVariationalAutoencoder.getCategoryName(NNVariationalAutoencoder.getPropCategory(prop)) ', NNVariationalAutoencoder.getr(' TAG ') must be inizialized to NoValue(). ' ...
					'Or there could be an error in NNVariationalAutoencoder.getr(' TAG ').'] ...
					)
				% get
				assert( ...
					~isa(nnvae.get(prop), 'NoValue'), ...
					[BRAPH2.STR ':NNVariationalAutoencoder:' BRAPH2.FAIL_TEST], ...
					['NNVariationalAutoencoder.get(' int2str(prop) ') must NOT be a NoValue, because it should have been calculated.'] ...
					)
				if isempty(nnvae.getPropSettings(prop))
					assert( ...
						nnvae.checkFormat(nnvae.getPropFormat(prop), nnvae.get(prop)), ...
						[BRAPH2.STR ':NNVariationalAutoencoder:' BRAPH2.FAIL_TEST], ...
						['NNVariationalAutoencoder.get(' int2str(prop) ') returns a value with the wrong format.'] ...
						)
				else
					assert( ...
						nnvae.checkFormat(nnvae.getPropFormat(prop), nnvae.get(prop), nnvae.getPropSettings(prop)), ...
						[BRAPH2.STR ':NNVariationalAutoencoder:' BRAPH2.FAIL_TEST], ...
						['NNVariationalAutoencoder.get(' int2str(prop) ') returns a value with the wrong format.'] ...
						)
				end
			case Category.EVANESCENT
				% getr
				assert( ...
					nnvae.getr(prop) == NNVariationalAutoencoder.getNoValue(), ...
					[BRAPH2.STR ':NNVariationalAutoencoder:' BRAPH2.FAIL_TEST], ...
					['Being a ' NNVariationalAutoencoder.getCategoryName(NNVariationalAutoencoder.getPropCategory(prop)) ', NNVariationalAutoencoder.getr(' int2str(prop) ') must be inizialized to NoValue(). ' ...
					'Or there could be an error in NNVariationalAutoencoder.getr(' int2str(prop) ').'] ...
					)
				assert( ...
					nnvae.getr(TAG) == NNVariationalAutoencoder.getNoValue(), ...
					[BRAPH2.STR ':NNVariationalAutoencoder:' BRAPH2.FAIL_TEST], ...
					['Being a ' NNVariationalAutoencoder.getCategoryName(NNVariationalAutoencoder.getPropCategory(prop)) ', NNVariationalAutoencoder.getr(' TAG ') must be inizialized to NoValue(). ' ...
					'Or there could be an error in NNVariationalAutoencoder.getr(' TAG ').'] ...
					)
				% get
				warning_backup = warning('off', [BRAPH2.STR ':NNVariationalAutoencoder']);
				assert( ...
					~isa(nnvae.get(prop), 'NoValue'), ...
					[BRAPH2.STR ':NNVariationalAutoencoder:' BRAPH2.FAIL_TEST], ...
					['NNVariationalAutoencoder.get(' int2str(prop) ') must NOT be a NoValue, because it should have been calculated.'] ...
					)
				if isempty(nnvae.getPropSettings(prop))
					assert( ...
						nnvae.checkFormat(nnvae.getPropFormat(prop), nnvae.get(prop)), ...
						[BRAPH2.STR ':NNVariationalAutoencoder:' BRAPH2.FAIL_TEST], ...
						['NNVariationalAutoencoder.get(' int2str(prop) ') returns a value with the wrong format.'] ...
						)
				else
					assert( ...
						nnvae.checkFormat(nnvae.getPropFormat(prop), nnvae.get(prop), nnvae.getPropSettings(prop)), ...
						[BRAPH2.STR ':NNVariationalAutoencoder:' BRAPH2.FAIL_TEST], ...
						['NNVariationalAutoencoder.get(' int2str(prop) ') returns a value with the wrong format.'] ...
						)
				end
				warning(warning_backup)
			otherwise % case {Category.METADATA, Category.PARAMETER, Category.DATA, Category.FIGURE, Category.GUI}
				assert( ...
					isequal(nnvae.getr(prop), NNVariationalAutoencoder.getPropDefaultConditioned(prop)), ...
					[BRAPH2.STR ':NNVariationalAutoencoder:' BRAPH2.FAIL_TEST], ...
					['NNVariationalAutoencoder.getr(' int2str(prop) ') must be inizialized to its default value ' ...
					'given by NNVariationalAutoencoder.getPropDefaultConditioned(' int2str(prop) '). ' ...
					'Or there could be an error in NNVariationalAutoencoder.getr(' int2str(prop) ').'] ...
					)
				assert( ...
					isequal(nnvae.getr(TAG), NNVariationalAutoencoder.getPropDefaultConditioned(prop)), ...
					[BRAPH2.STR ':NNVariationalAutoencoder:' BRAPH2.FAIL_TEST], ...
					['NNVariationalAutoencoder.getr(' TAG ') must be inizialized to its default value ' ...
					'given by NNVariationalAutoencoder.getPropDefaultConditioned(' int2str(prop) '). ' ...
					'Or there could be an error in NNVariationalAutoencoder.getr(' TAG ').'] ...
					)
		end
	end
end

%% Test 3: Memorize
if rand() >= (1 - .01) * BRAPH2TEST.RANDOM
	nnvae = NNVariationalAutoencoder( ...
		NNVariationalAutoencoder.ELCLASS, NNVariationalAutoencoder.getNoValue(), ...
		NNVariationalAutoencoder.NAME, NNVariationalAutoencoder.getNoValue(), ...
		NNVariationalAutoencoder.DESCRIPTION, NNVariationalAutoencoder.getNoValue(), ...
		NNVariationalAutoencoder.TEMPLATE, NNVariationalAutoencoder.getPropDefault(NNVariationalAutoencoder.TEMPLATE), ...
		NNVariationalAutoencoder.ID, NNVariationalAutoencoder.getPropDefault(NNVariationalAutoencoder.ID), ...
		NNVariationalAutoencoder.LABEL, NNVariationalAutoencoder.getPropDefault(NNVariationalAutoencoder.LABEL), ...
		NNVariationalAutoencoder.NOTES, NNVariationalAutoencoder.getPropDefault(NNVariationalAutoencoder.NOTES), ...
		NNVariationalAutoencoder.TOSTRING, NNVariationalAutoencoder.getNoValue(), ...
		NNVariationalAutoencoder.D, NNVariationalAutoencoder.getPropDefault(NNVariationalAutoencoder.D), ...
		NNVariationalAutoencoder.DP_CLASSES, NNVariationalAutoencoder.getPropDefault(NNVariationalAutoencoder.DP_CLASSES), ...
		NNVariationalAutoencoder.EPOCHS, NNVariationalAutoencoder.getPropDefault(NNVariationalAutoencoder.EPOCHS), ...
		NNVariationalAutoencoder.BATCH, NNVariationalAutoencoder.getPropDefault(NNVariationalAutoencoder.BATCH), ...
		NNVariationalAutoencoder.SHUFFLE, NNVariationalAutoencoder.getPropDefault(NNVariationalAutoencoder.SHUFFLE), ...
		NNVariationalAutoencoder.SOLVER, NNVariationalAutoencoder.getPropDefault(NNVariationalAutoencoder.SOLVER), ...
		NNVariationalAutoencoder.MODEL, NNVariationalAutoencoder.getNoValue(), ...
		NNVariationalAutoencoder.INPUTS, NNVariationalAutoencoder.getNoValue(), ...
		NNVariationalAutoencoder.TARGETS, NNVariationalAutoencoder.getNoValue(), ...
		NNVariationalAutoencoder.TRAIN, NNVariationalAutoencoder.getNoValue(), ...
		NNVariationalAutoencoder.VERBOSE, NNVariationalAutoencoder.getPropDefault(NNVariationalAutoencoder.VERBOSE), ...
		NNVariationalAutoencoder.PLOT_TRAINING, NNVariationalAutoencoder.getPropDefault(NNVariationalAutoencoder.PLOT_TRAINING), ...
		NNVariationalAutoencoder.PREDICT, NNVariationalAutoencoder.getNoValue(), ...
		NNVariationalAutoencoder.LEARN_RATE, NNVariationalAutoencoder.getPropDefault(NNVariationalAutoencoder.LEARN_RATE), ...
		NNVariationalAutoencoder.NUM_LATENT_REP, NNVariationalAutoencoder.getPropDefault(NNVariationalAutoencoder.NUM_LATENT_REP), ...
		NNVariationalAutoencoder.SIZE_INPUT, NNVariationalAutoencoder.getPropDefault(NNVariationalAutoencoder.SIZE_INPUT), ...
		NNVariationalAutoencoder.ITERATION_DIM, NNVariationalAutoencoder.getPropDefault(NNVariationalAutoencoder.ITERATION_DIM), ...
		NNVariationalAutoencoder.NUM_MBQ_OUTPUT, NNVariationalAutoencoder.getPropDefault(NNVariationalAutoencoder.NUM_MBQ_OUTPUT), ...
		NNVariationalAutoencoder.MINIBATCH_FORMAT_INPUT, NNVariationalAutoencoder.getNoValue(), ...
		NNVariationalAutoencoder.MINIBATCH_FORMAT_TARGET, NNVariationalAutoencoder.getNoValue(), ...
		NNVariationalAutoencoder.ENCODER, NNVariationalAutoencoder.getPropDefault(NNVariationalAutoencoder.ENCODER), ...
		NNVariationalAutoencoder.DECODER, NNVariationalAutoencoder.getPropDefault(NNVariationalAutoencoder.DECODER), ...
		NNVariationalAutoencoder.MBQ, NNVariationalAutoencoder.getNoValue(), ...
		NNVariationalAutoencoder.LOSS_FN, NNVariationalAutoencoder.getNoValue() ...
		);
	 
	for prop = 1:1:NNVariationalAutoencoder.getPropNumber()
	 
		% excluded props
		if any(prop == [])
			continue
		end
	 
		TAG = upper(NNVariationalAutoencoder.getPropTag(prop));
		switch NNVariationalAutoencoder.getPropCategory(prop)
			case Category.RESULT
				assert( ...
					~isa(nnvae.get(prop), 'NoValue'), ...
					[BRAPH2.STR ':NNVariationalAutoencoder:' BRAPH2.FAIL_TEST], ...
					['NNVariationalAutoencoder.get(' int2str(prop) ') must NOT be a NoValue, because it should have been calculated.'] ...
					)
				assert( ...
					isa(nnvae.getr(prop), 'NoValue'), ...
					[BRAPH2.STR ':NNVariationalAutoencoder:' BRAPH2.FAIL_TEST], ...
					['NNVariationalAutoencoder.getr(' int2str(prop) ') must be a NoValue, because it should NOT have been memorized.'] ...
					)
				assert( ...
					~isa(nnvae.memorize(prop), 'NoValue'), ...
					[BRAPH2.STR ':NNVariationalAutoencoder:' BRAPH2.FAIL_TEST], ...
					['NNVariationalAutoencoder.memorize(' int2str(prop) ') must NOT be a NoValue, because it should have been calculated.'] ...
					)
				assert( ...
					~isa(nnvae.getr(prop), 'NoValue'), ...
					[BRAPH2.STR ':NNVariationalAutoencoder:' BRAPH2.FAIL_TEST], ...
					['NNVariationalAutoencoder.getr(' int2str(prop) ') must NOT be a NoValue, because it should have been memorized.'] ...
					)
				assert( ...
					nnvae.checkFormat(nnvae.getPropFormat(prop), nnvae.getr(prop),nnvae.getPropSettings(prop)), ...
					[BRAPH2.STR ':NNVariationalAutoencoder:' BRAPH2.FAIL_TEST], ...
					['NNVariationalAutoencoder.getr(' int2str(prop) ') returns a value with the wrong format.'] ...
					)
			case Category.QUERY
	% 			warning_backup = warning('off', [BRAPH2.STR ':NNVariationalAutoencoder']);
				assert( ...
					~isa(nnvae.get(prop), 'NoValue'), ...
					[BRAPH2.STR ':NNVariationalAutoencoder:' BRAPH2.FAIL_TEST], ...
					['NNVariationalAutoencoder.get(' int2str(prop) ') must NOT be a NoValue, because it should have been calculated.'] ...
					)
				assert( ...
					isa(nnvae.getr(prop), 'NoValue'), ...
					[BRAPH2.STR ':NNVariationalAutoencoder:' BRAPH2.FAIL_TEST], ...
					['NNVariationalAutoencoder.getr(' int2str(prop) ') must be a NoValue, because it should NOT have been memorized.'] ...
					)
	% following tests excluded because properties QUERY should not be memorized
	% 			warning_backup = warning('off', [BRAPH2.STR ':NNVariationalAutoencoder']);
	% 			assert( ...
	% 				~isa(nnvae.memorize(prop), 'NoValue'), ...
	% 				[BRAPH2.STR ':NNVariationalAutoencoder:' BRAPH2.FAIL_TEST], ...
	% 				['NNVariationalAutoencoder.memorize(' int2str(prop) ') must NOT be a NoValue, because it should have been calculated.'] ...
	% 				)
	% 			warning(warning_backup)
	% 			assert( ...
	% 				~isa(nnvae.getr(prop), 'NoValue'), ...
	% 				[BRAPH2.STR ':NNVariationalAutoencoder:' BRAPH2.FAIL_TEST], ...
	% 				['NNVariationalAutoencoder.getr(' int2str(prop) ') must NOT be a NoValue, because it should have been memorized.'] ...
	% 				)
	% 			assert( ...
	% 				nnvae.checkFormat(nnvae.getPropFormat(prop), nnvae.getr(prop),nnvae.getPropSettings(prop)), ...
	% 				[BRAPH2.STR ':NNVariationalAutoencoder:' BRAPH2.FAIL_TEST], ...
	% 				['NNVariationalAutoencoder.getr(' int2str(prop) ') returns a value with the wrong format.'] ...
	% 				)
	% 			warning(warning_backup)
			case Category.EVANESCENT
				warning_backup = warning('off', [BRAPH2.STR ':NNVariationalAutoencoder']);
				assert( ...
					~isa(nnvae.get(prop), 'NoValue'), ...
					[BRAPH2.STR ':NNVariationalAutoencoder:' BRAPH2.FAIL_TEST], ...
					['NNVariationalAutoencoder.get(' int2str(prop) ') must NOT be a NoValue, because it should have been calculated.'] ...
					)
				warning(warning_backup)
				assert( ...
					isa(nnvae.getr(prop), 'NoValue'), ...
					[BRAPH2.STR ':NNVariationalAutoencoder:' BRAPH2.FAIL_TEST], ...
					['NNVariationalAutoencoder.getr(' int2str(prop) ') must be a NoValue, because it should NOT have been memorized.'] ...
					)
				assert( ...
					~isa(nnvae.memorize(prop), 'NoValue'), ...
					[BRAPH2.STR ':NNVariationalAutoencoder:' BRAPH2.FAIL_TEST], ...
					['NNVariationalAutoencoder.memorize(' int2str(prop) ') must NOT be a NoValue, because it should have been calculated.'] ...
					)
				assert( ...
					~isa(nnvae.getr(prop), 'NoValue'), ...
					[BRAPH2.STR ':NNVariationalAutoencoder:' BRAPH2.FAIL_TEST], ...
					['NNVariationalAutoencoder.getr(' int2str(prop) ') must NOT be a NoValue, because it should have been memorized.'] ...
					)
				assert( ...
					nnvae.checkFormat(nnvae.getPropFormat(prop), nnvae.getr(prop),nnvae.getPropSettings(prop)), ...
					[BRAPH2.STR ':NNVariationalAutoencoder:' BRAPH2.FAIL_TEST], ...
					['NNVariationalAutoencoder.getr(' int2str(prop) ') returns a value with the wrong format.'] ...
					)
				if nnvae.getPropFormat(prop) == Format.HANDLE
					warning_backup = warning('off', 'BRAPH2:NNVariationalAutoencoder');
					delete(ancestor(nnvae.get(prop), 'figure'))
					warning(warning_backup)
				end
		end
	end
	 
	if ~isempty(NNVariationalAutoencoder.getProps(Category.RESULT))
		for prop = 1:1:NNVariationalAutoencoder.getPropNumber()
	 
			% excluded props
			if any(prop == [])
				continue
			end
	 
			switch NNVariationalAutoencoder.getPropCategory(prop)
				case {Category.PARAMETER, Category.DATA}
					assert( ...
						nnvae.isLocked(prop), ...
						[BRAPH2.STR ':NNVariationalAutoencoder:' BRAPH2.FAIL_TEST], ...
						['NNVariationalAutoencoder.isLocked(' int2str(prop) ') must be locked because a result has been calculated.'] ...
						)
				otherwise
					assert( ...
						~nnvae.isLocked(prop), ...
						[BRAPH2.STR ':NNVariationalAutoencoder:' BRAPH2.FAIL_TEST], ...
						['NNVariationalAutoencoder.isLocked(' int2str(prop) ') must NOT be locked even though a result has been calculated.'] ...
						)
			end
		end
	end
end

%% Test 4: Lock 1
if rand() >= (1 - .01) * BRAPH2TEST.RANDOM
	nnvae = NNVariationalAutoencoder();
	 
	for prop = 1:1:NNVariationalAutoencoder.getPropNumber()
		TAG = upper(NNVariationalAutoencoder.getPropTag(prop));
		assert( ...
			~nnvae.isLocked(prop), ...
			[BRAPH2.STR ':NNVariationalAutoencoder:' BRAPH2.FAIL_TEST], ...
			['NNVariationalAutoencoder.isLocked(' int2str(prop) ') must NOT be locked when it is instantiated.'] ...
			)
		assert( ...
			~nnvae.isLocked(TAG), ...
			[BRAPH2.STR ':NNVariationalAutoencoder:' BRAPH2.FAIL_TEST], ...
			['NNVariationalAutoencoder.isLocked(' TAG ') must NOT be locked when it is instantiated.'] ...
			)
	end
	 
	nnvae.lock()
	 
	for prop = 1:1:NNVariationalAutoencoder.getPropNumber()
		switch NNVariationalAutoencoder.getPropCategory(prop)
			case {Category.PARAMETER, Category.DATA}
				assert( ...
					nnvae.isLocked(prop), ...
					[BRAPH2.STR ':NNVariationalAutoencoder:' BRAPH2.FAIL_TEST], ...
					['NNVariationalAutoencoder.isLocked(' int2str(prop) ') must be locked because the element is now locked.'] ...
					)
			case {Category.CONSTANT, Category.METADATA, Category.RESULT, Category.QUERY, Category.EVANESCENT, Category.FIGURE, Category.GUI}
				assert( ...
					~nnvae.isLocked(prop), ...
					[BRAPH2.STR ':NNVariationalAutoencoder:' BRAPH2.FAIL_TEST], ...
					['NNVariationalAutoencoder.isLocked(' int2str(prop) ') must NOT be locked even though the element is now locked.'] ...
					)
		end
	end
end

%% Test 5: Lock 2
if rand() >= (1 - .01) * BRAPH2TEST.RANDOM
	nnvae = NNVariationalAutoencoder();
	 
	warning_backup = warning('off', 'BRAPH2:NNVariationalAutoencoder');
	for prop = 1:1:NNVariationalAutoencoder.getPropNumber()
		nnvae.lock(prop)
		switch NNVariationalAutoencoder.getPropCategory(prop)
			case {Category.PARAMETER, Category.DATA, Category.FIGURE, Category.GUI}
				assert( ...
					nnvae.isLocked(prop), ...
					[BRAPH2.STR ':NNVariationalAutoencoder:' BRAPH2.FAIL_TEST], ...
					['NNVariationalAutoencoder.isLocked(' int2str(prop) ') must be locked.'] ...
					)
			case {Category.CONSTANT, Category.METADATA, Category.RESULT, Category.QUERY, Category.EVANESCENT}
				assert( ...
					~nnvae.isLocked(prop), ...
					[BRAPH2.STR ':NNVariationalAutoencoder:' BRAPH2.FAIL_TEST], ...
					['NNVariationalAutoencoder.isLocked(' int2str(prop) ') must NOT be locked even though locking has been attempted.'] ...
					)
		end
	end
	warning(warning_backup)
end

%% Test 6: Check
if rand() >= (1 - .01) * BRAPH2TEST.RANDOM
	nnvae = NNVariationalAutoencoder();
	 
	for prop = 1:1:NNVariationalAutoencoder.getPropNumber()
		TAG = upper(NNVariationalAutoencoder.getPropTag(prop));
		assert( ...
			nnvae.isChecked(prop), ...
			[BRAPH2.STR ':NNVariationalAutoencoder:' BRAPH2.FAIL_TEST], ...
			['NNVariationalAutoencoder.isChecked(' int2str(prop) ') must be checked when it is instantiated.'] ...
			)
		assert( ...
			nnvae.isChecked(TAG), ...
			[BRAPH2.STR ':NNVariationalAutoencoder:' BRAPH2.FAIL_TEST], ...
			['NNVariationalAutoencoder.isChecked(' TAG ') must be checked when it is instantiated.'] ...
			)
	end
	 
	nnvae.unchecked()
	 
	for prop = 1:1:NNVariationalAutoencoder.getPropNumber()
		assert( ...
			~nnvae.isChecked(prop), ...
			[BRAPH2.STR ':NNVariationalAutoencoder:' BRAPH2.FAIL_TEST], ...
			['NNVariationalAutoencoder.isChecked(' int2str(prop) ') must NOT be checked because it has been set to unchecked.'] ...
			)
	end
	 
	nnvae.checked()
	 
	for prop = 1:1:NNVariationalAutoencoder.getPropNumber()
		assert( ...
			nnvae.isChecked(prop), ...
			[BRAPH2.STR ':NNVariationalAutoencoder:' BRAPH2.FAIL_TEST], ...
			['NNVariationalAutoencoder.isChecked(' int2str(prop) ') must be checked because it has been set to checked.'] ...
			)
	end
end

%% Test 7: Callbacks
if rand() >= (1 - .01) * BRAPH2TEST.RANDOM
	% basic NNVariationalAutoencoder
	nnvae_0 = NNVariationalAutoencoder( ...
		NNVariationalAutoencoder.ELCLASS, NNVariationalAutoencoder.getNoValue(), ...
		NNVariationalAutoencoder.NAME, NNVariationalAutoencoder.getNoValue(), ...
		NNVariationalAutoencoder.DESCRIPTION, NNVariationalAutoencoder.getNoValue(), ...
		NNVariationalAutoencoder.TEMPLATE, NNVariationalAutoencoder.getPropDefault(NNVariationalAutoencoder.TEMPLATE), ...
		NNVariationalAutoencoder.ID, NNVariationalAutoencoder.getPropDefault(NNVariationalAutoencoder.ID), ...
		NNVariationalAutoencoder.LABEL, NNVariationalAutoencoder.getPropDefault(NNVariationalAutoencoder.LABEL), ...
		NNVariationalAutoencoder.NOTES, NNVariationalAutoencoder.getPropDefault(NNVariationalAutoencoder.NOTES), ...
		NNVariationalAutoencoder.TOSTRING, NNVariationalAutoencoder.getNoValue(), ...
		NNVariationalAutoencoder.D, NNVariationalAutoencoder.getPropDefault(NNVariationalAutoencoder.D), ...
		NNVariationalAutoencoder.DP_CLASSES, NNVariationalAutoencoder.getPropDefault(NNVariationalAutoencoder.DP_CLASSES), ...
		NNVariationalAutoencoder.EPOCHS, NNVariationalAutoencoder.getPropDefault(NNVariationalAutoencoder.EPOCHS), ...
		NNVariationalAutoencoder.BATCH, NNVariationalAutoencoder.getPropDefault(NNVariationalAutoencoder.BATCH), ...
		NNVariationalAutoencoder.SHUFFLE, NNVariationalAutoencoder.getPropDefault(NNVariationalAutoencoder.SHUFFLE), ...
		NNVariationalAutoencoder.SOLVER, NNVariationalAutoencoder.getPropDefault(NNVariationalAutoencoder.SOLVER), ...
		NNVariationalAutoencoder.MODEL, NNVariationalAutoencoder.getNoValue(), ...
		NNVariationalAutoencoder.INPUTS, NNVariationalAutoencoder.getNoValue(), ...
		NNVariationalAutoencoder.TARGETS, NNVariationalAutoencoder.getNoValue(), ...
		NNVariationalAutoencoder.TRAIN, NNVariationalAutoencoder.getNoValue(), ...
		NNVariationalAutoencoder.VERBOSE, NNVariationalAutoencoder.getPropDefault(NNVariationalAutoencoder.VERBOSE), ...
		NNVariationalAutoencoder.PLOT_TRAINING, NNVariationalAutoencoder.getPropDefault(NNVariationalAutoencoder.PLOT_TRAINING), ...
		NNVariationalAutoencoder.PREDICT, NNVariationalAutoencoder.getNoValue(), ...
		NNVariationalAutoencoder.LEARN_RATE, NNVariationalAutoencoder.getPropDefault(NNVariationalAutoencoder.LEARN_RATE), ...
		NNVariationalAutoencoder.NUM_LATENT_REP, NNVariationalAutoencoder.getPropDefault(NNVariationalAutoencoder.NUM_LATENT_REP), ...
		NNVariationalAutoencoder.SIZE_INPUT, NNVariationalAutoencoder.getPropDefault(NNVariationalAutoencoder.SIZE_INPUT), ...
		NNVariationalAutoencoder.ITERATION_DIM, NNVariationalAutoencoder.getPropDefault(NNVariationalAutoencoder.ITERATION_DIM), ...
		NNVariationalAutoencoder.NUM_MBQ_OUTPUT, NNVariationalAutoencoder.getPropDefault(NNVariationalAutoencoder.NUM_MBQ_OUTPUT), ...
		NNVariationalAutoencoder.MINIBATCH_FORMAT_INPUT, NNVariationalAutoencoder.getNoValue(), ...
		NNVariationalAutoencoder.MINIBATCH_FORMAT_TARGET, NNVariationalAutoencoder.getNoValue(), ...
		NNVariationalAutoencoder.ENCODER, NNVariationalAutoencoder.getPropDefault(NNVariationalAutoencoder.ENCODER), ...
		NNVariationalAutoencoder.DECODER, NNVariationalAutoencoder.getPropDefault(NNVariationalAutoencoder.DECODER), ...
		NNVariationalAutoencoder.MBQ, NNVariationalAutoencoder.getNoValue(), ...
		NNVariationalAutoencoder.LOSS_FN, NNVariationalAutoencoder.getNoValue() ...
		);
	 
	% NNVariationalAutoencoder with 1st callbacks
	nnvae_1 = NNVariationalAutoencoder( ...
		NNVariationalAutoencoder.ELCLASS, NNVariationalAutoencoder.getNoValue(), ...
		NNVariationalAutoencoder.NAME, NNVariationalAutoencoder.getNoValue(), ...
		NNVariationalAutoencoder.DESCRIPTION, NNVariationalAutoencoder.getNoValue(), ...
		NNVariationalAutoencoder.TEMPLATE, nnvae_0.getCallback(4), ..., ...
		NNVariationalAutoencoder.ID, nnvae_0.getCallback(5), ..., ...
		NNVariationalAutoencoder.LABEL, NNVariationalAutoencoder.getPropDefault(NNVariationalAutoencoder.LABEL), ...
		NNVariationalAutoencoder.NOTES, NNVariationalAutoencoder.getPropDefault(NNVariationalAutoencoder.NOTES), ...
		NNVariationalAutoencoder.TOSTRING, NNVariationalAutoencoder.getNoValue(), ...
		NNVariationalAutoencoder.D, nnvae_0.getCallback(9), ..., ...
		NNVariationalAutoencoder.DP_CLASSES, nnvae_0.getCallback(10), ..., ...
		NNVariationalAutoencoder.EPOCHS, nnvae_0.getCallback(11), ..., ...
		NNVariationalAutoencoder.BATCH, nnvae_0.getCallback(12), ..., ...
		NNVariationalAutoencoder.SHUFFLE, nnvae_0.getCallback(13), ..., ...
		NNVariationalAutoencoder.SOLVER, nnvae_0.getCallback(14), ..., ...
		NNVariationalAutoencoder.MODEL, NNVariationalAutoencoder.getNoValue(), ...
		NNVariationalAutoencoder.INPUTS, NNVariationalAutoencoder.getNoValue(), ...
		NNVariationalAutoencoder.TARGETS, NNVariationalAutoencoder.getNoValue(), ...
		NNVariationalAutoencoder.TRAIN, NNVariationalAutoencoder.getNoValue(), ...
		NNVariationalAutoencoder.VERBOSE, nnvae_0.getCallback(19), ..., ...
		NNVariationalAutoencoder.PLOT_TRAINING, NNVariationalAutoencoder.getPropDefault(NNVariationalAutoencoder.PLOT_TRAINING), ...
		NNVariationalAutoencoder.PREDICT, NNVariationalAutoencoder.getNoValue(), ...
		NNVariationalAutoencoder.LEARN_RATE, nnvae_0.getCallback(22), ..., ...
		NNVariationalAutoencoder.NUM_LATENT_REP, nnvae_0.getCallback(23), ..., ...
		NNVariationalAutoencoder.SIZE_INPUT, nnvae_0.getCallback(24), ..., ...
		NNVariationalAutoencoder.ITERATION_DIM, nnvae_0.getCallback(25), ..., ...
		NNVariationalAutoencoder.NUM_MBQ_OUTPUT, nnvae_0.getCallback(26), ..., ...
		NNVariationalAutoencoder.MINIBATCH_FORMAT_INPUT, NNVariationalAutoencoder.getNoValue(), ...
		NNVariationalAutoencoder.MINIBATCH_FORMAT_TARGET, NNVariationalAutoencoder.getNoValue(), ...
		NNVariationalAutoencoder.ENCODER, nnvae_0.getCallback(29), ..., ...
		NNVariationalAutoencoder.DECODER, nnvae_0.getCallback(30), ..., ...
		NNVariationalAutoencoder.MBQ, NNVariationalAutoencoder.getNoValue(), ...
		NNVariationalAutoencoder.LOSS_FN, NNVariationalAutoencoder.getNoValue() ...
		);
	 
	prop_number = NNVariationalAutoencoder.getPropNumber();
	for prop = 1:1:prop_number
		TAG = upper(NNVariationalAutoencoder.getPropTag(prop));
		switch NNVariationalAutoencoder.getPropCategory(prop)
			case {Category.PARAMETER, Category.DATA, Category.FIGURE, Category.GUI}
				assert( ...
					isa(nnvae_1.getr(prop), 'Callback'), ...
					[BRAPH2.STR ':NNVariationalAutoencoder:' BRAPH2.FAIL_TEST], ...
					['NNVariationalAutoencoder.getr(' int2str(prop) ') must be a callback.'] ...
					)
				assert( ...
					isequal(nnvae_1.get(prop), nnvae_0.get(prop)) && ~isa(nnvae_1.get(prop), 'Callback'), ...
					[BRAPH2.STR ':NNVariationalAutoencoder:' BRAPH2.FAIL_TEST], ...
					['NNVariationalAutoencoder.get(' int2str(prop) ') must be the actual property and NOT a callback.'] ...
					)
			otherwise
				assert( ...
					~isa(nnvae_1.getr(prop), 'Callback'), ...
					[BRAPH2.STR ':NNVariationalAutoencoder:' BRAPH2.FAIL_TEST], ...
					['NNVariationalAutoencoder.getr(' int2str(prop) ') must NOT be a callback.'] ...
					)
		end
	end
	 
	% NNVariationalAutoencoder with 2nd callbacks
	nnvae_2 = NNVariationalAutoencoder( ...
		NNVariationalAutoencoder.ELCLASS, NNVariationalAutoencoder.getNoValue(), ...
		NNVariationalAutoencoder.NAME, NNVariationalAutoencoder.getNoValue(), ...
		NNVariationalAutoencoder.DESCRIPTION, NNVariationalAutoencoder.getNoValue(), ...
		NNVariationalAutoencoder.TEMPLATE, nnvae_1.getCallback(4), ..., ...
		NNVariationalAutoencoder.ID, nnvae_1.getCallback(5), ..., ...
		NNVariationalAutoencoder.LABEL, NNVariationalAutoencoder.getPropDefault(NNVariationalAutoencoder.LABEL), ...
		NNVariationalAutoencoder.NOTES, NNVariationalAutoencoder.getPropDefault(NNVariationalAutoencoder.NOTES), ...
		NNVariationalAutoencoder.TOSTRING, NNVariationalAutoencoder.getNoValue(), ...
		NNVariationalAutoencoder.D, nnvae_1.getCallback(9), ..., ...
		NNVariationalAutoencoder.DP_CLASSES, nnvae_1.getCallback(10), ..., ...
		NNVariationalAutoencoder.EPOCHS, nnvae_1.getCallback(11), ..., ...
		NNVariationalAutoencoder.BATCH, nnvae_1.getCallback(12), ..., ...
		NNVariationalAutoencoder.SHUFFLE, nnvae_1.getCallback(13), ..., ...
		NNVariationalAutoencoder.SOLVER, nnvae_1.getCallback(14), ..., ...
		NNVariationalAutoencoder.MODEL, NNVariationalAutoencoder.getNoValue(), ...
		NNVariationalAutoencoder.INPUTS, NNVariationalAutoencoder.getNoValue(), ...
		NNVariationalAutoencoder.TARGETS, NNVariationalAutoencoder.getNoValue(), ...
		NNVariationalAutoencoder.TRAIN, NNVariationalAutoencoder.getNoValue(), ...
		NNVariationalAutoencoder.VERBOSE, nnvae_1.getCallback(19), ..., ...
		NNVariationalAutoencoder.PLOT_TRAINING, NNVariationalAutoencoder.getPropDefault(NNVariationalAutoencoder.PLOT_TRAINING), ...
		NNVariationalAutoencoder.PREDICT, NNVariationalAutoencoder.getNoValue(), ...
		NNVariationalAutoencoder.LEARN_RATE, nnvae_1.getCallback(22), ..., ...
		NNVariationalAutoencoder.NUM_LATENT_REP, nnvae_1.getCallback(23), ..., ...
		NNVariationalAutoencoder.SIZE_INPUT, nnvae_1.getCallback(24), ..., ...
		NNVariationalAutoencoder.ITERATION_DIM, nnvae_1.getCallback(25), ..., ...
		NNVariationalAutoencoder.NUM_MBQ_OUTPUT, nnvae_1.getCallback(26), ..., ...
		NNVariationalAutoencoder.MINIBATCH_FORMAT_INPUT, NNVariationalAutoencoder.getNoValue(), ...
		NNVariationalAutoencoder.MINIBATCH_FORMAT_TARGET, NNVariationalAutoencoder.getNoValue(), ...
		NNVariationalAutoencoder.ENCODER, nnvae_1.getCallback(29), ..., ...
		NNVariationalAutoencoder.DECODER, nnvae_1.getCallback(30), ..., ...
		NNVariationalAutoencoder.MBQ, NNVariationalAutoencoder.getNoValue(), ...
		NNVariationalAutoencoder.LOSS_FN, NNVariationalAutoencoder.getNoValue() ...
		);
	 
	prop_number = NNVariationalAutoencoder.getPropNumber();
	for prop = 1:1:prop_number
		TAG = upper(NNVariationalAutoencoder.getPropTag(prop));
		switch NNVariationalAutoencoder.getPropCategory(prop)
			case {Category.PARAMETER, Category.DATA, Category.FIGURE, Category.GUI}
				assert( ...
					isa(nnvae_2.getr(prop), 'Callback'), ...
					[BRAPH2.STR ':NNVariationalAutoencoder:' BRAPH2.FAIL_TEST], ...
					['NNVariationalAutoencoder.getr(' int2str(prop) ') must be a callback.'] ...
					)
				assert( ...
					isequal(nnvae_2.get(prop), nnvae_0.get(prop)) && ~isa(nnvae_1.get(prop), 'Callback'), ...
					[BRAPH2.STR ':NNVariationalAutoencoder:' BRAPH2.FAIL_TEST], ...
					['NNVariationalAutoencoder.get(' int2str(prop) ') must be the actual property and NOT a callback.'] ...
					)
			otherwise
				assert( ...
					~isa(nnvae_2.getr(prop), 'Callback'), ...
					[BRAPH2.STR ':NNVariationalAutoencoder:' BRAPH2.FAIL_TEST], ...
					['NNVariationalAutoencoder.getr(' int2str(prop) ') must NOT be a callback.'] ...
					)
		end
	end
	 
	% NNVariationalAutoencoder with 3rd callbacks
	nnvae_3 = NNVariationalAutoencoder( ...
		NNVariationalAutoencoder.ELCLASS, NNVariationalAutoencoder.getNoValue(), ...
		NNVariationalAutoencoder.NAME, NNVariationalAutoencoder.getNoValue(), ...
		NNVariationalAutoencoder.DESCRIPTION, NNVariationalAutoencoder.getNoValue(), ...
		NNVariationalAutoencoder.TEMPLATE, nnvae_2.getCallback(4), ..., ...
		NNVariationalAutoencoder.ID, nnvae_2.getCallback(5), ..., ...
		NNVariationalAutoencoder.LABEL, NNVariationalAutoencoder.getPropDefault(NNVariationalAutoencoder.LABEL), ...
		NNVariationalAutoencoder.NOTES, NNVariationalAutoencoder.getPropDefault(NNVariationalAutoencoder.NOTES), ...
		NNVariationalAutoencoder.TOSTRING, NNVariationalAutoencoder.getNoValue(), ...
		NNVariationalAutoencoder.D, nnvae_2.getCallback(9), ..., ...
		NNVariationalAutoencoder.DP_CLASSES, nnvae_2.getCallback(10), ..., ...
		NNVariationalAutoencoder.EPOCHS, nnvae_2.getCallback(11), ..., ...
		NNVariationalAutoencoder.BATCH, nnvae_2.getCallback(12), ..., ...
		NNVariationalAutoencoder.SHUFFLE, nnvae_2.getCallback(13), ..., ...
		NNVariationalAutoencoder.SOLVER, nnvae_2.getCallback(14), ..., ...
		NNVariationalAutoencoder.MODEL, NNVariationalAutoencoder.getNoValue(), ...
		NNVariationalAutoencoder.INPUTS, NNVariationalAutoencoder.getNoValue(), ...
		NNVariationalAutoencoder.TARGETS, NNVariationalAutoencoder.getNoValue(), ...
		NNVariationalAutoencoder.TRAIN, NNVariationalAutoencoder.getNoValue(), ...
		NNVariationalAutoencoder.VERBOSE, nnvae_2.getCallback(19), ..., ...
		NNVariationalAutoencoder.PLOT_TRAINING, NNVariationalAutoencoder.getPropDefault(NNVariationalAutoencoder.PLOT_TRAINING), ...
		NNVariationalAutoencoder.PREDICT, NNVariationalAutoencoder.getNoValue(), ...
		NNVariationalAutoencoder.LEARN_RATE, nnvae_2.getCallback(22), ..., ...
		NNVariationalAutoencoder.NUM_LATENT_REP, nnvae_2.getCallback(23), ..., ...
		NNVariationalAutoencoder.SIZE_INPUT, nnvae_2.getCallback(24), ..., ...
		NNVariationalAutoencoder.ITERATION_DIM, nnvae_2.getCallback(25), ..., ...
		NNVariationalAutoencoder.NUM_MBQ_OUTPUT, nnvae_2.getCallback(26), ..., ...
		NNVariationalAutoencoder.MINIBATCH_FORMAT_INPUT, NNVariationalAutoencoder.getNoValue(), ...
		NNVariationalAutoencoder.MINIBATCH_FORMAT_TARGET, NNVariationalAutoencoder.getNoValue(), ...
		NNVariationalAutoencoder.ENCODER, nnvae_2.getCallback(29), ..., ...
		NNVariationalAutoencoder.DECODER, nnvae_2.getCallback(30), ..., ...
		NNVariationalAutoencoder.MBQ, NNVariationalAutoencoder.getNoValue(), ...
		NNVariationalAutoencoder.LOSS_FN, NNVariationalAutoencoder.getNoValue() ...
		);
	 
	prop_number = NNVariationalAutoencoder.getPropNumber();
	for prop = 1:1:prop_number
		TAG = upper(NNVariationalAutoencoder.getPropTag(prop));
		switch NNVariationalAutoencoder.getPropCategory(prop)
			case {Category.PARAMETER, Category.DATA, Category.FIGURE, Category.GUI}
				assert( ...
					isa(nnvae_3.getr(prop), 'Callback'), ...
					[BRAPH2.STR ':NNVariationalAutoencoder:' BRAPH2.FAIL_TEST], ...
					['NNVariationalAutoencoder.getr(' int2str(prop) ') must be a callback.'] ...
					)
				assert( ...
					isequal(nnvae_3.get(prop), nnvae_0.get(prop)) && ~isa(nnvae_1.get(prop), 'Callback'), ...
					[BRAPH2.STR ':NNVariationalAutoencoder:' BRAPH2.FAIL_TEST], ...
					['NNVariationalAutoencoder.get(' int2str(prop) ') must be the actual property and NOT a callback.'] ...
					)
			otherwise
				assert( ...
					~isa(nnvae_3.getr(prop), 'Callback'), ...
					[BRAPH2.STR ':NNVariationalAutoencoder:' BRAPH2.FAIL_TEST], ...
					['NNVariationalAutoencoder.getr(' int2str(prop) ') must NOT be a callback.'] ...
					)
		end
	end
	 
end

%% Test 8: Copy
if rand() >= (1 - .01) * BRAPH2TEST.RANDOM
	% copy empty element
	nnvae = NNVariationalAutoencoder();
	 
	nnvae_copy = nnvae.copy();
	 
	assert(nnvae_copy ~= nnvae, ...
		[BRAPH2.STR ':NNVariationalAutoencoder:' BRAPH2.FAIL_TEST], ...
		'NNVariationalAutoencoder.copy() does not work. A copied element must point to a copied element.')
	assert(isequal(nnvae_copy, nnvae), ...
		[BRAPH2.STR ':NNVariationalAutoencoder:' BRAPH2.FAIL_TEST], ...
		'NNVariationalAutoencoder.copy() does not work. A copied element must have the same property values of the original element.')
	 
	for prop = 1:1:NNVariationalAutoencoder.getPropNumber()
		value = nnvae.getr(prop);
		value_copy = nnvae_copy.getr(prop);
		switch NNVariationalAutoencoder.getPropCategory(prop)
			case {Category.EVANESCENT}
				assert( ...
					isa(value_copy, 'NoValue'), ...
					[BRAPH2.STR ':NNVariationalAutoencoder:' BRAPH2.FAIL_TEST], ...
					'NNVariationalAutoencoder.copy() does not work. The copied value of an EVANESCENT property must be NoValue.' ...
					)
			otherwise
				if isa(value, 'NoValue')
					assert( ...
						value_copy == value, ...
						[BRAPH2.STR ':NNVariationalAutoencoder:' BRAPH2.FAIL_TEST], ...
						'NNVariationalAutoencoder.copy() does not work. There should be a unique instance of NoValue.' ...
						)
				elseif isa(value, 'Element')
					assert( ...
						value_copy ~= value, ...
						[BRAPH2.STR ':NNVariationalAutoencoder:' BRAPH2.FAIL_TEST], ...
						'NNVariationalAutoencoder.copy() does not work. The handle of a copied element should point to a copied element.' ...
						)
					assert( ...
						isequal(value_copy, value), ...
						[BRAPH2.STR ':NNVariationalAutoencoder:' BRAPH2.FAIL_TEST], ...
						'NNVariationalAutoencoder.copy() does not work. When empty, a copied element should be equal to the element.' ...
						)
				elseif iscell(value) && all(all(cellfun(@(x) isa(x, 'Element'), value)))
					for j = 1:1:length(value)
						assert( ...
							value_copy ~= value, ...
							[BRAPH2.STR ':NNVariationalAutoencoder:' BRAPH2.FAIL_TEST], ...
							'NNVariationalAutoencoder.copy() does not work. The handle of a copied element should point to a copied element.' ...
							)
						assert( ...
							isequal(value_copy, value), ...
							[BRAPH2.STR ':NNVariationalAutoencoder:' BRAPH2.FAIL_TEST], ...
							'NNVariationalAutoencoder.copy() does not work. When empty, a copied element should be equal to the element.' ...
							)
					end
				else
					assert( ...
						isequal(value_copy, value), ...
						[BRAPH2.STR ':NNVariationalAutoencoder:' BRAPH2.FAIL_TEST], ...
						'NNVariationalAutoencoder.copy() does not work. The value copy should be equal to the original.' ...
						)
				end
				assert( ...
					nnvae_copy.isLocked(prop) == nnvae.isLocked(prop), ...
					[BRAPH2.STR ':NNVariationalAutoencoder:' BRAPH2.FAIL_TEST], ...
					'NNVariationalAutoencoder.copy() does not work. The locked status of the copied and original elements must be the same.' ...
					)
				assert( ...
					nnvae_copy.isChecked(prop) == nnvae.isChecked(prop), ...
					[BRAPH2.STR ':NNVariationalAutoencoder:' BRAPH2.FAIL_TEST], ...
					'NNVariationalAutoencoder.copy() does not work. The checked status of the copied and original elements must be the same.' ...
					)
				assert( ...
					nnvae_copy.getPropSeed(prop) == nnvae.getPropSeed(prop), ...
					[BRAPH2.STR ':NNVariationalAutoencoder:' BRAPH2.FAIL_TEST], ...
					'NNVariationalAutoencoder.copy() does not work. The randomization seeds of the copied and original elements must be the same.' ...
					)
		end
	end
	 
	% copy element with default initialization and memorization
	nnvae = NNVariationalAutoencoder( ...
		NNVariationalAutoencoder.ELCLASS, NNVariationalAutoencoder.getNoValue(), ...
		NNVariationalAutoencoder.NAME, NNVariationalAutoencoder.getNoValue(), ...
		NNVariationalAutoencoder.DESCRIPTION, NNVariationalAutoencoder.getNoValue(), ...
		NNVariationalAutoencoder.TEMPLATE, NNVariationalAutoencoder.getPropDefault(NNVariationalAutoencoder.TEMPLATE), ...
		NNVariationalAutoencoder.ID, NNVariationalAutoencoder.getPropDefault(NNVariationalAutoencoder.ID), ...
		NNVariationalAutoencoder.LABEL, NNVariationalAutoencoder.getPropDefault(NNVariationalAutoencoder.LABEL), ...
		NNVariationalAutoencoder.NOTES, NNVariationalAutoencoder.getPropDefault(NNVariationalAutoencoder.NOTES), ...
		NNVariationalAutoencoder.TOSTRING, NNVariationalAutoencoder.getNoValue(), ...
		NNVariationalAutoencoder.D, NNVariationalAutoencoder.getPropDefault(NNVariationalAutoencoder.D), ...
		NNVariationalAutoencoder.DP_CLASSES, NNVariationalAutoencoder.getPropDefault(NNVariationalAutoencoder.DP_CLASSES), ...
		NNVariationalAutoencoder.EPOCHS, NNVariationalAutoencoder.getPropDefault(NNVariationalAutoencoder.EPOCHS), ...
		NNVariationalAutoencoder.BATCH, NNVariationalAutoencoder.getPropDefault(NNVariationalAutoencoder.BATCH), ...
		NNVariationalAutoencoder.SHUFFLE, NNVariationalAutoencoder.getPropDefault(NNVariationalAutoencoder.SHUFFLE), ...
		NNVariationalAutoencoder.SOLVER, NNVariationalAutoencoder.getPropDefault(NNVariationalAutoencoder.SOLVER), ...
		NNVariationalAutoencoder.MODEL, NNVariationalAutoencoder.getNoValue(), ...
		NNVariationalAutoencoder.INPUTS, NNVariationalAutoencoder.getNoValue(), ...
		NNVariationalAutoencoder.TARGETS, NNVariationalAutoencoder.getNoValue(), ...
		NNVariationalAutoencoder.TRAIN, NNVariationalAutoencoder.getNoValue(), ...
		NNVariationalAutoencoder.VERBOSE, NNVariationalAutoencoder.getPropDefault(NNVariationalAutoencoder.VERBOSE), ...
		NNVariationalAutoencoder.PLOT_TRAINING, NNVariationalAutoencoder.getPropDefault(NNVariationalAutoencoder.PLOT_TRAINING), ...
		NNVariationalAutoencoder.PREDICT, NNVariationalAutoencoder.getNoValue(), ...
		NNVariationalAutoencoder.LEARN_RATE, NNVariationalAutoencoder.getPropDefault(NNVariationalAutoencoder.LEARN_RATE), ...
		NNVariationalAutoencoder.NUM_LATENT_REP, NNVariationalAutoencoder.getPropDefault(NNVariationalAutoencoder.NUM_LATENT_REP), ...
		NNVariationalAutoencoder.SIZE_INPUT, NNVariationalAutoencoder.getPropDefault(NNVariationalAutoencoder.SIZE_INPUT), ...
		NNVariationalAutoencoder.ITERATION_DIM, NNVariationalAutoencoder.getPropDefault(NNVariationalAutoencoder.ITERATION_DIM), ...
		NNVariationalAutoencoder.NUM_MBQ_OUTPUT, NNVariationalAutoencoder.getPropDefault(NNVariationalAutoencoder.NUM_MBQ_OUTPUT), ...
		NNVariationalAutoencoder.MINIBATCH_FORMAT_INPUT, NNVariationalAutoencoder.getNoValue(), ...
		NNVariationalAutoencoder.MINIBATCH_FORMAT_TARGET, NNVariationalAutoencoder.getNoValue(), ...
		NNVariationalAutoencoder.ENCODER, NNVariationalAutoencoder.getPropDefault(NNVariationalAutoencoder.ENCODER), ...
		NNVariationalAutoencoder.DECODER, NNVariationalAutoencoder.getPropDefault(NNVariationalAutoencoder.DECODER), ...
		NNVariationalAutoencoder.MBQ, NNVariationalAutoencoder.getNoValue(), ...
		NNVariationalAutoencoder.LOSS_FN, NNVariationalAutoencoder.getNoValue() ...
		);
	 
	for prop = 1:1:NNVariationalAutoencoder.getPropNumber()
		if NNVariationalAutoencoder.getPropCategory(prop) == Category.QUERY
			% properties QUERY should not be memorized
			% warning_backup = warning('off', [BRAPH2.STR ':NNVariationalAutoencoder']);
			% nnvae.memorize(prop);
			% warning(warning_backup)
		elseif NNVariationalAutoencoder.getPropCategory(prop) == Category.EVANESCENT && nnvae.getPropFormat(prop) == Format.HANDLE
			nnvae.memorize(prop);
			warning_backup = warning('off', 'BRAPH2:NNVariationalAutoencoder');
			delete(ancestor(nnvae.get(prop), 'figure'))
			warning(warning_backup)
		else
			nnvae.memorize(prop);
		end
	end
	 
	% copy element with default initialization
	nnvae_copy = nnvae.copy();
	 
	for prop = 1:1:NNVariationalAutoencoder.getPropNumber()
		value = nnvae.getr(prop);
		value_copy = nnvae_copy.getr(prop);
		switch NNVariationalAutoencoder.getPropCategory(prop)
			case {Category.EVANESCENT Category.QUERY}
				assert( ...
					isa(value_copy, 'NoValue'), ...
					[BRAPH2.STR ':NNVariationalAutoencoder:' BRAPH2.FAIL_TEST], ...
					'NNVariationalAutoencoder.copy() does not work. The copied value of an EVANESCENT property must be NoValue.' ...
					)
			otherwise
				if isa(value, 'NoValue')
					assert( ...
						value_copy == value, ...
						[BRAPH2.STR ':NNVariationalAutoencoder:' BRAPH2.FAIL_TEST], ...
						'NNVariationalAutoencoder.copy() does not work. There should be a unique instance of NoValue.' ...
						)
				elseif isa(value, 'Element')
					assert( ...
						value_copy ~= value, ...
						[BRAPH2.STR ':NNVariationalAutoencoder:' BRAPH2.FAIL_TEST], ...
						'NNVariationalAutoencoder.copy() does not work. The handle of a copied element should point to a copied element.' ...
						)
					assert( ...
						isequal(value_copy, value), ...
						[BRAPH2.STR ':NNVariationalAutoencoder:' BRAPH2.FAIL_TEST], ...
						'NNVariationalAutoencoder.copy() does not work. When empty, a copied element should be equal to the element.' ...
						)
				elseif iscell(value) && all(all(cellfun(@(x) isa(x, 'Element'), value)))
					for j = 1:1:length(value)
						assert( ...
							value_copy ~= value, ...
							[BRAPH2.STR ':NNVariationalAutoencoder:' BRAPH2.FAIL_TEST], ...
							'NNVariationalAutoencoder.copy() does not work. The handle of a copied element should point to a copied element.' ...
							)
						assert( ...
							isequal(value_copy, value), ...
							[BRAPH2.STR ':NNVariationalAutoencoder:' BRAPH2.FAIL_TEST], ...
							'NNVariationalAutoencoder.copy() does not work. When empty, a copied element should be equal to the element.' ...
							)
					end
				else
					assert( ...
						isequal(value_copy, value), ...
						[BRAPH2.STR ':NNVariationalAutoencoder:' BRAPH2.FAIL_TEST], ...
						'NNVariationalAutoencoder.copy() does not work. The value copy should be equal to the original.' ...
						)
				end
	 
					assert( ...
						nnvae_copy.isLocked(prop) == nnvae.isLocked(prop), ...
						[BRAPH2.STR ':NNVariationalAutoencoder:' BRAPH2.FAIL_TEST], ...
						'NNVariationalAutoencoder.copy() does not work. The locked status of the copied and original elements must be the same.' ...
						)
	 
					assert( ...
						nnvae_copy.isChecked(prop) == nnvae.isChecked(prop), ...
						[BRAPH2.STR ':NNVariationalAutoencoder:' BRAPH2.FAIL_TEST], ...
						'NNVariationalAutoencoder.copy() does not work. The checked status of the copied and original elements must be the same.' ...
						)
	 
					assert( ...
						nnvae_copy.getPropSeed(prop) == nnvae.getPropSeed(prop), ...
						[BRAPH2.STR ':NNVariationalAutoencoder:' BRAPH2.FAIL_TEST], ...
						'NNVariationalAutoencoder.copy() does not work. The randomization seeds of the copied and original elements must be the same.' ...
						)
		end
	end
	 
	% copy element with callbacks
	nnvae_0 = NNVariationalAutoencoder( ...
		NNVariationalAutoencoder.ELCLASS, NNVariationalAutoencoder.getNoValue(), ...
		NNVariationalAutoencoder.NAME, NNVariationalAutoencoder.getNoValue(), ...
		NNVariationalAutoencoder.DESCRIPTION, NNVariationalAutoencoder.getNoValue(), ...
		NNVariationalAutoencoder.TEMPLATE, NNVariationalAutoencoder.getPropDefault(NNVariationalAutoencoder.TEMPLATE), ...
		NNVariationalAutoencoder.ID, NNVariationalAutoencoder.getPropDefault(NNVariationalAutoencoder.ID), ...
		NNVariationalAutoencoder.LABEL, NNVariationalAutoencoder.getPropDefault(NNVariationalAutoencoder.LABEL), ...
		NNVariationalAutoencoder.NOTES, NNVariationalAutoencoder.getPropDefault(NNVariationalAutoencoder.NOTES), ...
		NNVariationalAutoencoder.TOSTRING, NNVariationalAutoencoder.getNoValue(), ...
		NNVariationalAutoencoder.D, NNVariationalAutoencoder.getPropDefault(NNVariationalAutoencoder.D), ...
		NNVariationalAutoencoder.DP_CLASSES, NNVariationalAutoencoder.getPropDefault(NNVariationalAutoencoder.DP_CLASSES), ...
		NNVariationalAutoencoder.EPOCHS, NNVariationalAutoencoder.getPropDefault(NNVariationalAutoencoder.EPOCHS), ...
		NNVariationalAutoencoder.BATCH, NNVariationalAutoencoder.getPropDefault(NNVariationalAutoencoder.BATCH), ...
		NNVariationalAutoencoder.SHUFFLE, NNVariationalAutoencoder.getPropDefault(NNVariationalAutoencoder.SHUFFLE), ...
		NNVariationalAutoencoder.SOLVER, NNVariationalAutoencoder.getPropDefault(NNVariationalAutoencoder.SOLVER), ...
		NNVariationalAutoencoder.MODEL, NNVariationalAutoencoder.getNoValue(), ...
		NNVariationalAutoencoder.INPUTS, NNVariationalAutoencoder.getNoValue(), ...
		NNVariationalAutoencoder.TARGETS, NNVariationalAutoencoder.getNoValue(), ...
		NNVariationalAutoencoder.TRAIN, NNVariationalAutoencoder.getNoValue(), ...
		NNVariationalAutoencoder.VERBOSE, NNVariationalAutoencoder.getPropDefault(NNVariationalAutoencoder.VERBOSE), ...
		NNVariationalAutoencoder.PLOT_TRAINING, NNVariationalAutoencoder.getPropDefault(NNVariationalAutoencoder.PLOT_TRAINING), ...
		NNVariationalAutoencoder.PREDICT, NNVariationalAutoencoder.getNoValue(), ...
		NNVariationalAutoencoder.LEARN_RATE, NNVariationalAutoencoder.getPropDefault(NNVariationalAutoencoder.LEARN_RATE), ...
		NNVariationalAutoencoder.NUM_LATENT_REP, NNVariationalAutoencoder.getPropDefault(NNVariationalAutoencoder.NUM_LATENT_REP), ...
		NNVariationalAutoencoder.SIZE_INPUT, NNVariationalAutoencoder.getPropDefault(NNVariationalAutoencoder.SIZE_INPUT), ...
		NNVariationalAutoencoder.ITERATION_DIM, NNVariationalAutoencoder.getPropDefault(NNVariationalAutoencoder.ITERATION_DIM), ...
		NNVariationalAutoencoder.NUM_MBQ_OUTPUT, NNVariationalAutoencoder.getPropDefault(NNVariationalAutoencoder.NUM_MBQ_OUTPUT), ...
		NNVariationalAutoencoder.MINIBATCH_FORMAT_INPUT, NNVariationalAutoencoder.getNoValue(), ...
		NNVariationalAutoencoder.MINIBATCH_FORMAT_TARGET, NNVariationalAutoencoder.getNoValue(), ...
		NNVariationalAutoencoder.ENCODER, NNVariationalAutoencoder.getPropDefault(NNVariationalAutoencoder.ENCODER), ...
		NNVariationalAutoencoder.DECODER, NNVariationalAutoencoder.getPropDefault(NNVariationalAutoencoder.DECODER), ...
		NNVariationalAutoencoder.MBQ, NNVariationalAutoencoder.getNoValue(), ...
		NNVariationalAutoencoder.LOSS_FN, NNVariationalAutoencoder.getNoValue() ...
		);
	 
	nnvae = NNVariationalAutoencoder( ...
		NNVariationalAutoencoder.ELCLASS, NNVariationalAutoencoder.getNoValue(), ...
		NNVariationalAutoencoder.NAME, NNVariationalAutoencoder.getNoValue(), ...
		NNVariationalAutoencoder.DESCRIPTION, NNVariationalAutoencoder.getNoValue(), ...
		NNVariationalAutoencoder.TEMPLATE, nnvae_0.getCallback(4), ..., ...
		NNVariationalAutoencoder.ID, nnvae_0.getCallback(5), ..., ...
		NNVariationalAutoencoder.LABEL, NNVariationalAutoencoder.getPropDefault(NNVariationalAutoencoder.LABEL), ...
		NNVariationalAutoencoder.NOTES, NNVariationalAutoencoder.getPropDefault(NNVariationalAutoencoder.NOTES), ...
		NNVariationalAutoencoder.TOSTRING, NNVariationalAutoencoder.getNoValue(), ...
		NNVariationalAutoencoder.D, nnvae_0.getCallback(9), ..., ...
		NNVariationalAutoencoder.DP_CLASSES, nnvae_0.getCallback(10), ..., ...
		NNVariationalAutoencoder.EPOCHS, nnvae_0.getCallback(11), ..., ...
		NNVariationalAutoencoder.BATCH, nnvae_0.getCallback(12), ..., ...
		NNVariationalAutoencoder.SHUFFLE, nnvae_0.getCallback(13), ..., ...
		NNVariationalAutoencoder.SOLVER, nnvae_0.getCallback(14), ..., ...
		NNVariationalAutoencoder.MODEL, NNVariationalAutoencoder.getNoValue(), ...
		NNVariationalAutoencoder.INPUTS, NNVariationalAutoencoder.getNoValue(), ...
		NNVariationalAutoencoder.TARGETS, NNVariationalAutoencoder.getNoValue(), ...
		NNVariationalAutoencoder.TRAIN, NNVariationalAutoencoder.getNoValue(), ...
		NNVariationalAutoencoder.VERBOSE, nnvae_0.getCallback(19), ..., ...
		NNVariationalAutoencoder.PLOT_TRAINING, NNVariationalAutoencoder.getPropDefault(NNVariationalAutoencoder.PLOT_TRAINING), ...
		NNVariationalAutoencoder.PREDICT, NNVariationalAutoencoder.getNoValue(), ...
		NNVariationalAutoencoder.LEARN_RATE, nnvae_0.getCallback(22), ..., ...
		NNVariationalAutoencoder.NUM_LATENT_REP, nnvae_0.getCallback(23), ..., ...
		NNVariationalAutoencoder.SIZE_INPUT, nnvae_0.getCallback(24), ..., ...
		NNVariationalAutoencoder.ITERATION_DIM, nnvae_0.getCallback(25), ..., ...
		NNVariationalAutoencoder.NUM_MBQ_OUTPUT, nnvae_0.getCallback(26), ..., ...
		NNVariationalAutoencoder.MINIBATCH_FORMAT_INPUT, NNVariationalAutoencoder.getNoValue(), ...
		NNVariationalAutoencoder.MINIBATCH_FORMAT_TARGET, NNVariationalAutoencoder.getNoValue(), ...
		NNVariationalAutoencoder.ENCODER, nnvae_0.getCallback(29), ..., ...
		NNVariationalAutoencoder.DECODER, nnvae_0.getCallback(30), ..., ...
		NNVariationalAutoencoder.MBQ, NNVariationalAutoencoder.getNoValue(), ...
		NNVariationalAutoencoder.LOSS_FN, NNVariationalAutoencoder.getNoValue() ...
		);
	 
	nnvae_copy = nnvae.copy();
	nnvae_0_copy = nnvae_copy.getr('ID').get('EL');
	 
	for prop = 1:1:NNVariationalAutoencoder.getPropNumber()
		value = nnvae.getr(prop);
		value_copy = nnvae_copy.getr(prop);
		switch NNVariationalAutoencoder.getPropCategory(prop)
			case {Category.EVANESCENT}
				assert( ...
					isa(value_copy, 'NoValue'), ...
					[BRAPH2.STR ':NNVariationalAutoencoder:' BRAPH2.FAIL_TEST], ...
					'NNVariationalAutoencoder.copy() does not work. The copied value of an EVANESCENT property must be NoValue.' ...
					)
			otherwise
				if isa(value, 'NoValue')
					assert( ...
						value_copy == value, ...
						[BRAPH2.STR ':NNVariationalAutoencoder:' BRAPH2.FAIL_TEST], ...
						'NNVariationalAutoencoder.copy() does not work. There should be a unique instance of NoValue.' ...
						)
				elseif isa(value, 'Element')
					assert( ...
						value_copy ~= value, ...
						[BRAPH2.STR ':NNVariationalAutoencoder:' BRAPH2.FAIL_TEST], ...
						'NNVariationalAutoencoder.copy() does not work. The handle of a copied element should point to a copied element.' ...
						)
					assert( ...
						isequal(value_copy, value), ...
						[BRAPH2.STR ':NNVariationalAutoencoder:' BRAPH2.FAIL_TEST], ...
						'NNVariationalAutoencoder.copy() does not work. When empty, a copied element should be equal to the element.' ...
						)
				elseif iscell(value) && all(all(cellfun(@(x) isa(x, 'Element'), value)))
					for j = 1:1:length(value)
						assert( ...
							value_copy ~= value, ...
							[BRAPH2.STR ':NNVariationalAutoencoder:' BRAPH2.FAIL_TEST], ...
							'NNVariationalAutoencoder.copy() does not work. The handle of a copied element should point to a copied element.' ...
							)
						assert( ...
							isequal(value_copy, value), ...
							[BRAPH2.STR ':NNVariationalAutoencoder:' BRAPH2.FAIL_TEST], ...
							'NNVariationalAutoencoder.copy() does not work. When empty, a copied element should be equal to the element.' ...
							)
					end
				else
					assert( ...
						isequal(value_copy, value), ...
						[BRAPH2.STR ':NNVariationalAutoencoder:' BRAPH2.FAIL_TEST], ...
						'NNVariationalAutoencoder.copy() does not work. The value copy should be equal to the original.' ...
						)
				end
				if isa(value, 'Callback')
					assert( ...
						value == nnvae_0.getCallback(prop), ...
						[BRAPH2.STR ':NNVariationalAutoencoder:' BRAPH2.FAIL_TEST], ...
						'NNVariationalAutoencoder.copy() does not work. The callback should be obtained from NNVariationalAutoencoder.getCallback().' ...
						)
					assert( ...
						value_copy == nnvae_0_copy.getCallback(prop), ...
						[BRAPH2.STR ':NNVariationalAutoencoder:' BRAPH2.FAIL_TEST], ...
						'NNVariationalAutoencoder.copy() does not work. The callback should be obtained from NNVariationalAutoencoder.getCallback().' ...
						)
				end
	 
					assert( ...
						nnvae_copy.isLocked(prop) == nnvae.isLocked(prop), ...
						[BRAPH2.STR ':NNVariationalAutoencoder:' BRAPH2.FAIL_TEST], ...
						'NNVariationalAutoencoder.copy() does not work. The locked status of the copied and original elements must be the same.' ...
						)
	 
					assert( ...
						nnvae_copy.isChecked(prop) == nnvae.isChecked(prop), ...
						[BRAPH2.STR ':NNVariationalAutoencoder:' BRAPH2.FAIL_TEST], ...
						'NNVariationalAutoencoder.copy() does not work. The checked status of the copied and original elements must be the same.' ...
						)
	 
					assert( ...
						nnvae_copy.getPropSeed(prop) == nnvae.getPropSeed(prop), ...
						[BRAPH2.STR ':NNVariationalAutoencoder:' BRAPH2.FAIL_TEST], ...
						'NNVariationalAutoencoder.copy() does not work. The randomization seeds of the copied and original elements must be the same.' ...
						)
		end
	end
	 
end

%% Test 9: Template
if rand() >= (1 - .01) * BRAPH2TEST.RANDOM
	nnvae_template = NNVariationalAutoencoder();
	nnvae = NNVariationalAutoencoder('TEMPLATE', nnvae_template);
	 
	for prop = 1:1:NNVariationalAutoencoder.getPropNumber()
	 
		% excluded props
		if any(prop == [])
			continue
		end
	 
		TAG = upper(NNVariationalAutoencoder.getPropTag(prop));
		switch NNVariationalAutoencoder.getPropCategory(prop)
			case {Category.PARAMETER}
				if prop == NNVariationalAutoencoder.TEMPLATE
					assert( ...
						isa(nnvae.getr(prop), 'NNVariationalAutoencoder'), ...
						[BRAPH2.STR ':NNVariationalAutoencoder:' BRAPH2.FAIL_TEST], ...
						'NNVariationalAutoencoder TEMPLATE does not work. NNVariationalAutoencoder.getr(''TEMPLATE'') should be a NNVariationalAutoencoder element.' ...
						)
					assert( ...
						isa(nnvae_template.getr(prop), 'NoValue'), ...
						[BRAPH2.STR ':NNVariationalAutoencoder:' BRAPH2.FAIL_TEST], ...
						'NNVariationalAutoencoder TEMPLATE does not work. NNVariationalAutoencoder_template.getr(''TEMPLATE'') should be a NoValue.' ...
						)
				else
					assert( ...
						isa(nnvae.getr(prop), 'Callback'), ...
						[BRAPH2.STR ':NNVariationalAutoencoder:' BRAPH2.FAIL_TEST], ...
						['NNVariationalAutoencoder TEMPLATE does not work. NNVariationalAutoencoder.getr(' TAG ') should be a Callback.'] ...
						)
					assert( ...
						nnvae.getr(prop).get('EL') == nnvae_template && nnvae.getr(prop).get('PROP') == prop && strcmp(nnvae.getr(prop).get('TAG'), TAG), ...
						[BRAPH2.STR ':NNVariationalAutoencoder:' BRAPH2.FAIL_TEST], ...
						['NNVariationalAutoencoder TEMPLATE does not work. NNVariationalAutoencoder.getr(' TAG ') should be a Callback to nnvae_template.' TAG '.'] ...
						)
					assert( ...
						isa(nnvae_template.getr(prop), 'NoValue'), ...
						[BRAPH2.STR ':NNVariationalAutoencoder:' BRAPH2.FAIL_TEST], ...
						['NNVariationalAutoencoder TEMPLATE does not work. NNVariationalAutoencoder_template.getr(' TAG ') should be a NoValue.'] ...
						)
				end
			otherwise
				assert( ...
					isa(nnvae.getr(prop), 'NoValue'), ...
					[BRAPH2.STR ':NNVariationalAutoencoder:' BRAPH2.FAIL_TEST], ...
					['NNVariationalAutoencoder TEMPLATE does not work. NNVariationalAutoencoder.getr(' TAG ') should be a NoValue.'] ...
					)
				assert( ...
					isa(nnvae_template.getr(prop), 'NoValue'), ...
					[BRAPH2.STR ':NNVariationalAutoencoder:' BRAPH2.FAIL_TEST], ...
					['NNVariationalAutoencoder TEMPLATE does not work. NNVariationalAutoencoder_template.getr(' TAG ') should be a NoValue.'] ...
					)
		end
	end
end

%% Test 10: Save Load
if rand() >= (1 - .01) * BRAPH2TEST.RANDOM
	nnvae = NNVariationalAutoencoder( ...
		NNVariationalAutoencoder.ELCLASS, NNVariationalAutoencoder.getNoValue(), ...
		NNVariationalAutoencoder.NAME, NNVariationalAutoencoder.getNoValue(), ...
		NNVariationalAutoencoder.DESCRIPTION, NNVariationalAutoencoder.getNoValue(), ...
		NNVariationalAutoencoder.TEMPLATE, NNVariationalAutoencoder.getPropDefault(NNVariationalAutoencoder.TEMPLATE), ...
		NNVariationalAutoencoder.ID, NNVariationalAutoencoder.getPropDefault(NNVariationalAutoencoder.ID), ...
		NNVariationalAutoencoder.LABEL, NNVariationalAutoencoder.getPropDefault(NNVariationalAutoencoder.LABEL), ...
		NNVariationalAutoencoder.NOTES, NNVariationalAutoencoder.getPropDefault(NNVariationalAutoencoder.NOTES), ...
		NNVariationalAutoencoder.TOSTRING, NNVariationalAutoencoder.getNoValue(), ...
		NNVariationalAutoencoder.D, NNVariationalAutoencoder.getPropDefault(NNVariationalAutoencoder.D), ...
		NNVariationalAutoencoder.DP_CLASSES, NNVariationalAutoencoder.getPropDefault(NNVariationalAutoencoder.DP_CLASSES), ...
		NNVariationalAutoencoder.EPOCHS, NNVariationalAutoencoder.getPropDefault(NNVariationalAutoencoder.EPOCHS), ...
		NNVariationalAutoencoder.BATCH, NNVariationalAutoencoder.getPropDefault(NNVariationalAutoencoder.BATCH), ...
		NNVariationalAutoencoder.SHUFFLE, NNVariationalAutoencoder.getPropDefault(NNVariationalAutoencoder.SHUFFLE), ...
		NNVariationalAutoencoder.SOLVER, NNVariationalAutoencoder.getPropDefault(NNVariationalAutoencoder.SOLVER), ...
		NNVariationalAutoencoder.MODEL, NNVariationalAutoencoder.getNoValue(), ...
		NNVariationalAutoencoder.INPUTS, NNVariationalAutoencoder.getNoValue(), ...
		NNVariationalAutoencoder.TARGETS, NNVariationalAutoencoder.getNoValue(), ...
		NNVariationalAutoencoder.TRAIN, NNVariationalAutoencoder.getNoValue(), ...
		NNVariationalAutoencoder.VERBOSE, NNVariationalAutoencoder.getPropDefault(NNVariationalAutoencoder.VERBOSE), ...
		NNVariationalAutoencoder.PLOT_TRAINING, NNVariationalAutoencoder.getPropDefault(NNVariationalAutoencoder.PLOT_TRAINING), ...
		NNVariationalAutoencoder.PREDICT, NNVariationalAutoencoder.getNoValue(), ...
		NNVariationalAutoencoder.LEARN_RATE, NNVariationalAutoencoder.getPropDefault(NNVariationalAutoencoder.LEARN_RATE), ...
		NNVariationalAutoencoder.NUM_LATENT_REP, NNVariationalAutoencoder.getPropDefault(NNVariationalAutoencoder.NUM_LATENT_REP), ...
		NNVariationalAutoencoder.SIZE_INPUT, NNVariationalAutoencoder.getPropDefault(NNVariationalAutoencoder.SIZE_INPUT), ...
		NNVariationalAutoencoder.ITERATION_DIM, NNVariationalAutoencoder.getPropDefault(NNVariationalAutoencoder.ITERATION_DIM), ...
		NNVariationalAutoencoder.NUM_MBQ_OUTPUT, NNVariationalAutoencoder.getPropDefault(NNVariationalAutoencoder.NUM_MBQ_OUTPUT), ...
		NNVariationalAutoencoder.MINIBATCH_FORMAT_INPUT, NNVariationalAutoencoder.getNoValue(), ...
		NNVariationalAutoencoder.MINIBATCH_FORMAT_TARGET, NNVariationalAutoencoder.getNoValue(), ...
		NNVariationalAutoencoder.ENCODER, NNVariationalAutoencoder.getPropDefault(NNVariationalAutoencoder.ENCODER), ...
		NNVariationalAutoencoder.DECODER, NNVariationalAutoencoder.getPropDefault(NNVariationalAutoencoder.DECODER), ...
		NNVariationalAutoencoder.MBQ, NNVariationalAutoencoder.getNoValue(), ...
		NNVariationalAutoencoder.LOSS_FN, NNVariationalAutoencoder.getNoValue() ...
		);
	 
	filename = [fileparts(which('test_braph2')) filesep 'nnvariationalautoencoder_to_be_erased.b2'];
	 
	Element.save(nnvae, filename)
	 
	nnvae_loaded = Element.load(filename);
	 
	assert( ...
		isequal(nnvae.copy(), nnvae_loaded), ...
		[BRAPH2.STR ':NNVariationalAutoencoder:' BRAPH2.FAIL_TEST], ...
		'NNVariationalAutoencoder.save(nnvae) and/or NNVariationalAutoencoder.load() do not work.' ...
		)
	 
	delete(filename)
end

%% Test 11: JSON
if rand() >= (1 - .01) * BRAPH2TEST.RANDOM
	nnvae = NNVariationalAutoencoder( ...
		NNVariationalAutoencoder.ELCLASS, NNVariationalAutoencoder.getNoValue(), ...
		NNVariationalAutoencoder.NAME, NNVariationalAutoencoder.getNoValue(), ...
		NNVariationalAutoencoder.DESCRIPTION, NNVariationalAutoencoder.getNoValue(), ...
		NNVariationalAutoencoder.TEMPLATE, NNVariationalAutoencoder.getPropDefault(NNVariationalAutoencoder.TEMPLATE), ...
		NNVariationalAutoencoder.ID, NNVariationalAutoencoder.getPropDefault(NNVariationalAutoencoder.ID), ...
		NNVariationalAutoencoder.LABEL, NNVariationalAutoencoder.getPropDefault(NNVariationalAutoencoder.LABEL), ...
		NNVariationalAutoencoder.NOTES, NNVariationalAutoencoder.getPropDefault(NNVariationalAutoencoder.NOTES), ...
		NNVariationalAutoencoder.TOSTRING, NNVariationalAutoencoder.getNoValue(), ...
		NNVariationalAutoencoder.D, NNVariationalAutoencoder.getPropDefault(NNVariationalAutoencoder.D), ...
		NNVariationalAutoencoder.DP_CLASSES, NNVariationalAutoencoder.getPropDefault(NNVariationalAutoencoder.DP_CLASSES), ...
		NNVariationalAutoencoder.EPOCHS, NNVariationalAutoencoder.getPropDefault(NNVariationalAutoencoder.EPOCHS), ...
		NNVariationalAutoencoder.BATCH, NNVariationalAutoencoder.getPropDefault(NNVariationalAutoencoder.BATCH), ...
		NNVariationalAutoencoder.SHUFFLE, NNVariationalAutoencoder.getPropDefault(NNVariationalAutoencoder.SHUFFLE), ...
		NNVariationalAutoencoder.SOLVER, NNVariationalAutoencoder.getPropDefault(NNVariationalAutoencoder.SOLVER), ...
		NNVariationalAutoencoder.MODEL, NNVariationalAutoencoder.getNoValue(), ...
		NNVariationalAutoencoder.INPUTS, NNVariationalAutoencoder.getNoValue(), ...
		NNVariationalAutoencoder.TARGETS, NNVariationalAutoencoder.getNoValue(), ...
		NNVariationalAutoencoder.TRAIN, NNVariationalAutoencoder.getNoValue(), ...
		NNVariationalAutoencoder.VERBOSE, NNVariationalAutoencoder.getPropDefault(NNVariationalAutoencoder.VERBOSE), ...
		NNVariationalAutoencoder.PLOT_TRAINING, NNVariationalAutoencoder.getPropDefault(NNVariationalAutoencoder.PLOT_TRAINING), ...
		NNVariationalAutoencoder.PREDICT, NNVariationalAutoencoder.getNoValue(), ...
		NNVariationalAutoencoder.LEARN_RATE, NNVariationalAutoencoder.getPropDefault(NNVariationalAutoencoder.LEARN_RATE), ...
		NNVariationalAutoencoder.NUM_LATENT_REP, NNVariationalAutoencoder.getPropDefault(NNVariationalAutoencoder.NUM_LATENT_REP), ...
		NNVariationalAutoencoder.SIZE_INPUT, NNVariationalAutoencoder.getPropDefault(NNVariationalAutoencoder.SIZE_INPUT), ...
		NNVariationalAutoencoder.ITERATION_DIM, NNVariationalAutoencoder.getPropDefault(NNVariationalAutoencoder.ITERATION_DIM), ...
		NNVariationalAutoencoder.NUM_MBQ_OUTPUT, NNVariationalAutoencoder.getPropDefault(NNVariationalAutoencoder.NUM_MBQ_OUTPUT), ...
		NNVariationalAutoencoder.MINIBATCH_FORMAT_INPUT, NNVariationalAutoencoder.getNoValue(), ...
		NNVariationalAutoencoder.MINIBATCH_FORMAT_TARGET, NNVariationalAutoencoder.getNoValue(), ...
		NNVariationalAutoencoder.ENCODER, NNVariationalAutoencoder.getPropDefault(NNVariationalAutoencoder.ENCODER), ...
		NNVariationalAutoencoder.DECODER, NNVariationalAutoencoder.getPropDefault(NNVariationalAutoencoder.DECODER), ...
		NNVariationalAutoencoder.MBQ, NNVariationalAutoencoder.getNoValue(), ...
		NNVariationalAutoencoder.LOSS_FN, NNVariationalAutoencoder.getNoValue() ...
		);
	 
	[json, struct, el_list] = encodeJSON(nnvae);
	[nnvae_dec, struct_dec, el_list_dec] = Element.decodeJSON(json);
	 
	assert(nnvae_dec ~= nnvae, ...
		[BRAPH2.STR ':NNVariationalAutoencoder:' BRAPH2.FAIL_TEST], ...
		'NNVariationalAutoencoder.encodeJSON() or NNVariationalAutoencoder.decodeJSON() does not work. A JSON encoded/decoded element must point to an element other than the original one.' ...
		)
	if all(cellfun(@(prop) NNVariationalAutoencoder.getPropFormat(prop), num2cell(NNVariationalAutoencoder.getProps())) == Format.HANDLE) && all(cellfun(@(prop) NNVariationalAutoencoder.getPropFormat(prop), num2cell(NNVariationalAutoencoder.getProps())) == Format.NET)
		assert(isequal(nnvae_dec, nnvae), ...
			[BRAPH2.STR ':NNVariationalAutoencoder:' BRAPH2.FAIL_TEST], ...
			'NNVariationalAutoencoder.encodeJSON() or NNVariationalAutoencoder.decodeJSON() does not work. A JSON encoded/decoded element must have the same property values of the original element.' ...
			)
	end
end

%% Test 12: No Figures Left
if rand() >= (1 - 1) * BRAPH2TEST.RANDOM
	assert(isempty(findall(0, 'type', 'figure')), ...
		[BRAPH2.STR ':NNVariationalAutoencoder:' BRAPH2.FAIL_TEST], ...
		[' When testing NNVariationalAutoencoder no figures should be left over, either visible or not. ' ...
		int2str(length(findall(0, 'type', 'figure'))) ' figure(s) were left over.'] ...
		)
end

%% Test 13: Delete Figures
if rand() >= (1 - 1) * BRAPH2TEST.RANDOM
	delete(findall(0, 'type', 'figure'))
end

