%TEST_NNDATASETPROCESS

%% Test 1: Inspection Methods
if rand() >= (1 - .01) * BRAPH2TEST.RANDOM
	categories = num2cell(Category.getCategories());
	dtran = NNDatasetProcess();
	 
	% get('ELCLASS')
	if isa(NNDatasetProcess, 'ConcreteElement')
		assert(strcmp(NNDatasetProcess().get('ELCLASS'), 'NNDatasetProcess'), ...
			[BRAPH2.STR ':NNDatasetProcess:' BRAPH2.FAIL_TEST], ...
			'NNDatasetProcess().get(''ELCLASS'') should return ''NNDatasetProcess''.')
	end
	 
	% getBuild()
	assert(NNDatasetProcess.getBuild() == 1 && NNDatasetProcess.getBuild() > 0, ...
		[BRAPH2.STR ':NNDatasetProcess:' BRAPH2.FAIL_TEST], ...
		'NNDatasetProcess.getBuild() should return the NNDatasetProcess build number.')
	assert(dtran.getBuild() == 1 && dtran.getBuild() > 0 , ...
		[BRAPH2.STR ':NNDatasetProcess:' BRAPH2.FAIL_TEST], ...
		'dtran.getBuild() should return the NNDatasetProcess build number.')
	assert(Element.getBuild(dtran) == 1 && Element.getBuild(dtran) > 0, ...
		[BRAPH2.STR ':NNDatasetProcess:' BRAPH2.FAIL_TEST], ...
		'Element.getBuild(dtran) should return the NNDatasetProcess build number.')
	assert(Element.getBuild('NNDatasetProcess') == 1 && Element.getBuild('NNDatasetProcess') > 0, ...
		[BRAPH2.STR ':NNDatasetProcess:' BRAPH2.FAIL_TEST], ...
		'Element.getBuild(''NNDatasetProcess'') should return the NNDatasetProcess build number.')
	 
	% getClass()
	assert(strcmp(NNDatasetProcess.getClass(), 'NNDatasetProcess'), ...
		[BRAPH2.STR ':NNDatasetProcess:' BRAPH2.FAIL_TEST], ...
		'NNDatasetProcess.getClass() should return ''NNDatasetProcess''.')
	assert(strcmp(dtran.getClass(), 'NNDatasetProcess'), ...
		[BRAPH2.STR ':NNDatasetProcess:' BRAPH2.FAIL_TEST], ...
		'dtran.getClass() should return ''NNDatasetProcess''.')
	assert(strcmp(Element.getClass(dtran), 'NNDatasetProcess'), ...
		[BRAPH2.STR ':NNDatasetProcess:' BRAPH2.FAIL_TEST], ...
		'Element.getClass(dtran) should return ''NNDatasetProcess''.')
	assert(strcmp(Element.getClass('NNDatasetProcess'), 'NNDatasetProcess'), ...
		[BRAPH2.STR ':NNDatasetProcess:' BRAPH2.FAIL_TEST], ...
		'Element.getClass(''NNDatasetProcess'') should return ''NNDatasetProcess''.')
	 
	% getSubclasses()
	assert(isequal(NNDatasetProcess.getSubclasses(), subclasses('NNDatasetProcess', [], [], true)), ...
		[BRAPH2.STR ':NNDatasetProcess:' BRAPH2.FAIL_TEST], ...
		'NNDatasetProcess.getSubclasses() should return the same result as subclasses(''NNDatasetProcess'', [], [], true).')
	assert(isequal(dtran.getSubclasses(), subclasses('NNDatasetProcess', [], [], true)), ...
		[BRAPH2.STR ':NNDatasetProcess:' BRAPH2.FAIL_TEST], ...
		'el.getSubclasses() should return the same result as subclasses(''NNDatasetProcess'', [], [], true).')
	assert(isequal(Element.getSubclasses(dtran), subclasses('NNDatasetProcess', [], [], true)), ...
		[BRAPH2.STR ':NNDatasetProcess:' BRAPH2.FAIL_TEST], ...
		'Element.getSubclasses(dtran) should return the same result as subclasses(''NNDatasetProcess'', [], [], true).')
	assert(isequal(Element.getSubclasses('NNDatasetProcess'), subclasses('NNDatasetProcess', [], [], true)), ...
		[BRAPH2.STR ':NNDatasetProcess:' BRAPH2.FAIL_TEST], ...
		'Element.getSubclasses(''NNDatasetProcess'') should return the same result as subclasses(''NNDatasetProcess'', [], [], true).')
	 
	% getProps()
	assert(isempty(NNDatasetProcess.getProps()) || isequal(NNDatasetProcess.getProps(), 1:1:length(NNDatasetProcess.getProps())), ...
		[BRAPH2.STR ':NNDatasetProcess:' BRAPH2.FAIL_TEST], ...
		'NNDatasetProcess.getProps() should return a row vector [1:1:N].')
	assert(isempty(NNDatasetProcess.getProps()) || isequal(dtran.getProps(), 1:1:length(NNDatasetProcess.getProps())), ...
		[BRAPH2.STR ':NNDatasetProcess:' BRAPH2.FAIL_TEST], ...
		'dtran.getProps() should return a row vector [1:1:N].')
	assert(isempty(NNDatasetProcess.getProps()) || isequal(Element.getProps(dtran), 1:1:length(NNDatasetProcess.getProps())), ...
		[BRAPH2.STR ':NNDatasetProcess:' BRAPH2.FAIL_TEST], ...
		'Element.getProps(dtran) should return a row vector [1:1:N].')
	assert(isempty(NNDatasetProcess.getProps()) || isequal(Element.getProps('NNDatasetProcess'), 1:1:length(NNDatasetProcess.getProps())), ...
		[BRAPH2.STR ':NNDatasetProcess:' BRAPH2.FAIL_TEST], ...
		'Element.getProps(''NNDatasetProcess'') should return a row vector [1:1:N].')
	 
	% getProps(category)
	tmp = cellfun(@(category) NNDatasetProcess.getProps(category), categories, 'UniformOutput', false);
	assert(isempty(NNDatasetProcess.getProps()) || isequal(sort(horzcat(tmp{:})), 1:1:length(NNDatasetProcess.getProps())), ...
		[BRAPH2.STR ':NNDatasetProcess:' BRAPH2.FAIL_TEST], ...
		'NNDatasetProcess.getProps(category) does not work.')
	tmp = cellfun(@(category) dtran.getProps(category), categories, 'UniformOutput', false);
	assert(isempty(NNDatasetProcess.getProps()) || isequal(sort(horzcat(tmp{:})), 1:1:length(NNDatasetProcess.getProps())), ...
		[BRAPH2.STR ':NNDatasetProcess:' BRAPH2.FAIL_TEST], ...
		'dtran.getProps(category) does not work.')
	tmp = cellfun(@(category) Element.getProps(dtran, category), categories, 'UniformOutput', false);
	assert(isempty(NNDatasetProcess.getProps()) || isequal(sort(horzcat(tmp{:})), 1:1:length(NNDatasetProcess.getProps())), ...
		[BRAPH2.STR ':NNDatasetProcess:' BRAPH2.FAIL_TEST], ...
		'Element.getProps(dtran, category) does not work.')
	tmp = cellfun(@(category) Element.getProps('NNDatasetProcess', category), categories, 'UniformOutput', false);
	assert(isempty(NNDatasetProcess.getProps()) || isequal(sort(horzcat(tmp{:})), 1:1:length(NNDatasetProcess.getProps())), ...
		[BRAPH2.STR ':NNDatasetProcess:' BRAPH2.FAIL_TEST], ...
		'Element.getProps(''NNDatasetProcess'', category) does not work.')
	 
	% getPropNumber()
	assert(NNDatasetProcess.getPropNumber() == length(NNDatasetProcess.getProps()), ...
		[BRAPH2.STR ':NNDatasetProcess:' BRAPH2.FAIL_TEST], ...
		'NNDatasetProcess.getPropNumber() should return the number of properties.')
	assert(dtran.getPropNumber() == length(NNDatasetProcess.getProps()), ...
		[BRAPH2.STR ':NNDatasetProcess:' BRAPH2.FAIL_TEST], ...
		'dtran.getPropNumber() should return the number of properties.')
	assert(Element.getPropNumber(dtran) == length(NNDatasetProcess.getProps()), ...
		[BRAPH2.STR ':NNDatasetProcess:' BRAPH2.FAIL_TEST], ...
		'Element.getPropNumber(dtran) should return the number of properties.')
	assert(Element.getPropNumber('NNDatasetProcess') == length(NNDatasetProcess.getProps()), ...
		[BRAPH2.STR ':NNDatasetProcess:' BRAPH2.FAIL_TEST], ...
		'Element.getPropNumber(''NNDatasetProcess'') should return the number of properties.')
	 
	% getPropNumber(category)
	assert(sum(cellfun(@(category) NNDatasetProcess.getPropNumber(category), categories)) == NNDatasetProcess.getPropNumber(), ...
		[BRAPH2.STR ':NNDatasetProcess:' BRAPH2.FAIL_TEST], ...
		'NNDatasetProcess.getPropNumber(category) does not work.')
	assert(sum(cellfun(@(category) dtran.getPropNumber(category), categories)) == NNDatasetProcess.getPropNumber(), ...
		[BRAPH2.STR ':NNDatasetProcess:' BRAPH2.FAIL_TEST], ...
		'dtran.getPropNumber(category) does not work.')
	assert(sum(cellfun(@(category) Element.getPropNumber(dtran, category), categories)) == NNDatasetProcess.getPropNumber(), ...
		[BRAPH2.STR ':NNDatasetProcess:' BRAPH2.FAIL_TEST], ...
		'Element.getPropNumber(dtran, category) does not work.')
	assert(sum(cellfun(@(category) Element.getPropNumber('NNDatasetProcess', category), categories)) == NNDatasetProcess.getPropNumber(), ...
		[BRAPH2.STR ':NNDatasetProcess:' BRAPH2.FAIL_TEST], ...
		'Element.getPropNumber(''NNDatasetProcess'', category) does not work.')
	 
	% existsProp(prop)
	assert(~NNDatasetProcess.existsProp(NaN), ...
		[BRAPH2.STR ':NNDatasetProcess:' BRAPH2.FAIL_TEST], ...
		'NNDatasetProcess.existsProp(prop) does not work.')
	assert(~dtran.existsProp(NaN), ...
		[BRAPH2.STR ':NNDatasetProcess:' BRAPH2.FAIL_TEST], ...
		'dtran.existsProp(prop) does not work.')
	assert(~Element.existsProp(dtran, NaN), ...
		[BRAPH2.STR ':NNDatasetProcess:' BRAPH2.FAIL_TEST], ...
		'Element.existsProp(dtran, prop) does not work.')
	assert(~Element.existsProp('NNDatasetProcess', NaN), ...
		[BRAPH2.STR ':NNDatasetProcess:' BRAPH2.FAIL_TEST], ...
		'Element.existsProp(''NNDatasetProcess'', prop) does not work.')
	 
	assert_with_error('NNDatasetProcess.existsProp(NaN)', [BRAPH2.STR ':NNDatasetProcess:' BRAPH2.WRONG_INPUT])
	assert_with_error('varargin{1}.existsProp(NaN)', [BRAPH2.STR ':NNDatasetProcess:' BRAPH2.WRONG_INPUT], dtran)
	assert_with_error('Element.existsProp(varargin{1}, NaN)', [BRAPH2.STR ':NNDatasetProcess:' BRAPH2.WRONG_INPUT], dtran)
	assert_with_error('Element.existsProp(''NNDatasetProcess'', NaN)', [BRAPH2.STR ':NNDatasetProcess:' BRAPH2.WRONG_INPUT])
	 
	for prop = 1:1:NNDatasetProcess.getPropNumber()
		assert(NNDatasetProcess.existsProp(prop), ...
			[BRAPH2.STR ':NNDatasetProcess:' BRAPH2.FAIL_TEST], ...
			'NNDatasetProcess.existsProp(prop) does not work.')
		assert(dtran.existsProp(prop), ...
			[BRAPH2.STR ':NNDatasetProcess:' BRAPH2.FAIL_TEST], ...
			'dtran.existsProp(prop) does not work.')
		assert(Element.existsProp(dtran, prop), ...
			[BRAPH2.STR ':NNDatasetProcess:' BRAPH2.FAIL_TEST], ...
			'Element.existsProp(dtran, prop) does not work.')
		assert(Element.existsProp('NNDatasetProcess', prop), ...
			[BRAPH2.STR ':NNDatasetProcess:' BRAPH2.FAIL_TEST], ...
			'Element.existsProp(''NNDatasetProcess'', prop) does not work.')
	end
	 
	% existsTag(tag)
	assert(~NNDatasetProcess.existsTag(''), ...
		[BRAPH2.STR ':NNDatasetProcess:' BRAPH2.FAIL_TEST], ...
		'NNDatasetProcess.existsTag(tag) does not work.')
	assert(~dtran.existsTag(''), ...
		[BRAPH2.STR ':NNDatasetProcess:' BRAPH2.FAIL_TEST], ...
		'dtran.existsTag(tag) does not work.')
	assert(~Element.existsTag(dtran, ''), ...
		[BRAPH2.STR ':NNDatasetProcess:' BRAPH2.FAIL_TEST], ...
		'Element.existsTag(dtran, tag) does not work.')
	assert(~Element.existsTag('NNDatasetProcess', ''), ...
		[BRAPH2.STR ':NNDatasetProcess:' BRAPH2.FAIL_TEST], ...
		'Element.existsTag(''NNDatasetProcess'', tag) does not work.')
	 
	assert_with_error('NNDatasetProcess.existsTag('''')', [BRAPH2.STR ':NNDatasetProcess:' BRAPH2.WRONG_INPUT])
	assert_with_error('varargin{1}.existsTag('''')', [BRAPH2.STR ':NNDatasetProcess:' BRAPH2.WRONG_INPUT], dtran)
	assert_with_error('Element.existsTag(varargin{1}, '''')', [BRAPH2.STR ':NNDatasetProcess:' BRAPH2.WRONG_INPUT], dtran)
	assert_with_error('Element.existsTag(''NNDatasetProcess'', '''')', [BRAPH2.STR ':NNDatasetProcess:' BRAPH2.WRONG_INPUT])
	 
	for prop = 1:1:NNDatasetProcess.getPropNumber()
		tag = dtran.getPropTag(prop);
		assert(NNDatasetProcess.existsTag(tag), ...
			[BRAPH2.STR ':NNDatasetProcess:' BRAPH2.FAIL_TEST], ...
			'NNDatasetProcess.existsTag(tag) does not work.')
		assert(dtran.existsTag(tag), ...
			[BRAPH2.STR ':NNDatasetProcess:' BRAPH2.FAIL_TEST], ...
			'dtran.existsTag(tag) does not work.')
		assert(Element.existsTag(dtran, tag), ...
			[BRAPH2.STR ':NNDatasetProcess:' BRAPH2.FAIL_TEST], ...
			'Element.existsTag(dtran, tga) does not work.')
		assert(Element.existsTag('NNDatasetProcess', tag), ...
			[BRAPH2.STR ':NNDatasetProcess:' BRAPH2.FAIL_TEST], ...
			'Element.existsTag(''NNDatasetProcess'', tag) does not work.')
	end
	 
	% getPropProp(pointer)
	for prop = 1:1:NNDatasetProcess.getPropNumber()
		assert(NNDatasetProcess.getPropProp(prop) == prop, ...
			[BRAPH2.STR ':NNDatasetProcess:' BRAPH2.FAIL_TEST], ...
			'NNDatasetProcess.getPropProp(prop) does not work.')
		assert(dtran.getPropProp(prop) == prop, ...
			[BRAPH2.STR ':NNDatasetProcess:' BRAPH2.FAIL_TEST], ...
			'dtran.getPropProp(prop) does not work.')
		assert(Element.getPropProp(dtran, prop) == prop, ...
			[BRAPH2.STR ':NNDatasetProcess:' BRAPH2.FAIL_TEST], ...
			'Element.getPropProp(dtran, prop) does not work.')
		assert(Element.getPropProp('NNDatasetProcess', prop) == prop, ...
			[BRAPH2.STR ':NNDatasetProcess:' BRAPH2.FAIL_TEST], ...
			'Element.getPropProp(''NNDatasetProcess'', prop) does not work.')
	 
		tag = dtran.getPropTag(prop);
		assert(NNDatasetProcess.getPropProp(tag) == prop, ...
			[BRAPH2.STR ':NNDatasetProcess:' BRAPH2.FAIL_TEST], ...
			'NNDatasetProcess.getPropProp(tag) does not work.')
		assert(dtran.getPropProp(tag) == prop, ...
			[BRAPH2.STR ':NNDatasetProcess:' BRAPH2.FAIL_TEST], ...
			'dtran.getPropProp(tag) does not work.')
		assert(Element.getPropProp(dtran, tag) == prop, ...
			[BRAPH2.STR ':NNDatasetProcess:' BRAPH2.FAIL_TEST], ...
			'Element.getPropProp(dtran, tag) does not work.')
		assert(Element.getPropProp('NNDatasetProcess', prop) == prop, ...
			[BRAPH2.STR ':NNDatasetProcess:' BRAPH2.FAIL_TEST], ...
			'Element.getPropProp(''NNDatasetProcess'', tag) does not work.')
	end
	 
	% getPropTag(pointer)
	for prop = 1:1:NNDatasetProcess.getPropNumber()
		tag = dtran.getPropTag(prop);
	 
		assert(strcmp(NNDatasetProcess.getPropTag(prop), tag), ...
			[BRAPH2.STR ':NNDatasetProcess:' BRAPH2.FAIL_TEST], ...
			'NNDatasetProcess.getPropTag(prop) does not work.')
		assert(strcmp(dtran.getPropTag(prop), tag), ...
			[BRAPH2.STR ':NNDatasetProcess:' BRAPH2.FAIL_TEST], ...
			'dtran.getPropTag(prop) does not work.')
		assert(strcmp(Element.getPropTag(dtran, prop), tag), ...
			[BRAPH2.STR ':NNDatasetProcess:' BRAPH2.FAIL_TEST], ...
			'Element.getPropTag(dtran, prop) does not work.')
		assert(strcmp(Element.getPropTag('NNDatasetProcess', prop), tag), ...
			[BRAPH2.STR ':NNDatasetProcess:' BRAPH2.FAIL_TEST], ...
			'Element.getPropTag(''NNDatasetProcess'', prop) does not work.')
	 
		assert(strcmp(NNDatasetProcess.getPropTag(tag), tag), ...
			[BRAPH2.STR ':NNDatasetProcess:' BRAPH2.FAIL_TEST], ...
			'NNDatasetProcess.getPropTag(tag) does not work.')
		assert(strcmp(dtran.getPropTag(tag), tag), ...
			[BRAPH2.STR ':NNDatasetProcess:' BRAPH2.FAIL_TEST], ...
			'dtran.getPropTag(tag) does not work.')
		assert(strcmp(Element.getPropTag(dtran, tag), tag), ...
			[BRAPH2.STR ':NNDatasetProcess:' BRAPH2.FAIL_TEST], ...
			'Element.getPropTag(dtran, tag) does not work.')
		assert(strcmp(Element.getPropTag('NNDatasetProcess', prop), tag), ...
			[BRAPH2.STR ':NNDatasetProcess:' BRAPH2.FAIL_TEST], ...
			'Element.getPropTag(''NNDatasetProcess'', tag) does not work.')
	end
	 
	% getPropCategory(pointer)
	for prop = 1:1:NNDatasetProcess.getPropNumber()
		tag = dtran.getPropTag(prop);
	 
		assert(Category.existsCategory(NNDatasetProcess.getPropCategory(prop)), ...
			[BRAPH2.STR ':NNDatasetProcess:' BRAPH2.FAIL_TEST], ...
			'NNDatasetProcess.getPropCategory(prop) does not work.')
		assert(Category.existsCategory(dtran.getPropCategory(prop)), ...
			[BRAPH2.STR ':NNDatasetProcess:' BRAPH2.FAIL_TEST], ...
			'dtran.getPropCategory(prop) does not work.')
		assert(Category.existsCategory(Element.getPropCategory(dtran, prop)), ...
			[BRAPH2.STR ':NNDatasetProcess:' BRAPH2.FAIL_TEST], ...
			'Element.getPropCategory(dtran, prop) does not work.')
		assert(Category.existsCategory(Element.getPropCategory(dtran, prop)), ...
			[BRAPH2.STR ':NNDatasetProcess:' BRAPH2.FAIL_TEST], ...
			'Element.getPropCategory(''NNDatasetProcess'', prop) does not work.')
	 
		assert(Category.existsCategory(NNDatasetProcess.getPropCategory(tag)), ...
			[BRAPH2.STR ':NNDatasetProcess:' BRAPH2.FAIL_TEST], ...
			'NNDatasetProcess.getPropCategory(tag) does not work.')
		assert(Category.existsCategory(dtran.getPropCategory(tag)), ...
			[BRAPH2.STR ':NNDatasetProcess:' BRAPH2.FAIL_TEST], ...
			'dtran.getPropCategory(tag) does not work.')
		assert(Category.existsCategory(Element.getPropCategory(dtran, tag)), ...
			[BRAPH2.STR ':NNDatasetProcess:' BRAPH2.FAIL_TEST], ...
			'Element.getPropCategory(dtran, tag) does not work.')
		assert(Category.existsCategory(Element.getPropCategory(dtran, tag)), ...
			[BRAPH2.STR ':NNDatasetProcess:' BRAPH2.FAIL_TEST], ...
			'Element.getPropCategory(''NNDatasetProcess'', tag) does not work.')
	end
	 
	% getPropFormat(pointer)
	for prop = 1:1:NNDatasetProcess.getPropNumber()
		tag = dtran.getPropTag(prop);
	 
		assert(Format.existsFormat(NNDatasetProcess.getPropFormat(prop)), ...
			[BRAPH2.STR ':NNDatasetProcess:' BRAPH2.FAIL_TEST], ...
			'NNDatasetProcess.getPropFormat(prop) does not work.')
		assert(Format.existsFormat(dtran.getPropFormat(prop)), ...
			[BRAPH2.STR ':NNDatasetProcess:' BRAPH2.FAIL_TEST], ...
			'dtran.getPropFormat(prop) does not work.')
		assert(Format.existsFormat(Element.getPropFormat(dtran, prop)), ...
			[BRAPH2.STR ':NNDatasetProcess:' BRAPH2.FAIL_TEST], ...
			'Element.getPropFormat(dtran, prop) does not work.')
		assert(Format.existsFormat(Element.getPropFormat(dtran, prop)), ...
			[BRAPH2.STR ':NNDatasetProcess:' BRAPH2.FAIL_TEST], ...
			'Element.getPropFormat(''NNDatasetProcess'', prop) does not work.')
	 
		assert(Format.existsFormat(NNDatasetProcess.getPropFormat(tag)), ...
			[BRAPH2.STR ':NNDatasetProcess:' BRAPH2.FAIL_TEST], ...
			'NNDatasetProcess.getPropFormat(tag) does not work.')
		assert(Format.existsFormat(dtran.getPropFormat(tag)), ...
			[BRAPH2.STR ':NNDatasetProcess:' BRAPH2.FAIL_TEST], ...
			'dtran.getPropFormat(tag) does not work.')
		assert(Format.existsFormat(Element.getPropFormat(dtran, tag)), ...
			[BRAPH2.STR ':NNDatasetProcess:' BRAPH2.FAIL_TEST], ...
			'Element.getPropFormat(dtran, tag) does not work.')
		assert(Format.existsFormat(Element.getPropFormat(dtran, tag)), ...
			[BRAPH2.STR ':NNDatasetProcess:' BRAPH2.FAIL_TEST], ...
			'Element.getPropFormat(''NNDatasetProcess'', tag) does not work.')
	end
	 
	% getPropDescription(pointer)
	for prop = 1:1:NNDatasetProcess.getPropNumber()
		tag = dtran.getPropTag(prop);
	 
		assert(ischar(NNDatasetProcess.getPropDescription(prop)), ...
			[BRAPH2.STR ':NNDatasetProcess:' BRAPH2.FAIL_TEST], ...
			'NNDatasetProcess.getPropDescription(prop) does not work.')
		assert(ischar(dtran.getPropDescription(prop)), ...
			[BRAPH2.STR ':NNDatasetProcess:' BRAPH2.FAIL_TEST], ...
			'dtran.getPropDescription(prop) does not work.')
		assert(ischar(Element.getPropDescription(dtran, prop)), ...
			[BRAPH2.STR ':NNDatasetProcess:' BRAPH2.FAIL_TEST], ...
			'Element.getPropDescription(dtran, prop) does not work.')
		assert(ischar(Element.getPropDescription(dtran, prop)), ...
			[BRAPH2.STR ':NNDatasetProcess:' BRAPH2.FAIL_TEST], ...
			'Element.getPropDescription(''NNDatasetProcess'', prop) does not work.')
	 
		assert(ischar(NNDatasetProcess.getPropDescription(tag)), ...
			[BRAPH2.STR ':NNDatasetProcess:' BRAPH2.FAIL_TEST], ...
			'NNDatasetProcess.getPropDescription(tag) does not work.')
		assert(ischar(dtran.getPropDescription(tag)), ...
			[BRAPH2.STR ':NNDatasetProcess:' BRAPH2.FAIL_TEST], ...
			'dtran.getPropDescription(tag) does not work.')
		assert(ischar(Element.getPropDescription(dtran, tag)), ...
			[BRAPH2.STR ':NNDatasetProcess:' BRAPH2.FAIL_TEST], ...
			'Element.getPropDescription(dtran, tag) does not work.')
		assert(ischar(Element.getPropDescription(dtran, tag)), ...
			[BRAPH2.STR ':NNDatasetProcess:' BRAPH2.FAIL_TEST], ...
			'Element.getPropDescription(''NNDatasetProcess'', tag) does not work.')
	end
	 
	% getPropSettings(pointer)
	for prop = 1:1:NNDatasetProcess.getPropNumber()
		tag = dtran.getPropTag(prop);
	 
		settings = NNDatasetProcess.getPropSettings(prop);
		settings = dtran.getPropSettings(prop);
		settings = Element.getPropSettings(dtran, prop);
		settings = Element.getPropSettings('NNDatasetProcess', prop);
	 
		settings = NNDatasetProcess.getPropSettings(tag);
		settings = dtran.getPropSettings(tag);
		settings = Element.getPropSettings(dtran, tag);
		settings = Element.getPropSettings('NNDatasetProcess', tag);
	end
	 
	% getPropDefault(pointer)
	for prop = 1:1:NNDatasetProcess.getPropNumber()
		tag = dtran.getPropTag(prop);
	 
		default = NNDatasetProcess.getPropDefault(prop);
		default = dtran.getPropDefault(prop);
		default = Element.getPropDefault(dtran, prop);
		default = Element.getPropDefault('NNDatasetProcess', prop);
	 
		default = NNDatasetProcess.getPropDefault(tag);
		default = dtran.getPropDefault(tag);
		default = Element.getPropDefault(dtran, tag);
		default = Element.getPropDefault('NNDatasetProcess', tag);
	end
	 
	% getPropDefaultConditioned(pointer)
	for prop = 1:1:NNDatasetProcess.getPropNumber()
		tag = dtran.getPropTag(prop);
	 
		conditioned_default = NNDatasetProcess.getPropDefaultConditioned(prop);
		conditioned_default = dtran.getPropDefaultConditioned(prop);
		conditioned_default = Element.getPropDefaultConditioned(dtran, prop);
		conditioned_default = Element.getPropDefaultConditioned('NNDatasetProcess', prop);
	 
		conditioned_default = NNDatasetProcess.getPropDefaultConditioned(tag);
		conditioned_default = dtran.getPropDefaultConditioned(tag);
		conditioned_default = Element.getPropDefaultConditioned(dtran, tag);
		conditioned_default = Element.getPropDefaultConditioned('NNDatasetProcess', tag);
	end
	 
	% checkProp(pointer, value)
	for prop = 1:1:NNDatasetProcess.getPropNumber()
		tag = dtran.getPropTag(prop);
	 
		assert(~NNDatasetProcess.checkProp(prop, {'probably wrong value', 1}), ...
			[BRAPH2.STR ':NNDatasetProcess:' BRAPH2.FAIL_TEST], ...
			'NNDatasetProcess.checkProp(prop, value) does not work.')
		assert(~dtran.checkProp(prop, {'probably wrong value', 1}), ...
			[BRAPH2.STR ':NNDatasetProcess:' BRAPH2.FAIL_TEST], ...
			'dtran.checkProp(prop, value) does not work.')
		assert(~Element.checkProp(dtran, prop, {'probably wrong value', 1}), ...
			[BRAPH2.STR ':NNDatasetProcess:' BRAPH2.FAIL_TEST], ...
			'Element.checkProp(dtran, prop, value) does not work.')
		assert(~Element.checkProp('NNDatasetProcess', prop, {'probably wrong value', 1}), ...
			[BRAPH2.STR ':NNDatasetProcess:' BRAPH2.FAIL_TEST], ...
			'Element.checkProp(''NNDatasetProcess'', prop, value) does not work.')
	 
		assert_with_error('NNDatasetProcess.checkProp(varargin{1}, {''probably wrong value'', 1})', [BRAPH2.STR ':NNDatasetProcess:' BRAPH2.WRONG_INPUT], prop)
		assert_with_error('varargin{2}.checkProp(varargin{1}, {''probably wrong value'', 1})', [BRAPH2.STR ':NNDatasetProcess:' BRAPH2.WRONG_INPUT], prop, dtran)
		assert_with_error('Element.checkProp(varargin{2}, varargin{1}, {''probably wrong value'', 1})', [BRAPH2.STR ':NNDatasetProcess:' BRAPH2.WRONG_INPUT], prop, dtran)
		assert_with_error('Element.checkProp(''NNDatasetProcess'', varargin{1}, {''probably wrong value'', 1})', [BRAPH2.STR ':NNDatasetProcess:' BRAPH2.WRONG_INPUT], prop)
	 
		assert(~NNDatasetProcess.checkProp(tag, {'probably wrong value', 1}), ...
			[BRAPH2.STR ':NNDatasetProcess:' BRAPH2.FAIL_TEST], ...
			'NNDatasetProcess.checkProp(tag, value) does not work.')
		assert(~dtran.checkProp(tag, {'probably wrong value', 1}), ...
			[BRAPH2.STR ':NNDatasetProcess:' BRAPH2.FAIL_TEST], ...
			'dtran.checkProp(tag, value) does not work.')
		assert(~Element.checkProp(dtran, tag, {'probably wrong value', 1}), ...
			[BRAPH2.STR ':NNDatasetProcess:' BRAPH2.FAIL_TEST], ...
			'Element.checkProp(dtran, tag, value) does not work.')
		assert(~Element.checkProp('NNDatasetProcess', tag, {'probably wrong value', 1}), ...
			[BRAPH2.STR ':NNDatasetProcess:' BRAPH2.FAIL_TEST], ...
			'Element.checkProp(''NNDatasetProcess'', tag, value) does not work.')
	 
		assert_with_error('NNDatasetProcess.checkProp(varargin{1}, {''probably wrong value'', 1})', [BRAPH2.STR ':NNDatasetProcess:' BRAPH2.WRONG_INPUT], tag)
		assert_with_error('varargin{2}.checkProp(varargin{1}, {''probably wrong value'', 1})', [BRAPH2.STR ':NNDatasetProcess:' BRAPH2.WRONG_INPUT], tag, dtran)
		assert_with_error('Element.checkProp(varargin{2}, varargin{1}, {''probably wrong value'', 1})', [BRAPH2.STR ':NNDatasetProcess:' BRAPH2.WRONG_INPUT], tag, dtran)
		assert_with_error('Element.checkProp(''NNDatasetProcess'', varargin{1}, {''probably wrong value'', 1})', [BRAPH2.STR ':NNDatasetProcess:' BRAPH2.WRONG_INPUT], tag)
	 
		assert(NNDatasetProcess.checkProp(prop, Element.getPropDefaultConditioned(NNDatasetProcess, prop)), ...
			[BRAPH2.STR ':NNDatasetProcess:' BRAPH2.FAIL_TEST], ...
			'NNDatasetProcess.checkProp(prop, <conditioned default value>) does not work.')
		assert(dtran.checkProp(prop, Element.getPropDefaultConditioned(NNDatasetProcess, prop)), ...
			[BRAPH2.STR ':NNDatasetProcess:' BRAPH2.FAIL_TEST], ...
			'dtran.checkProp(prop, <conditioned default value>) does not work.')
		assert(Element.checkProp(dtran, prop, Element.getPropDefaultConditioned(NNDatasetProcess, prop)), ...
			[BRAPH2.STR ':NNDatasetProcess:' BRAPH2.FAIL_TEST], ...
			'Element.checkProp(dtran, prop, <conditioned default value>) does not work.')
		assert(Element.checkProp('NNDatasetProcess', prop, Element.getPropDefaultConditioned(NNDatasetProcess, prop)), ...
			[BRAPH2.STR ':NNDatasetProcess:' BRAPH2.FAIL_TEST], ...
			'Element.checkProp(''NNDatasetProcess'', prop, <conditioned default value>) does not work.')
	 
		assert(NNDatasetProcess.checkProp(tag, Element.getPropDefaultConditioned(NNDatasetProcess, prop)), ...
			[BRAPH2.STR ':NNDatasetProcess:' BRAPH2.FAIL_TEST], ...
			'NNDatasetProcess.checkProp(tag, <conditioned default value>) does not work.')
		assert(dtran.checkProp(tag, Element.getPropDefaultConditioned(NNDatasetProcess, prop)), ...
			[BRAPH2.STR ':NNDatasetProcess:' BRAPH2.FAIL_TEST], ...
			'dtran.checkProp(tag, <conditioned default value>) does not work.')
		assert(Element.checkProp(dtran, tag, Element.getPropDefaultConditioned(NNDatasetProcess, prop)), ...
			[BRAPH2.STR ':NNDatasetProcess:' BRAPH2.FAIL_TEST], ...
			'Element.checkProp(dtran, tag, <conditioned default value>) does not work.')
		assert(Element.checkProp('NNDatasetProcess', tag, Element.getPropDefaultConditioned(NNDatasetProcess, prop)), ...
			[BRAPH2.STR ':NNDatasetProcess:' BRAPH2.FAIL_TEST], ...
			'Element.checkProp(''NNDatasetProcess'', tag, <conditioned default value>) does not work.')
	 
	end
	 
end

%% Test 2: Instantiation - defaults
if rand() >= (1 - .01) * BRAPH2TEST.RANDOM
	dtran = NNDatasetProcess( ...
		NNDatasetProcess.ELCLASS, NNDatasetProcess.getNoValue(), ...
		NNDatasetProcess.NAME, NNDatasetProcess.getNoValue(), ...
		NNDatasetProcess.DESCRIPTION, NNDatasetProcess.getNoValue(), ...
		NNDatasetProcess.TEMPLATE, NNDatasetProcess.getPropDefault(NNDatasetProcess.TEMPLATE), ...
		NNDatasetProcess.ID, NNDatasetProcess.getPropDefault(NNDatasetProcess.ID), ...
		NNDatasetProcess.LABEL, NNDatasetProcess.getPropDefault(NNDatasetProcess.LABEL), ...
		NNDatasetProcess.NOTES, NNDatasetProcess.getPropDefault(NNDatasetProcess.NOTES), ...
		NNDatasetProcess.TOSTRING, NNDatasetProcess.getNoValue(), ...
		NNDatasetProcess.D, NNDatasetProcess.getNoValue() ...
		);
	 
	for prop = 1:1:NNDatasetProcess.getPropNumber()
	 
		% excluded props
		if any(prop == [])
			continue
		end
	 
		TAG = upper(NNDatasetProcess.getPropTag(prop));
		switch NNDatasetProcess.getPropCategory(prop)
			case {Category.CONSTANT, Category.RESULT, Category.QUERY}
				% getr
				assert( ...
					dtran.getr(prop) == NNDatasetProcess.getNoValue(), ...
					[BRAPH2.STR ':NNDatasetProcess:' BRAPH2.FAIL_TEST], ...
					['Being a ' NNDatasetProcess.getCategoryName(NNDatasetProcess.getPropCategory(prop)) ', NNDatasetProcess.getr(' int2str(prop) ') must be inizialized to NoValue(). ' ...
					'Or there could be an error in NNDatasetProcess.getr(' int2str(prop) ').'] ...
					)
				assert( ...
					dtran.getr(TAG) == NNDatasetProcess.getNoValue(), ...
					[BRAPH2.STR ':NNDatasetProcess:' BRAPH2.FAIL_TEST], ...
					['Being a ' NNDatasetProcess.getCategoryName(NNDatasetProcess.getPropCategory(prop)) ', NNDatasetProcess.getr(' TAG ') must be inizialized to NoValue(). ' ...
					'Or there could be an error in NNDatasetProcess.getr(' TAG ').'] ...
					)
				% get
				assert( ...
					~isa(dtran.get(prop), 'NoValue'), ...
					[BRAPH2.STR ':NNDatasetProcess:' BRAPH2.FAIL_TEST], ...
					['NNDatasetProcess.get(' int2str(prop) ') must NOT be a NoValue, because it should have been calculated.'] ...
					)
				if isempty(dtran.getPropSettings(prop))
					assert( ...
						dtran.checkFormat(dtran.getPropFormat(prop), dtran.get(prop)), ...
						[BRAPH2.STR ':NNDatasetProcess:' BRAPH2.FAIL_TEST], ...
						['NNDatasetProcess.get(' int2str(prop) ') returns a value with the wrong format.'] ...
						)
				else
					assert( ...
						dtran.checkFormat(dtran.getPropFormat(prop), dtran.get(prop), dtran.getPropSettings(prop)), ...
						[BRAPH2.STR ':NNDatasetProcess:' BRAPH2.FAIL_TEST], ...
						['NNDatasetProcess.get(' int2str(prop) ') returns a value with the wrong format.'] ...
						)
				end
			case Category.EVANESCENT
				% getr
				assert( ...
					dtran.getr(prop) == NNDatasetProcess.getNoValue(), ...
					[BRAPH2.STR ':NNDatasetProcess:' BRAPH2.FAIL_TEST], ...
					['Being a ' NNDatasetProcess.getCategoryName(NNDatasetProcess.getPropCategory(prop)) ', NNDatasetProcess.getr(' int2str(prop) ') must be inizialized to NoValue(). ' ...
					'Or there could be an error in NNDatasetProcess.getr(' int2str(prop) ').'] ...
					)
				assert( ...
					dtran.getr(TAG) == NNDatasetProcess.getNoValue(), ...
					[BRAPH2.STR ':NNDatasetProcess:' BRAPH2.FAIL_TEST], ...
					['Being a ' NNDatasetProcess.getCategoryName(NNDatasetProcess.getPropCategory(prop)) ', NNDatasetProcess.getr(' TAG ') must be inizialized to NoValue(). ' ...
					'Or there could be an error in NNDatasetProcess.getr(' TAG ').'] ...
					)
				% get
				warning_backup = warning('off', [BRAPH2.STR ':NNDatasetProcess']);
				assert( ...
					~isa(dtran.get(prop), 'NoValue'), ...
					[BRAPH2.STR ':NNDatasetProcess:' BRAPH2.FAIL_TEST], ...
					['NNDatasetProcess.get(' int2str(prop) ') must NOT be a NoValue, because it should have been calculated.'] ...
					)
				if isempty(dtran.getPropSettings(prop))
					assert( ...
						dtran.checkFormat(dtran.getPropFormat(prop), dtran.get(prop)), ...
						[BRAPH2.STR ':NNDatasetProcess:' BRAPH2.FAIL_TEST], ...
						['NNDatasetProcess.get(' int2str(prop) ') returns a value with the wrong format.'] ...
						)
				else
					assert( ...
						dtran.checkFormat(dtran.getPropFormat(prop), dtran.get(prop), dtran.getPropSettings(prop)), ...
						[BRAPH2.STR ':NNDatasetProcess:' BRAPH2.FAIL_TEST], ...
						['NNDatasetProcess.get(' int2str(prop) ') returns a value with the wrong format.'] ...
						)
				end
				warning(warning_backup)
			otherwise % case {Category.METADATA, Category.PARAMETER, Category.DATA, Category.FIGURE, Category.GUI}
				assert( ...
					isequal(dtran.getr(prop), NNDatasetProcess.getPropDefaultConditioned(prop)), ...
					[BRAPH2.STR ':NNDatasetProcess:' BRAPH2.FAIL_TEST], ...
					['NNDatasetProcess.getr(' int2str(prop) ') must be inizialized to its default value ' ...
					'given by NNDatasetProcess.getPropDefaultConditioned(' int2str(prop) '). ' ...
					'Or there could be an error in NNDatasetProcess.getr(' int2str(prop) ').'] ...
					)
				assert( ...
					isequal(dtran.getr(TAG), NNDatasetProcess.getPropDefaultConditioned(prop)), ...
					[BRAPH2.STR ':NNDatasetProcess:' BRAPH2.FAIL_TEST], ...
					['NNDatasetProcess.getr(' TAG ') must be inizialized to its default value ' ...
					'given by NNDatasetProcess.getPropDefaultConditioned(' int2str(prop) '). ' ...
					'Or there could be an error in NNDatasetProcess.getr(' TAG ').'] ...
					)
		end
	end
end

%% Test 3: Memorize
if rand() >= (1 - .01) * BRAPH2TEST.RANDOM
	dtran = NNDatasetProcess( ...
		NNDatasetProcess.ELCLASS, NNDatasetProcess.getNoValue(), ...
		NNDatasetProcess.NAME, NNDatasetProcess.getNoValue(), ...
		NNDatasetProcess.DESCRIPTION, NNDatasetProcess.getNoValue(), ...
		NNDatasetProcess.TEMPLATE, NNDatasetProcess.getPropDefault(NNDatasetProcess.TEMPLATE), ...
		NNDatasetProcess.ID, NNDatasetProcess.getPropDefault(NNDatasetProcess.ID), ...
		NNDatasetProcess.LABEL, NNDatasetProcess.getPropDefault(NNDatasetProcess.LABEL), ...
		NNDatasetProcess.NOTES, NNDatasetProcess.getPropDefault(NNDatasetProcess.NOTES), ...
		NNDatasetProcess.TOSTRING, NNDatasetProcess.getNoValue(), ...
		NNDatasetProcess.D, NNDatasetProcess.getNoValue() ...
		);
	 
	for prop = 1:1:NNDatasetProcess.getPropNumber()
	 
		% excluded props
		if any(prop == [])
			continue
		end
	 
		TAG = upper(NNDatasetProcess.getPropTag(prop));
		switch NNDatasetProcess.getPropCategory(prop)
			case Category.RESULT
				assert( ...
					~isa(dtran.get(prop), 'NoValue'), ...
					[BRAPH2.STR ':NNDatasetProcess:' BRAPH2.FAIL_TEST], ...
					['NNDatasetProcess.get(' int2str(prop) ') must NOT be a NoValue, because it should have been calculated.'] ...
					)
				assert( ...
					isa(dtran.getr(prop), 'NoValue'), ...
					[BRAPH2.STR ':NNDatasetProcess:' BRAPH2.FAIL_TEST], ...
					['NNDatasetProcess.getr(' int2str(prop) ') must be a NoValue, because it should NOT have been memorized.'] ...
					)
				assert( ...
					~isa(dtran.memorize(prop), 'NoValue'), ...
					[BRAPH2.STR ':NNDatasetProcess:' BRAPH2.FAIL_TEST], ...
					['NNDatasetProcess.memorize(' int2str(prop) ') must NOT be a NoValue, because it should have been calculated.'] ...
					)
				assert( ...
					~isa(dtran.getr(prop), 'NoValue'), ...
					[BRAPH2.STR ':NNDatasetProcess:' BRAPH2.FAIL_TEST], ...
					['NNDatasetProcess.getr(' int2str(prop) ') must NOT be a NoValue, because it should have been memorized.'] ...
					)
				assert( ...
					dtran.checkFormat(dtran.getPropFormat(prop), dtran.getr(prop),dtran.getPropSettings(prop)), ...
					[BRAPH2.STR ':NNDatasetProcess:' BRAPH2.FAIL_TEST], ...
					['NNDatasetProcess.getr(' int2str(prop) ') returns a value with the wrong format.'] ...
					)
			case Category.QUERY
	% 			warning_backup = warning('off', [BRAPH2.STR ':NNDatasetProcess']);
				assert( ...
					~isa(dtran.get(prop), 'NoValue'), ...
					[BRAPH2.STR ':NNDatasetProcess:' BRAPH2.FAIL_TEST], ...
					['NNDatasetProcess.get(' int2str(prop) ') must NOT be a NoValue, because it should have been calculated.'] ...
					)
				assert( ...
					isa(dtran.getr(prop), 'NoValue'), ...
					[BRAPH2.STR ':NNDatasetProcess:' BRAPH2.FAIL_TEST], ...
					['NNDatasetProcess.getr(' int2str(prop) ') must be a NoValue, because it should NOT have been memorized.'] ...
					)
	% following tests excluded because properties QUERY should not be memorized
	% 			warning_backup = warning('off', [BRAPH2.STR ':NNDatasetProcess']);
	% 			assert( ...
	% 				~isa(dtran.memorize(prop), 'NoValue'), ...
	% 				[BRAPH2.STR ':NNDatasetProcess:' BRAPH2.FAIL_TEST], ...
	% 				['NNDatasetProcess.memorize(' int2str(prop) ') must NOT be a NoValue, because it should have been calculated.'] ...
	% 				)
	% 			warning(warning_backup)
	% 			assert( ...
	% 				~isa(dtran.getr(prop), 'NoValue'), ...
	% 				[BRAPH2.STR ':NNDatasetProcess:' BRAPH2.FAIL_TEST], ...
	% 				['NNDatasetProcess.getr(' int2str(prop) ') must NOT be a NoValue, because it should have been memorized.'] ...
	% 				)
	% 			assert( ...
	% 				dtran.checkFormat(dtran.getPropFormat(prop), dtran.getr(prop),dtran.getPropSettings(prop)), ...
	% 				[BRAPH2.STR ':NNDatasetProcess:' BRAPH2.FAIL_TEST], ...
	% 				['NNDatasetProcess.getr(' int2str(prop) ') returns a value with the wrong format.'] ...
	% 				)
	% 			warning(warning_backup)
			case Category.EVANESCENT
				warning_backup = warning('off', [BRAPH2.STR ':NNDatasetProcess']);
				assert( ...
					~isa(dtran.get(prop), 'NoValue'), ...
					[BRAPH2.STR ':NNDatasetProcess:' BRAPH2.FAIL_TEST], ...
					['NNDatasetProcess.get(' int2str(prop) ') must NOT be a NoValue, because it should have been calculated.'] ...
					)
				warning(warning_backup)
				assert( ...
					isa(dtran.getr(prop), 'NoValue'), ...
					[BRAPH2.STR ':NNDatasetProcess:' BRAPH2.FAIL_TEST], ...
					['NNDatasetProcess.getr(' int2str(prop) ') must be a NoValue, because it should NOT have been memorized.'] ...
					)
				assert( ...
					~isa(dtran.memorize(prop), 'NoValue'), ...
					[BRAPH2.STR ':NNDatasetProcess:' BRAPH2.FAIL_TEST], ...
					['NNDatasetProcess.memorize(' int2str(prop) ') must NOT be a NoValue, because it should have been calculated.'] ...
					)
				assert( ...
					~isa(dtran.getr(prop), 'NoValue'), ...
					[BRAPH2.STR ':NNDatasetProcess:' BRAPH2.FAIL_TEST], ...
					['NNDatasetProcess.getr(' int2str(prop) ') must NOT be a NoValue, because it should have been memorized.'] ...
					)
				assert( ...
					dtran.checkFormat(dtran.getPropFormat(prop), dtran.getr(prop),dtran.getPropSettings(prop)), ...
					[BRAPH2.STR ':NNDatasetProcess:' BRAPH2.FAIL_TEST], ...
					['NNDatasetProcess.getr(' int2str(prop) ') returns a value with the wrong format.'] ...
					)
				if dtran.getPropFormat(prop) == Format.HANDLE
					warning_backup = warning('off', 'BRAPH2:NNDatasetProcess');
					delete(ancestor(dtran.get(prop), 'figure'))
					warning(warning_backup)
				end
		end
	end
	 
	if ~isempty(NNDatasetProcess.getProps(Category.RESULT))
		for prop = 1:1:NNDatasetProcess.getPropNumber()
	 
			% excluded props
			if any(prop == [])
				continue
			end
	 
			switch NNDatasetProcess.getPropCategory(prop)
				case {Category.PARAMETER, Category.DATA}
					assert( ...
						dtran.isLocked(prop), ...
						[BRAPH2.STR ':NNDatasetProcess:' BRAPH2.FAIL_TEST], ...
						['NNDatasetProcess.isLocked(' int2str(prop) ') must be locked because a result has been calculated.'] ...
						)
				otherwise
					assert( ...
						~dtran.isLocked(prop), ...
						[BRAPH2.STR ':NNDatasetProcess:' BRAPH2.FAIL_TEST], ...
						['NNDatasetProcess.isLocked(' int2str(prop) ') must NOT be locked even though a result has been calculated.'] ...
						)
			end
		end
	end
end

%% Test 4: Lock 1
if rand() >= (1 - .01) * BRAPH2TEST.RANDOM
	dtran = NNDatasetProcess();
	 
	for prop = 1:1:NNDatasetProcess.getPropNumber()
		TAG = upper(NNDatasetProcess.getPropTag(prop));
		assert( ...
			~dtran.isLocked(prop), ...
			[BRAPH2.STR ':NNDatasetProcess:' BRAPH2.FAIL_TEST], ...
			['NNDatasetProcess.isLocked(' int2str(prop) ') must NOT be locked when it is instantiated.'] ...
			)
		assert( ...
			~dtran.isLocked(TAG), ...
			[BRAPH2.STR ':NNDatasetProcess:' BRAPH2.FAIL_TEST], ...
			['NNDatasetProcess.isLocked(' TAG ') must NOT be locked when it is instantiated.'] ...
			)
	end
	 
	dtran.lock()
	 
	for prop = 1:1:NNDatasetProcess.getPropNumber()
		switch NNDatasetProcess.getPropCategory(prop)
			case {Category.PARAMETER, Category.DATA}
				assert( ...
					dtran.isLocked(prop), ...
					[BRAPH2.STR ':NNDatasetProcess:' BRAPH2.FAIL_TEST], ...
					['NNDatasetProcess.isLocked(' int2str(prop) ') must be locked because the element is now locked.'] ...
					)
			case {Category.CONSTANT, Category.METADATA, Category.RESULT, Category.QUERY, Category.EVANESCENT, Category.FIGURE, Category.GUI}
				assert( ...
					~dtran.isLocked(prop), ...
					[BRAPH2.STR ':NNDatasetProcess:' BRAPH2.FAIL_TEST], ...
					['NNDatasetProcess.isLocked(' int2str(prop) ') must NOT be locked even though the element is now locked.'] ...
					)
		end
	end
end

%% Test 5: Lock 2
if rand() >= (1 - .01) * BRAPH2TEST.RANDOM
	dtran = NNDatasetProcess();
	 
	warning_backup = warning('off', 'BRAPH2:NNDatasetProcess');
	for prop = 1:1:NNDatasetProcess.getPropNumber()
		dtran.lock(prop)
		switch NNDatasetProcess.getPropCategory(prop)
			case {Category.PARAMETER, Category.DATA, Category.FIGURE, Category.GUI}
				assert( ...
					dtran.isLocked(prop), ...
					[BRAPH2.STR ':NNDatasetProcess:' BRAPH2.FAIL_TEST], ...
					['NNDatasetProcess.isLocked(' int2str(prop) ') must be locked.'] ...
					)
			case {Category.CONSTANT, Category.METADATA, Category.RESULT, Category.QUERY, Category.EVANESCENT}
				assert( ...
					~dtran.isLocked(prop), ...
					[BRAPH2.STR ':NNDatasetProcess:' BRAPH2.FAIL_TEST], ...
					['NNDatasetProcess.isLocked(' int2str(prop) ') must NOT be locked even though locking has been attempted.'] ...
					)
		end
	end
	warning(warning_backup)
end

%% Test 6: Check
if rand() >= (1 - .01) * BRAPH2TEST.RANDOM
	dtran = NNDatasetProcess();
	 
	for prop = 1:1:NNDatasetProcess.getPropNumber()
		TAG = upper(NNDatasetProcess.getPropTag(prop));
		assert( ...
			dtran.isChecked(prop), ...
			[BRAPH2.STR ':NNDatasetProcess:' BRAPH2.FAIL_TEST], ...
			['NNDatasetProcess.isChecked(' int2str(prop) ') must be checked when it is instantiated.'] ...
			)
		assert( ...
			dtran.isChecked(TAG), ...
			[BRAPH2.STR ':NNDatasetProcess:' BRAPH2.FAIL_TEST], ...
			['NNDatasetProcess.isChecked(' TAG ') must be checked when it is instantiated.'] ...
			)
	end
	 
	dtran.unchecked()
	 
	for prop = 1:1:NNDatasetProcess.getPropNumber()
		assert( ...
			~dtran.isChecked(prop), ...
			[BRAPH2.STR ':NNDatasetProcess:' BRAPH2.FAIL_TEST], ...
			['NNDatasetProcess.isChecked(' int2str(prop) ') must NOT be checked because it has been set to unchecked.'] ...
			)
	end
	 
	dtran.checked()
	 
	for prop = 1:1:NNDatasetProcess.getPropNumber()
		assert( ...
			dtran.isChecked(prop), ...
			[BRAPH2.STR ':NNDatasetProcess:' BRAPH2.FAIL_TEST], ...
			['NNDatasetProcess.isChecked(' int2str(prop) ') must be checked because it has been set to checked.'] ...
			)
	end
end

%% Test 7: Callbacks
if rand() >= (1 - .01) * BRAPH2TEST.RANDOM
	% basic NNDatasetProcess
	dtran_0 = NNDatasetProcess( ...
		NNDatasetProcess.ELCLASS, NNDatasetProcess.getNoValue(), ...
		NNDatasetProcess.NAME, NNDatasetProcess.getNoValue(), ...
		NNDatasetProcess.DESCRIPTION, NNDatasetProcess.getNoValue(), ...
		NNDatasetProcess.TEMPLATE, NNDatasetProcess.getPropDefault(NNDatasetProcess.TEMPLATE), ...
		NNDatasetProcess.ID, NNDatasetProcess.getPropDefault(NNDatasetProcess.ID), ...
		NNDatasetProcess.LABEL, NNDatasetProcess.getPropDefault(NNDatasetProcess.LABEL), ...
		NNDatasetProcess.NOTES, NNDatasetProcess.getPropDefault(NNDatasetProcess.NOTES), ...
		NNDatasetProcess.TOSTRING, NNDatasetProcess.getNoValue(), ...
		NNDatasetProcess.D, NNDatasetProcess.getNoValue() ...
		);
	 
	% NNDatasetProcess with 1st callbacks
	dtran_1 = NNDatasetProcess( ...
		NNDatasetProcess.ELCLASS, NNDatasetProcess.getNoValue(), ...
		NNDatasetProcess.NAME, NNDatasetProcess.getNoValue(), ...
		NNDatasetProcess.DESCRIPTION, NNDatasetProcess.getNoValue(), ...
		NNDatasetProcess.TEMPLATE, dtran_0.getCallback(4), ..., ...
		NNDatasetProcess.ID, dtran_0.getCallback(5), ..., ...
		NNDatasetProcess.LABEL, NNDatasetProcess.getPropDefault(NNDatasetProcess.LABEL), ...
		NNDatasetProcess.NOTES, NNDatasetProcess.getPropDefault(NNDatasetProcess.NOTES), ...
		NNDatasetProcess.TOSTRING, NNDatasetProcess.getNoValue(), ...
		NNDatasetProcess.D, NNDatasetProcess.getNoValue() ...
		);
	 
	prop_number = NNDatasetProcess.getPropNumber();
	for prop = 1:1:prop_number
		TAG = upper(NNDatasetProcess.getPropTag(prop));
		switch NNDatasetProcess.getPropCategory(prop)
			case {Category.PARAMETER, Category.DATA, Category.FIGURE, Category.GUI}
				assert( ...
					isa(dtran_1.getr(prop), 'Callback'), ...
					[BRAPH2.STR ':NNDatasetProcess:' BRAPH2.FAIL_TEST], ...
					['NNDatasetProcess.getr(' int2str(prop) ') must be a callback.'] ...
					)
				assert( ...
					isequal(dtran_1.get(prop), dtran_0.get(prop)) && ~isa(dtran_1.get(prop), 'Callback'), ...
					[BRAPH2.STR ':NNDatasetProcess:' BRAPH2.FAIL_TEST], ...
					['NNDatasetProcess.get(' int2str(prop) ') must be the actual property and NOT a callback.'] ...
					)
			otherwise
				assert( ...
					~isa(dtran_1.getr(prop), 'Callback'), ...
					[BRAPH2.STR ':NNDatasetProcess:' BRAPH2.FAIL_TEST], ...
					['NNDatasetProcess.getr(' int2str(prop) ') must NOT be a callback.'] ...
					)
		end
	end
	 
	% NNDatasetProcess with 2nd callbacks
	dtran_2 = NNDatasetProcess( ...
		NNDatasetProcess.ELCLASS, NNDatasetProcess.getNoValue(), ...
		NNDatasetProcess.NAME, NNDatasetProcess.getNoValue(), ...
		NNDatasetProcess.DESCRIPTION, NNDatasetProcess.getNoValue(), ...
		NNDatasetProcess.TEMPLATE, dtran_1.getCallback(4), ..., ...
		NNDatasetProcess.ID, dtran_1.getCallback(5), ..., ...
		NNDatasetProcess.LABEL, NNDatasetProcess.getPropDefault(NNDatasetProcess.LABEL), ...
		NNDatasetProcess.NOTES, NNDatasetProcess.getPropDefault(NNDatasetProcess.NOTES), ...
		NNDatasetProcess.TOSTRING, NNDatasetProcess.getNoValue(), ...
		NNDatasetProcess.D, NNDatasetProcess.getNoValue() ...
		);
	 
	prop_number = NNDatasetProcess.getPropNumber();
	for prop = 1:1:prop_number
		TAG = upper(NNDatasetProcess.getPropTag(prop));
		switch NNDatasetProcess.getPropCategory(prop)
			case {Category.PARAMETER, Category.DATA, Category.FIGURE, Category.GUI}
				assert( ...
					isa(dtran_2.getr(prop), 'Callback'), ...
					[BRAPH2.STR ':NNDatasetProcess:' BRAPH2.FAIL_TEST], ...
					['NNDatasetProcess.getr(' int2str(prop) ') must be a callback.'] ...
					)
				assert( ...
					isequal(dtran_2.get(prop), dtran_0.get(prop)) && ~isa(dtran_1.get(prop), 'Callback'), ...
					[BRAPH2.STR ':NNDatasetProcess:' BRAPH2.FAIL_TEST], ...
					['NNDatasetProcess.get(' int2str(prop) ') must be the actual property and NOT a callback.'] ...
					)
			otherwise
				assert( ...
					~isa(dtran_2.getr(prop), 'Callback'), ...
					[BRAPH2.STR ':NNDatasetProcess:' BRAPH2.FAIL_TEST], ...
					['NNDatasetProcess.getr(' int2str(prop) ') must NOT be a callback.'] ...
					)
		end
	end
	 
	% NNDatasetProcess with 3rd callbacks
	dtran_3 = NNDatasetProcess( ...
		NNDatasetProcess.ELCLASS, NNDatasetProcess.getNoValue(), ...
		NNDatasetProcess.NAME, NNDatasetProcess.getNoValue(), ...
		NNDatasetProcess.DESCRIPTION, NNDatasetProcess.getNoValue(), ...
		NNDatasetProcess.TEMPLATE, dtran_2.getCallback(4), ..., ...
		NNDatasetProcess.ID, dtran_2.getCallback(5), ..., ...
		NNDatasetProcess.LABEL, NNDatasetProcess.getPropDefault(NNDatasetProcess.LABEL), ...
		NNDatasetProcess.NOTES, NNDatasetProcess.getPropDefault(NNDatasetProcess.NOTES), ...
		NNDatasetProcess.TOSTRING, NNDatasetProcess.getNoValue(), ...
		NNDatasetProcess.D, NNDatasetProcess.getNoValue() ...
		);
	 
	prop_number = NNDatasetProcess.getPropNumber();
	for prop = 1:1:prop_number
		TAG = upper(NNDatasetProcess.getPropTag(prop));
		switch NNDatasetProcess.getPropCategory(prop)
			case {Category.PARAMETER, Category.DATA, Category.FIGURE, Category.GUI}
				assert( ...
					isa(dtran_3.getr(prop), 'Callback'), ...
					[BRAPH2.STR ':NNDatasetProcess:' BRAPH2.FAIL_TEST], ...
					['NNDatasetProcess.getr(' int2str(prop) ') must be a callback.'] ...
					)
				assert( ...
					isequal(dtran_3.get(prop), dtran_0.get(prop)) && ~isa(dtran_1.get(prop), 'Callback'), ...
					[BRAPH2.STR ':NNDatasetProcess:' BRAPH2.FAIL_TEST], ...
					['NNDatasetProcess.get(' int2str(prop) ') must be the actual property and NOT a callback.'] ...
					)
			otherwise
				assert( ...
					~isa(dtran_3.getr(prop), 'Callback'), ...
					[BRAPH2.STR ':NNDatasetProcess:' BRAPH2.FAIL_TEST], ...
					['NNDatasetProcess.getr(' int2str(prop) ') must NOT be a callback.'] ...
					)
		end
	end
	 
end

%% Test 8: Copy
if rand() >= (1 - .01) * BRAPH2TEST.RANDOM
	% copy empty element
	dtran = NNDatasetProcess();
	 
	dtran_copy = dtran.copy();
	 
	assert(dtran_copy ~= dtran, ...
		[BRAPH2.STR ':NNDatasetProcess:' BRAPH2.FAIL_TEST], ...
		'NNDatasetProcess.copy() does not work. A copied element must point to a copied element.')
	assert(isequal(dtran_copy, dtran), ...
		[BRAPH2.STR ':NNDatasetProcess:' BRAPH2.FAIL_TEST], ...
		'NNDatasetProcess.copy() does not work. A copied element must have the same property values of the original element.')
	 
	for prop = 1:1:NNDatasetProcess.getPropNumber()
		value = dtran.getr(prop);
		value_copy = dtran_copy.getr(prop);
		switch NNDatasetProcess.getPropCategory(prop)
			case {Category.EVANESCENT}
				assert( ...
					isa(value_copy, 'NoValue'), ...
					[BRAPH2.STR ':NNDatasetProcess:' BRAPH2.FAIL_TEST], ...
					'NNDatasetProcess.copy() does not work. The copied value of an EVANESCENT property must be NoValue.' ...
					)
			otherwise
				if isa(value, 'NoValue')
					assert( ...
						value_copy == value, ...
						[BRAPH2.STR ':NNDatasetProcess:' BRAPH2.FAIL_TEST], ...
						'NNDatasetProcess.copy() does not work. There should be a unique instance of NoValue.' ...
						)
				elseif isa(value, 'Element')
					assert( ...
						value_copy ~= value, ...
						[BRAPH2.STR ':NNDatasetProcess:' BRAPH2.FAIL_TEST], ...
						'NNDatasetProcess.copy() does not work. The handle of a copied element should point to a copied element.' ...
						)
					assert( ...
						isequal(value_copy, value), ...
						[BRAPH2.STR ':NNDatasetProcess:' BRAPH2.FAIL_TEST], ...
						'NNDatasetProcess.copy() does not work. When empty, a copied element should be equal to the element.' ...
						)
				elseif iscell(value) && all(all(cellfun(@(x) isa(x, 'Element'), value)))
					for j = 1:1:length(value)
						assert( ...
							value_copy ~= value, ...
							[BRAPH2.STR ':NNDatasetProcess:' BRAPH2.FAIL_TEST], ...
							'NNDatasetProcess.copy() does not work. The handle of a copied element should point to a copied element.' ...
							)
						assert( ...
							isequal(value_copy, value), ...
							[BRAPH2.STR ':NNDatasetProcess:' BRAPH2.FAIL_TEST], ...
							'NNDatasetProcess.copy() does not work. When empty, a copied element should be equal to the element.' ...
							)
					end
				else
					assert( ...
						isequal(value_copy, value), ...
						[BRAPH2.STR ':NNDatasetProcess:' BRAPH2.FAIL_TEST], ...
						'NNDatasetProcess.copy() does not work. The value copy should be equal to the original.' ...
						)
				end
				assert( ...
					dtran_copy.isLocked(prop) == dtran.isLocked(prop), ...
					[BRAPH2.STR ':NNDatasetProcess:' BRAPH2.FAIL_TEST], ...
					'NNDatasetProcess.copy() does not work. The locked status of the copied and original elements must be the same.' ...
					)
				assert( ...
					dtran_copy.isChecked(prop) == dtran.isChecked(prop), ...
					[BRAPH2.STR ':NNDatasetProcess:' BRAPH2.FAIL_TEST], ...
					'NNDatasetProcess.copy() does not work. The checked status of the copied and original elements must be the same.' ...
					)
				assert( ...
					dtran_copy.getPropSeed(prop) == dtran.getPropSeed(prop), ...
					[BRAPH2.STR ':NNDatasetProcess:' BRAPH2.FAIL_TEST], ...
					'NNDatasetProcess.copy() does not work. The randomization seeds of the copied and original elements must be the same.' ...
					)
		end
	end
	 
	% copy element with default initialization and memorization
	dtran = NNDatasetProcess( ...
		NNDatasetProcess.ELCLASS, NNDatasetProcess.getNoValue(), ...
		NNDatasetProcess.NAME, NNDatasetProcess.getNoValue(), ...
		NNDatasetProcess.DESCRIPTION, NNDatasetProcess.getNoValue(), ...
		NNDatasetProcess.TEMPLATE, NNDatasetProcess.getPropDefault(NNDatasetProcess.TEMPLATE), ...
		NNDatasetProcess.ID, NNDatasetProcess.getPropDefault(NNDatasetProcess.ID), ...
		NNDatasetProcess.LABEL, NNDatasetProcess.getPropDefault(NNDatasetProcess.LABEL), ...
		NNDatasetProcess.NOTES, NNDatasetProcess.getPropDefault(NNDatasetProcess.NOTES), ...
		NNDatasetProcess.TOSTRING, NNDatasetProcess.getNoValue(), ...
		NNDatasetProcess.D, NNDatasetProcess.getNoValue() ...
		);
	 
	for prop = 1:1:NNDatasetProcess.getPropNumber()
		if NNDatasetProcess.getPropCategory(prop) == Category.QUERY
			% properties QUERY should not be memorized
			% warning_backup = warning('off', [BRAPH2.STR ':NNDatasetProcess']);
			% dtran.memorize(prop);
			% warning(warning_backup)
		elseif NNDatasetProcess.getPropCategory(prop) == Category.EVANESCENT && dtran.getPropFormat(prop) == Format.HANDLE
			dtran.memorize(prop);
			warning_backup = warning('off', 'BRAPH2:NNDatasetProcess');
			delete(ancestor(dtran.get(prop), 'figure'))
			warning(warning_backup)
		else
			dtran.memorize(prop);
		end
	end
	 
	% copy element with default initialization
	dtran_copy = dtran.copy();
	 
	for prop = 1:1:NNDatasetProcess.getPropNumber()
		value = dtran.getr(prop);
		value_copy = dtran_copy.getr(prop);
		switch NNDatasetProcess.getPropCategory(prop)
			case {Category.EVANESCENT Category.QUERY}
				assert( ...
					isa(value_copy, 'NoValue'), ...
					[BRAPH2.STR ':NNDatasetProcess:' BRAPH2.FAIL_TEST], ...
					'NNDatasetProcess.copy() does not work. The copied value of an EVANESCENT property must be NoValue.' ...
					)
			otherwise
				if isa(value, 'NoValue')
					assert( ...
						value_copy == value, ...
						[BRAPH2.STR ':NNDatasetProcess:' BRAPH2.FAIL_TEST], ...
						'NNDatasetProcess.copy() does not work. There should be a unique instance of NoValue.' ...
						)
				elseif isa(value, 'Element')
					assert( ...
						value_copy ~= value, ...
						[BRAPH2.STR ':NNDatasetProcess:' BRAPH2.FAIL_TEST], ...
						'NNDatasetProcess.copy() does not work. The handle of a copied element should point to a copied element.' ...
						)
					assert( ...
						isequal(value_copy, value), ...
						[BRAPH2.STR ':NNDatasetProcess:' BRAPH2.FAIL_TEST], ...
						'NNDatasetProcess.copy() does not work. When empty, a copied element should be equal to the element.' ...
						)
				elseif iscell(value) && all(all(cellfun(@(x) isa(x, 'Element'), value)))
					for j = 1:1:length(value)
						assert( ...
							value_copy ~= value, ...
							[BRAPH2.STR ':NNDatasetProcess:' BRAPH2.FAIL_TEST], ...
							'NNDatasetProcess.copy() does not work. The handle of a copied element should point to a copied element.' ...
							)
						assert( ...
							isequal(value_copy, value), ...
							[BRAPH2.STR ':NNDatasetProcess:' BRAPH2.FAIL_TEST], ...
							'NNDatasetProcess.copy() does not work. When empty, a copied element should be equal to the element.' ...
							)
					end
				else
					assert( ...
						isequal(value_copy, value), ...
						[BRAPH2.STR ':NNDatasetProcess:' BRAPH2.FAIL_TEST], ...
						'NNDatasetProcess.copy() does not work. The value copy should be equal to the original.' ...
						)
				end
	 
					assert( ...
						dtran_copy.isLocked(prop) == dtran.isLocked(prop), ...
						[BRAPH2.STR ':NNDatasetProcess:' BRAPH2.FAIL_TEST], ...
						'NNDatasetProcess.copy() does not work. The locked status of the copied and original elements must be the same.' ...
						)
	 
					assert( ...
						dtran_copy.isChecked(prop) == dtran.isChecked(prop), ...
						[BRAPH2.STR ':NNDatasetProcess:' BRAPH2.FAIL_TEST], ...
						'NNDatasetProcess.copy() does not work. The checked status of the copied and original elements must be the same.' ...
						)
	 
					assert( ...
						dtran_copy.getPropSeed(prop) == dtran.getPropSeed(prop), ...
						[BRAPH2.STR ':NNDatasetProcess:' BRAPH2.FAIL_TEST], ...
						'NNDatasetProcess.copy() does not work. The randomization seeds of the copied and original elements must be the same.' ...
						)
		end
	end
	 
	% copy element with callbacks
	dtran_0 = NNDatasetProcess( ...
		NNDatasetProcess.ELCLASS, NNDatasetProcess.getNoValue(), ...
		NNDatasetProcess.NAME, NNDatasetProcess.getNoValue(), ...
		NNDatasetProcess.DESCRIPTION, NNDatasetProcess.getNoValue(), ...
		NNDatasetProcess.TEMPLATE, NNDatasetProcess.getPropDefault(NNDatasetProcess.TEMPLATE), ...
		NNDatasetProcess.ID, NNDatasetProcess.getPropDefault(NNDatasetProcess.ID), ...
		NNDatasetProcess.LABEL, NNDatasetProcess.getPropDefault(NNDatasetProcess.LABEL), ...
		NNDatasetProcess.NOTES, NNDatasetProcess.getPropDefault(NNDatasetProcess.NOTES), ...
		NNDatasetProcess.TOSTRING, NNDatasetProcess.getNoValue(), ...
		NNDatasetProcess.D, NNDatasetProcess.getNoValue() ...
		);
	 
	dtran = NNDatasetProcess( ...
		NNDatasetProcess.ELCLASS, NNDatasetProcess.getNoValue(), ...
		NNDatasetProcess.NAME, NNDatasetProcess.getNoValue(), ...
		NNDatasetProcess.DESCRIPTION, NNDatasetProcess.getNoValue(), ...
		NNDatasetProcess.TEMPLATE, dtran_0.getCallback(4), ..., ...
		NNDatasetProcess.ID, dtran_0.getCallback(5), ..., ...
		NNDatasetProcess.LABEL, NNDatasetProcess.getPropDefault(NNDatasetProcess.LABEL), ...
		NNDatasetProcess.NOTES, NNDatasetProcess.getPropDefault(NNDatasetProcess.NOTES), ...
		NNDatasetProcess.TOSTRING, NNDatasetProcess.getNoValue(), ...
		NNDatasetProcess.D, NNDatasetProcess.getNoValue() ...
		);
	 
	dtran_copy = dtran.copy();
	dtran_0_copy = dtran_copy.getr('ID').get('EL');
	 
	for prop = 1:1:NNDatasetProcess.getPropNumber()
		value = dtran.getr(prop);
		value_copy = dtran_copy.getr(prop);
		switch NNDatasetProcess.getPropCategory(prop)
			case {Category.EVANESCENT}
				assert( ...
					isa(value_copy, 'NoValue'), ...
					[BRAPH2.STR ':NNDatasetProcess:' BRAPH2.FAIL_TEST], ...
					'NNDatasetProcess.copy() does not work. The copied value of an EVANESCENT property must be NoValue.' ...
					)
			otherwise
				if isa(value, 'NoValue')
					assert( ...
						value_copy == value, ...
						[BRAPH2.STR ':NNDatasetProcess:' BRAPH2.FAIL_TEST], ...
						'NNDatasetProcess.copy() does not work. There should be a unique instance of NoValue.' ...
						)
				elseif isa(value, 'Element')
					assert( ...
						value_copy ~= value, ...
						[BRAPH2.STR ':NNDatasetProcess:' BRAPH2.FAIL_TEST], ...
						'NNDatasetProcess.copy() does not work. The handle of a copied element should point to a copied element.' ...
						)
					assert( ...
						isequal(value_copy, value), ...
						[BRAPH2.STR ':NNDatasetProcess:' BRAPH2.FAIL_TEST], ...
						'NNDatasetProcess.copy() does not work. When empty, a copied element should be equal to the element.' ...
						)
				elseif iscell(value) && all(all(cellfun(@(x) isa(x, 'Element'), value)))
					for j = 1:1:length(value)
						assert( ...
							value_copy ~= value, ...
							[BRAPH2.STR ':NNDatasetProcess:' BRAPH2.FAIL_TEST], ...
							'NNDatasetProcess.copy() does not work. The handle of a copied element should point to a copied element.' ...
							)
						assert( ...
							isequal(value_copy, value), ...
							[BRAPH2.STR ':NNDatasetProcess:' BRAPH2.FAIL_TEST], ...
							'NNDatasetProcess.copy() does not work. When empty, a copied element should be equal to the element.' ...
							)
					end
				else
					assert( ...
						isequal(value_copy, value), ...
						[BRAPH2.STR ':NNDatasetProcess:' BRAPH2.FAIL_TEST], ...
						'NNDatasetProcess.copy() does not work. The value copy should be equal to the original.' ...
						)
				end
				if isa(value, 'Callback')
					assert( ...
						value == dtran_0.getCallback(prop), ...
						[BRAPH2.STR ':NNDatasetProcess:' BRAPH2.FAIL_TEST], ...
						'NNDatasetProcess.copy() does not work. The callback should be obtained from NNDatasetProcess.getCallback().' ...
						)
					assert( ...
						value_copy == dtran_0_copy.getCallback(prop), ...
						[BRAPH2.STR ':NNDatasetProcess:' BRAPH2.FAIL_TEST], ...
						'NNDatasetProcess.copy() does not work. The callback should be obtained from NNDatasetProcess.getCallback().' ...
						)
				end
	 
					assert( ...
						dtran_copy.isLocked(prop) == dtran.isLocked(prop), ...
						[BRAPH2.STR ':NNDatasetProcess:' BRAPH2.FAIL_TEST], ...
						'NNDatasetProcess.copy() does not work. The locked status of the copied and original elements must be the same.' ...
						)
	 
					assert( ...
						dtran_copy.isChecked(prop) == dtran.isChecked(prop), ...
						[BRAPH2.STR ':NNDatasetProcess:' BRAPH2.FAIL_TEST], ...
						'NNDatasetProcess.copy() does not work. The checked status of the copied and original elements must be the same.' ...
						)
	 
					assert( ...
						dtran_copy.getPropSeed(prop) == dtran.getPropSeed(prop), ...
						[BRAPH2.STR ':NNDatasetProcess:' BRAPH2.FAIL_TEST], ...
						'NNDatasetProcess.copy() does not work. The randomization seeds of the copied and original elements must be the same.' ...
						)
		end
	end
	 
end

%% Test 9: Template
if rand() >= (1 - .01) * BRAPH2TEST.RANDOM
	dtran_template = NNDatasetProcess();
	dtran = NNDatasetProcess('TEMPLATE', dtran_template);
	 
	for prop = 1:1:NNDatasetProcess.getPropNumber()
	 
		% excluded props
		if any(prop == [])
			continue
		end
	 
		TAG = upper(NNDatasetProcess.getPropTag(prop));
		switch NNDatasetProcess.getPropCategory(prop)
			case {Category.PARAMETER}
				if prop == NNDatasetProcess.TEMPLATE
					assert( ...
						isa(dtran.getr(prop), 'NNDatasetProcess'), ...
						[BRAPH2.STR ':NNDatasetProcess:' BRAPH2.FAIL_TEST], ...
						'NNDatasetProcess TEMPLATE does not work. NNDatasetProcess.getr(''TEMPLATE'') should be a NNDatasetProcess element.' ...
						)
					assert( ...
						isa(dtran_template.getr(prop), 'NoValue'), ...
						[BRAPH2.STR ':NNDatasetProcess:' BRAPH2.FAIL_TEST], ...
						'NNDatasetProcess TEMPLATE does not work. NNDatasetProcess_template.getr(''TEMPLATE'') should be a NoValue.' ...
						)
				else
					assert( ...
						isa(dtran.getr(prop), 'Callback'), ...
						[BRAPH2.STR ':NNDatasetProcess:' BRAPH2.FAIL_TEST], ...
						['NNDatasetProcess TEMPLATE does not work. NNDatasetProcess.getr(' TAG ') should be a Callback.'] ...
						)
					assert( ...
						dtran.getr(prop).get('EL') == dtran_template && dtran.getr(prop).get('PROP') == prop && strcmp(dtran.getr(prop).get('TAG'), TAG), ...
						[BRAPH2.STR ':NNDatasetProcess:' BRAPH2.FAIL_TEST], ...
						['NNDatasetProcess TEMPLATE does not work. NNDatasetProcess.getr(' TAG ') should be a Callback to dtran_template.' TAG '.'] ...
						)
					assert( ...
						isa(dtran_template.getr(prop), 'NoValue'), ...
						[BRAPH2.STR ':NNDatasetProcess:' BRAPH2.FAIL_TEST], ...
						['NNDatasetProcess TEMPLATE does not work. NNDatasetProcess_template.getr(' TAG ') should be a NoValue.'] ...
						)
				end
			otherwise
				assert( ...
					isa(dtran.getr(prop), 'NoValue'), ...
					[BRAPH2.STR ':NNDatasetProcess:' BRAPH2.FAIL_TEST], ...
					['NNDatasetProcess TEMPLATE does not work. NNDatasetProcess.getr(' TAG ') should be a NoValue.'] ...
					)
				assert( ...
					isa(dtran_template.getr(prop), 'NoValue'), ...
					[BRAPH2.STR ':NNDatasetProcess:' BRAPH2.FAIL_TEST], ...
					['NNDatasetProcess TEMPLATE does not work. NNDatasetProcess_template.getr(' TAG ') should be a NoValue.'] ...
					)
		end
	end
end

%% Test 10: Save Load
if rand() >= (1 - .01) * BRAPH2TEST.RANDOM
	dtran = NNDatasetProcess( ...
		NNDatasetProcess.ELCLASS, NNDatasetProcess.getNoValue(), ...
		NNDatasetProcess.NAME, NNDatasetProcess.getNoValue(), ...
		NNDatasetProcess.DESCRIPTION, NNDatasetProcess.getNoValue(), ...
		NNDatasetProcess.TEMPLATE, NNDatasetProcess.getPropDefault(NNDatasetProcess.TEMPLATE), ...
		NNDatasetProcess.ID, NNDatasetProcess.getPropDefault(NNDatasetProcess.ID), ...
		NNDatasetProcess.LABEL, NNDatasetProcess.getPropDefault(NNDatasetProcess.LABEL), ...
		NNDatasetProcess.NOTES, NNDatasetProcess.getPropDefault(NNDatasetProcess.NOTES), ...
		NNDatasetProcess.TOSTRING, NNDatasetProcess.getNoValue(), ...
		NNDatasetProcess.D, NNDatasetProcess.getNoValue() ...
		);
	 
	filename = [fileparts(which('test_braph2')) filesep 'nndatasetprocess_to_be_erased.b2'];
	 
	Element.save(dtran, filename)
	 
	dtran_loaded = Element.load(filename);
	 
	assert( ...
		isequal(dtran.copy(), dtran_loaded), ...
		[BRAPH2.STR ':NNDatasetProcess:' BRAPH2.FAIL_TEST], ...
		'NNDatasetProcess.save(dtran) and/or NNDatasetProcess.load() do not work.' ...
		)
	 
	delete(filename)
end

%% Test 11: JSON
if rand() >= (1 - .01) * BRAPH2TEST.RANDOM
	dtran = NNDatasetProcess( ...
		NNDatasetProcess.ELCLASS, NNDatasetProcess.getNoValue(), ...
		NNDatasetProcess.NAME, NNDatasetProcess.getNoValue(), ...
		NNDatasetProcess.DESCRIPTION, NNDatasetProcess.getNoValue(), ...
		NNDatasetProcess.TEMPLATE, NNDatasetProcess.getPropDefault(NNDatasetProcess.TEMPLATE), ...
		NNDatasetProcess.ID, NNDatasetProcess.getPropDefault(NNDatasetProcess.ID), ...
		NNDatasetProcess.LABEL, NNDatasetProcess.getPropDefault(NNDatasetProcess.LABEL), ...
		NNDatasetProcess.NOTES, NNDatasetProcess.getPropDefault(NNDatasetProcess.NOTES), ...
		NNDatasetProcess.TOSTRING, NNDatasetProcess.getNoValue(), ...
		NNDatasetProcess.D, NNDatasetProcess.getNoValue() ...
		);
	 
	[json, struct, el_list] = encodeJSON(dtran);
	[dtran_dec, struct_dec, el_list_dec] = Element.decodeJSON(json);
	 
	assert(dtran_dec ~= dtran, ...
		[BRAPH2.STR ':NNDatasetProcess:' BRAPH2.FAIL_TEST], ...
		'NNDatasetProcess.encodeJSON() or NNDatasetProcess.decodeJSON() does not work. A JSON encoded/decoded element must point to an element other than the original one.' ...
		)
	if all(cellfun(@(prop) NNDatasetProcess.getPropFormat(prop), num2cell(NNDatasetProcess.getProps())) == Format.HANDLE) && all(cellfun(@(prop) NNDatasetProcess.getPropFormat(prop), num2cell(NNDatasetProcess.getProps())) == Format.NET)
		assert(isequal(dtran_dec, dtran), ...
			[BRAPH2.STR ':NNDatasetProcess:' BRAPH2.FAIL_TEST], ...
			'NNDatasetProcess.encodeJSON() or NNDatasetProcess.decodeJSON() does not work. A JSON encoded/decoded element must have the same property values of the original element.' ...
			)
	end
end

%% Test 12: No Figures Left
if rand() >= (1 - 1) * BRAPH2TEST.RANDOM
	assert(isempty(findall(0, 'type', 'figure')), ...
		[BRAPH2.STR ':NNDatasetProcess:' BRAPH2.FAIL_TEST], ...
		[' When testing NNDatasetProcess no figures should be left over, either visible or not. ' ...
		int2str(length(findall(0, 'type', 'figure'))) ' figure(s) were left over.'] ...
		)
end

%% Test 13: Delete Figures
if rand() >= (1 - 1) * BRAPH2TEST.RANDOM
	delete(findall(0, 'type', 'figure'))
end

